### ISSUE TITLE
Document Sass usage instructions

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/ibm-products#1048]
Per https://ibm-casdesign.slack.com/archives/C013ZTX0N6B/p1626912155127300

[Guidance in Carbon's `styles` package](https://github.com/carbon-design-system/carbon/tree/main/packages/styles#usage) can be leveraged as a reference.

**Comment by elycheea** [comment]
This is now documented in the [Developing section](https://pages.github.ibm.com/carbon/ibm-products/developing/get-started/#styles) of the website relaunch.
