### ISSUE TITLE
Props with ‘node’ type need a useful storybook control

### ISSUE THREAD

**Issue by dcwarwick** [carbon-design-system/ibm-products#1097]
Various props have type 'node', enabling markup to be inserted rather than just strings. This is useful for props like title, subtitle, description, etc. However, in storybook, the default controls panel does not handle type 'node' well.

It used to be that these props would display as a JSON fragment with an edit button, but attempting to edit them would cause errors. In the latest storybook these props sometimes get a "Set string" button, but pressing the button causes immediate errors. 

We could disable these props in the controls panel, but that doesn't make very flexible stories. It would be better to find a good definition we can use for these props, and apply it wherever they occur. This could be a drop-down with a selection of pre-determined values, but it would be even better to find something that enables text values to be entered, but possibly combined with some pre-determined rich HTML options. A full HTML edit ability would be ideal, but unless it's easy to switch on is probably overkill!

 
<img width="1321" alt="Screen Shot 2021-07-28 at 7 16 54 PM" src="https://user-images.githubusercontent.com/14081333/127421208-e4578c5e-46a9-40ec-8b7a-440f13b912c2.png">
(__Originally posted by @andrea-gm in https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/1085#issuecomment-888746608__)

**Comment by elycheea** [comment]
Still relevant — I do think we’ve been moving toward updating `node`s with dropdown/selection, but could still be good to scrub our stories for more than need updating.

**Comment by elycheea** [comment]
Tagging @glapadre — think it could be a good project to work through as time permits.

**Comment by sstrubberg** [comment]
Closing because this is referring to older version of storybook.
