### ISSUE TITLE
Edit & Update: Cards

### ISSUE THREAD

**Issue by andrea-island** [carbon-design-system/ibm-products#1259]
# Name of component or pattern

Edit & Update: Cards

## Brief description

Editable cards allow a quick way to update assets in C&CS products.

## Details

[Link to Design](https://pages.github.ibm.com/cdai-design/pal/patterns/edit/usage#cards)

Editable card in Cloud PAL https://pages.github.ibm.com/ibmcloud/pal/components/card/usage#manual-edit-mode-(simple)

### Links to other materials

Reminder it may be helpful to post questions in #ccs-pal and tag the maintainer for quicker response and more eyes on it.

## Design Maintainer(s)

- Shelley Dignum

## Tasks

Before starting work on this epic, please review and complete the following.

- [ ] Initial review of design/existing code

### Working in Cloud and Cognitive package

- [ ] Have you reviewed our
      [contribution guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/.github/CONTRIBUTING.md)?
- [ ] Have you noted our
      [code guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/docs/CODE_GUIDELINES.md)?
- [ ] Did you use the CLI to scaffold your new component?

**Comment by davidmenendez** [comment]
Due to some confusion between the different PAL's about which card is being used the designs that exist for edit and update aren't based on the existing C&CS cards. I am currently waiting on the redesigns that use the correct card.
