### ISSUE TITLE
Edit header summary/description

### ISSUE THREAD

**Issue by shankalope** [carbon-design-system/ibm-products#1320]
# Edit header summary/description

## Brief description

In the ccs header component within the space used for summary, some use cases call for using this space to house a description of what is being viewed. For example the user may create an AI model and provide a description that we should subsequently allow them to edit.

In short the inclusion of the following would be preferable

~~1. Expansion of '[Edit](https://pages.github.ibm.com/cdai-design/pal/patterns/edit/)' guidance to include do's and do not's of header edits~~
~~2. The inclusion of an 'editSummary' toggle for all page headers that include the 'summary' prop.~~
~~3. Consider addition of character limits~~

~~Alternatively~~
 Most ideally

1. Implement the option for [Inline editing](https://pages.github.ibm.com/cdai-design/pal/patterns/edit/#inline-edit), I will contact Cameron Calder and get his thoughts.

Our UI devs have worked on implementing this in Watson AIOps, an example can be seen in the gif below. Ideally we want to remain compliant with CCS components.
 

## Details

[Design InVision](https://ibm.invisionapp.com/share/JBO1LD5HK69) 

[Prototype of Andrew Smith's animation northstar](https://pages.github.ibm.com/CDAI-UX-Engineering/motion-dashboard/projects/dashboard) (Includes edit icon but no interactive functionality.

Slack Shaun Lynch or email me at shaunlynch@ibm.com and I'll find a live test cluster if required.

### Links to other materials

[Sketch file](https://www.sketch.com/s/35c07dde-d94c-4111-bab3-c2c7fe06bcee)

![edit description](https://user-images.githubusercontent.com/15694545/136462690-636598a0-5436-465b-a6c4-b4658e8f4290.gif)

## Design Maintainer(s)

- Shaun Lynch
- TBD

## Tasks

Before starting work on this epic, please review and complete the following.

- [ ] Initial review of design/existing code

### Working in Cloud and Cognitive package

- [ ] Have you reviewed our
      [contribution guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/.github/CONTRIBUTING.md)?
- [ ] Have you noted our
      [code guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/docs/CODE_GUIDELINES.md)?
- [ ] Did you use the CLI to scaffold your new component?

**Comment by lee-chase** [comment]
Related to #1492

**Comment by elycheea** [comment]
[Should be i](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-page-header-pageheader--with-title&args=title:7)
