### ISSUE TITLE
step switching in CreateFullPage 

### ISSUE THREAD

**Issue by qi-wang** [carbon-design-system/ibm-products#1349]
## What package(s) are you using?

- [x ] Cloud & Cognitive
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## What did you want to know?

After completing the steps, "Change" links are displayed on the summary page to allow user switching to a specific step to change the input and go back to the summary page. Is it feasible for CreateFullPage? Can you advise how to implement it?
Is it feasible to click the step titles in the left influencer to go to a step and how? Thanks.

## Relevant information

My CreateFullPage contains several steps and the last step is a summary page that contains some links for user to go to a specific step.

**Comment by matthewgallo** [comment]
Hey @qi-wang! 👋   Do you have designers working on your team? It would be helpful to discuss this behavior in more detail with your team's designers and the designers who worked on the CreateFullPage and CreateTearsheet components. Thanks!

**Comment by qi-wang** [comment]
The request was from our UX designer. Here is the desired behavior:

- Ideally the user can switch to any step by clicking a step title in Influencer. The disableSubmit condition is still checked. If a step is not valid to go,  CreateFullPage stays in the current step. The step titles in Influencer do not have to be links but are enabled for user interactions. 
- "Change" links on the summary page (last page) leads to various steps. For example, user input field1 in step1, and input field2 in step2. There are "Change" links beside field1 and field2 values on summary page. When user clicks the link beside field1, the CreateFullPage component switches to step1. When user clicks the link beside field2, the CreateFullPage component switches to step2. If CreateFullPage can be enhanced to expose the control of currentStep, this behavior would be feasible.

For now I'm programmatically calling the click event on the Back and Next buttons to archive this. Here is the code FYI.
```
    const gotoStep = param => {
        if (typeof(param) === 'object') { // param is the event object
            param = param.target.id;
        }
        const index = param.substring(param.length - 1); // get the step index from the node id
        console.log("go to step: " + index);

        // get current step
        const li = document.querySelector('.bx--progress-step--current');
        const currentStep = li.querySelector('.bx--progress-step-button').getAttribute('index');
        const diff = currentStep - index;        
        const backBtn = document.querySelector('.exp--action-set__action-button.bx--btn--secondary');
        const nextBtn = document.querySelector('.exp--create-full-page__create-button');
        if (backBtn) {
            // go backward
            for (let i = 0; i < diff; i ++) {
                backBtn.click();
            }
            // go forward
            if (diff < 0) {
                for (let i = diff; i < 0; i ++) {
                    setTimeout(() => {
                        nextBtn.click();
                    }, 100);                        
                }
            }           
        }
    }

    componentDidMount() {
        const steps = document.querySelectorAll('.bx--progress-label');
        for(let i =0; i<steps.length;i++ ){
            steps[i].setAttribute('id', 'progress-' + i); // add id with step index to titles in influencer
            steps[i].addEventListener('click', this.gotoStep); // add handler for click event on the step titles
        }
    };
```

Thanks for looking into this request.

**Comment by matthewgallo** [comment]
I see. I think it would be helpful to have your designers speak with @andrea-gm, she worked on the designs for this component and I think would be interested in hearing more about your use case.

One thing I would be careful of in the code you shared above is hardcoding our prefix `exp` directly inside of a querySelector. The prefix for our component library is changing soon. What you should do instead is something like this:
```jsx
import { pkg } from "@carbon/ibm-cloud-cognitive/es/settings";
...
...
const backBtn = document.querySelector(`${pkg.prefix}--action-set__action-button.bx--btn--secondary`);
...
...
```

Even with this approach, the carbon prefix `bx` is still hardcoded and I believe in Carbon v11 the prefix is changing to `cds` so just be careful about that.

**Comment by qi-wang** [comment]
Thanks for the information about the prefix. Our designer has retired early this week. You may contact me if there are any questions regarding the use case.
