### ISSUE TITLE
Add support for navigation pattern

### ISSUE THREAD

**Issue by markcor11** [carbon-design-system/ibm-products#1661]
## What package(s) are you using?

- [ ] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [x] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

We need to use the ideNavigation component for a new product but it is not complete and does not currently contain all the behaviours to support the current navigation pattern.  

> Describe in detail the issue you're having.

https://carbon-for-ibm-products.netlify.app/?path=/story/cd-ai-legacy-components-idenavigation-legacy-ide-navigation-component--using-idesidenavlinks

> Is this issue related to a specific component?
ide-navigation

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

Just trying to use the component but does not match the design pattern.

**Comment by lee-chase** [comment]
HI @markcor11,

Navigation is not currently a Carbon for IBM Products component, but part of CD&AI. You can find a list of IBM Prouccts Core Assets listed here https://pages.github.ibm.com/cdai-design/pal/overview/asset-index.

You could contribute an update to the CD&AI or request a fix from one of their maintainers.
