### ISSUE TITLE
About modal: Update component to match new guidelines

### ISSUE THREAD

**Issue by tanteresa** [carbon-design-system/ibm-products#1776]
## What will this achieve?
- About modal component in Storybook https://carbon-for-ibm-products.netlify.app/?path=/story/overview-getting-started--page should reflect what has been designed on the PAL site https://pages.github.ibm.com/cdai-design/pal/patterns/about-modal/usage

## How will success be measured?

I can help QA the coded component.

## Additional information
Guidelines: https://pages.github.ibm.com/cdai-design/pal/patterns/about-modal/usage
Sketch file:https://ibm.box.com/s/yrp9ir128xh257i4qtmqvtg09hdxv7nc

**Comment by lee-chase** [comment]
Hello @tanteresa, my assumption here is that the design has changed or the implementation never met the original design. 

How we got here is not as important as how we move forward. Please document in this issue what you wish to be changed. I will mark as blocked awaiting further information.

**Comment by elycheea** [comment]
Hi @tanteresa!

Checking in on this issue. Can you clarify which parts of the implemented AboutModal needs to be updated to match the PAL?

**Comment by elycheea** [comment]
@lizisawizard Can you take a look at this after we wrap up your filtering issues?

**Comment by lizisawizard** [comment]
@tanteresa Coming back to Elysia's comment - I was wondering if you had any guidance on the following questions:
- The documentation says to use the dark version of the modal. Should I switch the storybook to feature only the dark mode of the component with a light mode tab?
- Does anything change with how tabs work on about modal? I couldn't find anything in the documentation
- Can you clarify the color variables you're using for the modal?
- The documentation mentioned that the version number can link to an external page. Should I add that to the component's functionality?

**Comment by elycheea** [comment]
Targeted for after IBM Products v2 release.
