### ISSUE TITLE
Carbon V11 Support

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-products#1869]
With Carbon V11 released on March 31st 2022 there are a number of questions to answer with regards to how it affects @carbon/ibm-products.

Break down of tasks:(Only convert to issue, assigned to epic, when ready to be worked on). 
- [x] #1870
- [ ] Find out when our consumers are wanting to move to V11 and discuss findings with the team.

**Comment by asfordmatt** [comment]
Just noting my interest in this. We will want to move up to V11 at some point, but don't have a timeframe as yet.

**Comment by Mikadv** [comment]
We are asked by our designers to use certain components of carbon 11 and want to utilize the build time improvements and code cleanup possibilities. Hence, we need this library on carbon 11 or our apps break. Now this means that `ibm-cloud-cognitive` is blocking us from upgrading to carbon 11 and to move forward.

Affected products: wkc-glossary, wkc-workflow, wkc-reference-data.
