### ISSUE TITLE
DataSpreadsheet: design release review

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#1976]
## Design review

FYI @mitchellbernstein

Component epic #1653 

### Standards

- [ ] All pattern updates/changes/iterations have been discussed with the
      component developer
- [ ] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [ ] The component behaves according to the guidelines set by the pattern
      maintainer
- [ ] The component’s UI matches the pattern specifications set by the pattern
      maintainer
- [ ] The component’s motion matches the specifications set by the pattern
      maintainer(s)
- [ ] The UI produced is responsive, cross-browser, and responds to the
      currently set Carbon theme.
- [ ] Colors, themes, sizes and additional props are true and correct, aligning
      with Carbon set tokens (unless otherwise specified by the pattern)
- [ ] Paddings/margins/spacings are true and correct, in both desktop and mobile
      views

### Storybook

- [x] A functioning component renders in Storybook
- [x] The Storybook displays multiple scenarios that show how the component can
      be used
- [x] Changing props in the Storybook updates the component

**Comment by matthewgallo** [comment]
Items discussed during latest design review:

- [ ] Resizable columns
- [ ] Reordering rows
- [ ] Cell header border color
- [ ] Cell contents on top of selection area
- [ ] Command + Click in safari doesn’t work

**Comment by chloeleekjh** [comment]
**Design review**


**1. (Visual) The font color of the selected status should follow the visual specification.**
<img width="734" alt="image" src="https://user-images.githubusercontent.com/110915132/183904417-c91257be-6867-4a98-a42f-b7a1b502a67b.png">


**2. (Visual) When the rows are multi-selcted, there shouldn't be the inner lines.**
<img width="651" alt="image" src="https://user-images.githubusercontent.com/110915132/183904757-ad664c80-77dc-42e9-b4e6-66de1389d4c2.png">


**3. (Visual) The selected status in the Gray 100 theme should follow the visual spec.**
<img width="575" alt="image" src="https://user-images.githubusercontent.com/110915132/183905319-05841692-64c2-4508-85e7-93201d9dfb59.png">

**Comment by chloeleekjh** [comment]
**Design review**

**4.(Behaviour) When there is a long content in the edit mode, it should not cover the whole row, yet should be treated like the specification below.**

<img width="587" alt="image" src="https://user-images.githubusercontent.com/110915132/183905692-b634fa8b-4981-44e1-87d2-a0fe80ebdf49.png">

**5. (Behaviour) Currently there is no hover effect applied. The headers should be highlighted as below.**
<img width="586" alt="image" src="https://user-images.githubusercontent.com/110915132/183906139-4384acc0-d605-4643-821e-213a6d54b456.png">



6. (Behaviour) Multi-row selection is not possible with `Shift` key.
<img width="582" alt="image" src="https://user-images.githubusercontent.com/110915132/183906441-a8a725ae-a43f-429a-a82d-649162ff2e8f.png">


**7. (Behaviour) Overall delete behaviour is not supported**
<img width="581" alt="image" src="https://user-images.githubusercontent.com/110915132/183906796-4b32f426-796c-4292-9a6e-50d0448c9b4a.png">



**8. Not sure if it's in our scope but optional examples like the context menu 
/panel options are not supported.**

**Comment by janhassel** [comment]
This is great! Just a few things I noticed:

1. Since you'll always need to provide an ID for `aria-labelledby`, there must be no `#` in front of the labelling element's ID.
https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/3f3588f5521d23e8bd74fb5fdd56101ea2952e34/packages/cloud-cognitive/src/components/DataSpreadsheet/DataSpreadsheet.js#L907

2. Shortcut <kbd>Ctrl</kbd><kbd>Home</kbd> is missing
Focus first cell in first row

3. Shortcut <kbd>Ctrl</kbd><kbd>End</kbd> is missing
Focus last cell in last row

4. When using the VoiceOver cursor to navigate through the spreadsheet and "clicking" on a cell to edit, the relationship is broken and when the user tries to navigate with the VoiceOver cursor without submitting the changes, they land back on the first cell in the first row. You could try setting `aria-owns` on the gridcell to the id of the textarea.

5. The deadzone button in the top left is missing a label (can be invisible).
<img width="99" alt="image" src="https://user-images.githubusercontent.com/28265588/184145974-364f38ea-a86a-411e-a53e-40fe18436117.png">

6. The entire grid needs to have a programmatically determinable name. Should this be enforced somehow by the component (e.g. requiring an `aria-label` prop) or should this be handled exclusively by the implementing team?

**Comment by elycheea** [comment]
@allcontributors add @janhassel and @chloeleekjh for design

**Comment by matthewgallo** [comment]
Thank you @chloeleekjh and @janhassel for both of your feedback here. I have first gone through Jan's feedback, I was able to address most of the items.

For 2 and 3, this works based on the resource key (control for windows and command on mac). I added labels for items 1, 5, and 6. Would you be able to provide a screen recording of the VoiceOver issue. I don't think I'm fully understanding the problem there.

**Comment by matthewgallo** [comment]
Hi @chloeleekjh, I've had a chance to address some of the items you mentioned above. I have some notes that I'll leave below:

1. Updated active cell text color to use `text-secondary`/`text-02`
2. I think this is the intended behavior because the rows are separate selection areas. For example, if you use shift + click or shift + arrow keys you can change the size of the current selection area which will update the selection area without the inner lines. For example, see below:
![image](https://user-images.githubusercontent.com/10215203/186425365-bd069d78-a553-404f-a302-31a3b069f341.png)
3. I've made updates to use cyan in dark mode
4. In terms of the width of the cell when it is being edited, we tried to follow behavior similar to google sheets and excel where the editing cell increases by increments of the cell's width until it reaches the outer container at which point it begins to wrap.
5. When reviewing the hover guidance, we found that neither google sheets or excel support this interaction. Can we review this interaction?
6. Multi row selection is still left to be completed, I'll try to address it this week
7. Cell deletion has been added with this [PR](https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/2220)

**Comment by matthewgallo** [comment]
Hi @chloeleekjh and @janhassel 👋  would you be able to review the updates here. Mitchell and I had discussed about adding multi row selection (with shift key) after the initial release of this component. Is that something that still sounds ok?

**Comment by chloeleejh** [comment]
Hi @matthewgallo Thank you for the updates.
I had time to review everything here below:
1. This looks great.
2. I agree with the distinction between the selected 'area' vs. multiple selected 'lines'. So update is needed.
3. This looks great.
4. I am okay with that.
5. I'd say this is a very additional feature that can be aborted right now.
6. Thank you.
7. Couldn't check the progress in [here](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-dataspreadsheet-dataspreadsheet-canary--with-many-columns)

**Comment by elycheea** [comment]
> Additional point: I found that currently there is no guideline about the 'resizing columns' which is a quite crucial point for the users..Not sure how it was communicated by Mitchell before but this should be the next important item to work on for both design guidelines and implementation.

We’re heading to the Accessibility Guild today to discuss columns resizing for Datagrid today, and we’ve asked some of the designers from Datagrid to attend as well. It might be a bit late for you, but we can share an update since I expect we’ll want the resize behavior to be similar.

**Comment by chloeleejh** [comment]
@elycheea Sounds great! please share the update here in this thread so we could track it! @matthewgallo Putting our Slack discussion here so we do not miss these later. Just in case.
<img width="1019" alt="Screenshot 2022-11-21 at 09 34 00" src="https://user-images.githubusercontent.com/10721141/203003015-6331a46d-03f2-48ca-bef3-ae58b68849f9.png">

**Comment by elycheea** [comment]
@chloeleejh Hi! Forgot to follow up on this but this is the prototype of the behavior we’re pursuing.
https://deploy-preview-2464--carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--basic-usage
