### ISSUE TITLE
Combo Button

### ISSUE THREAD

**Issue by qbi11y** [carbon-design-system/ibm-products#2075]
Make updates to the combo button component per designer design updates. This breaks 1430 into smaller issues:[https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/1430](url)

**Comment by qbi11y** [comment]
Questions to be answered:
* .bx--btn is a Carbon class set to 63px
* Is it truly 160px min-width
* Is adding rules a Carbon ask?
* how do sizes get added?

**Comment by elycheea** [comment]
Based on Popover component, which is v11. For current v10 version, we’ll need to use Overflow but can update to Popover for v11 version.

**Comment by elycheea** [comment]
https://react.carbondesignsystem.com/?path=/story/experimental-unstable-combobutton--default
