### ISSUE TITLE
Combo button design review

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#2148]
## Design review

Component epic #

### Standards

- [ ] All pattern updates/changes/iterations have been discussed with the
      component developer
- [x] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [ ] The component behaves according to the guidelines set by the pattern
      maintainer
- [ ] The component’s UI matches the pattern specifications set by the pattern
      maintainer
- [x] The component’s motion matches the specifications set by the pattern
      maintainer(s)
- [ ] The UI produced is responsive, cross-browser, and responds to the
      currently set Carbon theme.
- [x] Colors, themes, sizes and additional props are true and correct, aligning
      with Carbon set tokens (unless otherwise specified by the pattern)
- [ ] Paddings/margins/spacings are true and correct, in both desktop and mobile
      views

### Storybook

- [x] A functioning component renders in Storybook
- [x] The Storybook displays multiple scenarios that show how the component can
      be used
- [x] Changing props in the Storybook updates the component

**Comment by qbi11y** [comment]
Component behaves according to the guidelines set by the pattern maintainer
- Focus width needs to be 100%
- Remove icon support, remove the storybook example
- Padding 1rem on each side of icon
- Large is larger than expected should be 48, icon button should be complete square (default not lg)
- Disable, and Danger only on menu item
- Disable button itself
- Carbon icon button should be used as the icon button

UI produced is responsive, cross-browser, and responds to the
currently set Carbon theme.
- when menu is open icon button gets darker g90/g100, shadow as well on menu button
- Active state or not active state for icon button (Laura talk to Carbon team)
- Remove active state color after click, so it doesn't persist, cds-primary color

Paddings/margins/spacings are true and correct, in both desktop and mobile views
- min width 160px
