### ISSUE TITLE
Side panel: Title truncation does not occur on strings with no spaces

### ISSUE THREAD

**Issue by joyful-these** [carbon-design-system/ibm-products#2185]
## Detailed description

If a long string with no spaces is entered in the title prop of the Side panel component, truncation does not occur like it should.
For example, a title like "WWWWWWWWWWWWWWWWWWWWWWWWWWWWW" will get cut off on the first line, without a visual cue that the title is longer. It should be truncated with an ellipsis.

## Screenshots

![Screenshot 2022-08-16 at 09-40-58 Carbon for IBM Products](https://user-images.githubusercontent.com/108295261/184901945-27bf652f-6e8d-40ce-8142-5e19714c65d1.png)
Demonstration of the bug.

![Screenshot 2022-08-16 at 10-07-20 Carbon for IBM Products](https://user-images.githubusercontent.com/108295261/184902085-994ddc6d-05c8-474b-bf15-d91e6ca7c022.png)
Typical truncation behavior.

**Comment by punnoosewilson** [comment]
@joyful-these 
The **Side panel: Title truncation** issue is resolved. 
<img width="1490" alt="image" src="https://user-images.githubusercontent.com/40118548/187910306-b76be8f4-b47b-46f3-882e-c0c2e69466a3.png">

You can check and close the issue.
