### ISSUE TITLE
Release: lock file does not get updated in publish commit

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#2186]
## What will this achieve?

Because package versions change after each release, the lock file should also be updated. When we upgraded yarn versions we had to add `YARN_ENABLE_IMMUTABLE_INSTALLS` to the release action to allow things to run as expected (given that the action will cause yarn lock changes), however, it looks like including this flag also does not add `yarn.lock` in the publish commit. We need to figure out a way to make sure it's included otherwise it has to be done manually after the fact.

Affects both v10 and v11 releases.

## How will success be measured?

When `yarn.lock` is included in publish commit once again

## Additional information

- Designs
- Existing code
- etc

**Comment by elycheea** [comment]
Believe this is still an issue we need to investigate.
