### ISSUE TITLE
Enhancement: change RemoveModal prop type for body

### ISSUE THREAD

**Issue by arimori** [carbon-design-system/ibm-products#2289]
# Name of component or pattern
[RemoveModal](https://carbon-for-ibm-products.netlify.app/?path=/docs/ibm-products-patterns-remove-removemodal--standard)
## Brief description
The idea is to make the `body` prop able to accept node as value instead of just "string" in order to allow adding more detailed texts to the component. It doesn't break if passing `ReactNode` component, however it causes warning messages about the prop type.

## Example:
This is an example of the a `RemoveModal` that receives as `body` prop the following HTML:
```jsx
  const Body = () => (
    <>
      <span>
        Removing bx1001 will permanently remove the configuration.
      </span>
      <span>
        <strong>Note: </strong> This action cannot be undone.
      </span>
    </>
  );
``` 
![RemoveModal_Example](https://user-images.githubusercontent.com/46824758/193048437-7186bbf2-58dc-47ab-b58a-6d8e98c9477c.png)

## Details
[Link to example or existing component - RemoveModal](https://carbon-for-ibm-products.netlify.app/?path=/docs/ibm-products-patterns-remove-removemodal--standard)

**Comment by adamlsmith981** [comment]
@matthewgallo yep i can do :)
