### ISSUE TITLE
Page Header Title Icon is missing css className 'c4p--page-header__title-icon' when icon is used as a function

### ISSUE THREAD

**Issue by akhandsi** [carbon-design-system/ibm-products#2458]
## What package(s) are you using?

- [X] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

When using the Page Header components from @carbon/ibm-products 
https://v11-carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-page-header-pageheader--fully-loaded-and-some

For me, the following code will add this class 'c4p--page-header__title-icon' into title SVG
`
title: {
   icon: User,
   text: 'Title Text',
},
`
However, the following code does not add the expected class
`
title: {
    icon: (): ReactElement => <User size={24}/>,
    text: 'Title Text',
},
`
> What version of the @carbon/ibm-products 
> 2.0 rc

## Steps to reproduce the issue

1. Create a page header component
2. Supply title as an object where icon is a function rather then object
3. Notice the padding are off, investigate to see 'c4p--page-header__title-icon' is missing from title svg

## Additional information

![Screen Shot 2022-11-10 at 5 12 48 PM](https://user-images.githubusercontent.com/8444514/201364579-571a67c1-7408-4065-83a1-7da84a919b1a.png)

**Comment by SimonFinney** [comment]
@akhandsi For this, I believe the syntax would be:

```js
icon: (props) => <User size={24} {...props} />
```
