### ISSUE TITLE
TagSet popover content is overlapping another TagSet values

### ISSUE THREAD

**Issue by shankar343** [carbon-design-system/ibm-products#2486]
## What package(s) are you using?

 "@carbon/ibm-products": "2.0.0-rc.2"
"@carbon/react": "^1.16.0",
Carbon v11

## Detailed description
When we clicking on TagSet component, the popover container of it overlaps next TagSet Component. And it just overflow its parent component. In Prev version, tooltip component was implemented, which was not overlapping another TagSet.

> Is this issue related to a specific component?
Yes TagSet Component of "@carbon/ibm-products": "2.0.0-rc.2"

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Popover container of a TagSet shouldn't overlap another tagset

> What browser are you working in?
All Browser

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
"@carbon/ibm-products": "2.0.0-rc.2"

> Please create a reduced test case in CodeSandbox
>https://codesandbox.io/s/nostalgic-cherry-ygp2bu?file=/src/App.js

<img width="166" alt="image" src="https://user-images.githubusercontent.com/30149749/203354796-074f67ee-5f8d-4ce2-9114-68e1f6ebe74e.png">

- Screenshots or code
- Notes

**Comment by elycheea** [comment]
This appears to be the same issue. Looks like a PR is already opened to address this. 🤞  
https://github.com/carbon-design-system/carbon/issues/12142
