### ISSUE TITLE
Datagrid design review: Filtering

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#2500]
## Design review — Filter flyout and summary

- Component epic #1607 #2499
- Designers/reviewers: Virginia Nicholson, Shelley Dignum (@sdignum)
- Links: [PAL guidance](https://pages.github.ibm.com/cdai-design/pal/components/data-table/filters) / [Storybook, flyout](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-flyout--flyout-batch)

---

### Standards

- [ ] All pattern updates/changes/iterations have been discussed with the
      component developer
- [ ] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [ ] The component behaves according to the guidelines set by the pattern
      maintainer
- [ ] The component’s UI matches the pattern specifications set by the pattern
      maintainer
- [ ] The component’s motion matches the specifications set by the pattern
      maintainer(s)
- [ ] The UI produced is responsive, cross-browser, and responds to the
      currently set Carbon theme.
- [ ] Colors, themes, sizes and additional props are true and correct, aligning
      with Carbon set tokens (unless otherwise specified by the pattern)
- [ ] Paddings/margins/spacings are true and correct, in both desktop and mobile
      views

### Storybook

- [ ] A functioning component renders in Storybook
- [ ] The Storybook displays multiple scenarios that show how the component can
      be used
- [ ] Changing props in the Storybook updates the component

**Comment by elycheea** [comment]
## Design review — Filter panel

- Component epic #1607 #2499
- Designers/reviewers: Virginia Nicholson, Shelley Dignum (@sdignum)
- Links: [PAL guidance](https://pages.github.ibm.com/cdai-design/pal/components/data-table/filters) / [Storybook](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--filtering)

---

### Standards

- [ ] All pattern updates/changes/iterations have been discussed with the
      component developer
- [ ] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [ ] The component behaves according to the guidelines set by the pattern
      maintainer
- [ ] The component’s UI matches the pattern specifications set by the pattern
      maintainer
- [ ] The component’s motion matches the specifications set by the pattern
      maintainer(s)
- [ ] The UI produced is responsive, cross-browser, and responds to the
      currently set Carbon theme.
- [ ] Colors, themes, sizes and additional props are true and correct, aligning
      with Carbon set tokens (unless otherwise specified by the pattern)
- [ ] Paddings/margins/spacings are true and correct, in both desktop and mobile
      views

### Storybook

- [ ] A functioning component renders in Storybook
- [ ] The Storybook displays multiple scenarios that show how the component can
      be used
- [ ] Changing props in the Storybook updates the component

**Comment by sdignum** [comment]
@AlexanderMelox 
Initial comments based on reviewing the filter flyout and summary work:

Looking great overall!! Thanks!

    - Filter summary
        - [ ] Add the rule (divider line) for filter summary to separate the search and action bar from the summary bar
        - [ ] Tags should be the filterable tags so a user can remove one filter at a time
        - [ ] Clear filters button should hug the filter tags (right now it's aligned right)
        - [ ] Where's the 'List all' chevron?
        - [ ] Label should match sentence case (first letter capitalized)
        - [ ] Overflow…currently flashing on first click, and fix line height
    
    - Filter flyout
        - [ ] Why is text input showing the code text?
        - [ ] Text input, when you type something in and then delete it, is registering a filter tag with a label but no value
        - [ ] Is there going to be the instant updates version (with no buttons)?
        - [ ] Single column option?
        - [ ] Responsive for mid size? (only see it responsive for mobile)
        - [ ] Mobile responsive is switching the flyout contents and clears the selected filters
        - [ ] Mobile responsive should only have 16px between options (looks like 32 right now)

**Comment by vsnichols** [comment]
Hey @AlexanderMelox ! Awesome work! I totally agree with Shelley's comments, especially the need for a single column option. 

I also think @sdignum we may need to think about how to handle this component as the viewport narrows, before it hits mobile. Currently it starts spilling past the edge of the table.

<img width="1351" alt="Screenshot 2023-01-26 at 8 04 57 AM" src="https://user-images.githubusercontent.com/39408106/214856771-24eff28d-dedc-400f-a16e-3143069542be.png">


For now Alex could we
- [ ] Move the filter icon to be as far right as possible in react storybook?

**Comment by AlexanderMelox** [comment]
Created and issue for the FilterFlyout responsiveness https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/2696

**Comment by My-Money29** [comment]
Conduction my own design review today, starting with repeating comments pointed out by @sdignum that can an be ticked-off as _done_.

**@sdignum's comments:** 

Filter summary 
- [x]  Tags should be the filterable tags so a user can remove one filter at a time
- [x] Tags not visible on instant
- [x]  Overflow…currently flashing on first click

Filter flyout:
- [x] Text input, when you type something in and then delete it, is registering a filter tag with a label but no value https://github.com/carbon-design-system/ibm-products/issues/2677

**Tomer's comments:**

1. Filter panel:
- [ ] Tooltip for the "Filter" panel is labeled "Open filters" - Should say "Filter"

2. Filter summary:
- [ ] Tag should be center aligned to the tooltip item.
![Screenshot 2023-11-08 at 15 17 29](https://github.com/carbon-design-system/ibm-products/assets/101175720/50829ba5-3080-4f9a-9712-b9c0366cce16)
- [ ] Date format presented in the Filter panel are mm/dd/yyyy and in the tags formatted as dd/mm/yyyy
![Screenshot 2023-11-08 at 15 23 46](https://github.com/carbon-design-system/ibm-products/assets/101175720/74930f9c-8bed-4e47-9423-b1c86b33f113)

3. Filter flyout:
- [ ] Tooltip for the "Filter" flyout is labeled "Open filters" - Should say "Filter"
- [ ] Filter flyout - "Visits" input field to be Number input field.
Tag result label to follow the default tag text format - sentence case, space between words.
- [ ] Password strength tag label result - Change tag label from "passwordStrength:" to "Password strength:"
- [ ] Marital status tag label result - Change tag label from "status" to "Marital status"

**Comment by elycheea** [comment]
> * [ ]  Label should match sentence case (first letter capitalized)
> * [ ] Tag result label to follow the default tag text format - sentence case, space between words.
> * [ ]  Password strength tag label result - Change tag label from "passwordStrength:" to "Password strength:"
> * [ ]  Marital status tag label result - Change tag label from "status" to "Marital status"

@sdignum @My-Money29 these will be addressed in #3892

Opened several follow up issues to hopefully address these although I’m currently suggested “list all” as a possible enhancement if we can ensure no breaking changes between current state and future state. #3894 and #3046
