### ISSUE TITLE
Datagrid design review: Horizontal scrolling and responsiveness

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#2509]
## Design review

- Component epic #1607 #2499
- Designers/reviewers: Virginia Nicholson, Jennifer Jennings (@jjennings7)
- Links: [PAL guidance](https://pages.github.ibm.com/cdai-design/pal/components/data-table/scrolling/usage) / [Storybook v2](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-datagrid-canary--frozen-columns) / [Storybook v1](https://v1-ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-datagrid-canary--frozen-columns) — for unfrozen rows, see batch actions or actions dropdown

---

### Standards

- [x] All pattern updates/changes/iterations have been discussed with the
      component developer
- [x] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [ ] The component behaves according to the guidelines set by the pattern
      maintainer
- [x] The component’s UI matches the pattern specifications set by the pattern
      maintainer
- [x] The component’s motion matches the specifications set by the pattern
      maintainer(s)
- [x] The UI produced is responsive, cross-browser, and responds to the
      currently set Carbon theme.
- [x] Colors, themes, sizes and additional props are true and correct, aligning
      with Carbon set tokens (unless otherwise specified by the pattern)
- [x] Paddings/margins/spacings are true and correct, in both desktop and mobile
      views

### Storybook

- [x] A functioning component renders in Storybook
- [ ] The Storybook displays multiple scenarios that show how the component can
      be used
- [x] Changing props in the Storybook updates the component

**Comment by matthewgallo** [comment]
• Rename `Sticky column` story to `Frozen columns`

**Comment by elycheea** [comment]
^ FYI @Ratheeshrajan

**Comment by jjennings7** [comment]
@matthewgallo @elycheea @Ratheeshrajan I'm unable to check the boxes in the design review section for some reason. Can one of you please check them off for me? With the exception of the following, all the rest can be marked:

> - [ ] The component behaves according to the guidelines set by the pattern maintainer

See Matt's comment above with the few small changes needed 


> - [ ] The Storybook displays multiple scenarios that show how the component can be used

There are no controls or knobs for this component. As we mentioned to Matt, it would be nice to include a control or knob so the storybook user can freeze or unfreeze the first column, or the last column (actions), or both. Currently, both are frozen in the example. 

Regarding @matthewgallo 's comment above:

> To think about:
> • Row index labels to left of selectable row/checkbox

Here's an example screenshot of what he's referring to from my product, DataStage:


![Screen Shot 2022-12-15 at 3 19 00 PM](https://user-images.githubusercontent.com/48838320/207987265-bdfd3e0b-f766-40a4-8da4-6b417326a96e.png)


One last thing I noticed is the title on the table, "click action menu". I don't think that's supposed to be there?

![Screen Shot 2022-12-15 at 3 21 38 PM](https://user-images.githubusercontent.com/48838320/207987503-3752df53-6af4-4407-9893-5fecbda13cd9.png)

**Comment by elycheea** [comment]
@jjennings7 We left off the row index changes for now since it caused some unexpected behaviors and felt like it’s out of scope for our first release. We can open a separate issue as an enhancement later. If the current changes look good, feel free to close this out. 🙆‍♀️

**Comment by elycheea** [comment]
Thank you @jjennings7!!

**Comment by elycheea** [comment]
@jjennings7 or @vsnichols just reopened so we can double check the behavior in v2 and check for accessibility.

**Comment by elycheea** [comment]
@kristastarr to review for accessibility.
Feel free to remove any checks that don’t apply.

---

## Accessibility review

### [Keyboard](https://www.ibm.com/able/toolkit/develop/keyboard)

#### Level 1

- [ ] Properly code the navigation order
  - [ ] Ensure interactive elements are reachable with the keyboard
  - [ ] Where possible, achieve the desired tab order by adjusting the DOM,
        rather than overriding the tabindex
  - [ ] When overriding the default focus indicator, confirm focus is highly
        visible
- [ ] Implement established keyboard conventions
  - [ ] Use standard HTML elements where possible, using CSS to alter appearance
        not behavior
  - [ ] Be familiar with established keyboard conventions
  - [ ] Implement keyboard operation for custom elements

#### Level 2

- [ ] Ensure keyboard access to complex interactions
  - [ ] Make custom media player and animation controls keyboard accessible

#### Level 3

- [ ] Code screen updates predictably
  - [ ] Use "activate" rather than "focus" as a trigger
  - [ ] Use an onchange event without disorienting the user

### [Dynamic updates](https://www.ibm.com/able/toolkit/develop/dynamic-updates)

#### Level 1

- [ ] Provide errors accessibly
  - [ ] Use accessible methods to implement error messages
  - [ ] Implement validation and notification to minimize interruptions

#### Level 2

- [ ] Make content accessible that appears on hover or focus
  - [ ] Ensure <kbd>Esc</kbd> dismisses new content
  - [ ] If content appears on hover, the new content needs to remain visible
        until dismissed
  - [ ] Moving the pointer away from the trigger should not be the action that
        dismisses the new content
  - [ ] Ensure custom tooltips and similar hover text can be triggered by
        keyboard
  - [ ] Discuss alternatives to hover text
  - [ ] Use caution where interactive controls appear in the hover text
- [ ] Code cancellation actions accessibly
  - [ ] Provide accessible ways of cancelling pointer interaction
- [ ] Properly code status messages
  - [ ] Use `role=status` to advise on the success or results of an action
  - [ ] Use `role=alert` or an ARIA live region to convey a suggestion or
        warning

#### Level 3

- [ ] Allow reduced motion
  - [ ] Implement motion media queries to reduce user risk

### [Text and non-text](https://www.ibm.com/able/toolkit/develop/text-and-non-text)

#### Level 1

- [ ] Implement text alternatives for meaningful images, sound, and visual data
  - [ ] Give decorative images an ALT attribute with an empty string (`alt=""`)
  - [ ] Use HTML, ARIA, or technology-specific techniques to add short text
        alternatives
  - [ ] Where relevant text exists in the UI, use `aria-labelledby` and
        `aria-describedby` to reference
  - [ ] Provide an accessible method for exposing long text alternatives
  - [ ] Embed multimedia content that supports closed captions
- [ ] Implement correct structure and metadata
  - [ ] Code headings according to specifications
  - [ ] ~Code the `<title>` element on every page according to specifications~
  - [ ] ~Set the language for each page~

#### Level 2

- [ ] Add additional structure where appropriate
  - [ ] Use `<figcaption>` and `<caption>` elements where figures and tables are
        titled
  - [ ] Add additional context to generic link names
  - [ ] Consider adding regions and other ARIA roles to distinguish text
        groupings

#### Level 3

- [ ] ~Mark up foreign words and abbreviations~
  - [ ] ~Use the `lang` attribute for foreign words and phrases~
  - [ ] Use `<abbr>` elements and title attributes to expand abbreviations
- [ ] Achieve necessary reading order
  - [ ] Order content appropriately in the DOM
  - [ ] Only use CSS to alter text position without altering meaning

### [User input](https://www.ibm.com/able/toolkit/develop/user-input)

#### Level 1

- [ ] Associate labels with inputs
  - [ ] Programmatically associate inputs with labels
  - [ ] Add accessible names for inputs lacking visible labels
- [ ] Provide correct name, role, and value
  - [ ] If repurposing a standard component, use ARIA to set the correct name
        and role
  - [ ] On custom components, use ARIA to expose `name`, `role`, and `value`

#### Level 2

- [ ] Reduce conflict between the visible label and a component's accessible
      name
  - [ ] Match the accessible name to the visible label
  - [ ] Include the text of the label in the accessible name

#### Level 3

- [ ] Indicate the purpose of common inputs
  - [ ] Use HTML `autocomplete` attributes, where appropriate

**Comment by kristastarr** [comment]
Styling comments:
1.  When resizing columns such that the text is truncated in one or more of the columns, on hover, the text in both columns shows and is overlapping 
<img width="1160" alt="Screenshot 2023-07-05 at 10 21 01 AM" src="https://github.com/carbon-design-system/ibm-products/assets/21047571/f2b66e89-e889-4469-9fa4-80053dfe458a">

2. When hovering the mouse on the table header text, the cursor appears as a `text` cursor which makes it look editable.  The title text does show on hover of the header text, but not on hover of the rest of the cell.  Is that the desired behavior? 

3. I re-sized the table in various ways and also used browser zoom to simulate a screen enlarger. I didn't investigate exactly when/why but sometimes there is an empty column between the headers, and sometimes the overflow menu column is the incorrect width, as shown here at 200% browser zoom: 
<img width="984" alt="Screenshot 2023-07-05 at 2 10 57 PM" src="https://github.com/carbon-design-system/ibm-products/assets/21047571/d571f9b3-f165-450c-8b53-83cc84536e8b">

4.  The L/R arrow keys correctly scroll the parts of the table that are not sticky.  However, depending on the width of the table, it's possible that it isn't evident that there are more columns than what are shown.  To me it's not really clear from a visual standpoint that the table is scrollable in those cases.   Example: here, it's not evident that there are 7 more columns in the table 
<img width="934" alt="Screenshot 2023-07-05 at 11 23 55 AM" src="https://github.com/carbon-design-system/ibm-products/assets/21047571/05b3a76b-8543-4255-9a43-6da307abd8d5">


Keyboard and Mac Voiceover testing: 
5.  As discussed in other issues (like https://github.com/carbon-design-system/ibm-products/issues/3118) we have the situation where the contents of each cell are a group, so you have to arrow three times to move to the next cell.  In this component, this behavior is present in table header and all table items here.  In the `Sort` component, it is not present in the table header but is there in the table items.  

6.  In this component as well as `Batch actions`, https://github.com/carbon-design-system/ibm-products/issues/3118 when a checkbox is selected, voiceover gives no indication that the blue "X items selected" bar appears and offers additional actions.  Could look at using aria-live to provide live updates that new content has been added to the screen
https://github.com/carbon-design-system/ibm-products/issues/3118

**Comment by jjennings7** [comment]
In addition to the styling issues Krista noted:

The tooltip for the action button seems to be within the table and not above it, so it gets cut off but you can scroll to see it, causing a white column to appear:

![Image](https://github.com/carbon-design-system/ibm-products/assets/48838320/e81e7761-228e-456b-8861-64f25500166e)

![Image](https://github.com/carbon-design-system/ibm-products/assets/48838320/7db27d9b-05b3-4f24-acf9-4155d54bf51c)

The vertical border to delineate the frozen columns seems to be missing in the header, so the header text looks cut off if it's partially scrolled:

![Image](https://github.com/carbon-design-system/ibm-products/assets/48838320/ff5afda1-7822-4952-b563-cc00fbfe3285)

![Image](https://github.com/carbon-design-system/ibm-products/assets/48838320/d460a8a4-9027-4b89-99c6-25a640cf51da)

Regarding the scroll bar issue Krista noted, not sure if it would exactly help that issue, but I noticed the scroll bar spans the entire width of the table instead of being contained within the scrollable area. Could/should it be contained?

![Image](https://github.com/carbon-design-system/ibm-products/assets/48838320/b59880bb-70a5-45e6-825f-d631a61d8f84)

And lastly, I would still like to see controls or knobs so that people checking out the component know they have a couple choices of which columns to freeze and they can try it out in the storybook.

**Comment by davidmenendez** [comment]
after reviewing the most up to date version of datagrid it appears that all of these concerns have been addressed with the exception of this note

> And lastly, I would still like to see controls or knobs so that people checking out the component know they have a couple choices of which columns to freeze and they can try it out in the storybook.

we've had some initial conversations about providing more sandboxes or codepens with datagrid examples so that users are able to interact more with the code. unfortunately, due to the nature of the mechanisms that datagrid is built on, storybook controls aren't well suited to allow users to turn things on and off.

closing this as complete 🥳
