### ISSUE TITLE
Text is cutoff in TagSet overflow list

### ISSUE THREAD

**Issue by AlexanderMelox** [carbon-design-system/ibm-products#2557]
<img width="194" alt="Screenshot 2022-12-09 at 6 40 54 PM" src="https://user-images.githubusercontent.com/12755042/206812614-d955d85d-fbed-4982-9035-fdb44f00b0c9.png">
<img width="169" alt="Screenshot 2022-12-09 at 6 43 20 PM" src="https://user-images.githubusercontent.com/12755042/206812793-2fdb1015-e8cb-4538-a872-dc8cf702911d.png">

## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

When using letters like 'p', the line heights cuts off

> Is this issue related to a specific component?

`<TagSet />`

> What browser are you working in?

Google chrome

**Comment by elycheea** [comment]
During team scrum today, we investigated and found that there’s border radius from the Carbon tag that is the cause and not line height.
