### ISSUE TITLE
Bring the IdeHome component from CDAI to ibm-products

### ISSUE THREAD

**Issue by marekdano** [carbon-design-system/ibm-products#2567]
# Name of component
**Home**

## Brief description

My team works on the [Event Streams](https://test.cloud.ibm.com/eventstreams-provisioning/6a7f4e38-f218-48ef-9dd2-df408747568e/create) service UI on IBM Cloud and the Home page is built with the [IdeHome](https://carbon-for-ibm-products.netlify.app/?path=/story/cd-ai-legacy-components-idehome-legacy--with-one-set) component from @carbon/ibm-cloud-cognitive-cdai. We're planning to upgrade the UI to carbon 11 which requires having IdeHome component in carbon 11. As we already know the @carbon/ibm-cloud-cognitive-cdai library will not be upgraded to carbon 11, so we'd like to ask to bring the IdeHome component to @carbon/ibm-products where carbon 11 is going to be available next year.

This is the screenshot of our home page that we need to have with carbon 11:
<img width="1586" alt="Screenshot 2022-11-29 at 16 48 56" src="https://user-images.githubusercontent.com/1914165/207544063-82e3cb76-5b65-4719-8065-c7c95275b416.png">

## Details

The current [IdeHome](https://carbon-for-ibm-products.netlify.app/?path=/story/cd-ai-legacy-components-idehome-legacy--with-one-set) component

## Design Maintainer(s)

- Owner/main maintainer(s)
- Second/backup maintainer(s)

## Tasks

Before starting work on this epic, please review and complete the following.

- [ ] Initial review of design/existing code

### Working in Carbon for IBM Products package

- [ ] Have you reviewed our
      [contribution guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/.github/CONTRIBUTING.md)?
- [ ] Have you noted our
      [code guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/docs/CODE_GUIDELINES.md)?
- [ ] Did you use the CLI to scaffold your new component?

**Comment by marekdano** [comment]
This is still required to be developed for the IBM Event Streams service when the Event Streams UI is move to carbon 11.

**Comment by asfordmatt** [comment]
We also use `IdeHome` in App Connect

**Comment by vic6** [comment]
+1 Api Connect also uses `IdeHome`

**Comment by sstrubberg** [comment]
Happy to revisit this if needed.

**Comment by stefan-cooper** [comment]
We also use `IdeHome` in Event Endpoint Management. It looks like we will need to create our own version of this component as part of our move to Carbon 11 as-is today.
