### ISSUE TITLE
Get click callback in expandable rows of Datagrid?

### ISSUE THREAD

**Issue by houhoucoop** [carbon-design-system/ibm-products#2603]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## What did you want to know?
According to the [README](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/1ed3a18d22e3368d11d26270681e815b560cba87/packages/cloud-cognitive/src/components/Datagrid/Datagrid.mdx#expandable-rows), the `Datagrid` supports expandable rows with the use of the `useExpandedRow` hook and able to custom the expanded content with `ExpandedRowContentComponent`, but it seems there is no way to get the click callback function or pass a custom click function when toggling the row?

**Comment by jagathgj** [comment]
Hi @elycheea , There is a possibility to get the click callback function or pass a custom click function without altering the codebase. Below is a hook function to do the same.

const useExpandListener = (hooks) => {
  const getProps = (props, { row }) => {
    return { ...props, onClick: () => { console.log('Row Toggled', row.id); props.onClick(); } }
  }
  hooks.getToggleRowExpandedProps.push(getProps);
};


Consumer can either use this hook or I can add it to codebase. Whats your thoughts on this?

**Comment by AlexanderMelox** [comment]
I do like this idea @jagathgj but I think it's prob easier just having the "handler" callbacks inside the components to avoid confusion. I do understand it tidy's up the codebase but in certain examples like FilterPanel, I have a lot more than just a click, I have an onChange handler on every input and an open and close callback.

**Comment by ConradSchmidt** [comment]
@AlexanderMelox adding a prop would (at some point) defeat the point of the hook system in the datagrid, because if you hard coding these features you remove the flexibility of the hook system.

You could integrate the `useExpandListener` into the repo, even though I'm not convinced that having this feature available will lead to good UX - triggering something else when expanding seems "disconnected" (it's not like clicking on a row).

If you still want to go the route of using a prop, be aware how this would work:
1. one hook which is applied to all rows
2. each row has its own hook

**Comment by AlexanderMelox** [comment]
@ConradSchmidt Sorry when I meant prop I meant the properties that we pass into useDatagrid()

**Comment by AlexanderMelox** [comment]
I would not use the hooks for developer things, where as the hooks in our situation are "plugins" that add extra functionality to the table. 

We've been using this approach before like below 
<img width="612" alt="Screenshot 2023-02-09 at 12 12 59 PM" src="https://user-images.githubusercontent.com/12755042/217887811-6a861a14-a739-4ed1-917e-9b2e2f04a9da.png">

**Comment by ConradSchmidt** [comment]
I guess its fine line between an addition to exiting feature (prop) and adding a new feature (hook), because an "on expansion click listener" can be seen as both. But I can see how an `onExpand` (`onExpandChange`) prop could work here :)

**Comment by elycheea** [comment]
@jagathgj Are you able to move forward with this one based on the discussions from @AlexanderMelox and @ConradSchmidt?

**Comment by jagathgj** [comment]
> @jagathgj Are you able to move forward with this one based on the discussions from @AlexanderMelox and @ConradSchmidt?

Yes @elycheea. I will add the event handler and callback function.
