### ISSUE TITLE
Datagrid design review: Row action buttons

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#2606]
## Design review

- Component epic #1607 #2499
- Designers/reviewers: 
- Links: [PAL guidance](https://pages.github.ibm.com/cdai-design/pal/components/data-table/row-action-buttons/usage) / [Storybook v2](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-rowactionbuttons--row-action-buttons-usage-story) / [Storybook v1](https://v1-ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-rowactionbuttons--row-action-buttons-usage-story)

---

Component epic #1609 

### Standards

- [ ] All pattern updates/changes/iterations have been discussed with the
      component developer
- [x] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [ ] The component behaves according to the guidelines set by the pattern
      maintainer
- [ ] The component’s UI matches the pattern specifications set by the pattern
      maintainer
- [x] The component’s motion matches the specifications set by the pattern
      maintainer(s)
- [ ] The UI produced is responsive, cross-browser, and responds to the
      currently set Carbon theme.
- [ ] Colors, themes, sizes and additional props are true and correct, aligning
      with Carbon set tokens (unless otherwise specified by the pattern)
- [ ] Paddings/margins/spacings are true and correct, in both desktop and mobile
      views

### Storybook

- [ ] A functioning component renders in Storybook
- [ ] The Storybook displays multiple scenarios that show how the component can
      be used
- [ ] Changing props in the Storybook updates the component

**Comment by elycheea** [comment]
@johannasuarez-koval or someone from her team can hopefully review this one.

**Comment by elycheea** [comment]
@thefirstartist to help with accessibility.
Feel free to remove any checks that don’t apply.

---

## Accessibility review

### [Keyboard](https://www.ibm.com/able/toolkit/develop/keyboard)

#### Level 1

- [ ] Properly code the navigation order
  - [ ] Ensure interactive elements are reachable with the keyboard
  - [ ] Where possible, achieve the desired tab order by adjusting the DOM,
        rather than overriding the tabindex
  - [ ] When overriding the default focus indicator, confirm focus is highly
        visible
- [ ] Implement established keyboard conventions
  - [ ] Use standard HTML elements where possible, using CSS to alter appearance
        not behavior
  - [ ] Be familiar with established keyboard conventions
  - [ ] Implement keyboard operation for custom elements

#### Level 2

- [ ] Ensure keyboard access to complex interactions
  - [ ] Make custom media player and animation controls keyboard accessible

#### Level 3

- [ ] Code screen updates predictably
  - [ ] Use "activate" rather than "focus" as a trigger
  - [ ] Use an onchange event without disorienting the user

### [Dynamic updates](https://www.ibm.com/able/toolkit/develop/dynamic-updates)

#### Level 1

- [ ] Provide errors accessibly
  - [ ] Use accessible methods to implement error messages
  - [ ] Implement validation and notification to minimize interruptions

#### Level 2

- [ ] Make content accessible that appears on hover or focus
  - [ ] Ensure <kbd>Esc</kbd> dismisses new content
  - [ ] If content appears on hover, the new content needs to remain visible
        until dismissed
  - [ ] Moving the pointer away from the trigger should not be the action that
        dismisses the new content
  - [ ] Ensure custom tooltips and similar hover text can be triggered by
        keyboard
  - [ ] Discuss alternatives to hover text
  - [ ] Use caution where interactive controls appear in the hover text
- [ ] Code cancellation actions accessibly
  - [ ] Provide accessible ways of cancelling pointer interaction
- [ ] Properly code status messages
  - [ ] Use `role=status` to advise on the success or results of an action
  - [ ] Use `role=alert` or an ARIA live region to convey a suggestion or
        warning

#### Level 3

- [ ] Allow reduced motion
  - [ ] Implement motion media queries to reduce user risk

### [Text and non-text](https://www.ibm.com/able/toolkit/develop/text-and-non-text)

#### Level 1

- [ ] Implement text alternatives for meaningful images, sound, and visual data
  - [ ] Give decorative images an ALT attribute with an empty string (`alt=""`)
  - [ ] Use HTML, ARIA, or technology-specific techniques to add short text
        alternatives
  - [ ] Where relevant text exists in the UI, use `aria-labelledby` and
        `aria-describedby` to reference
  - [ ] Provide an accessible method for exposing long text alternatives
  - [ ] Embed multimedia content that supports closed captions
- [ ] Implement correct structure and metadata
  - [ ] Code headings according to specifications
  - [ ] ~Code the `<title>` element on every page according to specifications~
  - [ ] ~Set the language for each page~

#### Level 2

- [ ] Add additional structure where appropriate
  - [ ] Use `<figcaption>` and `<caption>` elements where figures and tables are
        titled
  - [ ] Add additional context to generic link names
  - [ ] Consider adding regions and other ARIA roles to distinguish text
        groupings

#### Level 3

- [ ] ~Mark up foreign words and abbreviations~
  - [ ] ~Use the `lang` attribute for foreign words and phrases~
  - [ ] Use `<abbr>` elements and title attributes to expand abbreviations
- [ ] Achieve necessary reading order
  - [ ] Order content appropriately in the DOM
  - [ ] Only use CSS to alter text position without altering meaning

### [User input](https://www.ibm.com/able/toolkit/develop/user-input)

#### Level 1

- [ ] Associate labels with inputs
  - [ ] Programmatically associate inputs with labels
  - [ ] Add accessible names for inputs lacking visible labels
- [ ] Provide correct name, role, and value
  - [ ] If repurposing a standard component, use ARIA to set the correct name
        and role
  - [ ] On custom components, use ARIA to expose `name`, `role`, and `value`

#### Level 2

- [ ] Reduce conflict between the visible label and a component's accessible
      name
  - [ ] Match the accessible name to the visible label
  - [ ] Include the text of the label in the accessible name

#### Level 3

- [ ] Indicate the purpose of common inputs
  - [ ] Use HTML `autocomplete` attributes, where appropriate

**Comment by thefirstartist** [comment]
1. When there are only one or two actions, show action buttons on hover only.
<img width="501" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/40870771/e1f3c18a-cb5b-4dbe-b6c6-9bb05437339b">

2. When the overflow menu is opened near the bottom of the page, the menu got cut off.
<img width="514" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/40870771/c8e3195e-539f-45fb-a00e-68d3f5a2e878">

3. In pagination, next and previous page icon should be disabled when there's only one page.
<img width="286" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/40870771/76b8866b-7fa0-494c-ba3d-6cfb444acb21">

**Comment by elycheea** [comment]
@thefirstartist 

> When there are only one or two actions, show action buttons on hover only. However, when a [frozen column](https://pages.github.ibm.com/cdai-design/pal/components/data-table/scrolling/usage#frozen-columns) is used, those actions will be moved into a persistent overflow menu once horizontal scrolling kicks in.

Since you also volunteered for the design review, curious what your thoughts are on this. I lean towards investigating this behavior as an enhancement and releasing without this behavior at first so we can explore the interaction a bit more. As we discussed in DSAG last time, if you cannot tab through each row, it may be tricky to focus on the actions if they appear on hover. I’m less familiar with the `Datagrid` extensions so don’t know if this would actually be quite simple.

> When the overflow menu is opened near the bottom of the page, the menu got cut off.

@matthewgallo Can we look into whether or not `OverflowMenu` in Carbon 11 also support `autoAlign`? Or there might be an easier option. I’m not sure we can assume that the last (or last few) row should change overflow direction so trying to weigh our options. Or can product teams change the row action menu direction? 🤔

**Comment by thefirstartist** [comment]
**Design review:**
1. Column headers need to be in sentence-case. Row index, First name, Last name. ([Content guide](https://carbondesignsystem.com/components/data-table/usage#content))
2. Column header can be truncated only if it is more than 2 words.  ([Content guide](https://carbondesignsystem.com/components/data-table/usage#content))
<img width="699" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/40870771/215eb679-ae6c-4dea-a7d7-7bf55ec4a5d1">

**Comment by elycheea** [comment]
Linking this as a related issue: https://github.com/carbon-design-system/ibm-products/issues/3226

**Comment by elycheea** [comment]
@vsnichols @thefirstartist Wanted to route back to the conversation on row action button behavior since Virginia reached out this morning. We’re noticing discrepancies between the guidance for [frozen columns](https://pages.github.ibm.com/cdai-design/pal/components/data-table/scrolling/usage#frozen-columns) and [row action buttons](https://pages.github.ibm.com/cdai-design/pal/components/data-table/row-action-buttons/usage).

So to clarify, we’re suggesting a few different behaviors for row actions —
- If 2 row actions exist, each shows on hover but not frozen*
  - 2 row actions should never be frozen??
- If more than 2 row actions exist, these become an overflow menu that appears on hover
  - The overflow menu _can_ be frozen

*Does this mean they can also be scrolled off the page? Are we reserving the space for them (similar to frozen columns), or do they remain fixed but obscure content when the Datagrid scrolls — or do they scroll with the Datagrid entirely?

**Comment by elycheea** [comment]
FYI @matthewgallo

**Comment by thefirstartist** [comment]
@elycheea 
I think that 2 row actions should never be frozen. Otherwise, you'd see an empty column on the right of the table until users hover over them. It's acceptable if they become scrollable off the page. 
Another option is using an overflow menu for all actions, whether 1, 2, or more than 2, when they are frozen. This way, we can address the empty column issue and prevent them from scrolling off the page.

**Comment by vsnichols** [comment]
@thefirstartist that is definitely what I am recommending - when frozen we always use an overflow

**Comment by vsnichols** [comment]
@elycheea does the above address your concerns? Is there anything I need to address specifically? The [row action guidance](https://pages.github.ibm.com/cdai-design/pal/components/data-table/row-action-buttons/usage) spells out the expected behavior pretty well - additionally the [scrolling guidance ](https://pages.github.ibm.com/cdai-design/pal/components/data-table/row-action-buttons/usage)specifies that row actions should change to an overflow menu if the action column is frozen.

![Screenshot 2023-10-24 at 8 34 15 AM](https://github.com/carbon-design-system/ibm-products/assets/39408106/55f4221d-f3bd-4eba-ad7c-518ff4db7753)

**Comment by matthewgallo** [comment]
The changes included in https://github.com/carbon-design-system/ibm-products/pull/3778 address all of the items in this design review. I think we'll be able to close this once it is merged.
