### ISSUE TITLE
Datagrid design review: Batch actions

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#2607]
## Design review

- Component epic #1607 #2499
- Designers/reviewers: 
- Links: [PAL guidance](https://pages.github.ibm.com/cdai-design/pal/components/data-table/batchactions/usage) / [Storybook](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--batch-actions) / [Storybook](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--select-items-in-all-pages)

---

### Standards

- [ ] All pattern updates/changes/iterations have been discussed with the
      component developer
- [ ] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [ ] The component behaves according to the guidelines set by the pattern
      maintainer
- [ ] The component’s UI matches the pattern specifications set by the pattern
      maintainer
- [ ] The component’s motion matches the specifications set by the pattern
      maintainer(s)
- [ ] The UI produced is responsive, cross-browser, and responds to the
      currently set Carbon theme.
- [ ] Colors, themes, sizes and additional props are true and correct, aligning
      with Carbon set tokens (unless otherwise specified by the pattern)
- [ ] Paddings/margins/spacings are true and correct, in both desktop and mobile
      views

### Storybook

- [ ] A functioning component renders in Storybook
- [ ] The Storybook displays multiple scenarios that show how the component can
      be used
- [ ] Changing props in the Storybook updates the component

**Comment by elycheea** [comment]
@vsnichols 💪

**Comment by elycheea** [comment]
@kristastarr to review for accessibility.
Feel free to remove any checks that don’t apply.

---

## Accessibility review

### [Keyboard](https://www.ibm.com/able/toolkit/develop/keyboard)

#### Level 1

- [ ] Properly code the navigation order
  - [ ] Ensure interactive elements are reachable with the keyboard
  - [ ] Where possible, achieve the desired tab order by adjusting the DOM,
        rather than overriding the tabindex
  - [ ] When overriding the default focus indicator, confirm focus is highly
        visible
- [ ] Implement established keyboard conventions
  - [ ] Use standard HTML elements where possible, using CSS to alter appearance
        not behavior
  - [ ] Be familiar with established keyboard conventions
  - [ ] Implement keyboard operation for custom elements

#### Level 2

- [ ] Ensure keyboard access to complex interactions
  - [ ] Make custom media player and animation controls keyboard accessible

#### Level 3

- [ ] Code screen updates predictably
  - [ ] Use "activate" rather than "focus" as a trigger
  - [ ] Use an onchange event without disorienting the user

### [Dynamic updates](https://www.ibm.com/able/toolkit/develop/dynamic-updates)

#### Level 1

- [ ] Provide errors accessibly
  - [ ] Use accessible methods to implement error messages
  - [ ] Implement validation and notification to minimize interruptions

#### Level 2

- [ ] Make content accessible that appears on hover or focus
  - [ ] Ensure <kbd>Esc</kbd> dismisses new content
  - [ ] If content appears on hover, the new content needs to remain visible
        until dismissed
  - [ ] Moving the pointer away from the trigger should not be the action that
        dismisses the new content
  - [ ] Ensure custom tooltips and similar hover text can be triggered by
        keyboard
  - [ ] Discuss alternatives to hover text
  - [ ] Use caution where interactive controls appear in the hover text
- [ ] Code cancellation actions accessibly
  - [ ] Provide accessible ways of cancelling pointer interaction
- [ ] Properly code status messages
  - [ ] Use `role=status` to advise on the success or results of an action
  - [ ] Use `role=alert` or an ARIA live region to convey a suggestion or
        warning

#### Level 3

- [ ] Allow reduced motion
  - [ ] Implement motion media queries to reduce user risk

### [Text and non-text](https://www.ibm.com/able/toolkit/develop/text-and-non-text)

#### Level 1

- [ ] Implement text alternatives for meaningful images, sound, and visual data
  - [ ] Give decorative images an ALT attribute with an empty string (`alt=""`)
  - [ ] Use HTML, ARIA, or technology-specific techniques to add short text
        alternatives
  - [ ] Where relevant text exists in the UI, use `aria-labelledby` and
        `aria-describedby` to reference
  - [ ] Provide an accessible method for exposing long text alternatives
  - [ ] Embed multimedia content that supports closed captions
- [ ] Implement correct structure and metadata
  - [ ] Code headings according to specifications
  - [ ] ~Code the `<title>` element on every page according to specifications~
  - [ ] ~Set the language for each page~

#### Level 2

- [ ] Add additional structure where appropriate
  - [ ] Use `<figcaption>` and `<caption>` elements where figures and tables are
        titled
  - [ ] Add additional context to generic link names
  - [ ] Consider adding regions and other ARIA roles to distinguish text
        groupings

#### Level 3

- [ ] ~Mark up foreign words and abbreviations~
  - [ ] ~Use the `lang` attribute for foreign words and phrases~
  - [ ] Use `<abbr>` elements and title attributes to expand abbreviations
- [ ] Achieve necessary reading order
  - [ ] Order content appropriately in the DOM
  - [ ] Only use CSS to alter text position without altering meaning

### [User input](https://www.ibm.com/able/toolkit/develop/user-input)

#### Level 1

- [ ] Associate labels with inputs
  - [ ] Programmatically associate inputs with labels
  - [ ] Add accessible names for inputs lacking visible labels
- [ ] Provide correct name, role, and value
  - [ ] If repurposing a standard component, use ARIA to set the correct name
        and role
  - [ ] On custom components, use ARIA to expose `name`, `role`, and `value`

#### Level 2

- [ ] Reduce conflict between the visible label and a component's accessible
      name
  - [ ] Match the accessible name to the visible label
  - [ ] Include the text of the label in the accessible name

#### Level 3

- [ ] Indicate the purpose of common inputs
  - [ ] Use HTML `autocomplete` attributes, where appropriate

**Comment by kristastarr** [comment]
Keyboard accessibility: 
The only concern I have is that when you are on Primary button, and press tab with the intention of moving to the checkbox in the first table row, you have to press tab 3 extra times before you end up there.  It is not clear where focus is during those extra tabs.  This may be more toolbar-related, and I documented it in https://github.com/carbon-design-system/ibm-products/issues/3117 as well.  

The checkboxes on the table items can successfully be checked/selected using space bar.  Is there a reason they cannot be selected by pressing enter as well? If no, might be something to consider. 

Not accessibility related, but I love the micro-animation of the blue "X items selected" bar that appears when you select an item 🙌

**Comment by kristastarr** [comment]
Voiceover testing using Mac voiceover:
1. Checkboxes - Each checkbox is correctly indicated as "checked" or "unchecked" but it is unclear what each checkbox is tied to, ie if I check a checkbox, it is not clear what I am selecting - what is in that row, etc. so it needs some aria labels - probably could use "aria-labeledby" to label each checkbox with content from a certain column.  See screenshot for voiceover description :
<img width="830" alt="Screenshot 2023-07-05 at 9 40 02 AM" src="https://github.com/carbon-design-system/ibm-products/assets/21047571/4790a9da-134b-4e5b-84ff-e02701cfdf00">

If the table itself had a description or label, it might help give some context to what I would be doing if I were "selecting all" or "deselecting all", but even with that, it would not be clear for each individual row. 

Also once I check or uncheck a checkbox, I'm not sure how to get the screenreader to proceed with reading the rest of the row content.  I can tab to the next checkbox, but that seems to be all I can do.

**Comment by vsnichols** [comment]
## Design review

This is coming along but there are still some fairly significant visual bugs in the [Carbon storybook](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--batch-actions):

- [ ] Batch action options are not vertically center aligned
- [ ] Responsive behavior does not act as expected
- [ ] "More" option should appear programmatically with a chevron not a + icon
- [ ] Add behavior for [actions across multiple pages](https://pages.github.ibm.com/cdai-design/pal/components/data-table/batchactions/usage#actions-across-multiple-pages) - show knob/ option in storybook

@elycheea @kristastarr  FYI

### Batch action options are not vertically center aligned

Actual

<img width="1204" alt="Screenshot 2023-07-11 at 5 02 27 PM" src="https://github.com/carbon-design-system/ibm-products/assets/39408106/3208fb16-4eec-4166-a93f-d1e6972f9f57">

Expected

<img width="931" alt="Screenshot 2023-07-11 at 5 13 57 PM" src="https://github.com/carbon-design-system/ibm-products/assets/39408106/b4a9bba1-88bc-401f-bb51-29b3b25197de">



Expected

**Comment by elycheea** [comment]
@vsnichols I believe the misalignment was a bug that was introduced with `MenuButton` and `ComboButton` update! We’ll look into this!

> Add behavior for actions across multiple pages

This one needs to be handled by Carbon first since it’s currently not possible to implement this without changes to the `DataTable`. I believe we have a version of this in the [`More` menu here](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--select-items-in-all-pages) so it’s still possible to achieve, but the button placement in the left is not currently.
