### ISSUE TITLE
Datagrid design review: Clickable row items

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#2608]
## Design review

- Component epic #1607 #2499
- Designers/reviewers: 
- Links: [PAL guidance](https://pages.github.ibm.com/cdai-design/pal/components/data-table/clickable-row-items/usage) / [Storybook](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-clickablerow)

---

### Standards

- [ ] All pattern updates/changes/iterations have been discussed with the
      component developer
- [x] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [ ] The component behaves according to the guidelines set by the pattern
      maintainer
- [ ] The component’s UI matches the pattern specifications set by the pattern
      maintainer
- [ ] The component’s motion matches the specifications set by the pattern
      maintainer(s)
- [x] The UI produced is responsive, cross-browser, and responds to the
      currently set Carbon theme.
- [ ] Colors, themes, sizes and additional props are true and correct, aligning
      with Carbon set tokens (unless otherwise specified by the pattern)
- [ ] Paddings/margins/spacings are true and correct, in both desktop and mobile
      views

### Storybook

- [x] A functioning component renders in Storybook
- [ ] The Storybook displays multiple scenarios that show how the component can
      be used
- [ ] Changing props in the Storybook updates the component

**Comment by elycheea** [comment]
@johannasuarez-koval hope you can help with this review, but let me know if we need to reallocate or if someone else from your team can help with this. Need to release the base component before the extensions. 🔥

**Comment by elycheea** [comment]
@thefirstartist to help with accessibility.
Feel free to remove any checks that don’t apply.

---

## Accessibility review

### [Keyboard](https://www.ibm.com/able/toolkit/develop/keyboard)

#### Level 1

- [ ] Properly code the navigation order
  - [ ] Ensure interactive elements are reachable with the keyboard
  - [ ] Where possible, achieve the desired tab order by adjusting the DOM,
        rather than overriding the tabindex
  - [ ] When overriding the default focus indicator, confirm focus is highly
        visible
- [ ] Implement established keyboard conventions
  - [ ] Use standard HTML elements where possible, using CSS to alter appearance
        not behavior
  - [ ] Be familiar with established keyboard conventions
  - [ ] Implement keyboard operation for custom elements

#### Level 2

- [ ] Ensure keyboard access to complex interactions
  - [ ] Make custom media player and animation controls keyboard accessible

#### Level 3

- [ ] Code screen updates predictably
  - [ ] Use "activate" rather than "focus" as a trigger
  - [ ] Use an onchange event without disorienting the user

### [Dynamic updates](https://www.ibm.com/able/toolkit/develop/dynamic-updates)

#### Level 1

- [ ] Provide errors accessibly
  - [ ] Use accessible methods to implement error messages
  - [ ] Implement validation and notification to minimize interruptions

#### Level 2

- [ ] Make content accessible that appears on hover or focus
  - [ ] Ensure <kbd>Esc</kbd> dismisses new content
  - [ ] If content appears on hover, the new content needs to remain visible
        until dismissed
  - [ ] Moving the pointer away from the trigger should not be the action that
        dismisses the new content
  - [ ] Ensure custom tooltips and similar hover text can be triggered by
        keyboard
  - [ ] Discuss alternatives to hover text
  - [ ] Use caution where interactive controls appear in the hover text
- [ ] Code cancellation actions accessibly
  - [ ] Provide accessible ways of cancelling pointer interaction
- [ ] Properly code status messages
  - [ ] Use `role=status` to advise on the success or results of an action
  - [ ] Use `role=alert` or an ARIA live region to convey a suggestion or
        warning

#### Level 3

- [ ] Allow reduced motion
  - [ ] Implement motion media queries to reduce user risk

### [Text and non-text](https://www.ibm.com/able/toolkit/develop/text-and-non-text)

#### Level 1

- [ ] Implement text alternatives for meaningful images, sound, and visual data
  - [ ] Give decorative images an ALT attribute with an empty string (`alt=""`)
  - [ ] Use HTML, ARIA, or technology-specific techniques to add short text
        alternatives
  - [ ] Where relevant text exists in the UI, use `aria-labelledby` and
        `aria-describedby` to reference
  - [ ] Provide an accessible method for exposing long text alternatives
  - [ ] Embed multimedia content that supports closed captions
- [ ] Implement correct structure and metadata
  - [ ] Code headings according to specifications
  - [ ] ~Code the `<title>` element on every page according to specifications~
  - [ ] ~Set the language for each page~

#### Level 2

- [ ] Add additional structure where appropriate
  - [ ] Use `<figcaption>` and `<caption>` elements where figures and tables are
        titled
  - [ ] Add additional context to generic link names
  - [ ] Consider adding regions and other ARIA roles to distinguish text
        groupings

#### Level 3

- [ ] ~Mark up foreign words and abbreviations~
  - [ ] ~Use the `lang` attribute for foreign words and phrases~
  - [ ] Use `<abbr>` elements and title attributes to expand abbreviations
- [ ] Achieve necessary reading order
  - [ ] Order content appropriately in the DOM
  - [ ] Only use CSS to alter text position without altering meaning

### [User input](https://www.ibm.com/able/toolkit/develop/user-input)

#### Level 1

- [ ] Associate labels with inputs
  - [ ] Programmatically associate inputs with labels
  - [ ] Add accessible names for inputs lacking visible labels
- [ ] Provide correct name, role, and value
  - [ ] If repurposing a standard component, use ARIA to set the correct name
        and role
  - [ ] On custom components, use ARIA to expose `name`, `role`, and `value`

#### Level 2

- [ ] Reduce conflict between the visible label and a component's accessible
      name
  - [ ] Match the accessible name to the visible label
  - [ ] Include the text of the label in the accessible name

#### Level 3

- [ ] Indicate the purpose of common inputs
  - [ ] Use HTML `autocomplete` attributes, where appropriate

**Comment by thefirstartist** [comment]
keyboard navigation issues found in Clickable row with side panel:
1. After opening and dismissing the side panel from row 3, pressing tab key again will move the focus to the first row of the table. The desired behavior should be moving the focus down to row 4.
<img width="957" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/40870771/a3166f52-f016-455a-98ef-8e9dc76c0921">

2. While the focus ring appears on the Close button in side panel, pressing the tab key again doesn't do anything. The desired behavior should be moving the focus back to row 2.
<img width="1120" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/40870771/bad9fa09-7d55-4f4b-9358-6c92f38ff60c">

**Comment by thefirstartist** [comment]
Design review:
1. Browser tooltip is missing from the Doc link column. Truncated items always include a browser tooltip on hover to show the entire string, name, or phrase that the ellipsis is representing. 
![image](https://github.com/carbon-design-system/ibm-products/assets/40870771/c6e5164c-0e02-4be7-a901-9fbef8b76838)
2. Cursor for the link shows finger for about 1 second then turns to arrow. I think it should be finger all the time.
3. Age and Visits are numerical columns and should be right aligned. ([Numerical data alignment rule](![image](https://github.com/carbon-design-system/ibm-products/assets/40870771/227c22c7-2b05-4706-97a2-b90d292b7cc3)))
4. For column headers, should be Row index, First name, and Last name (sentence-case)
5. Need story for multiple select ([PAL guideline](https://pages.github.ibm.com/cdai-design/pal/components/data-table/clickable-row-items/usage/#multi-select-and-batch-action))
6. The spacing between the side panel and the table should be 16px
![image](https://github.com/carbon-design-system/ibm-products/assets/40870771/6e937b2e-52ac-42e5-9ef8-65b1f231f239)

**Comment by elycheea** [comment]
@all-contributors add @thefirstartist for accessibility and design

**Comment by elycheea** [comment]
> 1. Browser tooltip is missing from the Doc link column. Truncated items always include a browser tooltip on hover to show the entire string, name, or phrase that the ellipsis is representing.
> 3. Age and Visits are numerical columns and should be right aligned. ([Numerical data alignment rule](https://pages.github.ibm.com/cdai-design/pal/components/data-table/column-alignment/usage#numerical-data))
> 4. Column headers should be sentence cases: Row index, First name, and Last name.
> 7. Add "Show details" link in side panel and it should be the default focus when the side panel is opened.

Good call. Our examples should reflect the desired behavior when possible. Will be fixed in upcoming PRs #3224 and #3225.

> 2. Cursor for the link shows finger for about 1 second then turns to arrow. I think it should be finger all the time.

Not actually able to replicate this one.

> 5. Need story for multiple select ([PAL guideline](https://pages.github.ibm.com/cdai-design/pal/components/data-table/clickable-row-items/usage/#multi-select-and-batch-action))

This is actually part of the [`Row action buttons` stories](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-rowactionbuttons--row-action-buttons-batch-actions-usage-story) instead. That said, I don’t believe we’re currently disabling during batch so we can look into the best way to handle that. #2606 

> 6. The spacing between the side panel and the table is too big:
> The gap should be 16px

This is fixed after @matthewgallo’s latest update to Storybook docs. #3187 

> 8. Need story for [tooltip and tags](https://pages.github.ibm.com/cdai-design/pal/components/data-table/clickable-row-items/usage/#tooltips-tags-and-secondary-links).

I consider this more of an example use case than specific pattern. I don’t think we have any sort of overflow for these sort of list items although I know this was documented as an example of overflows when Laura was looking at a tag overflow pattern.
 
> 9. Header should not show hover feedback if the column is not sortable. (found in all datagrid pages)

Going to include this in #3118 or open a separate issue for this since it looks like it’s in the base component.
