### ISSUE TITLE
[BUG]: Datagrid > FilterPanel: ActionSet positioning when screen is less than 600 px

### ISSUE THREAD

**Issue by AlexanderMelox** [carbon-design-system/ibm-products#2683]
At small screen heights (<600) we’re seeing the action set issue again that we previously resolved with clamp. 

<img width="1711" alt="Screenshot 2023-02-20 at 1 06 04 PM" src="https://user-images.githubusercontent.com/12755042/220175380-df10e6ce-de6d-40a0-baab-a5ec4b1eceeb.png">

I belive a way we can fix this is to remove the stickiness and any overflows when it's a small height that way it just scrolls normally on the page

**Comment by davidmenendez** [comment]
this appears to be working now. @AlexanderMelox can you please confirm?
