### ISSUE TITLE
Datagrid actions toolbar responsiveness broken in Storybook 

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#2686]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)

## Detailed description

> Describe in detail the issue you're having.

Stories using the actions toolbar now show the larger screen toolbar items in addition to the responsive menu. I’m guessing this was introduced in some of the filtering changes.
This can be seen at smaller screen sizes (using `sm — mid range` as the screen size in Storybook); for example: [Actions dropdown](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--actions-dropdown) story

> Is this issue related to a specific component?

Datagrid actions toolbar

> What did you expect to happen? What happened instead? What would you like to
> see changed?

At smaller screens, this should just show the responsive menu — this was previously working.
https://pages.github.ibm.com/cdai-design/pal/components/data-table/scrolling/usage/#responsive-behavior

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
v1.43.0

## Steps to reproduce the issue

1. Go to Datagrid story with actions toolbar, such as the [Actions dropdown](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--actions-dropdown) story
2. Change screen size in Storybook to `sm — mid range`
3. Table toolbar no longer collapses to just the responsive menu. Instead, it shows both the original table toolbar breaking out of the width, and the responsive menu side-by-side.

![image.png](https://images.zenhubusercontent.com/6109a215337f0517b2f0e02f/d9528c0f-6d92-4ba6-b93b-e7049f4999b1)

**Comment by elycheea** [comment]
@Ratheeshrajan @AlexanderMelox I think either of you can look into this after your current items although please review each other’s work. Not expecting this to be too big of a change 🤞, hopefully just a some misplaced logic that we can fix quickly, but please share in our discussions if it’s more complicated than that.

**Comment by Ratheeshrajan** [comment]
@elycheea @AlexanderMelox I'll take this one. Thanks.

**Comment by Ratheeshrajan** [comment]
Restored the toolbar responsiveness in #2692. But we need to work on implementing filter panel inside the mobile modal as in the [doc](https://pages.github.ibm.com/cdai-design/pal/components/data-table/filters#responsive)

**Comment by davidmenendez** [comment]
needs v11 PR
