### ISSUE TITLE
Datagrid: open modal or tearsheet causes misalignment in header

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#2724]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

When tearsheet/modal is opened from Datagrid using denseheader, the header area grows

> Is this issue related to a specific component?

Datagrid with denseHeader

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Header area increased in size, but table header/body should not change

![image](https://user-images.githubusercontent.com/1717398/223843477-ca04ea4a-f324-4823-b923-b73f49e2ad16.png)

![image](https://user-images.githubusercontent.com/1717398/223843850-fda5d8a0-719c-4514-8618-c28c47b08291.png)

Looks like this is the line causing the issue. If this was for the responsive behavior, we may want to add a media query to prevent this from affecting the the datagrid when it shouldn’t. Otherwise `align-content: start` might also work.

## Steps to reproduce the issue

1. Navigate to [customize columns story](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-columncustomization--column-customization-usage-story&args=useDenseHeader:true)
2. Set `useDenseHeader` to true in controls
3. Activate the Customize Columns tearsheet

## Additional information

- Screenshots or code
- Notes

**Comment by elycheea** [comment]
FYI @Ratheeshrajan — lower priority but also probably an easy fix

**Comment by Ratheeshrajan** [comment]
Closing as #3056 & #3069 merged.
