### ISSUE TITLE
Datagrid rerenders in specific scenarios in v2

### ISSUE THREAD

**Issue by Ratheeshrajan** [carbon-design-system/ibm-products#2725]
some times need to click twice on the button to open the filter panel/flyout. This is noticed in v11.

## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
Carbon for IBM Products v2.0.0-rc.20

## Steps to reproduce the issue

1. Click on the filter flyout/panel button

## Additional information

https://user-images.githubusercontent.com/305492/224034547-f4d8cbea-d7c7-46e7-9c96-adee2e163c13.mov

**Comment by elycheea** [comment]
@AlexanderMelox @Ratheeshrajan Can you help estimate the size for this. Seems like the re-render issue.

**Comment by elycheea** [comment]
Editable cells, actions dropdown, etc are some areas @matthewgallo’s encountered.
