### ISSUE TITLE
V11 Pageheader ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-products#2744]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

In this repo https://github.ibm.com/lee-chase/lgeo-presentation.

1. In the code comment in the PageHeader usage in `Page/CarbonEcosystem`
2. Run and open the app
3.  Use the drop down to change to the `CarbonEcosystem` page
4. Refresh fixes it briefly
5. Resize page to see second image

go to the `Carbon Ecosystem` page the resize observer exceeds the loop limit

<img width="1703" alt="image" src="https://user-images.githubusercontent.com/15086604/225706321-b2d2ea6a-c05f-44da-a8d9-9f4465658f53.png">

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/15086604/225708015-a712d321-cff5-4c61-b3a6-83f508232a45.png">

**Comment by lee-chase** [comment]
OK so this is a bit weird.

- With no changes I tried the project `Layout-2023` clicked through to the `Carbon Ecysystem` page which had a `Page Header` and it failed.
- Copied the project folder. Deleted all routes except Home, About, NotFound404 and `Carbon-Ecosystem`. It worked.
- Added the other routes back, it worked.
- Renamed the project folder layout-2023 to c4p-test, the only difference. It worked. 
- Renamed the project folder back to layout-2023 and IT WORKED!!!!!!

**Comment by lee-chase** [comment]
OK. So the version of ReactResizeDetector we are on is out of date. 

A fix went in last November that may fix this and the author also suggests React 18 fixes this.

https://github.com/maslianok/react-resize-detector/issues/45

Assuming this fixes us it is probably in V8 (January) and V9 (11 days ago) we are on V7 which is 10 months old. 

I tried hacking this locally to use V9 but it appeared to cause all updates to stop, or hung my browser.

@elycheea @davidmenendez but I think I need to do it as a part of a build, which I'll try tomorrow.

P.S.  The package author also seems keen for people to use container media queries where possible https://github.com/maslianok/react-resize-detector#do-you-really-need-this-library. If this works then perhaps in the life of V2 we ditch in favor of container queries and using native ResizeObserver.

**Comment by lee-chase** [comment]
Unfortunately this does not appear to be fixed in V8 and V9 hangs and/or does not update.

We could try another library or write our own ResizeObserver hook. This author has created several hooks which look well written. https://www.npmjs.com/package/@react-hook/resize-observer

**Comment by lee-chase** [comment]
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/15086604/236012494-11767a1a-8f31-4a88-87d4-abe2bbd63efd.png">

**Comment by lee-chase** [comment]
<img width="654" alt="image" src="https://user-images.githubusercontent.com/15086604/236012604-93039fdc-63b3-4f82-83ed-5aef16e41f56.png">

**Comment by davidmenendez** [comment]
@lee-chase has this issue been fixed?

**Comment by lee-chase** [comment]
Yes afte rmerge into V1.

**Comment by MariaStthpl** [comment]
@lee-chase It seems that these changes have caused an unexpected behavior:

| Before [42f6d0a](https://github.com/carbon-design-system/ibm-cloud-cognitive/commit/42f6d0af498683e7c2dd7a37d869b5af803ea7b5) | After [42f6d0a](https://github.com/carbon-design-system/ibm-cloud-cognitive/commit/42f6d0af498683e7c2dd7a37d869b5af803ea7b5) | 
| --------------- | --------------- | 
| ![image](https://github.com/carbon-design-system/ibm-cloud-cognitive/assets/33152738/bc67c05f-9c8d-4b70-b665-33217300148d) | ![image](https://github.com/carbon-design-system/ibm-cloud-cognitive/assets/33152738/649d22ac-c249-4702-bb74-4780056a19a2) |

Please notice that before these changes, we are seeing a finite number of occurrences of the `ResizeObserver loop limit exceeded` error. However, after the changes, the error is triggered infinite times.

Also, I am using the `React Developer Tools` Chrome extension and I have enabled the Profiler setting to highlight any component that is rendered, as shown in the screenshot below
![image](https://github.com/carbon-design-system/ibm-cloud-cognitive/assets/33152738/3d272054-b049-406f-b78a-2f804bfd907c)
and we can quickly notice that after the changes the `PageHeader` component is constantly re-rendering.

**Comment by omar-zahid** [comment]
Page header actions are also affected. Try to add an action button with a label and react will re-render infinitely. Not sure if this is related.

**Comment by elycheea** [comment]
Hoping this is addressed now. With no follow up since 3 weeks, going to call this closed. 🤞
