### ISSUE TITLE
Tearsheet buttons default to `xl` when they should default to `2xl` in Carbon v11

### ISSUE THREAD

**Issue by fbarroso24** [carbon-design-system/ibm-products#2770]
What is the proper way to pass `size` to the [Tearsheet ](https://carbon-for-ibm-products.netlify.app/?path=/docs/ibm-products-components-tearsheet-tearsheet--tearsheet#component-api) `actions` buttons?  The `actions` description says it will pass along additional props to the [Button ](https://react.carbondesignsystem.com/?path=/docs/components-button--default#component-api) component.  When i try `className` it correctly gets passed along to the [Button](https://react.carbondesignsystem.com/?path=/docs/components-button--default#component-api). However, passing along size does not appear to work.  

It appears to default to size=xl every time. 
Screenshot 1 below shows how I'm instantiating size 
![image](https://user-images.githubusercontent.com/8657768/227393148-280673f0-c32c-47e0-9e35-1369a8f9bcd5.png)

& screenshot 2 below shows how it keeps using size='xl' (e.g. cds--btn--xl) regardless.
![image](https://user-images.githubusercontent.com/8657768/227393176-40026193-1e99-4909-bfeb-ddbbdcf258ac.png)

## Title line template: [Title]: Brief description
Tearsheet buttons default to `xl` when they should default to `2xl` in Carbon v11.  Also, consider updating component to allow users to pass in button size as per what is described in the storybook (see below)
![image](https://user-images.githubusercontent.com/8657768/227393088-3fcfb4c6-0023-4177-990a-a40edca9edcc.png)
-->

## What package(s) are you using?
 I'm using @carbon/ibm-products": "2.0.0-rc.13" and @carbon/react": "1.23.0".

- [ ] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.
1.  The default button size for tearsheet should be size='2xl'.  Currently it is `xl`.
2. The size prop is not being forwarded via the [Tearsheet actions](https://carbon-for-ibm-products.netlify.app/?path=/docs/ibm-products-components-tearsheet-tearsheet--tearsheet#component-api) prop? Even though the Storybook currently states that it should be forwarded.
![image](https://user-images.githubusercontent.com/8657768/227393453-e5c0b220-0333-4eb5-996a-a70c061242c1.png)

> Is this issue related to a specific component?
Tearsheet buttons

The full slack thread can be read here: https://ibm-industrysolutions.slack.com/archives/C013ZTX0N6B/p1679512735680089

**Comment by elycheea** [comment]
@SimonFinney Unsure whether we should support passing `size` prop for tearsheet actions since I don’t believe this was designed to support all sizes. We should definitely fix the defaults though and consider updating our documentation if not supported in Tearsheet.

Might ping Cameron for someone to weigh in.

**Comment by elycheea** [comment]
Reopening since @Laura-Marshall caught that even though we’re now using `2xl`, the size is still not reflected in our tearsheets. Currently guessing that it’s due to overrides from `ActionSet` 👀
