### ISSUE TITLE
toolbarBatchActions bug in datagrid component

### ISSUE THREAD

**Issue by Billzg13** [carbon-design-system/ibm-products#2771]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

it seems that if I try to show only 1 button for `toolbarBatchActions` it won't show it, instead they will only show up if I have more than 3 actions

> Is this issue related to a specific component?

`Datagrid component`

> What did you expect to happen? What happened instead? What would you like to

I would expect the toolbar to show as many buttons/actions I need including only 1. Instead we need at least 3 buttons/actions for it to work. 

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

```
package.json:     
    "@carbon/charts": "1.6.1",
    "@carbon/charts-react": "1.6.1",
    "@carbon/ibm-products": "2.0.0-rc.17",
    "@carbon/react": "1.19.0",
```

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Turbonomic/ibm 

## Additional information

In `ibm-cloud-cognitive/packages/cloud-cognitive/src/components/Datagrid/Datagrid/DatagridToolbar.js`
line 134 through 137 this if seems to handle that case.

@davidmenendez

**Comment by matthewgallo** [comment]
Hey @Billzg13, sorry for the delay here. It will be fixed with the PRs above and you'll be able to see this reflected in the next release!

**Comment by Billzg13** [comment]
hey @matthewgallo is this fixed? Should I close it?
