### ISSUE TITLE
Update alignment of tooltip in UserProfileImage

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#2796]
From the [user profile image](https://github.ibm.com/CDAI-design/pal/issues/1154) migration design reviews —

Tooltip position on the user profile image has changed between v1 and v2.

v1 | v2
---|---
<img src="https://images.zenhubusercontent.com/6109a215337f0517b2f0e02f/8969ac65-5df8-49d7-98ed-6740e9e2b50d" width="200"/> | <img src="https://images.zenhubusercontent.com/6109a215337f0517b2f0e02f/a9a459b8-38ef-4ca5-8faa-f32002eb702c" width="200"/>

Looks like there is now a single `align` prop. We can probably provide some control over setting this (possibly even set a default to minimize regression).

**Comment by Ratheeshrajan** [comment]
Closing as #3044 merged.
