### ISSUE TITLE
Issue after migrating to ibm-products*rc2 version

### ISSUE THREAD

**Issue by gopinathpatro** [carbon-design-system/ibm-products#2800]
The issue seen while running npm start is as below,

./node_modules/framer-motion/dist/es/components/AnimatePresence/index.mjs
Can't import the named export 'Children' from non EcmaScript module (only default export is available).

Also it is observed that, the issue is seen "@carbon/ibm-products": "^2.0.0-rc.3"  onward.

**Comment by elycheea** [comment]
We’ve seen this issue and believe it’s related to ESM. Please take a look at #2378 as well as the documentation [here](https://github.com/carbon-design-system/ibm-cloud-cognitive/tree/main/packages/cloud-cognitive#webpack-4).
