### ISSUE TITLE
Remove extra padding from export modal

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#2812]
From the [export modal](https://github.ibm.com/CDAI-design/pal/issues/1159) migration review —

Export modal includes an extra `24px` margin at the bottom of the modal not in v1 or in the Figma files.

![image.png](https://images.zenhubusercontent.com/6109a215337f0517b2f0e02f/3b9fcbda-4fa0-4456-bb13-99e58db1e40f)

**Note:** Issues with the https://github.com/carbon-design-system/ibm-cloud-cognitive/labels/v2 label should be cut from the `carbon-v11` branch (until our branch renames occur — see #2884 plans).

**Comment by Saivaraprasad48** [comment]
@elycheea 
Please assign it to me.

**Comment by elycheea** [comment]
@mgallo25 will be looking into this issue. 🎉
