### ISSUE TITLE
[Datagrid] Window is not defined when SSR

### ISSUE THREAD

**Issue by houhoucoop** [carbon-design-system/ibm-products#2833]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

Get `window is not defined` when server side rendering (Next.js)
> Is this issue related to a specific component?

Datagrid
> What did you expect to happen? What happened instead? What would you like to
> see changed?

It works fine in @carbon/ibm-products 1.34.0, then the error show up when upgrade to latest version 1.47.0.
Not sure the root cause is the [dependencies upgrade](https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/2731/files?diff=split&w=0#diff-ec299191490e813772878f9ec7b5cd5fb9c754583b687b5e0e6483d9db2dfb48) in version 1.46.2 or not.
> What browser are you working in?

Google Chrome
> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

@carbon/ibm-products 1.47.0

## Additional information

![image](https://user-images.githubusercontent.com/77039366/230269246-942a9e58-4240-4198-9b4a-fd613d34f032.jpg)
```javascript
const datagridState = useDatagrid(
    {
      columns,
      data,
      isFetching,
      manualPagination: true,
      pageCount: total,
      autoResetPage: false,
      DatagridPagination,
      DatagridActions,
      ExpandedRowContentComponent,
    },
    useExpandedRow,
    useStickyColumn,
    useActionsColumn
 );
```

**Comment by elycheea** [comment]
Should be addressed with #3059 #3058
