### ISSUE TITLE
Storybook 7 breaks storybook-addon-carbon-theme

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-products#2847]
This package,  published on NPM, and part of our source base needs some remedial work to be updated to storybook 7 #2846 

To do:
- Publish V1 targeting storybook 6.
- Publish V2 targeting storybook 7.
- Move to format used by @carbon/react perhaps submitting PR to Carbon.

**Comment by elycheea** [comment]
Should look into how Carbon has handle their theming in Storybook to work as an addon. May see if Carbon can release this as an addon instead of managing this ourselves.

**Comment by elycheea** [comment]
Closing since we moved to the same theme switcher as Carbon core when we moved to Storybook 8.
