### ISSUE TITLE
Reverse Saving pattern icons

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#2849]
Originally from [saving migration review](https://github.ibm.com/CDAI-design/pal/issues/1162), but this is not a regression but a bug on our part.

![image](https://user-images.githubusercontent.com/1717398/231308440-2d9dbe85-03bd-411b-941f-727eb3f01df9.png)

Currently, we show the checkmark in the `default` state and the save icon in the `success` (“saved”) state. This should be reverse where the `default` state uses the `Save` icon and `success` uses the checkmark.

**Comment by GabrielMurry** [comment]
Hey! You can assign this to me, I'd love to fix it.
