### ISSUE TITLE
Update status icons for in-progress, pending, and running

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#2850]
## What will this achieve?

Enhancement to match the updated guidance. Originally discovered during the [status icon migration review](https://github.ibm.com/CDAI-design/pal/issues/1163).

Icons for `in-progress`, `pending`, and `running` are inconsistent with what’s currently published in the [design guidance](https://pages.github.ibm.com/cdai-design/pal/patterns/status-icons/usage) and in Figma. The design guidance and Figma also follow the Carbon icons for `in-progress` and `pending` so are likely correct.

## How will success be measured?

Icons should be updated to match the current version.

## Additional information

- [Status icons guidance](https://pages.github.ibm.com/cdai-design/pal/patterns/status-icons/usage)
- [Figma gray 10](https://www.figma.com/file/GqvE8KdjEfxyS6viCHpX6Q/(v11)-Gray-10---IBM-Products?node-id=1-1334&t=GWI9lTtNKIzs3n6a-0) | [Figma gray 100](https://www.figma.com/file/fwNkj3378pG2z4sFDFYYPj/(v11)-Gray-100---IBM-Products?node-id=9895-328639&t=UemCYydFekKnAKYs-0)

For good measure, Sam Ting @thefirstartist was listed as the original design maintainer and may still be able to help respond to questions.

**Comment by thefirstartist** [comment]
@elycheea 
It seems both storybooks are showing old `in progress` and `pending` icons and should be corrected to match design guideline. We changed these two icons in order to align with Carbon.
