### ISSUE TITLE
Enhance datagrid component to return the whole selected record

### ISSUE THREAD

**Issue by Billzg13** [carbon-design-system/ibm-products#2909]
## What will this achieve?

Enchance datagrid component to return the whole selected row instead of just selected row id for the selected rows.

## How will success be measured?

If I can grab the selected rows ( whole row ) instead of `selectedRowIds` from `useDatagrid`

### package.json

    "@carbon/charts": "1.6.1",
    "@carbon/charts-react": "1.6.1",
    "@carbon/ibm-products": "2.0.0-rc.17",
    "@carbon/react": "1.19.0",

**Comment by elycheea** [comment]
@matthewgallo to follow up and verify if this is addressed already.

**Comment by matthewgallo** [comment]
Hey @Billzg13, this is something that we added recently and will be available in the next release (our releases happen Tuesday mornings).

With the new changes, when you use the `useSelectRows` hook along with the `onRowSelect` callback function supplied to the `useDatagrid` hook, you will be able to get the row object and the event back. See the [Datagrid docs here](https://carbon-for-ibm-products.netlify.app/?path=/docs/ibm-products-components-datagrid-datagrid-canary--basic-usage#selecting-rows) for more details.

When this update is released, you would simply have the following to get the row object on row selection change:
```jsx
const datagridState = useDatagrid(
  {
    columns,
    data,
    onRowSelect: (row, event) => console.log(row, event),
  },
  useSelectRows
);
```

**Comment by vnikiten01** [comment]
@Billzg13 correct me if I am wrong,  i believe what we were looking for is not to get the single row back on selection, but instead a way to get back all selected items as the original row objects.

Currently datagrid supports `selectedRowIds: string[]` 
And we were interested in getting something like this `selectedRows: T[]`

**Comment by Billzg13** [comment]
@matthewgallo created new issue according to @vnikiten01 comment above, should I close this issue?
