### ISSUE TITLE
[Datagrid] Filter panel state does not update after changing filters with `setAllFilters` function

### ISSUE THREAD

**Issue by xmannyxfreshx1** [carbon-design-system/ibm-products#2913]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

After manually updating the filters via `setAllFilters` from https://react-table-v7.tanstack.com/docs/api/useFilters#instance-properties, the internal filter state is update within datagrid but the filter panel does not reflect those changes. Filters show previous state.

> Is this issue related to a specific component?

Datagrid, filter panel

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Exception is that the filter panel re-renders with the updated state after changing the filters with `setAllFilters`.
The `<FilterSummary/>` component reflects the changes correctly.

> What browser are you working in?

Chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

1.49.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

CP4WAIOps

## Steps to reproduce the issue

1. Render a table with the filter panel enabled
2. Apply filters
3. Attempt to pragmatically change the filters using `setAllFilters`
4. Notice that datagridstate.state.filters and `<FilterSummary/>` update accordingly while the filter panel keeps the previous selections. (i.e. previous checkboxes checked etc.)

## Additional information

- Screenshots or code
- Notes

**Comment by elycheea** [comment]
@AlexanderMelox to verify if this has been addressed or separate issue.

**Comment by xmannyxfreshx1** [comment]
@AlexanderMelox I just tried the latest build that includes your fix for the initial filters and that works great!
This issue, however is not resolved.

**Comment by AlexanderMelox** [comment]
Issue has been resolved in #3024
