### ISSUE TITLE
Tearsheet content is on third layer, instead of first

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/ibm-products#2922]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

In #2762, tearsheet content was wrapped in `Layer` which is good but unfortunately the layering is currently off.
The tearsheet content should be on the first layer (currently on the third), the tearsheet header and influencer should be on the second.

> Is this issue related to a specific component?

Tearsheet

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Tearsheet layering is off. This causes visual regressions in g90 and g100 themes as well as preventing the usage of any layers inside the tearsheet content by the consumer.

> What browser are you working in?

Chrome 112

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

`@carbon/ibm-products@2.0.0-rc.26`

## Steps to reproduce the issue

1. Open tearsheet story: https://v11-carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-tearsheet-tearsheet--tearsheet
2. Change theme to either g90 or g100
3. Alternatively, inspect in code. The tearsheet content is on `cds--layer-three`, but should be on `cds--layer-one`.

## Additional information

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/28265588/234267664-5ce303a2-5b87-4643-b482-8a89225165ec.png">

**Comment by jagathgj** [comment]
Fixed and merged it. Hence closing.
