### ISSUE TITLE
[Datagrid] Seeing separate errors while using `useSelectRows` and `useSelectAllWithToggle` with `useCustomizeColumns`

### ISSUE THREAD

**Issue by xmannyxfreshx1** [carbon-design-system/ibm-products#2933]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.
Errors appear when trying to bring up the customize columns tearsheet while using the hooks `useSelectRows` and `useSelectAllWithToggle`.
Error seen with just `useSelectRows`:

![Screenshot 2023-04-26 at 11 24 23 AM](https://user-images.githubusercontent.com/13371221/234624165-99e91eaf-f7cb-4178-84c5-46c1dfb219e6.png)

Error seen with both `useSelectRows` and `useSelectAllWithToggle`.

![Screenshot 2023-04-26 at 11 19 44 AM](https://user-images.githubusercontent.com/13371221/234622967-ba95b878-d181-429d-8f4e-ec076147f48e.png)

> Is this issue related to a specific component?

Datagrid

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Expect the column customizer to render while using these two hooks

> What browser are you working in?

Chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

1.49.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

CP4WAIOps

## Steps to reproduce the issue

1. Render a datagrid using `useSelectRows` and `useSelectAllWithToggle` with `useCustomizeColumns`
2. Notice error when trying to customize the columns
3. Remove a hook, then notice a slightly different error.

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/angry-stallman-muehg2?file=/src/Example/Example.js

## Additional information

- Screenshots or code
- Notes

**Comment by matthewgallo** [comment]
Hey @xmannyxfreshx1, Datagrid doesn't support `useSelectRows` with `useCustomizeColumns` currently. We'll gladly accept contributions to support the two of them together. Our team may look at this in the future after we finish things up with our v2 release.

**Comment by xmannyxfreshx1** [comment]
@matthewgallo It was supported previously. This issues https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/2820 addressed the checkboxes moving after customizing the columns. I think after changes were made to address this issue https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/2837 (`useCustomizeColumns` and `useSortableColumns` not working together) is when I saw the errors when using `useSelectRows`.

**Comment by matthewgallo** [comment]
This should now be fixed with https://github.com/carbon-design-system/ibm-products/pull/3344
