### ISSUE TITLE
Improve notification panel responsiveness

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#2946]
Originally from [notifications panel migration review](https://github.ibm.com/CDAI-design/pal/issues/1152). Since these are not regressions from the v1, these can be addressed after the initial v2 release.

![image.png](https://images.zenhubusercontent.com/6109a215337f0517b2f0e02f/4809795b-66d3-4778-b921-a6e363bf14d5)

**Comment by Ratheeshrajan** [comment]
Closing as #3041 merged
