### ISSUE TITLE
[Datagrid, FilterPanel (Batch)] Deselect filters without applying and closing the filter panel causes summary to lose tags

### ISSUE THREAD

**Issue by joyful-these** [carbon-design-system/ibm-products#2947]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

Steps to reproduce:
1. In the filter panel (with batch update method), select any filter checkbox and click the apply button.
2. Deselect the same filter checkbox, without pressing the apply button.
3. Close the filter panel. The filter tag in the filter summary bar disappears.

This can be reproduced from the storybook: https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--filter-panel

> Is this issue related to a specific component?

Datagrid, FilterPanel (Batch)

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The filter tags in the filter summary bar should not disappear, since the apply button was not pressed after deselecting the filter checkbox.

> What browser are you working in?

Chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

1.50.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

CP4WAIOps

**Comment by AlexanderMelox** [comment]
This issue has been resolved and is a duplicate.

PR: #3024
