### ISSUE TITLE
[Datagrid] Stringify "cyclic object value" error in useFilters hook when using a Node as Checkbox labelText value

### ISSUE THREAD

**Issue by sdepuy** [carbon-design-system/ibm-products#2948]
## What package(s) are you using?

- [X] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

When using a **Checkbox** filter with a **Node** as **labelText**, an error is thrown in the **useFilters** hook when trying to stringify the filterState.

> Is this issue related to a specific component?

When using filters in **Datagrid** component

> What did you expect to happen? What happened instead? What would you like to
> see changed?

No exception, full support for Checkbox labelText node types

> What browser are you working in?

Chrome and FF

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

"@carbon/ibm-products": "2.0.0-rc.27"

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Content Services on AWS

## Steps to reproduce the issue

1. Define a **Datagrid** checkbox filter with a **Node** as **labelText** value:

Ex:
```
{
      type: "checkbox",
      column: "dataType",
      props: {
        FormGroup: {
          legendText: "Test Filter",
        },
        Checkbox: [
          {
            id: "id1",
            labelText: <><View /><span>text1</span></>,
            value: "text1",
          },
          {
            id: "id2",
            labelText: <><Edit /><span>text2</span></>,
            value: "text2",
          }
        ]
      }
    }
```
2. The following exception is thrown:

<img width="806" alt="image" src="https://user-images.githubusercontent.com/16355647/235311960-6935a5c5-0147-40ab-bd5b-91f76e5053db.png">

**Comment by AlexanderMelox** [comment]
@sdepuy Apart from the error, does it still work or it crashed the whole app?

**Comment by sdepuy** [comment]
@AlexanderMelox It crashes the whole app.

**Comment by AlexanderMelox** [comment]
Looking into this and seems pretty interesting. I know why it's happening it's when storing references from state into refs.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cyclic_object_value

**Comment by matthewgallo** [comment]
My guess is that at some point during the second half of last year this was resolved. I tested against the latest changes and was able to provide a `labelText` using a node and did not have any issues.

```jsx
{
    type: 'checkbox',
    column: 'passwordStrength',
    props: {
      FormGroup: {
        legendText: 'Password strength',
      },
      Checkbox: [
        {
          id: 'normal',
          labelText: <>Normal</>,
          value: 'normal',
        },
        {
          id: 'minor-warning',
          labelText: <>Minor warning</>,
          value: 'minor-warning',
        },
        {
          id: 'critical',
          labelText: <>Critical</>,
          value: 'critical',
        },
      ],
    },
  },
```

@sdepuy If you still experience any issues on the latest version, I'd be happy to help look into this further!
