### ISSUE TITLE
[Datagrid]: Cannot reorder hidden columns in Customize Columns panel

### ISSUE THREAD

**Issue by K-Markopoulos** [carbon-design-system/ibm-products#2952]
## What package(s) are you using?
ibm-products@2.0.0-rc.28

## Detailed description

> Describe in detail the issue you're having.

If there are hidden columns, when opening the Customize Columns tearsheet, user cannot reorder the hidden columns, even after making them visible. Dragging & dropping these columns doesn't move the columns at all, and sometimes other columns move instead of them.

Also, the tearsheet remains dirty after submitting it and the Save button is available the next time you open it, without making any changes.

> Is this issue related to a specific component?

Datagrid with CustomizeColumnsTearSheet

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The functionality is inconsistent and the items in the list are not moved as expected.

## Steps to reproduce the issue

It can be easily reproduced in storybook
1. Open storybook and go to Datagrid -> [WIth Column Customization story](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-columncustomization--column-customization-usage-story)
2. Click Customize Columns action button
3. Enable Age column and try moving Age column a few items above.

[Reordering columns issue.webm](https://user-images.githubusercontent.com/41068510/235665212-04dbc84d-1f7f-4d05-902c-150b25697585.webm)

**Comment by elycheea** [comment]
Marking this as blocked until we restore drag and drop behavior in customize columns that was removed in #3446

**Comment by matthewgallo** [comment]
This is no longer an issue with the new drag and drop approach which is now available in `2.11.0`.
