### ISSUE TITLE
Incorrect color in notification bell when on light theme

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-products#2960]
The Carbon UIShell is themeable in V11 so this now looks incorrect.

## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

See the bell, it's not very visible.

![image](https://user-images.githubusercontent.com/15086604/236270082-41153b64-5386-4b95-b5e0-c0711e2aa9f6.png)

**Comment by lee-chase** [comment]
@elycheea should be simple to fix

**Comment by Ratheeshrajan** [comment]
@elycheea, yes, I believe still there are some hardcoded fill in header icons and SVG.

**Comment by Ratheeshrajan** [comment]
Closing as #3103 merged.
