### ISSUE TITLE
*Enhancement Request* for NotificationsPanel Componenent to have option to remove 'Do not Disturb' toggle from panel 

### ISSUE THREAD

**Issue by bridgettepepper** [carbon-design-system/ibm-products#2975]
## What package(s) are you using?
**NotificationsPanel Component** - https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-patterns-notifications-notificationspanel--default&args=doNotDisturbDefaultToggled:false;doNotDisturbLabel 

Version - @carbon/ibm-products - 'latest' 

- [X ] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## What did you want to know?

First want to say how much I love the notifications panel component you all have created! I love that I did not have to create my own and use something already there

My enhancement request - would it be possible to have the 'doNotDisturb' toggle / text be optional to remove from the panel without having to alter the component code within the package? Not all applications (including mine) would require this feature out the gate, and being able to easily remove it would be a great feature. 

Example: removing the settings / 'view more' buttons from the component is easily done by commenting out the below lines within  <NotificationsPanel /> :
//onViewAllClick={}
//onSettingsClick={() => console.log('Clicked settings gear button')}

Unfortunately doing the same for 'Do not Disturb' event does nothing - //onDoNotDisturbChange={function noRefCheck(){}}

Thank you for considering this enhancement! Please let me know if any additional information is needed. Keep up the great work :D 

- Bridgette

**Comment by elycheea** [comment]
@Ratheeshrajan Since I’ve already added you to a few notifications related issues. :)

**Comment by Ratheeshrajan** [comment]
closing this as #3102
