### ISSUE TITLE
About modal API needs review following changes

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-products#2976]
Noted that the additionalInfo is still an array, but we are only rendering the first element. 

While it might be useful to cope with and without array the array version should be deprecated if no longer apprpriate

**Comment by lee-chase** [comment]
@glapadre as you recently changed this is it one you can pick up? I'll be. happy to review.

**Comment by glapadre** [comment]
@davidmenendez thanks for jumping on this, I just saw this message!
