### ISSUE TITLE
Create flow tearsheet not respecting application theme

### ISSUE THREAD

**Issue by omar-zahid** [carbon-design-system/ibm-products#2996]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

Root theme is set to `g100` but the tearsheet is still on light theme.

> Is this issue related to a specific component?

Tearsheet component

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Tearsheet should follow set theme

> What browser are you working in?

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

` "@carbon/ibm-products": "^2.0.0-rc.27"`

## Additional information

- Screenshots or code
![image](https://github.com/carbon-design-system/ibm-cloud-cognitive/assets/57479337/3c1c4769-f236-4c97-a400-61c3a4b822ba)

**Comment by matthewgallo** [comment]
Hey @omar-zahid, can you provide a code sandbox or stackblitz reproduction for us? Our [example](https://codesandbox.io/p/sandbox/github/carbon-design-system/ibm-products/tree/main/examples/carbon-for-ibm-products/CreateTearsheet?file=%2Fsrc%2FExample%2FExample.jsx%3A1%2C1) shows the create tearsheet responding to the theme that is set. There does seem to be a minor discrepancy in the disabled button state which is something we can address.

**Comment by omar-zahid** [comment]
Thanks @matthewgallo. This issue is specific to the `Theme` component from `@carbon/react`.
Here's the codesandbox for reference.
https://codesandbox.io/p/sandbox/tender-smoke-2r0wbc?file=%2Fsrc%2FExample%2FExample.jsx%3A1%2C1

Other components such as `PageHeader` and `Card` works just fine.
