### ISSUE TITLE
Update type and theme tokens

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#3028]
## What will this achieve?

Replace v10 type and theme tokens (e.g. `productive-heading-03` :arrow_right: `heading-03`). During [v2 migration reviews](https://github.ibm.com/CDAI-design/pal/issues?q=is%3Aissue+is%3Aopen+label%3A%22project%3A+Carbon+11%22), a number of designers noticed that the tokens were still referencing older versions.

https://github.com/carbon-design-system/carbon/blob/main/docs/migration/v11.md

## How will success be measured?

Older tokens should be removed

## Additional information

- [Carbon v11 migration](https://github.com/carbon-design-system/carbon/blob/main/docs/migration/v11.md)
- [v2 migration reviews](https://github.ibm.com/CDAI-design/pal/issues?q=is%3Aissue+is%3Aopen+label%3A%22project%3A+Carbon+11%22)

**Comment by Ratheeshrajan** [comment]
Closing as #3144 merged.
