### ISSUE TITLE
Card overflow menu missing title attribute

### ISSUE THREAD

**Issue by nictownsend** [carbon-design-system/ibm-products#3038]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

`2.0.1`

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Event Automation - Event Processing capability

GA June 2023

## Steps to reproduce the issue

1. Add a menu item to a Productive card that causes ellipsis truncation
2. There is no title on hover so you cannot read the text

> Please create a reduced test case in CodeSandbox
>
https://codesandbox.io/p/sandbox/dazzling-sanne-lpryjl?file=%2Fsrc%2FExample%2FExample.jsx%3A16%2C34

## Additional information

https://react.carbondesignsystem.com/?path=/story/components-overflowmenu--default - has `requireTitle` which enables the `title` attribute to the menu item

**Comment by elycheea** [comment]
@jagathgj can you take a look? Seems straightforward, but feel free to reach out to @davidmenendez if you have questions.

**Comment by jagathgj** [comment]
@nictownsend,  When adding longer text, we can provide a prop `requireTitle: true` inside overflowActions so that longer text can be visible as tooltip while hovering.

<img width="513" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/29351394/68aaeba4-3b6c-44ed-8df2-2d8f38f873ac">


Here is the sandbox:

https://codesandbox.io/p/sandbox/muddy-sea-ww4nyq?file=%2Fsrc%2FExample%2FExample.jsx%3A37%2C9-37%2C28

@elycheea FYI

**Comment by elycheea** [comment]
@nictownsend Did @jagathgj’s suggestion work for you or do we need to look into this further?

**Comment by nictownsend** [comment]
Hi, yes this worked - https://carbon-for-ibm-products.netlify.app/?path=/docs/ibm-products-components-cards-productivecard--docs#with-overflow should be updated to make it clear what properties are acceptable on `overflowActions`, currently:

```
Use an overflow menu instead of action icons. Refer to design documentation for implementation guidelines
[{ id: string, itemText: string, onClick: func, onKeyDown: func }]
```

**Comment by jagathgj** [comment]
@nictownsend This is already included in [carbondesignsystem](https://react.carbondesignsystem.com/?path=/docs/components-overflowmenu--overview), as the overflow menu itself is a basic component.

**Comment by nictownsend** [comment]
@jagathgj - in which case please can we link to that in https://github.com/carbon-design-system/ibm-products/blob/873be579a83893b82c5774e36b353c868e507d1e/packages/ibm-products/src/components/ProductiveCard/ProductiveCard.js#L105 and remove the prop types.

Otherwise `tsx` is going to be unhappy with trying to use the other props from OverflowMenu.
