### ISSUE TITLE
[Datagrid, FilterSummary] Tags overflow is unintuitive to see all tags

### ISSUE THREAD

**Issue by joyful-these** [carbon-design-system/ibm-products#3046]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

It takes too many steps to see the full titles of all the applied filters. If I click on the overflow button, it shows a list of the additional filters, but some are truncated if the text is too long. If I want to see the full titles, I have to either hover over the text, or click the "View all tags" button (which only appears when there are a lot of overflow items).

![3603fe9a-347e-43ba-b505-e4d2919e56b7](https://github.com/carbon-design-system/ibm-products/assets/108295261/f9088a33-824e-475d-a246-d875a24257bd)

> Is this issue related to a specific component?

FilterSummary

> What did you expect to happen? What happened instead? What would you like to
> see changed?

When I click the overflow button, I expect to see all of the applied tags, without any truncated text.
Instead of displaying the tooltip, it could just show the "View all tags" modal window.

Current flow:
1. Click overflow button
2. Click "View all tags" at the bottom of the tooltip
3. See all tags with full titles in the modal window

Proposed flow:
1. Click overflow button
2. See all tags with full titles in the modal window

<img width="823" alt="Screenshot 2023-05-24 at 3 27 36 PM" src="https://github.com/carbon-design-system/ibm-products/assets/108295261/5fdda047-06e1-449d-9f05-417ed9f80ad8">

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

1.51.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

CP4WAIOps

**Comment by elycheea** [comment]
@Laura-Marshall @sdignum This looks a bit more like a design question since it’s a bit different than the current behavior in our TagSet. (Laura, I know we have TagOverflow proposed in v2 but think it shares the same behavior as well?)

**Comment by elycheea** [comment]
@Laura-Marshall Some more possible overlap with TagOverflow and TagWallFilter discussions.

**Comment by elycheea** [comment]
@joyful-these There’s been an update that allows you to view all tags within the filter summary (although not a modal).
