### ISSUE TITLE
[Datagrid, Flyout] filter Flyout does not open after cleaning the filter

### ISSUE THREAD

**Issue by igorgrv** [carbon-design-system/ibm-products#3070]
## What package(s) are you using?

- [X] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

While testing the Filter Flyout - Example from [CodeSandbox](https://codesandbox.io/p/sandbox/datagrid-flyout-search-n1go1x?file=%2Fsrc%2FExample%2Futils%2FDatagridActions.jsx%3A1%2C1) - I noticed that after we open flyout menu and click on 'clear filters' the flyout does NOT open again.

> Is this issue related to a specific component?

Yes, [Filter Flyout](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-filtering-flyout--flyout-batch)
 
> What did you expect to happen? What happened instead? What would you like to
> see changed?

I would expect the filter flyout to open again

> What browser are you working in?

Chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

"@carbon/ibm-products": "^2.4.0"

## Steps to reproduce the issue

Here's an example from [CodeSandbox](https://codesandbox.io/p/sandbox/datagrid-flyout-search-n1go1x?file=%2Fsrc%2FExample%2Futils%2FDatagridActions.jsx%3A1%2C1).

https://github.com/carbon-design-system/ibm-products/assets/44535773/f48fcdf6-53dd-4daf-9ab1-6e5b05b2cf65

**Comment by elycheea** [comment]
@AlexanderMelox Is this related to the `FilterContext` PRs?

**Comment by davidmenendez** [comment]
@igorgrv can you confirm if this issue is still persisting? i wasn't able to replicate it and the code sandbox link is broken for me.

**Comment by davidmenendez** [comment]
@igorgrv any updates?
