### ISSUE TITLE
Module not found: Error: Can't resolve '@carbon/ibm-products'

### ISSUE THREAD

**Issue by kranky23** [carbon-design-system/ibm-products#3071]
I am getting the above error when I am importing the below line.
`import { PageHeader } from "@carbon/ibm-products";`
I am using React 18. Kindly help me.

**Comment by kranky23** [comment]
Yes. I'm using react 18 and that's why it is causing the issue

**Comment by elycheea** [comment]
Ahhh, we don’t support that yet but it’s in our backlog. Closing this issue for now since this will hopefully be addressed by #2895 🤞
