### ISSUE TITLE
Datagrid design review: Pagination

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#3119]
## Design review

- Component epic #1607 #2499 
- Links: [PAL guidance](https://pages.github.ibm.com/cdai-design/pal/components/data-table/settings/usage) / [Storybook v2](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-datagrid-canary--with-pagination) / [Storybook v1](https://v1-ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-datagrid-canary--with-pagination)
  - Pagination ([Carbon](https://www.carbondesignsystem.com/components/data-table/usage/#multi-select-and-batch-action))
  - Ability to handle thousands of entries

---

### Standards

- [ ] All pattern updates/changes/iterations have been discussed with the
      component developer
- [x] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [x] The component behaves according to the guidelines set by the pattern
      maintainer
- [x] The component’s UI matches the pattern specifications set by the pattern
      maintainer
- [x] The component’s motion matches the specifications set by the pattern
      maintainer(s)
- [x] The UI produced is responsive, cross-browser, and responds to the
      currently set Carbon theme.
- [ ] Colors, themes, sizes and additional props are true and correct, aligning
      with Carbon set tokens (unless otherwise specified by the pattern)
- [x] Paddings/margins/spacings are true and correct, in both desktop and mobile
      views

### Storybook

- [x] A functioning component renders in Storybook
- [ ] The Storybook displays multiple scenarios that show how the component can
      be used
- [x] Changing props in the Storybook updates the component

**Comment by elycheea** [comment]
@sdignum is this one you feel comfortable looking into? If not, we can reallocate to someone else. These should be mostly based on the current Carbon behavior though so hopefully straightforward enough.

**Comment by elycheea** [comment]
@thefirstartist to double check accessibility.
Feel free to remove any checks that don’t apply.

---

## Accessibility review

### [Keyboard](https://www.ibm.com/able/toolkit/develop/keyboard)

#### Level 1

- [ ] Properly code the navigation order
  - [ ] Ensure interactive elements are reachable with the keyboard
  - [ ] Where possible, achieve the desired tab order by adjusting the DOM,
        rather than overriding the tabindex
  - [ ] When overriding the default focus indicator, confirm focus is highly
        visible
- [ ] Implement established keyboard conventions
  - [ ] Use standard HTML elements where possible, using CSS to alter appearance
        not behavior
  - [ ] Be familiar with established keyboard conventions
  - [ ] Implement keyboard operation for custom elements

#### Level 2

- [ ] Ensure keyboard access to complex interactions
  - [ ] Make custom media player and animation controls keyboard accessible

#### Level 3

- [ ] Code screen updates predictably
  - [ ] Use "activate" rather than "focus" as a trigger
  - [ ] Use an onchange event without disorienting the user

### [Dynamic updates](https://www.ibm.com/able/toolkit/develop/dynamic-updates)

#### Level 1

- [ ] Provide errors accessibly
  - [ ] Use accessible methods to implement error messages
  - [ ] Implement validation and notification to minimize interruptions

#### Level 2

- [ ] Make content accessible that appears on hover or focus
  - [ ] Ensure <kbd>Esc</kbd> dismisses new content
  - [ ] If content appears on hover, the new content needs to remain visible
        until dismissed
  - [ ] Moving the pointer away from the trigger should not be the action that
        dismisses the new content
  - [ ] Ensure custom tooltips and similar hover text can be triggered by
        keyboard
  - [ ] Discuss alternatives to hover text
  - [ ] Use caution where interactive controls appear in the hover text
- [ ] Code cancellation actions accessibly
  - [ ] Provide accessible ways of cancelling pointer interaction
- [ ] Properly code status messages
  - [ ] Use `role=status` to advise on the success or results of an action
  - [ ] Use `role=alert` or an ARIA live region to convey a suggestion or
        warning

#### Level 3

- [ ] Allow reduced motion
  - [ ] Implement motion media queries to reduce user risk

### [Text and non-text](https://www.ibm.com/able/toolkit/develop/text-and-non-text)

#### Level 1

- [ ] Implement text alternatives for meaningful images, sound, and visual data
  - [ ] Give decorative images an ALT attribute with an empty string (`alt=""`)
  - [ ] Use HTML, ARIA, or technology-specific techniques to add short text
        alternatives
  - [ ] Where relevant text exists in the UI, use `aria-labelledby` and
        `aria-describedby` to reference
  - [ ] Provide an accessible method for exposing long text alternatives
  - [ ] Embed multimedia content that supports closed captions
- [ ] Implement correct structure and metadata
  - [ ] Code headings according to specifications
  - [ ] ~Code the `<title>` element on every page according to specifications~
  - [ ] ~Set the language for each page~

#### Level 2

- [ ] Add additional structure where appropriate
  - [ ] Use `<figcaption>` and `<caption>` elements where figures and tables are
        titled
  - [ ] Add additional context to generic link names
  - [ ] Consider adding regions and other ARIA roles to distinguish text
        groupings

#### Level 3

- [ ] ~Mark up foreign words and abbreviations~
  - [ ] ~Use the `lang` attribute for foreign words and phrases~
  - [ ] Use `<abbr>` elements and title attributes to expand abbreviations
- [ ] Achieve necessary reading order
  - [ ] Order content appropriately in the DOM
  - [ ] Only use CSS to alter text position without altering meaning

### [User input](https://www.ibm.com/able/toolkit/develop/user-input)

#### Level 1

- [ ] Associate labels with inputs
  - [ ] Programmatically associate inputs with labels
  - [ ] Add accessible names for inputs lacking visible labels
- [ ] Provide correct name, role, and value
  - [ ] If repurposing a standard component, use ARIA to set the correct name
        and role
  - [ ] On custom components, use ARIA to expose `name`, `role`, and `value`

#### Level 2

- [ ] Reduce conflict between the visible label and a component's accessible
      name
  - [ ] Match the accessible name to the visible label
  - [ ] Include the text of the label in the accessible name

#### Level 3

- [ ] Indicate the purpose of common inputs
  - [ ] Use HTML `autocomplete` attributes, where appropriate

**Comment by sdignum** [comment]
@elycheea I believe my review of this is complete...see design issue for details and things I noticed.

**Comment by thefirstartist** [comment]
Accessibility review is done. All good.

**Comment by elycheea** [comment]
From @sdignum https://github.com/carbon-design-system/ibm-products/issues/2499#issuecomment-1595018459

### Standards
- [ ]  All pattern updates/changes/iterations have been discussed with the
component developer
- [x] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior
- [x] The component behaves according to the guidelines set by the pattern maintainer
- [x] The component’s UI matches the pattern specifications set by the pattern maintainer'
- [x] The component’s motion matches the specifications set by the pattern maintainer(s)
- [x] The UI produced is responsive, cross-browser, and responds to the currently set Carbon theme.
- [x] Colors, themes, sizes and additional props are true and correct, aligning with Carbon set tokens (unless otherwise specified by the pattern). 
- For the v1 data grid, the "of 4 pages" in in text-02, but it should be "text-01"
<img width="1453" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/10590403/95c5235c-a66c-4733-a19b-e2ce3626acc3">

- Note: The tooltip for dark themes looks wrong (I see this on Carbon stuff as well) - it shows a shadow on both the caret and the tooltip container, creating a line between the caret and the content area.
- [x] Paddings/margins/spacings are true and correct, in both desktop and mobile views

### Storybook

- [x] A functioning component renders in Storybook
- [ ] The Storybook displays multiple scenarios that show how the component can be used 
- According to Carbon guidance on the [data table section](https://carbondesignsystem.com/components/data-table/usage/#pagination) and the [Pagination guidance](https://carbondesignsystem.com/components/pagination/usage), there should be a simple view, one with disabled pages, and one where the number of pages are unknown, but I don't see a way to look at those variations in Storybook.
- Also, Carbon pagination storybook allows for adjusting height of the pagination bar (sm, med, large)
- [x] Changing props in the Storybook updates the component - N/A

**Comment by elycheea** [comment]
@sdignum So took a closer look, I think datagrid v1 is coming directly from Carbon and not something we changed.

Checked with @matthewgallo during DSAG today and `Pagination` is something that the developer can pass in using the Carbon component so I think the variants you described would be accounted for that way.

If we still want to override the `$text-02` from Carbon, we can open an issue but I _believe_ we can close this one if no other concerns!

**Comment by sdignum** [comment]
Sounds good @elycheea. 👍 Since it's Carbon v10 they probably made the decision to not fix on purpose and instead just fixed it for v11  🤷‍♀️ I'm fine with closing it

**Comment by elycheea** [comment]
Whooo. First design review closed from our round 2 of reviews. THANK YOU @sdignum and @thefirstartist!

**Comment by elycheea** [comment]
@all-contributors add @sdignum for design

@all-contributors add @thefirstartist for accessibility and design
