### ISSUE TITLE
Story writing review

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-products#3128]
Over time we appear to have ended up with a number of different patterns to write our stories.

All stories really should:
1. Declare a Template and use it to create stories. NOTE: This is required to get `code` on the docs page.
2. Call prepare story.
3. Use the correct storybook layout e.g. `fullscreen`, `padded` or `centered`. We currently default to centered.
4. All stories should include a JSDoc comment describing the main reason for using the componetn.
5. When we write JSDoc blocks use ` not ' to highlight text.
6. Components that react to resizing should include the utility DisplayBox in their story.

**Comment by elycheea** [comment]
Should also reference this for #3180
