### ISSUE TITLE
FilterSummary should use a display box like ActionBar

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-products#3130]
The resizing of FilterSummary cannot be visually tested in Storybook.

It should use the display box as per `ActionBar` where the width of the container can be controlled in storybook.

Note DisplayBox is a utility component found in `global/js/utils`

![image](https://github.com/carbon-design-system/ibm-products/assets/15086604/279e33de-573d-4e85-b9b9-4265214a6783)

**Comment by elycheea** [comment]
#3171 should be the v1 version of this.
