### ISSUE TITLE
Release action issues

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#3151]
The v2 release action fails but still publishes, because the step to commit the updated lock file fails. @elycheea shared that we might not actually need to worry about this now that we're using the latest version of `lerna` ([see more details here](https://github.com/lerna/lerna/issues/3551)).

The v1 release action fails and does not publish because `@carbon/ibm-cloud-cognitive-core` is getting published from both `main` and `main_v1` which is causing mismatched version issues. To resolve this we need to do a major version bump for that package on the `main` branch (v2) to avoid the clashing versions.

**Comment by elycheea** [comment]
Thank you @matthewgallo for documenting this in an issue. 🙏
