### ISSUE TITLE
Security releases: publishing under `v1-latest` dist-tag

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#3153]
## What will this achieve?

The security package is still getting published under the `v1-latest` dist-tag because it's part of the group of packages published from `release-v1.yml`. What we need to happen is publish `ibm-products` under `v1-latest` and publish security as `latest`. Change will need to be made [here](https://github.com/carbon-design-system/ibm-products/blob/main/.github/workflows/release-v1.yml#L43-L45).

## How will success be measured?

`@carbon/ibm-products: 1.x.x` => `v1-latest` dist-tag
`@carbon/security` => `latest` dist-tag

## Additional information

- Designs
- Existing code
- etc

**Comment by elycheea** [comment]
@lee-chase Mind taking a look at this if you have a moment between the upgrades?
