### ISSUE TITLE
Page header actions re-rendering

### ISSUE THREAD

**Issue by rahulrkr08** [carbon-design-system/ibm-products#3162]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

I am facing some issue with `PageHeader` component, issue is the page actions (`ButtonSetWithOverflow`) is retendering an infinite loop. Which causes mouse click event is not to work with actions.

> Is this issue related to a specific component?

Yes, `PageHeader`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

Chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

"@carbon/ibm-products": "^2.2.0",
"@carbon/react": "^1.31.3",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Additional information

<img width="1790" alt="Screenshot 2023-06-23 at 7 17 58 PM" src="https://github.com/carbon-design-system/ibm-products/assets/2932484/0dcad177-9ebb-46ca-aec9-6b506b91532f">

**Comment by elycheea** [comment]
@rahulrkr08 Can you throw together a quick in CodeSandbox to help us reproduce this?

**Comment by elycheea** [comment]
@rahulrkr08 Are you still seeing this issue? I know we made some updates around the resizeObserver that was causing re-rendering issues.

**Comment by rahulrkr08** [comment]
Apologies, for the delay... seems the issue is resolved with latest package. Thanks for looking.
