### ISSUE TITLE
Options tile toggle is not working as expected

### ISSUE THREAD

**Issue by sdepuy** [carbon-design-system/ibm-products#3163]
## What package(s) are you using?

- [X] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

The `onToggle` callback does not get invoked when clicking on the toggle component of the `Options tile` component.

Note that when using the keyboard to focus the toggle element and push the SPACE key, it works as expected.

> Is this issue related to a specific component?

Yes, `Options tile`.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The `onToggle` callback should be called so we can manage the `enabled` state of the component.

> What browser are you working in?

Chrome and FF

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

Using @carbon/ibm-products v2.1.3 or v2.2.0 and @carbon/react v1.31.3.

Note that the @carbon/react `Toggle` underlying component works as expected.

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Content Service on AWS.

## Steps to reproduce the issue

```
<div>
          <OptionsTile
            enabled={enabled}
            onToggle={setEnabled}
            title="Hardware acceleration"
          />
          <Toggle
            size="sm"
            toggled={enabled}
            onToggle={setEnabled}
            labelA="Hardware acceleration"
            labelB="Hardware acceleration"
          />
</div>
```

The `Options tile` component does not work but the `Toggle` component works fine.

> Please create a reduced test case in CodeSandbox
>
[> https://codesandbox.io/s/github/carbon-design-system/ibm-products/tree/main/examples/carbon-for-ibm-products/SidePanel
](https://codesandbox.io/p/sandbox/github/carbon-design-system/ibm-products/tree/main/examples/carbon-for-ibm-products/OptionsTile?file=%2Fsrc%2FExample%2FExample.jsx%3A1%2C1)

## Additional information

- Screenshots or code
- Notes

**Comment by rakesh-musturi** [comment]
@sdepuy every thing works by justing adding an onClick function to optionTile component. 
https://codesandbox.io/p/sandbox/zen-kapitsa-wqx572
check this one, i have just added to your code and it works.
Will updage the storybook too
cc @elycheea
