### ISSUE TITLE
[DataGrid] onSort causes first sort in DataGrid to not work

### ISSUE THREAD

**Issue by cgerein** [carbon-design-system/ibm-products#3197]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

Passing a custom sort function to `useDataGrid()` with `onSort` causes the first sort you try to do to not change the actual sort state on the column, but the `onSort` function will still be called. This will cause onSort to call with the id and sort order you would expect, but the DataGrid will still show the previous order. Any clicks/changes to column order after the first click works how you would expect it to.

`"@carbon/ibm-products": "2.1.2"`

## Steps to reproduce the issue

1. Pass an `onSort` function to the DataGrid state
```
useDataGrid({ ...state, onSort: () => {} }, ...plugins, useSortableColumns)
```
2. Go to your DataGrid and try to sort a column
3. Depending on your function, it will have been called, but the column state will be the same
4. Clicking the column to sort again will call the `onSort` function again with the same parameters, and will properly set the columns sort state

Here's an example of the issue
https://codesandbox.io/p/sandbox/tender-northcutt-5lw2vc?file=%2Fsrc%2FExample%2FExample.jsx%3A9%2C24

## Additional information

- Screenshots or code
- Notes

**Comment by davidmenendez** [comment]
hey @cgerein i tried to recreate this, but in your example and locally i found that adding `onSort` actually prevents the sort from firing at all. the problem is that when you pass `onSort` you're signifying that you will be handling sorting the column yourself. so when you're callback is just `(a, b) => console.log(a, b)` nothing happens because no sorting has actually taken place.

can you clarify what your expected behavior is?

**Comment by elycheea** [comment]
Maybe be worth pointing the documentation to `react-table` here in name of separating business and component logic.

**Comment by cgerein** [comment]
Hey, thanks for taking a look. I'm still seeing the issue with it in that codesandbox in the description. Essentially what I was seeing there and locally was that the first click you did to sort a column would be called with ASC, but the column state wouldn't change. By that I meant that the column header wouldn't update the sort state.

Once you clicked the header a second time it shows the ascending icon properly, but is also still passing ASC to the `onSort` function. After that second click the column was sorting, or calling the `onSort` with the correct parameters.

My expected behaviour would be that clicking twice on a column header doesn't pass `ASC` to the `onSort` twice.

**Comment by davidmenendez** [comment]
ok i see what you're saying. let me verify that this is an issue on our end and not with the underlying react table library.

**Comment by davidmenendez** [comment]
hey @cgerein just to give a quick update- i've been investigating this, but i haven't been able to find a conclusive reason for why this is happening. i think this may be put on hold for a bit because there are some more pressing issues, but we're still looking into this.

**Comment by ljcarot** [comment]
We've been investigating [TanStack ](https://tanstack.com/table/latest)[Table](https://tanstack.com/table/latest), a third-party, open-source offering, which provides extensive data table capabilities surpassing what our Carbon Datagrid offers. It provides much more flexibility and customization. TanStack Table is headless which means it can easily be added alongside Datagrid component in your product or application. The benefits of more flexibility for product teams and less maintenance for Carbon makes it a win win. Lastly, it is available in multiple frameworks including [React](https://github.com/carbon-design-system/tanstack-carbon/tree/main/react#readme) and [Web Component](https://github.com/carbon-design-system/tanstack-carbon/tree/main/web-components#readme) so it provides an option to non-React product teams.

For these reasons, we have decided to transition from building our own custom table component to using an example-based approach with TanStack Table. Datagrid will still exist in our library for existing teams but we are announcing the deprecation* of the Datagrid component in v2.54.0 release so teams can begin to work through the transition. Details about how to use both Datagrid and TanStack together can be found [here](https://github.com/carbon-design-system/tanstack-carbon/tree/main). 

*Deprecation means that no new features will be added however sev 1 and sev 2 bugs will be supported.
