### ISSUE TITLE
Improve Datagrid table descriptions for accessibility

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#3246]
There are a few screenreader issues when testing with voiceover setting on Mac. 

1. Table description 
- Currently voiceover provides only a vague description of the table.  Need to add `aria-label`, `aria-describedby`or `caption` to provide accessible description of the table.  Although this is something that the developer implementing this component will need to supply, so probably something we should mention in guidelines or possible add a prop for?
See: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/table_role

_Originally posted by @kristastarr in https://github.com/carbon-design-system/ibm-products/issues/3118#issuecomment-1616741501_

**Comment by davidmenendez** [comment]
i believe this will be fixed by a PR i already opened to add a title to table...

https://github.com/carbon-design-system/ibm-products/pull/3325

**Comment by davidmenendez** [comment]
fixed in https://github.com/carbon-design-system/ibm-products/pull/3362
