### ISSUE TITLE
Can't resolve 'lottie-web' in `SteppedAnimatedMedia` in `@carbon/ibm-products@1.55.0`

### ISSUE THREAD

**Issue by s100** [carbon-design-system/ibm-products#3352]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

Attempting a simple webpack build with `@carbon/ibm-products`, I see this error:

```
Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve 'lottie-web' in 'C:\Users\088857866\WebstormProjects\ace-electron\node_modules\@carbon\ibm-products\es\components\SteppedAnimatedMedia'
```

> Is this issue related to a specific component?

`<SteppedAnimatedMedia>`

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

`@carbon/ibm-products@1.55.0`

## Steps to reproduce the issue

Probably the issue is here:

https://github.com/carbon-design-system/ibm-products/blame/4a7110b38042c4dabcddc49901ce68169dd7f18b/packages/ibm-products/src/components/SteppedAnimatedMedia/SteppedAnimatedMedia.js#L10

`@carbon/ibm-products@1.55.0` does not specify a production dependency on `lottie-web`, so naturally this import will fail.

## Additional information

This problem is not present in the previous version, `@carbon/ibm-products@1.54.2`.

**Comment by matthewgallo** [comment]
This is now resolved with https://github.com/carbon-design-system/ibm-products/pull/3354 and `@carbon/ibm-products@1.55.1` has been published.

**Comment by dbrugger** [comment]
Having this error now with 2.19.0:

```
> next build
   ▲ Next.js 14.0.4
10% building ...ndencies 60/181 modulesFailed to compile.
../node_modules/@carbon/ibm-products/es/components/SteppedAnimatedMedia/SteppedAnimatedMedia.js
Module not found: Can't resolve 'lottie-web'
https://nextjs.org/docs/messages/module-not-found
Import trace for requested module:
../node_modules/@carbon/ibm-products/es/components/SteppedAnimatedMedia/index.js
../node_modules/@carbon/ibm-products/es/components/InlineTip/InlineTip.js
../node_modules/@carbon/ibm-products/es/components/InlineTip/index.js
../node_modules/@carbon/ibm-products/es/components/index.js
../node_modules/@carbon/ibm-products/es/index.js
```


2.18.1 worked fine

**Comment by elycheea** [comment]
Reopening for @dbrugger — probably the same issue in v2 although I think we added InlineTip (which uses SteppedAnimatedMedia) about a month ago. 🤔 We’ll investigate though.
