### ISSUE TITLE
Demote `h1` in NotificationsPanel

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#3379]
NotificationsPanel currently uses `h1` as a heading. Most of our components should probably use `h2` or `h3` at highest. Comparable components such as the `SidePanel` and novice-to-pro panel that @paul-balchin-ibm is looking into will use `h2` which may be a more appropriate heading level.

- [ ] Replace `h1` tag in NotificationsPanel with `h2`

**Comment by daimbk** [comment]
can i work on this
