### ISSUE TITLE
All Datagrids have a blank column on the right

### ISSUE THREAD

**Issue by lily-peng** [carbon-design-system/ibm-products#3401]
## Bug description
The [Datagrid](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--basic-usage) component includes a blank column on the right for some reason. This doesn't allow our columns to cover the full width of the component for a seamless look.

## Steps to reproduce 
How do we reproduce the error you described above: (ex. below)
1. This can be viewed in any Datagrid story in Storybook
2. Can also be viewed in any Codesandbox with Datagrid. Example from the docs: https://codesandbox.io/s/github/carbon-design-system/ibm-products/tree/main_v1/examples/carbon-for-ibm-products/Datagrid

## URL/Link of Page
https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--basic-usage

https://codesandbox.io/s/github/carbon-design-system/ibm-products/tree/main_v1/examples/carbon-for-ibm-products/Datagrid

## Expected behavior
There shouldn't be an empty column, the users' columns should be all the component creates.

### Viewing Platform:
 - OS: macOS
 - Browser: Chrome
 - Version: storybook v2.7.0

## Screenshots

https://media.github.ibm.com/user/340510/files/12c37511-8366-4246-8b4d-a5361b48eaeb

**Comment by matthewgallo** [comment]
This extra column was initially added to create a bit extra buffer so the actual last column could be resized since the resizer placement is on the right of the column you are resizing. I'll look into if we might be able to decrease the size of the empty column or even better if we might be able to remove it entirely.

**Comment by matthewgallo** [comment]
Hey @lily-peng, just reaching back out regarding the extra/spacer column, the purpose is to provide an affordance to resize the last column. For example, if the table spans the full width of the page, the edge of the last column is so close to the edge of the window and can prevent proper resizing on that column.

**Comment by elycheea** [comment]
@lily-peng We could potentially investigate a way to turn off resizable columns and remove the extra column without the plugin, but think if we have resizable columns enabled, this is helps with ease of use.

**Comment by SeonyuK** [comment]
Even though to help the resizable columns, I don't think we should have that big empty column. The column takes way to much space. It is worse with row actions

**Comment by marinamas** [comment]
This issue still exists in the latest version of IBM products (2.37.0). Any timiline on fixing this

**Comment by sstrubberg** [comment]
Thanks for the update @marinamas. I'll que it up for the next sprint.

**Comment by Emily1799** [comment]
Will this require a code change to get the fix for, once it makes it off the backlog? Or will things just be 'right' then? I'm also impacted by this and need to know if I have to set myself a reminder 🙂

**Comment by davidmenendez** [comment]
@lily-peng @SeonyuK @marinamas @Emily1799 i have a draft PR to demonstrate what the table would look like without the spacer column. can y'all take a look and provide feedback? thanks

[storybook preview](https://deploy-preview-5377--carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid--basic-usage&globals=viewport:basic)

**Comment by SeonyuK** [comment]
Yeah this looks much better

**Comment by Emily1799** [comment]
And this fix would work with resizable columns turned off as well? There doesn't seem to be an example of that in Storybook. If so, then this looks much better, yeah.

**Comment by marinamas** [comment]
which version will these changes be available?
