### ISSUE TITLE
Data Table Filter component should allow user to remove filters individually

### ISSUE THREAD

**Issue by lily-peng** [carbon-design-system/ibm-products#3402]
## Bug description
Hi team, it appears the Data Table Filter component in Storybook does not have the ability to remove individual filters, only the ability to clear all: https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-panel--panel-batch

In the design doc, it looks like users should be able to remove filters one-by-one: https://pages.github.ibm.com/cdai-design/pal/components/data-table/filters/#filter-summary

Is this a bug that is currently being worked on? Our team is looking to use this component but will have many different filters under accordions, and it would be much less user-friendly if users would have to open/close accordions and scroll through them to remove filters.

## Steps to reproduce 
How do we reproduce the error you described above: (ex. below)
1. Go to 'https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-panel--panel-batch'
2. Open filters using top-left icon button 
3. Apply a filter
4. Notice that filter pills don't allow removal of the filter

## URL/Link of Page
Link here: https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-panel--panel-batch

## Expected behavior
The ability to remove individual filters in the Data Table Filter component

## Screenshots
<img width="457" alt="image" src="https://media.github.ibm.com/user/340510/files/4b8d9576-010f-4418-95e4-09b476989465">
<img width="1140" alt="image" src="https://media.github.ibm.com/user/340510/files/56259e4b-4b7a-4552-b143-02bdc6a15f1c">

**Comment by elycheea** [comment]
This looks mostly complete (see [FilterSummary](https://ibm-products.carbondesignsystem.com/?path=/docs/ibm-products-internal-filtersummary--docs)), but we may want to consider `filter: true` as the default for filters in the filter summary. Believe the original designs intended this as well.

I think our filter examples should show this with the filters at least. @lily-peng feel free to contribute here if you’ve got any pockets of time. ;)

**Comment by lee-chase** [comment]
Probably should do @elycheea, there is however no provision for the removal of individual filters.

**Comment by lee-chase** [comment]
I think it would be better if someone familiar with DataGrid should update FilterSummary.

**Comment by matthewgallo** [comment]
This work has been merged in #3582 and #3630 and will be included in next weeks release.
