### ISSUE TITLE
[datagrid] bug: error in component when using useCustomizeColumns and useSelectRows hooks together

### ISSUE THREAD

**Issue by SunnyJohal** [carbon-design-system/ibm-products#3412]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?
Chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
2.6.1

## Steps to reproduce the issue

1. Create a new datagrid and add the `useCustomizeColumns` hook and button. This will work as normal and show the tearsheet when the button is clicked.
2. Now add the useSelectRows hook to the `useDatagrid` function call
3. Click the `CustomizeColumnsButton` again.
4. An error appears: Cannot read properties of undefined (reading 'props')

## Additional information

- Console log message:
```
DraggableItemsList.js:41 Uncaught TypeError: Cannot read properties of undefined (reading 'props')
    at checkTitle2 (DraggableItemsList.js:41:30)
    at getColTitle2 (DraggableItemsList.js:46:91)
    at DraggableItemsList.js:51:14
    at Array.filter (<anonymous>)
    at DraggableItemsList2 (DraggableItemsList.js:50:4)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
```

- Notes
I think this is an issue with the column definition for the select row column.

**Comment by SunnyJohal** [comment]
Fixed in latest release, closing.

**Comment by elycheea** [comment]
We can investigate this when we reinstate drag and drop in customize columns.

**Comment by martin31821** [comment]
I'm suffering from the same issue in v2.11.0, even with #3344 merged, with the exact same stacktrace. 

I think a permanent fix to this issue would be to also check `col.Header().props` and `col.Header().props.children` for undefined. 

Code: https://github.com/matthewgallo/ibm-products/blob/main/packages/ibm-products/src/components/Datagrid/utils/getColTitle.js#L16

**Comment by Ratheeshrajan** [comment]
@elycheea I had a look into this issue, but I have not been able to reproduce this issue locally. Also tried in codesandbox with `"@carbon/ibm-products": "2.22.0",` and `"@carbon/ibm-products": "2.11.0",` https://codesandbox.io/p/devbox/datagrid-userowselect-columncustomization-4l4chn

**Comment by sstrubberg** [comment]
Closing. Happy to re-open if this is still an issue
