### ISSUE TITLE
CreateTearsheet content page going blank when onClose handler returning false

### ISSUE THREAD

**Issue by shankar343** [carbon-design-system/ibm-products#3413]
CreateTearsheet content page going blank when onClose handler returning false

## Detailed description

> Describe in detail the issue you're having.
Whenever "Cancel" btn is clicked, onClose handler is called. If that onClose method handler returning "false", then entire CreateTearsheet component is going blank.

> Is this issue related to a specific component?
Yes, IBM-products (CreateTearsheet)

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Expectation is similar to Tearsheet component, CreateTearsheet component should allow users to close Modal on need basis. If user wants to keep the CreateTearsheet page remain open, then it doesn't allow it. 
Returning "false" from onClose handler keeping the page remain open, but clearing all content.

> What browser are you working in?
All browser

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
"@carbon/ibm-products": "^2.6.0",

> Please create a reduced test case in CodeSandbox
>
[> https://codesandbox.io/s/github/carbon-design-system/ibm-products/tree/main/examples/carbon-for-ibm-products/SidePanel
](https://stackblitz.com/edit/github-yd7vvy?file=src%2FExample%2FExample.jsx,package.json)

## Additional information

- Screenshots or code

<img width="613" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/30149749/1e2e2dee-66be-431c-aeae-4faaafc4d6da">

**Comment by elycheea** [comment]
@shankar343 can you share the example with us? We were trying to check an example we previously had a link for but seems like it’s working in the link we currently have.

**Comment by shankar343** [comment]
Hi,
Already added link.... but adding again for reference
https://stackblitz.com/edit/github-yd7vvy?file=src%2FExample%2FExample.jsx

**Comment by davidmenendez** [comment]
hey @shankar343 thanks for opening this up. so the intended behavior here in that `onClose` should close the modal. i don't think i'm following your description of expected behavior. i see in the code what's causing the blank content to appear, but again please help me understand your use case. thanks!

**Comment by davidmenendez** [comment]
@shankar343 i've opened up a PR to address this
