### ISSUE TITLE
SidePanels, at both left and right, leads to accessibility issue The <div> element has the id "c4p--side-panel-outer" that is already in use

### ISSUE THREAD

**Issue by RafflesiaKhan** [carbon-design-system/ibm-products#3414]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## What did you want to know?
I am using **SidePanels**, at both left and right, 
anyone familiar with the accessibility issue `The <div> element has the id "c4p--side-panel-outer" that is already in use`
Providing unique id to different SidePanels does not help, c4p--side-panel-outer is some inside class of SidePanel

## Relevant information

###Screenshorts 

![image](https://github.com/carbon-design-system/ibm-products/assets/11699686/9c8d18fc-fc04-4f16-9c89-7c919ba5a514)

![image](https://github.com/carbon-design-system/ibm-products/assets/11699686/83318d4e-e4d4-45af-9ebc-df3ad6c8008a)

**Comment by elycheea** [comment]
@lee-chase can you help investigate this? Surprised to see `c4p--side-panel-outer` as an ID instead of a class? 👀

**Comment by elycheea** [comment]
Seems like we just need to add a uuid/useId here.

**Comment by ArslanYM** [comment]
Can i work on this?

**Comment by davidmenendez** [comment]
@RafflesiaKhan a fix has been pushed to address this and should be in the next release
