### ISSUE TITLE
Productive Card: Support for dropdown  along with actionIcons in header and footer 

### ISSUE THREAD

**Issue by ArunJoshiIn** [carbon-design-system/ibm-products#3416]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

Current Productive card component does not support other actionable icons or input elements ( eg: dropdown) along with overflow menu in header section. Would be nice if we have that flexibility in header and footer components of productive card to include the dropdown items or other elements along with action icons 

> Is this issue related to a specific component?
yes, productive card component 
https://ibm-products.carbondesignsystem.com/?path=/docs/ibm-products-components-cards-productivecard--docs 

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
v2.7.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Turbonomic 

## Additional information

![image](https://github.com/carbon-design-system/ibm-products/assets/33432564/6f962ab1-6718-4769-bbac-2d8c56cd2703)

**Comment by elycheea** [comment]
@ArunJoshiIn This is an interesting use case we haven’t seen much of before. May be worth raising in #ibmproducts-pal for more design input before we explore this pattern further.

**Comment by elycheea** [comment]
@ArunJoshiIn Were you able to share this with the design guild yet? If not, maybe worth reaching out to @carrenelloyd or Tomer to help advance this.

**Comment by ArunJoshiIn** [comment]
> @ArunJoshiIn Were you able to share this with the design guild yet? If not, maybe worth reaching out to @carrenelloyd or Tomer to help advance this.

@elycheea - actually our implementation is being driven by design and their requirements
- Adam.Kaynan@ibm.com
