### ISSUE TITLE
Add support to change Datagrid toolbar height

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#3451]
> In the guidance, it says that the toolbar height should change as the user adjusts the row height. Neither v1 or v2 demonstrate this in the storybook. 
>
> - [ ] **Action item:** Decide if this should still be included in the pattern even if it is not going to be supported behavior of the component.

_Originally posted by @Ashley-Bock in https://github.com/carbon-design-system/ibm-products/issues/3117#issuecomment-1591931929_

> ... is this something we changed intentionally, something users have control over instead of us, or something that was missed. I could imagine this being a little bit tricky for some of the smaller sizes.

_Originally posted by @elycheea in https://github.com/carbon-design-system/ibm-products/issues/3117#issuecomment-1595340914_

**Comment by ljcarot** [comment]
We've been investigating [TanStack ](https://tanstack.com/table/latest)[Table](https://tanstack.com/table/latest), a third-party, open-source offering, which provides extensive data table capabilities surpassing what our Carbon Datagrid offers. It provides much more flexibility and customization. TanStack Table is headless which means it can easily be added alongside Datagrid component in your product or application. The benefits of more flexibility for product teams and less maintenance for Carbon makes it a win win. Lastly, it is available in multiple frameworks including [React](https://github.com/carbon-design-system/tanstack-carbon/tree/main/react#readme) and [Web Component](https://github.com/carbon-design-system/tanstack-carbon/tree/main/web-components#readme) so it provides an option to non-React product teams.

For these reasons, we have decided to transition from building our own custom table component to using an example-based approach with TanStack Table. Datagrid will still exist in our library for existing teams but we are announcing the deprecation* of the Datagrid component in v2.54.0 release so teams can begin to work through the transition. Details about how to use both Datagrid and TanStack together can be found [here](https://github.com/carbon-design-system/tanstack-carbon/tree/main). 

*Deprecation means that no new features will be added however sev 1 and sev 2 bugs will be supported.
