### ISSUE TITLE
User need some indication to identify `there is more information available and needs to do horizontal scrolling` on Datagrid if it's width exceeds viewport.

### ISSUE THREAD

**Issue by tineshpradeep** [carbon-design-system/ibm-products#3481]
In DatGrid component user need some indication to identify there is more information available and needs to do horizontal scrolling on Datagrid if it exceeds viewport.

## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description
In DatGrid component if there is more fields and it beyonds our viewport then there is a scroll option available for the user but there is no indication that we have more information/ columns available on the same table and we can scroll horizontally to see that. So better indicates there is more information and user needs to do horizontal scrolling.

> Describe in detail the issue you're having.

> Is this issue related to a specific component?
DATAGRID
> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?
Chrome/Firefox
> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
 "@carbon/ibm-products": "2.4.1"

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Open any Datagrid example 
2. Reduce the browser size/ check the table with large number of columns
3. Scroll is available but no indication that we should scroll to see the remaining details/columns that hidden on our viewport.

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-products/tree/main/examples/carbon-for-ibm-products/SidePanel

Additional information

Attached a recording for reference.
Here we can see whole columns in normal view but if browser size reduced/ if large number of columns will available then user should scroll horizontally to view the whole data but there is no indication for the user that they should scroll horizontally for view whole data. So better indicates there is more information and user needs to do horizontal scrolling.
https://github.com/carbon-design-system/ibm-products/assets/38095378/d34b4fd1-56e8-49e6-892a-4ace19c7cf83

**Comment by lee-chase** [comment]
It is an interesting dilemma as the user, operating system and/or browser have chosen to hide the scroll bar. It may also be the case that the Tearsheet is not an appropriate place to display a large table.

**Comment by elycheea** [comment]
CC @vsnichols if you also had thoughts about how to approach this.

**Comment by ljcarot** [comment]
We've been investigating [TanStack ](https://tanstack.com/table/latest)[Table](https://tanstack.com/table/latest), a third-party, open-source offering, which provides extensive data table capabilities surpassing what our Carbon Datagrid offers. It provides much more flexibility and customization. TanStack Table is headless which means it can easily be added alongside Datagrid component in your product or application. The benefits of more flexibility for product teams and less maintenance for Carbon makes it a win win. Lastly, it is available in multiple frameworks including [React](https://github.com/carbon-design-system/tanstack-carbon/tree/main/react#readme) and [Web Component](https://github.com/carbon-design-system/tanstack-carbon/tree/main/web-components#readme) so it provides an option to non-React product teams.

For these reasons, we have decided to transition from building our own custom table component to using an example-based approach with TanStack Table. Datagrid will still exist in our library for existing teams but we are announcing the deprecation* of the Datagrid component in v2.54.0 release so teams can begin to work through the transition. Details about how to use both Datagrid and TanStack together can be found [here](https://github.com/carbon-design-system/tanstack-carbon/tree/main). 

*Deprecation means that no new features will be added however sev 1 and sev 2 bugs will be supported.
