### ISSUE TITLE
[Datagrid, EmptyState] Showing incomplete/unnecessary line on the bottom

### ISSUE THREAD

**Issue by youngjunekoh** [carbon-design-system/ibm-products#3483]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

Seen from the `ibm-products` storybook:
![Screenshot 2023-09-20 at 10 00 48 AM](https://github.com/carbon-design-system/ibm-products/assets/60585804/86bdc1f4-aa8a-4517-a9d6-1d7a6d874591)

Seen from my developing environment:
![Screenshot 2023-09-20 at 10 00 56 AM](https://github.com/carbon-design-system/ibm-products/assets/60585804/11281144-df8d-4308-a3f0-7bf5da1bf1b4)

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?
Chrome for Mac

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

Version 2.8.1

**Comment by youngjunekoh** [comment]
<img width="678" alt="Screenshot 2023-09-28 at 12 01 33 PM" src="https://github.com/carbon-design-system/ibm-products/assets/60585804/2f272afc-4b00-4bf4-97bc-de9c211dca7f">

Had a conversation with Paul today, hover state is yet to be addressed.

fyi @paul-balchin-ibm 

Thank you team for the efforts! Best.

**Comment by paul-balchin-ibm** [comment]
See also #3514

**Comment by matthewgallo** [comment]
[v1 accompanying PR](https://github.com/carbon-design-system/ibm-products/pull/3540)
