### ISSUE TITLE
CreateFullPage Header Extension

### ISSUE THREAD

**Issue by baraaabdelsalam** [carbon-design-system/ibm-products#3486]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)

## Detailed description
The header is defined in the designs, but it has not been incorporated into the code.

![Screenshot 2023-09-21 at 14 54 34](https://github.com/carbon-design-system/ibm-products/assets/22206101/3e71a989-c9d3-4740-885d-4defe58b65a3)

> Is this issue related to a specific component?

Yes, CreateFullPage

**Comment by elycheea** [comment]
@CoderRedwing this one is already in a PR from the author of this issue. :)
