### ISSUE TITLE
Investigate stylelint highlighting in VSCode

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#3491]
## What will this achieve?

Lint for everyone locally — figure out what settings are conflicting

## How will success be measured?

Stylelint issues are shown in VS Code

## Additional information

- Designs
- Existing code
- etc

**Comment by lee-chase** [comment]
In about modal for instance if I change 43 to a px value, this should be highlighted in VSCode. Running the script `lint:styles` does report it.

```
padding: 0 20px 0 $spacing-05;
```

**Comment by paul-balchin-ibm** [comment]
These are my personal notes condensed from `vscode-stylelint`'s [documentation](https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint)

**VSCode**
1. Install VSCode's Stylelint extension `vscode-stylelint`
2. Open Settings page > find `stylelint.validate`, add "css" and "scss". Optionally include "less" and "postcss".

**`package.json`**, `vscode-stylelint` doesn't work with `stylelint` version 13 or less: 
- `$ npm install stylelint@latest`

If the above still doesn't work, it may be that global linting packages are interfering.

**Optional, uninstall global linting packages**

List global packages from anywhere using CLI
- `$ npm list -g --depth=0`

Run this command to uninstall a global package
- `$ npm uninstall -g <package_name>`

Global directories for reference
- Mac: `/usr/local/lib/node_modules`
- Windows 7+: `%USERPROFILE%\AppData\Roaming\npm\node_modules`

**Comment by sstrubberg** [comment]
Does Lee's [stylelint plugin](https://github.com/carbon-design-system/stylelint-plugin-carbon-tokens) solve for this?

**Comment by matthewgallo** [comment]
Hey @paul-balchin-ibm, we're using `"stylelint": "^15.x.x"` so I'm not sure if this is still applicable for our library. Are you ok with closing this?
