### ISSUE TITLE
🐛 DataGrid - issue with panel closing behavior

### ISSUE THREAD

**Issue by al2613** [carbon-design-system/ibm-products#3511]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

filter panel doesn't properly close after adjusting column width

> Is this issue related to a specific component?
DataGrid component

> What did you expect to happen? What happened instead? What would you like to
> see changed?

panel should close

> What browser are you working in?
chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

2.8.4 (currently is an issue on 2.1.0 as well)

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

w3 app 

## Steps to reproduce the issue

https://github.com/carbon-design-system/ibm-products/assets/27175307/8705a41c-dbe4-497f-af76-fa2b0f701351

## Additional information
- recording attached

**Comment by matthewgallo** [comment]
Hi @al2613, I was taking a look at this today and it appears that with the latest changes this is no longer an issue. If you still observe this after upgrading to the latest version feel free to reopen!
