### ISSUE TITLE
React 18 with Jest Unit Tests Failing

### ISSUE THREAD

**Issue by al2613** [carbon-design-system/ibm-products#3512]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

Jest testing framework fails due to dependency issue with `react-dnd`

```
  /Users/annettelin/Desktop/w3-carbon/ibmer-carbon-components/node_modules/react-dnd/dist/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export * from './core/index.js';
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

    > 1 | import { pkg } from "@carbon/ibm-products";
```

> Is this issue related to a specific component?

N/A 

> What did you expect to happen? What happened instead? What would you like to
> see changed?

our test cases to pass

> What browser are you working in?
chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

@carbon/ibm-products 2.8.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

w3 app

## Additional information
this seems to have been an issue before - not entirely sure if there's some sort of workaround in the meantime https://github.com/carbon-design-system/ibm-products/issues/1949

**Comment by matthewgallo** [comment]
Upgrading to `@carbon/ibm-products: 2.9.0` resolves this issue as `react-dnd` was removed in that version.
