### ISSUE TITLE
Add support for resize column to fit content

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#3516]
Originally from #1923
We should do some evaluation on data tables to determine if this makes sense in the Datagrid context. Some of the interactions described feel more akin to a DataSpreadsheet.

### Desired behavior
1. Hover over the right side of the column header until a horizontal split cursor appears.
2. Double-click the column line.
3. The column is resized to fit the contents.

![doubleClick](https://user-images.githubusercontent.com/5809654/163623937-7118dbf8-b482-429a-919f-71d3fa8d4f85.gif)

```[tasklist]
### Tasks
- [ ] Evaluate whether this interaction is appropriate for data tables (or data spreadsheets)
- [ ] Work with design to define a comparable experience for keyboard users
```

**Comment by ljcarot** [comment]
We've been investigating [TanStack ](https://tanstack.com/table/latest)[Table](https://tanstack.com/table/latest), a third-party, open-source offering, which provides extensive data table capabilities surpassing what our Carbon Datagrid offers. It provides much more flexibility and customization. TanStack Table is headless which means it can easily be added alongside Datagrid component in your product or application. The benefits of more flexibility for product teams and less maintenance for Carbon makes it a win win. Lastly, it is available in multiple frameworks including [React](https://github.com/carbon-design-system/tanstack-carbon/tree/main/react#readme) and [Web Component](https://github.com/carbon-design-system/tanstack-carbon/tree/main/web-components#readme) so it provides an option to non-React product teams.

For these reasons, we have decided to transition from building our own custom table component to using an example-based approach with TanStack Table. Datagrid will still exist in our library for existing teams but we are announcing the deprecation* of the Datagrid component in v2.54.0 release so teams can begin to work through the transition. Details about how to use both Datagrid and TanStack together can be found [here](https://github.com/carbon-design-system/tanstack-carbon/tree/main). 

*Deprecation means that no new features will be added however sev 1 and sev 2 bugs will be supported.
