### ISSUE TITLE
[DATAGRID] Hover tooltip for Datagrid sort accessible?

### ISSUE THREAD

**Issue by youngjunekoh** [carbon-design-system/ibm-products#3526]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## What did you want to know?
![Screenshot 2023-10-02 at 4 05 04 PM](https://github.com/carbon-design-system/ibm-products/assets/60585804/0033a1df-8ca7-4acd-bae4-9aacebe1ce05)

Notice that hovering over the sort arrows do not indicate sorting order whatsoever. Would be nice if they can indicate some sorting method (i.e. from screenshot above, `First Name, Ascending` ...)

I am using `ibm-products: v2.10.2`

**Comment by elycheea** [comment]
@youngjunekoh Going to close this based on yesterday’s discussion. We do have `aria-sort` in place, but if we find this is still an issue for some reason, feel free to re-open this.
