### ISSUE TITLE
Fix vertical alignment in larger row heights

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#3548]
When using larger row heights, such as `xl`, text should be aligned to the top.

[Storybook v2](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-rowheightsettings--default-settings-usage-story) / [v1](https://v1-ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-rowheightsettings--default-settings-usage-story)

---

According to Carbon, the data in the 'Extra large height' cell aligns to the top vertically.

<img width="817" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/40870771/7601a1bd-c6d5-4948-a1c1-ff59f08920ea">
  
I see that data is center-aligned vertically in the storybook:
<img width="671" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/40870771/1b9c6288-5085-41fd-ae0a-3f1be41fce10">

_Originally posted by @thefirstartist in https://github.com/carbon-design-system/ibm-products/issues/3508#issuecomment-1747530116_

**Comment by nikhilgarg26** [comment]
hey @elycheea i am new to open source can you guide me on this
and how to reproduce that issue

**Comment by elycheea** [comment]
Hi @nikhilgarg26! I added some additional links to the Storybook. I believe the reference made by the person reporting the issue was from this [story in Carbon](https://react.carbondesignsystem.com/?path=/story/components-datatable-basic--xl-with-two-lines).

**Comment by nikhilgarg26** [comment]
as of i understand the issue i need to make [this ](https://react.carbondesignsystem.com/?path=/story/components-datatable-basic--xl-with-two-lines) vertically center aligned 

![image](https://github.com/carbon-design-system/ibm-products/assets/116938919/b40f90b1-2b7c-417d-937e-5677055d07a7)

**Comment by nikhilgarg26** [comment]
can we you provide the file where the cshnges need to be made

**Comment by Tanush-J** [comment]
I will give this a try

**Comment by Tanush-J** [comment]
So, I was able to produce this behavior,

https://github.com/carbon-design-system/ibm-products/assets/75922615/a47c90a3-628a-4beb-aee2-7c3a5ba80342

is this the behavior expected?

**Comment by matthewgallo** [comment]
Completed in #3709 and #3718
