### ISSUE TITLE
Influencer is hardcoded into EditTearsheet component

### ISSUE THREAD

**Issue by silvaDominic** [carbon-design-system/ibm-products#3554]
## Brief description

The EditTearsheet component is using a local variable for the influencer element.

## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

The EditTearsheet component features an optional property to include/override the influencer element. This is inaccessible because the influencer element is defined using a local variable of the same name. Curiously, the influencer property is not explicitly included in the forwarded refs like all other props.

![Screenshot 2023-10-05 at 2 47 14 PM](https://github.com/carbon-design-system/ibm-products/assets/12387334/cede8e78-27e3-4124-a9fd-6426fd900c0d)

> Is this issue related to a specific component?

[EditTearsheet](https://github.com/carbon-design-system/ibm-products/blob/main/packages/ibm-products/src/components/EditTearsheet/EditTearsheet.js)

> What did you expect to happen?
- Expected the influencer to be derived from child (EditTearsheetForm) titles as it is with the CreateTearsheet component.
- Expected the influencer to be overridable.
   - Expect the influencer prop to give access to some kind of 'next form' handler so a custom one can associate certain forms with certain influencer items

> What happened instead?
- A local, example influencer is defined instead.

> What would you like to see changed?
- A default behavior that corresponds with the CreateTearsheet pattern (influencer list items are derived from child titles).
- A mechanism to override the influencer.

> What browser are you working in?

Chrome/FF

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive) package are you using?

- carbon/ibm-products: 2.10.2
- carbon/react: 1.35.0

> What offering/product do you work on?

[IBM Turbonomic](https://www.ibm.com/products/turbonomic)

> Any pressing ship or release dates we should be aware of?
- Impacting development of major feature that utilizes tearsheets (Create and Edit).
- Sprint deadline of 10/10/2023
- Feature deadline, GA by end of Q4 2023

## Steps to reproduce the issue
1. Create an EditTearsheet (in the open state) with **two** corresponding EditTearsheetForms

### Issue 1
2. Give the EditTearsheetForms custom titles
3. Observe how influencer looks like this:
![Screenshot 2023-10-06 at 12 27 12 PM](https://github.com/carbon-design-system/ibm-products/assets/12387334/368fc854-5927-4171-9054-5dc27aa3c713)
4. Observe how clicking last 2 items renders nothing in tearsheet as there's no associate form.

## Issue 2
2. Create a custom influencer like below:
```
    function influencer() {
        return (
            <div className='tearsheet-stories__dummy-influencer-block'>
                <SideNav
                    aria-label='Side navigation'
                    className={`${blockClass}__side-nav`}
                    expanded
                    isFixedNav={false}
                >
                    <SideNavItems>
                        <SideNavMenuItem
                            key={0}
                        >
                            Dummy label
                        </SideNavMenuItem>
                    </SideNavItems>
                </SideNav>
            </div>
        )
    }
```
3. Pass it as a prop to `EditTearsheet` like:
`influencer={influencer()}`
4. Observe how it has no effect on influencer

## Additional information
- Spoke with and confirmed issue with @matthewgallo.

**Comment by matthewgallo** [comment]
Published in `2.11.1`.
