### ISSUE TITLE
Datagrid: specific row action buttons should only show on row hover

### ISSUE THREAD

**Issue by vsnichols** [carbon-design-system/ibm-products#3557]
## What will this achieve?

This is a correction to a draft component extension to be implemented before release. @matthewgallo @elycheea FYI

## How will success be measured?

[Coded component](https://ibm-products.carbondesignsystem.com/?path=/docs/ibm-products-components-datagrid-datagrid-canary-extensions-rowactionbuttons--docs) matches [design guidelines](https://pages.github.ibm.com/cdai-design/pal/components/data-table/row-action-buttons/usage) 

## Additional information

Requested changes to match design specs
- Row action buttons, used if only 1 or 2 actions exist, should only appear on row hover 
- Do not use specific row action buttons with frozen action column
- If the action column has been frozen it must use the overflow icon no matter how many actions are available
- Can we change examples 1 and 3 in storybook to have fewer columns so that they don't use a frozen column (see above)

**Comment by elycheea** [comment]
@vsnichols I think this is probably one we can prototype to discuss a bit more. I do have concerns about some of the specific interactions and ensuring that we can communicate to a keyboard user that there are actions before they reach the actions themselves — while they can reach them via tabbing, there’s no affordances to let them know that they can keep tabbing in this case.

Also with actions appearing on hover, are we intending that on hover they overlay the content behind them.

**Comment by vsnichols** [comment]
Thanks @elycheea @matthewgallo maybe we can talk thru the recommended behavior and how to handle tabbing

- Actions should still have own column even when they just only show on row hover, they should not overlay content
- On a table where content does not fit, and horizontal scroll kicks in, best practice (maybe we make it automatic) is for the action column to freeze
- On freeze, no matter how many actions are available, we display an overflow menu

<img width="897" alt="Screenshot 2023-10-09 at 5 09 24 PM" src="https://github.com/carbon-design-system/ibm-products/assets/39408106/2dbfb657-1d62-4930-a5ea-1f80edde8a60">

**Comment by matthewgallo** [comment]
https://github.com/carbon-design-system/ibm-products/pull/3778 includes the changes listed above for row action buttons, notable:
- frozen columns _always_ render items in an overflow menu
- non frozen columns only show on row hover/focus of icon buttons
