### ISSUE TITLE
PageHeader: extend subtitle to support officially also ReactElement

### ISSUE THREAD

**Issue by ShiriKremer** [carbon-design-system/ibm-products#3575]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description
According to documentation, PageHeader substring is of type **string**.  
We need to include a link in the substring text to point to further information.  We passed to the PageHeader substring property a ReactElement to try to support this and it worked. But we saw a warning:
==>Warning: Failed prop type: Invalid prop `subtitle` of type `object` supplied to `PageHeader`, expected `string`

 My requested behavior is to extend the official subtitle definition type to include:
ReactElement | string

> Is this issue related to a specific component?

PageHeader component

> What browser are you working in?

 Chrome 

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
package are you using?

2.10.1

> What offering/product do you work on? Any pressing ship or release dates we
should be aware of?

IBM Turbonomic

**Comment by matthewgallo** [comment]
Hey @ShiriKremer, this has been fixed and will be delivered in the next release (Tuesday morning).
