### ISSUE TITLE
Fix alignment of inline loading in save pattern state

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#3617]
Also caught a small alignment issue in the [Saving](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-patterns-saving-saving--manual) pattern —

<img width="681" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/1717398/8cd36c39-0a91-4ecb-a518-5364b69927a2">

The loading icon is not vertically centered.

_Originally posted by @elycheea in https://github.com/carbon-design-system/ibm-products/pull/3571#pullrequestreview-1675083624_
            
**Note:** With SCSS changes, you may need to update the styles snapshot. (Can find this in the package.json.)

```
yarn test:c4p:snapshot
```
```[tasklist]
### Acceptance criteria
- [ ] Vertically center the loading icon when saving
```

**Comment by Pinaka-Pani-18** [comment]
I would like to work on this issue, Could you please assign me?

**Comment by hamzailyas237** [comment]
Is this issue still persists ? I would like to work on this.
