### ISSUE TITLE
Prevent draggable items from being dropped into locked column position

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#3624]
> Oooh, thanks for fixing this. So this implementation still allows us to drag to the position of a locked column but prevents the reordering from updating? I think ideally, we should prevent dropping into the locked column position, but understand if that’s not possible with dnd-kit now. 🤔

_Originally posted by @elycheea in https://github.com/carbon-design-system/ibm-products/pull/3598#pullrequestreview-1677306919_

**Comment by Ratheeshrajan** [comment]
Closing as #4180 & #4182
