### ISSUE TITLE
FilterSummary: Can't close filters when filters are inside the dropdown

### ISSUE THREAD

**Issue by AlexanderMelox** [carbon-design-system/ibm-products#3627]
The user is not able to close filters inside the dropdown:
![Screenshot 2023-10-17 at 2 56 01 PM](https://github.com/carbon-design-system/ibm-products/assets/12755042/fac72869-1503-492d-83d0-61a6dceaf0b3)

We should prob get design involved here. 

```[tasklist]
### Tasks
```

**Comment by AlexanderMelox** [comment]
<img width="1001" alt="Screenshot 2023-10-17 at 3 02 48 PM" src="https://github.com/carbon-design-system/ibm-products/assets/12755042/f32c3457-14ac-4d8b-ba7b-fdfd04efb3d8">

**Comment by matthewgallo** [comment]
Update from @Laura-Marshall, TagSet should be able to support rendering the overflow items as filter/interactive tags.
<img width="733" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/10215203/1ea30f68-3ce9-4aa7-9dce-89ef4b9e1221">

**Comment by Laura-Marshall** [comment]
@matthewgallo To add more context:

The tag overflow guidance is meant to supersede TagSet for v11, but I'm not sure if its been scoped. One of the enhancements is to add this functionality, as well as to allow the +X tag to be used with other non tag elements.

https://pages.github.ibm.com/cdai-design/pal/components/tag-overflow/usage/

Its not displaying in our nav so not sure if someone can add it in to replace Tag Set for greater visibility?

**Comment by matthewgallo** [comment]
The ability to close filters from the overflow has been added to the current TagSet component (v1 and v2). We can open a new/separate issue for renaming TagSet in v2 to TagOverflow.
