### ISSUE TITLE
getAutoSizedColumnWidth not working as expected

### ISSUE THREAD

**Issue by lalomayida** [carbon-design-system/ibm-products#3650]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

I am using the Carbon for IBM Products package to work with a datagrid, and I'm attempting to make the column sizes dynamically adjust to the content within each column. According to the documentation, this can be achieved using the `getAutoSizedColumnWidth` function. However, I've encountered an issue where it seems to only expand the column width if the header text is long enough, seemingly ignoring the data accessor.

> Is this issue related to a specific component?

This issue is related to the datagrid component in the Carbon for IBM Products package.

> What did you expect to happen? What happened instead? What would you like to see changed?

I expected that the `getAutoSizedColumnWidth` function would dynamically adjust the column width based on the content of the specified data accessor. However, it appears to only expand the column width if the header text is long enough, ignoring the data accessor. I would like to see this dynamic sizing feature work as intended, adjusting the column width based on the content.

> What browser are you working in?

I am working in Firefox.

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive) package are you using?

I am using version 2.3.0 of the `@carbon/ibm-products` package.

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

I am working on Financial / Offboarding application. The tool has to be delivered on November 1st. We can hard-code the width size while this issue is being addressed

## Steps to reproduce the issue

1. Create a datagrid with columns configured as follows:
   ```javascript
   Columns Object:
   {
       Header: 'Last Name',
       accessor: 'employee.lastName',
       width: getAutoSizedColumnWidth(data, 'employee.lastName', 'Last Name')
   },
   {
       Header: 'Middle Name',
       accessor: 'employee.middleName',
       width: getAutoSizedColumnWidth(data, 'employee.middleName', 'Middle Name')
   },
   {
       Header: 'First Name',
       accessor: 'employee.firstName',
       width: getAutoSizedColumnWidth(data, 'employee.firstName', 'First Name')
   },
   {
       Header: 'Preferred Name',
       accessor: 'employee.preferredName',
       width: getAutoSizedColumnWidth(data, 'employee.preferredName', 'Preferred Name')
   }

2. Populate the datagrid with the following data:
    ```
    {
        "employee": {
            "lastName": "TNAMLAST040260",
            "middleName": "",
            "firstName": "TNAMFRST040260",
            "preferredName": "TNAMPREF040260"
        }
    }
    ```

3. Observe that the column width does not adjust dynamically based on the content of the data accessor.

![image](https://github.com/carbon-design-system/ibm-products/assets/51863317/c9e0b8aa-747b-4f5a-a547-3506f1a9e1d6)

4. Sandbox

https://codesandbox.io/p/sandbox/awesome-rumple-n6v7zy?file=%2Fsrc%2FExample%2FExample.jsx%3A73%2C7
```[tasklist]
### Acceptance criteria
- [ ] Review CodeSandbox
- [ ] Review and debug current `getAutoSizedColumnWidth`
- [ ] Refactor as needed ...
- [ ] Add new example in Storybook for autosized columns
```

**Comment by davidmenendez** [comment]
@lalomayida thanks for opening up this issue and I apologize for such a long time since anyone responded.

your codesandbox is no longer working, but i was able to create my own based on the criteria you specified and i was unable to replicate the bug you're experiencing. i know it's been a while since this was first opened. can you verify if you're still experiencing this problem on the most recent version of ibm-products?

here is the [sandbox i created](https://codesandbox.io/p/devbox/goofy-maria-zwpf54). as you can see the header for `id` is very short with a very long uuid string, but the column sizes appropriately.



![Image](https://github.com/user-attachments/assets/43e6556b-d7d7-4365-bf68-408feded4508)

**Comment by davidmenendez** [comment]
haven't been able to replicate and haven't heard back from @lalomayida so i'm going to mark this as closed. feel free to reopen if you continue to experience this issue.
