### ISSUE TITLE
Datagrid[useActionsColumn]: support `isDelete` prop

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#3662]
https://github.com/carbon-design-system/ibm-products/pull/3657/files#r1367387172

## What will this achieve?

We should use the `prepareProps` utility to remove the `isDelete` prop if there are either 1 or 2 column actions, because as @paul-balchin-ibm pointed out the `OverflowMenu` trigger component does not accept `isDelete` as a property. 

## How will success be measured?
When `prepareProps` is used to remove `isDelete` if there are 1 or 2 actions to prevent prop type errors.

## Additional information

- Designs
- Existing code
- etc

**Comment by Ratheeshrajan** [comment]
Closing as #4161 & #4173
