### ISSUE TITLE
IBM Plex San font does not works well on some situation

### ISSUE THREAD

**Issue by guobinzhao** [carbon-design-system/ibm-products#3678]
https://github.ibm.com/tools-for-aps/zh/issues/36546#issuecomment-65558931
pls check the issue on the above link since we have not found a stable recreate steps, but disabling the local font will bypass the issue.

**Comment by matthewgallo** [comment]
This is an issue for the core Carbon team. I suggest opening an issue for them to take a look.

https://github.com/carbon-design-system/carbon/issues/new/choose
