### ISSUE TITLE
Storybook console warning: Each child in `DatagridSimpleBody` should have a unique "key" prop

### ISSUE THREAD

**Issue by paul-balchin-ibm** [carbon-design-system/ibm-products#3679]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)

## Detailed description

> Describe in detail the issue you're having.

When running Storybook locally, I see console warnings across many stories.

http://localhost:3000/?path=/story/ibm-products-components-datagrid-datagrid-canary--basic-usage

```
Warning: Each child in a list should have a unique "key" prop. 
Check the render method of `DatagridSimpleBody`...
```

> Is this issue related to a specific component?

Yes: `packages/ibm-products/src/components/Datagrid/Datagrid/DatagridSimpleBody.js`

> What did you expect to happen? What happened instead? What would you like to see changed?

We should not see these console warnings at all.

> What browser are you working in?

Chrome, latest.

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive) package are you using?

v2.12

> Any pressing ship or release dates we should be aware of?

No.

## Steps to reproduce the issue

1. Fork and clone `@carbon/ibm-products` to your local machine.
2. `yarn` to install packages.
3. `yarn storybook` to run Storybook.
4. Open the browser to each of the URLs listed above.
6. Open the browser's dev tools.
7. Select the "Console" tab to view the console warnings.

**Comment by paul-balchin-ibm** [comment]
After some research, this may not be fixable. 

The `render` function of DatagridSimpleBody is mapping through object-oriented code instead of a React/JSX/DOM element node. This is where a "key" property would normally be applied. 

(Example code simplified for clarity)
```
const DatagridSimpleBody = () => {
  return (
    <TableBody ... >
      {rows.map((row) => {
        prepareRow(row);
        return row.RowRenderer({ row });
      })}
    </TableBody>
  );
};
```

**Comment by matthewgallo** [comment]
I believe we just needed to add the key to fragment in `DatagridRow` which is the component that `row.RowRenderer` renders. https://github.com/carbon-design-system/ibm-products/pull/3772
