### ISSUE TITLE
DataGrid Column Customization breaks when trying to reorder last column of the table

### ISSUE THREAD

**Issue by marinamas** [carbon-design-system/ibm-products#3708]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive) - Yes
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.
    Using a Datagrid with selectable column and reordering the last column to a different position breaks the DataGrid.

> Is this issue related to a specific component?
Yes , DataGrid column customization

> What did you expect to happen? What happened instead? What would you like to
> see changed?
   I should be able to reorder all the columns of the table expect for the freezed columns

> What browser are you working in?
 Chrome & Safari

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive) -  
"@carbon/ibm-products": "2.12.1",
 "@carbon/react": "1.41.0",

> Please create a reduced test case in CodeSandbox
https://codesandbox.io/s/keen-cloud-2ffcfr

## Additional information

- Screenshots or code
<img width="1728" alt="Screenshot 2023-10-27 at 7 03 00 PM" src="https://github.com/carbon-design-system/ibm-products/assets/80206173/53bb6289-156c-47c2-9e03-1c83ce629d83">

```[tasklist]
### Tasks
```

**Comment by matthewgallo** [comment]
Hey @marinamas, I just checked with the latest changes and I am not seeing this issue anymore. I would try updating to the latest version of `@carbon/ibm-products` and if you still see this behavior feel free to reopen this issue and we'll take another look!
