### ISSUE TITLE
datagrid and filter panel extensions 

### ISSUE THREAD

**Issue by tkolanko** [carbon-design-system/ibm-products#3713]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## What did you want to know?

What's the status of filtering searching for datagrid. I can get the search input to appear by passing in showFilterSearch but searching has no effect, looking at https://github.com/carbon-design-system/ibm-products/blob/0f226a6af5fd9c21aa5d39f26266f561895385b9/packages/ibm-products/src/components/Datagrid/Datagrid/addons/Filtering/FilterPanel.js#L223-L233 it looks like it doesn't do anything right now

**Comment by matthewgallo** [comment]
Hey @tkolanko, this is something that is not completed yet. The snippet you shared above actually is supposed to search your filters in the panel itself. See design [here](https://pages.github.ibm.com/cdai-design/pal/components/data-table/filters#filter-panel) for more details.

You can do a global search (outside of the filter panel/flyout). String search/filter isn't something that is currently included in the filter panel/flyout as of right now.

**Comment by elycheea** [comment]
@tkolanko We are closing this, but if you have additional questions, please feel free to reopen, open a new issue, or reach out.
