### ISSUE TITLE
Bug: Tearsheet —— Unexpected scrolling behaviour

### ISSUE THREAD

**Issue by Sachin-B-Suresh** [carbon-design-system/ibm-products#3715]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

 I am seeing an odd issue with <Tearsheet> component in chrome and safari. 
Using @carbon/ibm-products v2.1.0

> The Tearsheet header gets clipped and extra spacing is added in the footer of the component. Refer the gif attached. 
I have messaged the same [on slack](https://ibm-security.slack.com/archives/CRV39QKP0/p1607523654128300).

## Solution
Removing overflow css property from the tearsheet resolves the issue.
> As a workaround i am currently using the following property
.c4p--tearsheet .c4p--tearsheet__container--lower {
    overflow: unset;
}

I found the exact issue fixed in Ibm-security package, https://github.com/carbon-design-system/ibm-security/pull/866

![error](https://github.com/carbon-design-system/ibm-products/assets/41235479/82a986ae-c950-4917-a868-6e3d87e80353)

**Comment by makafsal** [comment]
@Sachin-B-Suresh I have attempted to replicate the reported issue; however, I have not been successful in reproducing it. I would appreciate your assistance in guiding me through the steps to replicate the issue accurately.

**Comment by elycheea** [comment]
@Sachin-B-Suresh Are you able to replicate this in our Storybook? If not, can you share a minimal reproduction in CodeSandbox or Stackblitz so @makafsal can investigate this further?
