### ISSUE TITLE
Proposal: Publish styles as separate package

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-products#3716]
Publishing the styles as an independent package. E.g. `@carbon/ibm-products-styles`

This would mirror the Carbon core pattern and allow the production of WebComponents as part of the Carbon AI project which looks to make use of Tearsheet and SidePanel.

NOTE: WebComponents would not want to load other non-dev-dependencies

**Comment by elycheea** [comment]
Successfully published in latest release [`@carbon/ibm-products-styles@2.17.0`](https://www.npmjs.com/package/@carbon/ibm-products-styles/v/2.17.0).
