### ISSUE TITLE
Datagrid: Extra, empty column added to table

### ISSUE THREAD

**Issue by silvaDominic** [carbon-design-system/ibm-products#3721]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

After upgrading from 2.11.3 to 2.13.0 all instances of our datagrids have an extra, empty column added to them.

> Is this issue related to a specific component?

The datagrid.

> What did you expect to happen?

No change to # of columns.

> What happened instead?

Additional column was added.

> What browser are you working in?

Chrome/FF/Safari

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

2.13.0

> What offering/product do you work on?

[IBM Turbonomic](https://www.ibm.com/products/turbonomic)

> Any pressing ship or release dates we should be aware of?

Blocking development of multiple teams

## Steps to reproduce the issue

1. Use IBM Carbon version 2.11.3
2. Observe datargid columns
3. Upgrade to at least 2.13.0
4. Observe datagrid columns

## Additional information

https://github.com/carbon-design-system/ibm-products/assets/12387334/7c94b90b-838c-4c5a-b500-5e5a65d8b312

_Observe how multiple datagrids now have an extra, empty column._

![Screenshot 2023-10-30 at 12 29 08 PM](https://github.com/carbon-design-system/ibm-products/assets/12387334/8034e255-c568-4afe-93eb-8ebf8f7fe518)

_Column has an empty `div` as content._

I believe the issue was caused in https://github.com/carbon-design-system/ibm-products/pull/3669 which was part of v2.12.1.

**Comment by matthewgallo** [comment]
Fix will be included in tomorrow's release
