### ISSUE TITLE
datagrid panel filtering extension assumes full viewport height

### ISSUE THREAD

**Issue by tkolanko** [carbon-design-system/ibm-products#3725]
## What package(s) are you using?

See https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-panel--panel-batch 

When you open the filtering panel it takes the full height of the screen, this becomes problematic when you also enable pagination. The pagination toolbar gets pushed past the bottom of the screen

## Steps to reproduce the issue

1. Use panel filtering extension
2. use pagination extension

https://stackblitz.com/edit/github-6w6hhw-7yg7ha?file=src%2FExample%2FExample.jsx
## Additional information

- Screenshots or code
- Notes

**Comment by matthewgallo** [comment]
Confirmed with @sdignum, if the filter panel and pagination are included together, the pagination is meant to sit flush with the rows and not below the filter panel. See example below:
<img width="708" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/10215203/9aeaa8e6-71ce-455e-8734-f1b8e96ce600">

I'll make sure to include this change in the work for this issue.
