### ISSUE TITLE
datagrid filter flyout cancel button does nothing

### ISSUE THREAD

**Issue by tkolanko** [carbon-design-system/ibm-products#3736]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

The cancel button is not active by default when opening the filter flyout and clicking the cancel button after setting a filter does not close the panel

## Steps to reproduce the issue

1. Go to https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-flyout--flyout-batch
2. Open the filter flyout - cancel is disabled
3. Change a filter
4. Click cancel
5. Nothing happens
## Additional information

- Screenshots or code
- Notes

**Comment by davidmenendez** [comment]
confirmed with @vsnichols that this is the intended behavior. @tkolanko the bug fix has been opened in #4142 and should be merged shortly. thanks for bringing this to our attention.
