### ISSUE TITLE
datagrid is unusable after adjusting column widths

### ISSUE THREAD

**Issue by tkolanko** [carbon-design-system/ibm-products#3737]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

After manually adjusting a column width the datagrid is no longer interactable with a mouse

## Steps to reproduce the issue

1. Go to https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-columncustomization--column-customization-usage-story
2. Manually expand first name
The following problems occur:
1. Try to click search, you immediately lose focus
2. Try to click customize columns, nothing happens

## Additional information

- Screenshots or code
- Notes

**Comment by matthewgallo** [comment]
Thanks for opening this issue @tkolanko, we've merged a PR for v1 and v2 to fix this and it will be included in our next release.
