### ISSUE TITLE
Edit Tearsheet: Primary and secondary action buttons use the same callback

### ISSUE THREAD

**Issue by silvaDominic** [carbon-design-system/ibm-products#3744]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

The callback method `onHandleModalClicked` is used for _both_ actions

> Describe in detail the issue you're having.

Unable to distinguish functionality between close and submit behavior.

> Is this issue related to a specific component?

EditTearsheet component.

> What browser are you working in?

Chrome/FF/Safari

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive) package are you using?

2.14.0

> What offering/product do you work on?

[IBM Turbonomic](https://www.ibm.com/products/turbonomic)

## Steps to reproduce the issue

1. Set `onClose` and `onHandleModalClicked` to 2 separate event handlers.
2. Open the tearsheet and click secondary button ('Cancel')
3. Click primary button ('Submit')

## Additional information

https://github.com/carbon-design-system/ibm-products/assets/12387334/d049fe40-8bc4-4fcd-bc83-f64b15871b8c

_Observe that the `onHandleModalClicked` event handler is called for both._

`EditTearsheet.js`

![Screenshot 2023-11-01 at 4 02 00 PM](https://github.com/carbon-design-system/ibm-products/assets/12387334/312ffdb9-ca0e-4fa6-afc0-c4945261c0bf)

_Observe that the same handler is used for both actions._

**Comment by matthewgallo** [comment]
Thanks for contributing this fix @silvaDominic! It will be included in the next release.
