### ISSUE TITLE
 useActionsColumn (2 menu items, icons) with useStickyColumn, horizontal scroll is always enabled

### ISSUE THREAD

**Issue by el-moshme** [carbon-design-system/ibm-products#3747]
## Title line template: [Title]: Brief description

When the actions column is an overflow menu and sticky:right, it doesn't create a horizontal scrollbar on the table. 
When the actions column is the 2 menu icons, and sticky:right, it does create a horizontal scroll bar on the table. 

## What package(s) are you using?

@carbon/ibm-products: 1.56.0

## Detailed description

> Describe in detail the issue you're having.
The horizontal scrollbar is always visible when sticky:right is applied to the actions column and the actions column is 2 menu items, aka buttons. 

> Is this issue related to a specific component?
Datagrid 

> What did you expect to happen? What happened instead? What would you like to
> see changed?
I would like to see the action items contained in the table column and when there is room for all content, no horizontal scrollbar. 

> What browser are you working in?
chrome

> What version of the @carbon/ibm-products
> package are you using? 1.56.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of? projects service, cloud.ibm.com/projects

## Steps to reproduce the issue

1. Step one Created datagrid state with   useActionsColumn, useStickyColumn,
2. Step two Make actions column sticky:right
3. Step three Add 2 row actions

> Please create a reduced test case in CodeSandbox
TBD

## Additional information
<img width="1160" alt="Screenshot 2023-11-02 at 10 58 26 AM" src="https://github.com/carbon-design-system/ibm-products/assets/27785752/1c1f2083-5f55-4063-b2d7-e4b7b5e20eeb">

- Notes

**Comment by vsnichols** [comment]
Hey @matthewgallo I am working with Nancy on this. The bug is actually causing the icons to always appear cut off, and for the horizontal scroll bar to appear.

**Comment by matthewgallo** [comment]
Hey @el-moshme and @vsnichols! @el-moshme can you share your column definitions? If you'd be able to create a code sandbox as well that would be really helpful in debugging what is going on. My guess is that you've not included the `useStickyColumn` hook, along with the `sticky: 'right'` property on the last column.

**Comment by el-moshme** [comment]
@matthewgallo @vsnichols  I cannot recreate it in code sandbox. https://codesandbox.io/p/sandbox/datagrid-bug-dqvx6f
I don't see the same behaviour.  

I could not add useSortableColumns to the example although it is in my UI.
I did not understand the error to fix it.

**Comment by el-moshme** [comment]
@matthewgallo I will try and get some help to reproduce from my team next week. Or maybe the issue is in our code base - something else on the page.

**Comment by el-moshme** [comment]
@matthewgallo actually I found something in our code that is likely the issue.  I will close this for now.  Thanks.
