### ISSUE TITLE
Datagrid: Actions dropdown design review

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#3780]
## Design review

This will probably be a quicker review, we just need to double check the implementation of the actions dropdown (see screenshot below) against the design guidance.
![Screenshot 2023-11-08 at 9 41 06 AM](https://github.com/carbon-design-system/ibm-products/assets/10215203/1ac6cce1-a73b-4c80-bd75-b55427223600)

Component epic #

### Standards

- [ ] All pattern updates/changes/iterations have been discussed with the
      component developer
- [ ] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [ ] The component behaves according to the guidelines set by the pattern
      maintainer
- [ ] The component’s UI matches the pattern specifications set by the pattern
      maintainer
- [ ] The component’s motion matches the specifications set by the pattern
      maintainer(s)
- [ ] The UI produced is responsive, cross-browser, and responds to the
      currently set Carbon theme.
- [ ] Colors, themes, sizes and additional props are true and correct, aligning
      with Carbon set tokens (unless otherwise specified by the pattern)
- [ ] Paddings/margins/spacings are true and correct, in both desktop and mobile
      views

### Storybook

- [ ] A functioning component renders in Storybook
- [ ] The Storybook displays multiple scenarios that show how the component can
      be used
- [ ] Changing props in the Storybook updates the component

**Comment by My-Money29** [comment]
1. Implementation of the actions dropdown follows design guidance 
2. Keyboard nav works as intended.
