### ISSUE TITLE
Datagrid ExpandedRowContentComponent component unable to use hooks 

### ISSUE THREAD

**Issue by lluisrojass** [carbon-design-system/ibm-products#3782]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)

## Detailed description

The `<Datagrid />` expanded row component is unable to utilize hooks freely. If 2 or more hook dependent `ExpandedRowContentComponent` components are rendered, an error is thrown: `Rendered more hooks than during the previous render.`. Furthermore, since the component is treated internally as a function, it would not support a class based component workaround: https://github.com/carbon-design-system/ibm-products/blob/main/packages/ibm-products/src/components/Datagrid/Datagrid/DatagridExpandedRow.js#L42C12-L42C39. 

Expected behavior: I would expect expanded rows to support modern hook based components, but I would also expect that since the name is capitalized `ExpandedRowContentComponent`, and contains the word `Component`, that it be treated as a component internally and rendered via JSX, facilitating the use of class based components

Here is a codesandbox reproduction: https://codesandbox.io/s/nervous-wright-hc6fdd?file=/src/Table.js

`@carbon/ibm-products` version: 2.15.1
`@carbon/react` version: 1.41.2

**Comment by matthewgallo** [comment]
https://github.com/carbon-design-system/ibm-products/pull/3787

**Comment by matthewgallo** [comment]
Hey @lluisrojass, thanks for the detailed issue and joining office hours yesterday to discuss further. This fix should be included in our next weekly release (Nov 14).

**Comment by lluisrojass** [comment]
Thank you, the fix is working properly. Cheers!
