### ISSUE TITLE
Closing the DataGrid filter panel with instant update removes selected filters

### ISSUE THREAD

**Issue by al2613** [carbon-design-system/ibm-products#3788]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)

## Detailed description

> Describe in detail the issue you're having.
closing the filter panel clears the selected filters. this doesn't seem to happen in batch update

> Is this issue related to a specific component?
DataGrid

> What did you expect to happen? What happened instead? What would you like to
> see changed?
filters should remain

> What browser are you working in?
chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> 2.13

https://github.com/carbon-design-system/ibm-products/assets/27175307/5f562413-e248-4aea-933c-7272e9c61aa7

**Comment by elycheea** [comment]
Confirmed this is visible in our [Storybook](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-panel--panel-instant) during call on Nov 9.
