### ISSUE TITLE
Set up `@carbon/ibm-products-community`

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#3814]
## What will this achieve?

Creates a space for product teams to share community or experimental code that may be not be fully maintained by the core IBM Products team. This could also be a good space for work that’s currently going through the DSAG process or new proposals that are being shared.

## Additional information

- Designs
- Existing code
- etc

**Comment by elycheea** [comment]
https://github.com/carbon-design-system/ibm-products/issues/3871#issue-2019118763

**Comment by elycheea** [comment]
Also maybe reach out to @asfordmatt for feedback on this structure/approach as well.

**Comment by davidmenendez** [comment]
per slack conversation with @asfordmatt 

> thanks David, that looks great. I'll take a more detailed look later, but I think we might be okay with having it only in the main branch for v2 / Carbon 11. There are a few products migrating from  the ibm-cloud-cognitive-cdai package to ibm-products  in preparation for moving up to C11. But there is no replacement for IdeHome  so we will look to contribute a C11 version of that component to this new package ibm-products-community

since the community package was merged in the v2 branch i'll go ahead and close this as done for now. if we need to get a v1 version going i think we can open a separate issue for that 👍
