### ISSUE TITLE
Last hovered row stays in that state when you leave the datagrid table using useRowIsMouseOver 

### ISSUE THREAD

**Issue by el-moshme** [carbon-design-system/ibm-products#3819]
## Brief description
The issue is shown in the example in docs
https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--is-hover-on-row
I would expect the row hover behaviour to stop when the mouse is not over the row any longer 

## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)

## Detailed description

> Describe in detail the issue you're having.

> Is this issue related to a specific component?
Datagrid

> What did you expect to happen? What happened instead? What would you like to
> see changed?
When no longer hovering a row, the hover behaviour stops 

> What browser are you working in?
Chrome 

> What version of the @carbon/ibm-products 
> package are you using?
Issue is visible in demo 
https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--is-hover-on-row

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. [Step one](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--is-hover-on-row)
2. Step two hover over table rows
3. move mouse away from table. 

> Please create a reduced test case in CodeSandbox
Not required, as the example is in the docs. 

## Additional information

- Screenshots or code

**Comment by elycheea** [comment]
@Ratheeshrajan can you help @anamikaanu96 with learning the Datagrid enough to address this one. @anamikaanu96 you can take this issue on _after_ the alignment issue.
