### ISSUE TITLE
Improve test coverage for expandable and nested rows and row height settings

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#3820]
## What will this achieve?

Increase test coverage to at least 80%

## How will success be measured?

80+% test coverage

## Additional information

- Designs
- Existing code
- etc

**Comment by elycheea** [comment]
Note — let’s take stock of some testing best practices we should document.

**Comment by matthewgallo** [comment]
Files to check test coverage:
```
DatagridExpandedRow.js
useRowExpander.js
useNestedRowExpander.js
useNestedRows.js
useExpandedRow.js
RowSizeDropdown.js
RowSizeRadioGroup.js
useFocusRowExpander.js
```
