### ISSUE TITLE
The only two actions the action buttons display the overflow menu

### ISSUE THREAD

**Issue by SeonyuK** [carbon-design-system/ibm-products#3843]
For Datagrid Extension RowActionButtons, if there are only two actions the action buttons are display inline and more than two will have an overflow menu button.

## What package(s) are you using?

- [X] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

For Datagrid Extension RowActionButtons, if there are only two actions the action buttons should display inline and more than two should have an overflow menu button. But now the overflow menu displays two or fewer actions
> Is this issue related to a specific component?

Datagrid
> What did you expect to happen? What happened instead? What would you like to
> see changed?

If there are only two actions the action buttons should display inline and more than two should have an overflow menu button. 
> What browser are you working in?

Chrome
> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

2.16.0
> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-products/tree/main/examples/carbon-for-ibm-products/SidePanel

## Additional information
Because  !isColumnSticky is added  in the line 54 in useActionsColumn.js

- Screenshots or code
- Notes

**Comment by elycheea** [comment]
Closing as _not a regression_. As we clarified and discussed over Slack, there was a correction from the design spec — when row actions are used with sticky columns, they should always appear in an overflow now[^1].

[^1]: https://github.com/carbon-design-system/ibm-products/issues/3557#issuecomment-1800104709
