### ISSUE TITLE
Clean up Datagrid stories

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#3863]
Reorganize Datagrid stories so that base component features are exposed top level and “extensions” are included as extensions.

The base component of the Datagrid includes the following features
– Table headers
– Clickable row items
– Row action buttons
– Batch actions
– Empty state
– Frozen columns (scrolling)
– Responsiveness (scrolling)
– Column alignment
– Infinite scrolling
– Resizable columns

Some earlier proposals for reorganizing the stories although batch actions still may better suit the base section for now.

![Image](https://github.com/carbon-design-system/ibm-products/assets/1717398/1b0d78c3-0086-43f7-9830-268fc7f23e36)

**Comment by elycheea** [comment]
Moving to Later for now since some of the previous cleanup broke docs. May want to revisit this after we do some Storybook improvements.

**Comment by ljcarot** [comment]
Done
