### ISSUE TITLE
docs(Create): discrepancy in create flow component spacing

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#3865]
Originally posted by Lily Olive[^1].

## What will this achieve?
Fixes a discrepancy in tearsheet position in the create tearsheet Storybook.

## How will success be measured?
Storybook should show or at least allow CreateTearsheet to set `verticalPosition: lower`. It appears to be working but props are not being pass in the Storybook componnets.

## Additional information

> ### Bug description
> there is a discrepancy in the PAL createflow dev component spacing that differs from the PAL online guidance for where to place component in terms of height from top of page. [Guidance states we should place it 88px from top of page](https://pages.github.ibm.com/cdai-design/pal/patterns/creation-flows/usage/), dev component in storybook has it at 48px from top. 
> ### Steps to reproduce 
> How do we reproduce the error you described above: (ex. below)
> 1. Go to https://pages.github.ibm.com/cdai-design/pal/patterns/creation-flows/usage/  
> 2. Click on 'Wide tearsheet' section jump at top, see and view "alignment" that shows spacing guidance for how high up to position Createflow tearsheet in UI page (says 88px, see screenshot)
> 3. Likewise, navigate to createflow pattern in PAL storybook https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-patterns-create-flows-createtearsheet--multi-step-tearsheet
> 4. View in "inspect" to see difference in padding from guidance.
> 
> ### URL/Link of Page
> [PAL createflow spacing guidance: ](https://pages.github.ibm.com/cdai-design/pal/patterns/creation-flows/usage/#wide-tearsheet)
> 
> ### Expected behavior
> PAL spacing guidance should match dev storybook component so designers can plan for implementation accurately. 
> 
> #### Viewing Platform:
>  - Browser: Chrome
>  - Version 119.0.6045.159
> 
> ### Screenshots
> **PAL online spacing specs for 88px from top of page from online guidance (link above)**
> ![createflow spacing from PAL guideance](https://media.github.ibm.com/user/275038/files/39f956ed-7126-45b4-afe3-da5a07a7f7a7)
> 
> Component in PAL dev storybook showing top height 48px not the 88px guidance states.
> 
> ![createflow storybook px spacing](https://media.github.ibm.com/user/275038/files/903f42bc-152a-461d-a783-0566d766d552)
> 

[^1]: https://github.ibm.com/CDAI-design/pal/issues/1440

**Comment by matthewgallo** [comment]
Control for `verticalPosition` prop working in storybook now 🥳 

https://github.com/carbon-design-system/ibm-products/assets/10215203/0235bc14-2475-42f6-90ef-476e4e408f06
