### ISSUE TITLE
Clear filters in the datagrid filterpanel does not work as expected

### ISSUE THREAD

**Issue by radhika1015** [carbon-design-system/ibm-products#3867]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.
Clicking on filter panel cancel button after clearing previously set filters causes the cleared filters to be displayed again.

> Is this issue related to a specific component?
Datagrid

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Expected behavior is clicking on cancel should clear the filter panel but not reapply the cleared filters.

> What browser are you working in?
Chrome Version 119.0.6045.159

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
@carbon/ibm-products 1.61.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Resilient SOAR uax 2.0

## Steps to reproduce the issue

1. Set a filter in the datagrid filter panel and  click apply
2. Filters are applied and populated in the Filter summary panel
3. Click clear filter button in the Filter summary panel
4. click another filter in the filter panel
5. Click the cancel button in the filter panel

## Additional information

https://github.com/carbon-design-system/ibm-products/assets/13211057/9d7d2f6c-925d-4943-a653-dd26872d41c3

**Comment by elycheea** [comment]
Possibly related to #3801 but will investigate further when we pick up #3801

**Comment by matthewgallo** [comment]
This is actually the intended behavior as of right now as discussed with @AlexanderMelox. Going to chat with @sdignum to see if the "Clear filters" button can change to reset all filter history.

**Comment by AlexanderMelox** [comment]
Technically, we do not have a reset filter. So whenever we "clear filters" and the user adds any other filters and then changes their mind and "cancels"; Cancel will revert to the previous filters before the user opened the panel.

**Comment by matthewgallo** [comment]
Behavior of `Clear filters` button in the filter summary has changed to remove all history as expected. This change will be reflected in next week's release (Tuesday morning).
