### ISSUE TITLE
 Filter Summary panel tooltip remains open after clicking outside the tooltip

### ISSUE THREAD

**Issue by radhika1015** [carbon-design-system/ibm-products#3869]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.
Filter summary panel tooltip remains open even after clicking outside the tooltip

> Is this issue related to a specific component?
Datagrid

> What did you expect to happen? What happened instead? What would you like to
> see changed?
The tooltip should not be visible
> What browser are you working in?
Chrome Version 119.0.6045.159

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
@carbon/ibm-products 1.61.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Resilient SOAR uax 2.0
## Steps to reproduce the issue

1. Apply a few filters from the filter panel so that the +x is displayed
2. Click on the +x
3. Close individual filters one at a time - the tooltip stays open

## Additional information

https://github.com/carbon-design-system/ibm-products/assets/13211057/95b2b354-3f8c-4cae-81b4-8f775611e673

**Comment by matthewgallo** [comment]
Hi @radhika1015, I'm not able to reproduce this issue in the latest v1. Can you provide a code sandbox?

**Comment by matthewgallo** [comment]
I was able to reproduce this issue in v2 and have created a [PR](https://github.com/carbon-design-system/ibm-products/pull/3997) to fix it. However, I still am not seeing this behavior in v1.
