### ISSUE TITLE
Add support for listing all filters in filter summary

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#3894]
List all chevron may need prototyping to evaluate and is already related to #3046 where @joyful-these shared a proposed flow.

The design guidance does not show an example of the expanded list view, but I expect this would cause the height of the datagrid to shift in some cases if vertical scrolling is not used. I think a prototype would help answer these questions, but would suggest this as a possible enhancement since I think we could introduce the change without breaking changes. 🤔 

![image](https://user-images.githubusercontent.com/1717398/287798069-f6d1689e-d9e6-459d-82cf-0ed5d5690227.png)

--- 

> ### Filter summary
> - Clear filters button should hug the filter tags (currently right aligned)
> - Where's the 'List all' chevron?
> - Label should match sentence case (first letter capitalized)

_Originally posted by @sdignum in https://github.com/carbon-design-system/ibm-products/issues/2500#issuecomment-1343315181_

**Comment by elycheea** [comment]
If the list is expanded, should it affect the height of the table or do we scroll? If we leave to default, most likely will see layout shift.

**Comment by matthewgallo** [comment]
[Here is a prototype](https://deploy-preview-4030--carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-extensions-panel--panel-batch) showing the chevron icon button to display more filter tags. If the expand button is clicked, the `multiline` prop from the `TagSet` is set to `true`.

Below is also a quick screen recording of the proposed interaction:

https://github.com/carbon-design-system/ibm-products/assets/10215203/2ec31ba3-33f3-4f16-a76f-76d0ea2862b0

**Comment by matthewgallo** [comment]
This still requires a v1 PR to be opened before we can officially close this issue.

**Comment by ljcarot** [comment]
@matthewgallo What's remaining on this issue?
