### ISSUE TITLE
Fix partial animation of side panel title when scrolled with small amounts of content

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-products#3901]
When the total available side panel scroll is small title can look odd in it's scrolled state. Either leaving a slightly transitioned title or an action-toolbar that is a long way from the title.

## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1.  In storybook using the developer tools delete some of the side panel content.
2. Adjust the size of the window so the content is just bigger than the window.
3. Scroll down.

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-products/tree/main/examples/carbon-for-ibm-products/SidePanel

## Additional information

<img width="496" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/15086604/b582f9ec-eeac-47b0-bc1e-1b004b365ac5">

<img width="492" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/15086604/90bc51cc-06eb-4ba9-aef0-5ab01c808594">

**Comment by elycheea** [comment]
I have failed to replicate this. 😅  Let’s chat next time you’re able to join us.

**Comment by lee-chase** [comment]
@elycheea this was fixed by previous #4141 

The SidePanel now checks the amount of space being scrolled (on display or resize).
