### ISSUE TITLE
N2P guide banner-optional left padding

### ISSUE THREAD

**Issue by cameroncalder** [carbon-design-system/ibm-products#3903]
Enhance the N2P guide banner by adding an optional left-side padding control, equipping developers with the option to change the padding from 16 to 32. This will make it so product teams can place the guide banner starting flush to the left edge of the screen and keep the icon aligned w/ the first column of the Carbon grid.

<img width="1350" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/50155706/664f9f47-9391-4542-bc4d-3bffb67e41e3">

**Comment by paul-balchin-ibm** [comment]
Reopening as we're still waiting for the `v1` fix.

**Comment by paul-balchin-ibm** [comment]
`v1` and `v2` PRs are merged. Closing.
