### ISSUE TITLE
index-without-carbon.css incorrectly includes carbon css

### ISSUE THREAD

**Issue by justindm234** [carbon-design-system/ibm-products#3949]
## What package(s) are you using?

- [X] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

@carbon/ibm-products/css/index-without-carbon.css incorrectly includes carbon css. This breaks applications if the build carbon css (e.g. `@use @carbon/react`) before importing @carbon/ibm-products/css/index-without-carbon.css.

In my application's case, doing so, caused our carbon `OverflowMenu` buttons and `HeaderGlobalAction` buttons to turn blue

Using the following `index.jsx` imports:
```
import '~/setup/carbon.setup.scss'
import '@carbon/charts/styles.css'
import '@carbon/ibm-products/css/index-without-carbon.css'
```

With c4p@2.5.0 the UI's OverflowMenu (lower left) and HeaderGlobalActions (upper right) render as expected

![image](https://github.com/carbon-design-system/ibm-products/assets/15637876/f64193bf-a13c-4ada-ac08-3638a08f5e98)

With c4p@2.12.1 (and 2.17.1) the UI's OverflowMenu (lower left) and HeaderGlobalActions (upper right) render blue with incorrect padding

![image](https://github.com/carbon-design-system/ibm-products/assets/15637876/faa1661e-366a-4588-8791-058259268344)

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expect @carbon/ibm-products/css/index-without-carbon.css to not include carbon css

> What browser are you working in?

See in Chrome and Firefox

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

Seen in 2.12.1 and 2.17.1; not seen in 2.5.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Z Hardware Management Console; no pressing release date

## Steps to reproduce the issue

1. Build @carbon/ibm-products/css/index-without-carbon.css
2. grep it for ".cds--btn--primary" (it also includes other carbon css rules)

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-products/tree/main/examples/carbon-for-ibm-products/SidePanel

## Additional information

- Screenshots or code
- Notes

**Comment by matthewgallo** [comment]
Fixed and released in `v2.18.0`.
