### ISSUE TITLE
[BUG] Page Header: Collapsed breadcrumb tab disappears

### ISSUE THREAD

**Issue by CarmineBruno** [carbon-design-system/ibm-products#3972]
## What package(s) are you using?

- Carbon for IBM Products v 2.15.1

## Detailed description

Interact with the page actions in page header when is collapsed make the breadcrumb tab disappears.

![image](https://github.com/carbon-design-system/ibm-products/assets/70442479/eaa28fdb-fb8b-4b92-b021-6ca9e7e83f05)

## Steps to reproduce the issue

Unfortunately in the storybook the actions doesn't really works, but you can reproduce the behavior anyway

1. Step one
Go to: https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-page-header-pageheader--with-actions-toolbar

Open the developer panel (so we can reproduce the behavior later).

![image](https://github.com/carbon-design-system/ibm-products/assets/70442479/9f1cd8d0-0090-45f6-bdb8-a3cdfcb70073)

2. Step two

Scroll down until the header is collapsed like this

![image](https://github.com/carbon-design-system/ibm-products/assets/70442479/0bd1f25e-f957-4d72-999a-cdec96fe06a3)

3. Step three

Increase or reduce the size of the developer tools panel.
If you did everything correctly you shouldn't see the collapsed header anymore.

![image](https://github.com/carbon-design-system/ibm-products/assets/70442479/d10d8eb9-cf3e-458d-93c9-02c0cf58b040)

## Note

The meaning of this steps is only to show the bug.
In my project the behavior occurs by scroll down the page and click on any action present on the page header.

Thank you everybody for your time!

**Comment by elycheea** [comment]
Verified that this is a v2 specific issue.

**Comment by elycheea** [comment]
### Acceptance criteria
Breadcrumbs should not disappear on viewport resize.
