### ISSUE TITLE
SidePanel: investigate positioning of close icon/slug

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#3975]
## What will this achieve?

With the latest changes in SidePanel, the close button and the slug are placed such that there is an overlap with the scrollbar. I think we should explore how we can position them so that they can be flush to the top but not overlapping the scroll if possible.

![image (9)](https://github.com/carbon-design-system/ibm-products/assets/10215203/82a3d59f-e251-42c6-82a5-89b659adc3bb)

**Comment by elycheea** [comment]
I think this issue in the close icon was already present when we did the migration to C11. I do remember Simon looking into this but we had some inconsistencies due to the scrollbar gutter. (Many of our designers have scrollbars only appearing on scroll ... and no telling what their customers are doing, hah).

Maybe `scrollbar-gutter: stable` could be an option but probably need to test a few scenarios with/without scrollbars on.

**Comment by elycheea** [comment]
Notes from backlog today — Could also try something similar to how Carbon modals work. But scrolling animation may have some different requirements.

**Comment by lee-chase** [comment]
Hmm. This requires a bit more thought than I expected. 

The problem is fixing something to the top, but also wanting the title to settle in that horizontal space is problematic.

**Comment by lee-chase** [comment]
@elycheea not sure how this would be done, posted as a challenge on the UXE channel

https://codepen.io/lee-chase/pen/zYbPoVK/46752b22af517a3eb0d195710cfe8330

**Comment by lee-chase** [comment]
I think this needs a design review @elycheea. Resizing the scroll bar is tricky to achieve and probably not desirable.

**Comment by elycheea** [comment]
Note, this is NOT an issue when using static header on side panel.

**Comment by makafsal** [comment]
@elycheea @lee-chase @matthewgallo I've taken a look at the issue, and I've got a solution in mind. Please take a peek at the screenshot I've attached for a rough implementation of what I'm thinking. Let me know what you think.


https://github.com/carbon-design-system/ibm-products/assets/9197089/3bc19dc0-19fd-447e-81c1-9bd903ac8bb7



https://github.com/carbon-design-system/ibm-products/assets/9197089/60c304bf-6dc6-4fbd-94ca-ca87f3494d7e

**Comment by makafsal** [comment]
@elycheea - I've discussed this with @devadula-nandan about his suggestion after a detailed discussion we concluded that his suggestion violates Carbon guidelines. Hence, he suggested that to move with my current solution. 


@elycheea @matthewgallo @lee-chase I would like to hear your comments and feedback.
