### ISSUE TITLE
Datagrid[Filtering]: dropdown not visible because of stacking context issue

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#3976]
## What package(s) are you using?

- [X] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)

## Detailed description

> Describe in detail the issue you're having.

If a dropdown filter is included in the Datagrid filter panel, it is not visible when open due to stacking context issues, until Carbon includes `floating-ui` for components like Dropdown, OverflowMenu, other Menus, we should come up with a temporary solution so that dropdowns can be used in the filter panel.
> Is this issue related to a specific component?

Datagrid filter panel, dropdowns
> What did you expect to happen? What happened instead? What would you like to
> see changed?

Expected to be able to view dropdown items when opened
> What browser are you working in?

Chrome
> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

Latest
> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

N/A
## Steps to reproduce the issue

1. Open `status` dropdown from Datagrid filter panel, notice how the chevron changes from closed position to open but the menu items are not visible.

**Comment by elycheea** [comment]
Suggestion from @matthewgallo could try to use portals to keep dropdowns visible until floating UI is visible.

**Comment by elycheea** [comment]
Continuing to explore `floating-ui` alongside Carbon as a way to resolve this.

**Comment by ljcarot** [comment]
We've been investigating [TanStack ](https://tanstack.com/table/latest)[Table](https://tanstack.com/table/latest), a third-party, open-source offering, which provides extensive data table capabilities surpassing what our Carbon Datagrid offers. It provides much more flexibility and customization. TanStack Table is headless which means it can easily be added alongside Datagrid component in your product or application. The benefits of more flexibility for product teams and less maintenance for Carbon makes it a win win. Lastly, it is available in multiple frameworks including [React](https://github.com/carbon-design-system/tanstack-carbon/tree/main/react#readme) and [Web Component](https://github.com/carbon-design-system/tanstack-carbon/tree/main/web-components#readme) so it provides an option to non-React product teams.

For these reasons, we have decided to transition from building our own custom table component to using an example-based approach with TanStack Table. Datagrid will still exist in our library for existing teams but we are announcing the deprecation* of the Datagrid component in v2.54.0 release so teams can begin to work through the transition. Details about how to use both Datagrid and TanStack together can be found [here](https://github.com/carbon-design-system/tanstack-carbon/tree/main). 

*Deprecation means that no new features will be added however sev 1 and sev 2 bugs will be supported.
