### ISSUE TITLE
[BUG] Page header - doesn't support menu button

### ISSUE THREAD

**Issue by Laura-Marshall** [carbon-design-system/ibm-products#3984]
## What package(s) are you using?

- [X] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive) (Carbon 10)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

Describe in detail the issue you're having.
The menu button from Carbon for IBM Products doesn't work in the page header. We assumed this is because the component is canary. However, my dev thinks that the page header restricts to either a menu button or regular buttons, and doesn't allow both to be used. 

![image](https://github.com/carbon-design-system/ibm-products/assets/53219208/819f0915-d8e6-4089-9b7f-f01671cddc00)

### Desired design
<img width="899" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/53219208/3ff50c00-bfae-4317-af2f-6e79ab22a6f8">

**What offering/product do you work on? Any pressing ship or release dates weshould be aware of?**
App Connect SaaS. We are migrating to Carbon 11 in March, and as part of that work we are adopting the page header across the board. This is the one instance of the page header that isn't working. 

**Please create a reduced test case in CodeSandbox**
Can ask my dev if needed. 

```[tasklist]
### Tasks
```

**Comment by elycheea** [comment]
@Laura-Marshall In v1, you would still need to enable the Canary component[^1].
Should be as simple as

```jsx
pkg.component.ButtonMenu = true;
```

However, I do think your developer is probably right about us restricting the type of actions that can be passed. 😓

[^1]: [Enabling canary components and flagged features](https://github.com/carbon-design-system/ibm-products/tree/main/packages/ibm-products#enabling-canary-components-and-flagged-features)

**Comment by Laura-Marshall** [comment]
@elycheea Would we be able to request an enhancement removing some of those restrictions? In March we want to adopt the Carbon menu button + another in the page header (I assume as the menu button is new, it might not be supported in the v2 header?)

**Comment by elycheea** [comment]
I think this is a reasonable request ... however, a design task for you if we need to support this ...

![Image](https://github.com/carbon-design-system/ibm-products/assets/1717398/b611f014-49c5-4416-9f87-296828cc6095)

At smaller screen sizes, this collapses into a menu button. (Business logic we currently handle).

![Image](https://github.com/carbon-design-system/ibm-products/assets/1717398/f112e237-e3da-4603-b249-5e6e978f1ae9)

What’s the equivalent behavior for this if we allow support for a menu button?

Fwiw, we’ve been trying to reduce the amount of business logic we own in each component, but this one is probably hard to accomplish without refactoring a bit. 🤔


-- 

Notes for after the holidays so we don’t lose this train of thought ...

[Breadcrumb](https://react.carbondesignsystem.com/?path=/docs/components-breadcrumb--overview) might feel comparable with how they allow an OverflowMenu as a possible Breadcrumb Item. But they don’t handle the collapsing of items when space decreases — instead they wrap to the next line. (Compare against our [BreadcrumbWithOverflow](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-internal-breadcrumbwithoverflow--default)) when you change the `containerWidth`.

I definitely think the functionality we provide is useful, but probably need some smarter brains from our UXEs to figure out if it’s possible to provide this utility without owning more business logic for every possible outcome. 🤔

**Comment by elycheea** [comment]
@asfordmatt Chatting with Laura about some tricky behaviors since there _are_ a few breakpoints that would collapse from two buttons to a menu button and stumbled into “user defined actions” in the `pageActions` examples. Looks like it’s _possible_ although as you might expect, the behavior would require a bit of work. (These are tested in v2 since I have it up currently, but as far as I’m aware, this shouldn’t have changed significantly from v1.)

![Image](https://github.com/carbon-design-system/ibm-products/assets/1717398/652561b6-b297-4d4a-80b4-145a6b635cfd)
