### ISSUE TITLE
Investigate Storybook simplification

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#3986]
After discussion with @lee-chase and @davidmenendez, we think it would be work removing some of our custom functionality. Even when David set up recently Storybooks for other projects, there’s a lot more overhead we have today — even setting up the community package, it was a bit of extra work.

We should evaluate how much this would take and review what we should keep from a clean slate.
```[tasklist]
### Acceptance criteria
- [x] Review findings from #2846
- [x] Explore a clean slate Storybook 7 (or 8??)
- [ ] Playback with the team to establish what functionality we remove and what should be re-added
- [ ] Discuss approach to give everyone exposure to changes to story format, dynamic titles, etc.
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4527
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4532
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4539
```

**Comment by matthewgallo** [comment]
Some initial thoughts, the `story-structure.js` file is what is currently used to sort stories and can even include stories in a "Lost and found" section, but it requires us to add new components to that file every time we create new components in our library. We could potentially have a configuration that could do something similar but without the need for this file.

**Comment by elycheea** [comment]
Could be nice if longer term we shifted more towards a more flattened hierarchy like Carbon’s, especially since our v2 does not include the CDAI and Security libraries.

Might look something like

- Overview (welcome, examples)
- Components
- Patterns
- Experimental (separate canary from stable)
- Internal (not meant for global usage)
- Community
