### ISSUE TITLE
missing lottie-web dependency

### ISSUE THREAD

**Issue by wkeese** [carbon-design-system/ibm-products#3991]
#3800 introduced a dependency on lottie-web, so it needs to be added to package.json.

cc @paul-balchin-ibm

**Comment by paul-balchin-ibm** [comment]
Hi, a new release was just built to deal with this specific issue. 

Please try installing version `@carbon/ibm-products` version `2.19.2`.

**Comment by wkeese** [comment]
Hi @paul-balchin-ibm, I still don't see it listed in package.json (https://github.com/carbon-design-system/ibm-products/commits/main/package.json), am I missing something?

**Comment by paul-balchin-ibm** [comment]
@wkeese it was added to `./packages/ibm-products/package.json`

https://github.com/carbon-design-system/ibm-products/commits/main/packages/ibm-products/package.json

**Comment by wkeese** [comment]
Ah I see, OK thanks!
