### ISSUE TITLE
Getting could not resolve "lottie-web" error when used with Vite tooling

### ISSUE THREAD

**Issue by ppillai7777** [carbon-design-system/ibm-products#3992]
## What package(s) are you using?
    "@carbon/ibm-products": "^2.19.1",
    "@carbon/react": "^1.46.0",
    "react-dom": "^18.2.0",
    "react-redux": "^9.0.4",
    "redux": "^5.0.0",
    "redux-actions": "^3.0.0",
    "redux-saga": "^1.2.3"

## Detailed description
I added component from @carbon/ibm-products on the page. When tried to access the landing page, gets the following error on the terminal:

  VITE v5.0.10  ready in 502 ms

  ➜  Local:   http://localhost:5174/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
✘ [ERROR] Could not resolve "lottie-web"

    node_modules/@carbon/ibm-products/es/components/SteppedAnimatedMedia/SteppedAnimatedMedia.js:16:19:
      16 │ import lottie from 'lottie-web';
         ╵                    ~~~~~~~~~~~~

  You can mark the path "lottie-web" as external to exclude it from the bundle, which will remove
  this error and leave the unresolved path in the bundle.

If I add the  lottie-web dependency into my application then problem is resolved.

**Comment by paul-balchin-ibm** [comment]
Hi, a new release was just built to deal with this specific issue. 

Please try installing version `@carbon/ibm-products` version `2.19.2`.

**Comment by ppillai7777** [comment]
Thank you for quick fix on this. I confirm that the fix is working as expected.
