### ISSUE TITLE
Datagrid filter panel: Clicking on a filter and then refreshing in the Datagrid clears the selected filter.

### ISSUE THREAD

**Issue by seymoneg** [carbon-design-system/ibm-products#4012]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

> Is this issue related to a specific component?
- Datagrid Filter panel batch option

> What did you expect to happen? What happened instead? What would you like to
> see changed?
-  When I click on a filter in the filter panel and then immediately refresh the data grid without applying or canceling the filter changes, the filters are removed. The expectation is for only the datagrid to refresh when the button is clicked, and for the filters to still be applied until the user either accepts or cancels.

> What browser are you working in?
- Chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
- ```"@carbon/ibm-products": "2.19.2",```

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
- CP4WAIops

## Steps to reproduce the issue

1. Open filter panel
2. Select a filter
3. Click the refresh button in the datagrid
4. Selected filter disappears 

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/p/devbox/datagrid-filter-panel-with-mocked-refresh-forked-fdhwgs?file=%2Fpackage.json%3A20%2C1-20%2C39

## Additional information

- Screenshots or code
- Notes

**Comment by matthewgallo** [comment]
Hi @seymoneg, we had a similar issue a while back that @xmannyxfreshx1 (also from WAIOPS) opened and was addressed. Would you be able to take a quick look and confirm if he was describing the same issue?
https://github.com/carbon-design-system/ibm-products/issues/3801

**Comment by seymoneg** [comment]
Hi @matthewgallo our issues are similar. 

The issue @xmannyxfreshx1 was talking about was when you select and apply a filter (ex. 'Developer'), clear the filters, add another filter (ex. 'Researcher') , and then click cancel, the 'Developer' filter is brought back.

My issue is with when I add a filter (ex. 'Developer') and then immediately refresh the data table without canceling or applying, the 'Developer' tag disappears. I want the filter to remain until the user either cancels or applies the filter.

**Comment by matthewgallo** [comment]
Ah I see, thank you for extra context.
