### ISSUE TITLE
Create new UserAvatar component

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#4021]
**The `UserAvatar` should be created as a new component (v2 `main` branch only)** — this is both to introduce new suggested name from design, but also account for breaking changes that would occur if we simply update or rename the current `UserProfileImage`.

To quickly scaffold a new component, you can use `yarn generate ComponentName`[^1]. New components and patterns should include the `canary` flag[^1].

While the original `UserProfileImage` uses both a `kind` prop to set a user or group icon, in our new `UserAvatar`, we can consolidate these by using `renderIcon`, as many components do in both `@carbon/ibm-products` and `@carbon/react`.

Initial component can default background to a theme token or just `$cyan-50` or `$cyan-60` to start. We’ll address the color system in #4035.

```[tasklist]
### Acceptance criteria
- [x] Scaffold new component files
- [x] List new component with a `canary` flag under the Components section of Storybook
- [x] Ensure new component supports `className` prop
- [x] Add support for `renderIcon` prop with `User` icon as a default
- [x] Add support for Carbon `Tooltip` on hover or focus (`tooltipText` and `tooltipAlignment`)
- [x] Ensure that focus ring is visible when user avatar is interactive (design issue [#1394](https://github.ibm.com/CDAI-design/pal/issues/1394))
- [x] Update and add tests for each new prop
```

[^1]: [Contributing docs](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CONTRIBUTING.md)

**Comment by jaymehta002** [comment]
can you mention more about this issue?
