### ISSUE TITLE
Investigate why certain checks are not being captured in CI checks / locally

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#4043]
- style snapshot
- cspell
- formatter
- commitlint

**Comment by matthewgallo** [comment]
Adding this error I got today when running the snapshot since it feels related to this issue
![image (13)](https://github.com/carbon-design-system/ibm-products/assets/10215203/085162ea-c13c-476c-8d80-809ba0f10d6d)

**Comment by davidmenendez** [comment]
also tagging this PR that shouldn't have been allowed to commit due to a cspell error https://github.com/carbon-design-system/ibm-products/pull/4535
