### ISSUE TITLE
<a11y> Content is not within a landmark element

### ISSUE THREAD

**Issue by xubinnb** [carbon-design-system/ibm-products#4056]
===== ENVIRONMENT =====
Browser: Version 105.0.5195.125 (Official Build) (arm64)
Automatically update Chrome for all users Learn more
Test Tool Type: IBM Accessbility Checker

===== DEFECT DESCRIPTION ===== 
Problem 1: Content is not within a landmark element

=====STEPS TO REPRODUCE =====
Go to https://dev.console.test.cloud.ibm.com/projects
Click the options icon

Use IBM Equal Access Accessibility Checker to scan

===== EXPECTED RESULT =====
[IBM 1.3.1 Info and Relationships](https://www.ibm.com/able/requirements/requirements/#1_3_1)
Information, structure, and relationships conveyed through presentation can be programmatically determined or are available in text.

[IBM 2.4.1 Bypass Blocks](https://www.ibm.com/able/requirements/requirements/#2_4_1)
A mechanism is available to bypass blocks of content that are repeated on multiple Web pages.

===== SCREEN CAPTURE =====
<img width="1278" alt="image" src="https://media.github.ibm.com/user/42629/files/a5451fec-1616-4355-b387-dc82ec2cb360">
<img width="1277" alt="image" src="https://media.github.ibm.com/user/42629/files/4fc355a6-d311-4c84-90ad-554ebc79f0bc">
<img width="1274" alt="image" src="https://media.github.ibm.com/user/42629/files/e0bc98cb-8191-412e-abba-681bf09a6786">

**Comment by elycheea** [comment]
@xubinnb Can you share more information about your specific versions of Carbon and Carbon for IBM Products? The component being referenced looks like menu or overflow menu from Carbon in which case this may need to be opened in their repository.

If you can provide more context for us when opening issues, such as the components you are using that are causing issues, that will help us respond more quickly.

**Comment by flannanl** [comment]
@carbon/ibm-products: 1.61.0
carbon-components-react: 7.59.16
carbon-components: 10.56.0

**Comment by xubinnb** [comment]
@elycheea Is this possible to reopen this issue? As I can not reopen in my side.

**Comment by elycheea** [comment]
FYI, seems like a known issue — Carbon does provide [`data-floating-menu-container`](https://v7-react.carbondesignsystem.com/?path=/docs/components-overflowmenu--default) that we can use to render, but in a quick test, we run into some overflow issues.


![Image](https://github.com/carbon-design-system/ibm-products/assets/1717398/fc0daef8-f80a-485a-8dfd-706509a7fbe4)

**Comment by elycheea** [comment]
Likely related to https://github.com/carbon-design-system/carbon/issues/14139

**Comment by ljcarot** [comment]
No longer triaging v1.  If issue exists in v2, please open a new issue.
