### ISSUE TITLE
Add responsive behavior for full page errors

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#4081]
Work with @thefirstartist using the deploy preview in the PR to refine appropriate responsive behavior for the full page error and variants.

### Design notes
Because the headings use fluid type, these should scale down for smaller screen sizes. Text should remain aligned left, while the image should scale or fix to smaller screen sizes.

```[tasklist]
### Tasks
- [ ] Design review with @thefirstartist and @My-Money29 
```

**Comment by elycheea** [comment]
@thefirstartist Nandan already has a first pass at this in the deploy preview. Can share the link.

**Comment by devadula-nandan** [comment]
https://deploy-preview-4211--carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-patterns-full-page-error-fullpageerror-canary--full-page-error

**Comment by thefirstartist** [comment]
@elycheea @devadula-nandan Looks good! Just one thing, I see the illustration in Chrome and Firefox, but it disappears in Safari.
