### ISSUE TITLE
Prototype ways we can use existing resizeObserver to apply `TagOverflow` for different content

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#4087]
Unlike the original `TagSet`, the `TagOverflow` is meant to work with [other UI elements](https://pages.github.ibm.com/cdai-design/pal/components/tag-overflow/usage/#other-ui-elements) than only tags.

Based on discussions with Laura, we think it’d be helpful for @szinta to create a prototype of how this might work for your data since it seems the current version of the TagSet was not able to accommodate some spacing conditions you see in product.

My crude interpretation of the discussion from this morning ... today to use something like this, you can append the `TagSet` component at the end of a list of non-tag items, but it’s very static and does not additional context that you get from using this with tags.

Ideally, our product teams would like to provide more details in the overflow for content other than just tags, and have these work with the existing tag resize functionality.

<img width="576" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/1717398/77d6df40-c749-4e60-8dee-36293ed8b071">

Suggest that Sinta works with `@bijoy.v` and `@edwinbaby` over Slack to understand their use case and evaluate our options. We do try not to include more business logic than necessary, but also want to ensure that the suggestions we provide are ones that can scale across your different product use cases.

FYI @Laura-Marshall @asfordmatt

**Comment by elycheea** [comment]
@szinta You can also work with @davidmenendez on this one since he recently took a look at what a TagSet refactor might look like so this could be a good opportunity to discuss more high level what approach makes sense for this.

**Comment by davidmenendez** [comment]
hey @szinta i through together a quick prototype of my own to try rewrite some of the functionality i thought could be updated and improved on in the current tagset component https://github.com/davidmenendez/tagset_prototype

feel free to reach out to me to discuss implementation or to bounce ideas off each other 👍

**Comment by szinta** [comment]
The initial version of the TagOverflow prototype is available at https://pages.github.ibm.com/CDAI-UX-Engineering/c4ip-tag-overflow/. This prototype's first section demonstrates the functionality of the existing [Tagset](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-tag-set-tagset--hundreds-of-tags&globals=carbonTheme:white) component, while the next three sections showcase the behaviour of the proposed [TagOverflow](https://pages.github.ibm.com/cdai-design/pal/components/tag-overflow/usage) component with a list of Tags, UserProfileImages, and custom icon components respectively.

@elycheea  @Laura-Marshall Please have a look and let me know your feedback.

**Comment by Laura-Marshall** [comment]
This is fantastic Sinta!

Only spot is the alignment: we would want the + tag to always be centered within the group height wise.

<img width="303" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/53219208/8cd07362-8821-4820-986f-8efd18a5cc32">


Everything else looks great though, great to see it responding with the browser size :)

**Comment by szinta** [comment]
> Only spot is the alignment: we would want the + tag to always be centered within the group height wise.

This is fixed now.
