### ISSUE TITLE
Include variants and content for tag overflow tooltips

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#4090]
The tooltip of the tag overflow should display content from the item labels.

There are [two variants for this](https://pages.github.ibm.com/cdai-design/pal/components/tag-overflow/usage/#styling) — “read-only tags” and “interactive”/filterable tags.

### Design notes
- When rendering read-only text, content should wrap if it does not fit the toggletip width (288px)
- When rendering `tag`, content should truncate if the whole tag does not fit the toggletip width

### Development notes
Relevant props from original `TagSet`.
- `overflowAlign`
- `overflowType`
- `showAllTagsLabel`
- `overflowClassName`

```[tasklist]
### Acceptance criteria
- [x] Add support to modify toggletip position using `overflowAlign`
- [x] Add support for rendering text or tags as `overflowType` inside the toggletip
- [x] Add `showAllLabel` if more than 10 tags are show in the overflow
- [x] Add support for `overflowClassName` for the toggletip popup
- [ ] Review accessibility using the [IBM Accessibility Checker browser extension](https://github.com/IBMa/equal-access)
- [ ] Add and update tests for each prop or scenario
```

**Comment by szinta** [comment]
As per [design notes](https://pages.github.ibm.com/cdai-design/pal/components/tag-overflow/usage/#other-ui-elements), 

> When using a tag overflow for other items, text should be used in the toggletip to display the remaining items. Using text in the toggletip ensures the content is accessible.

So I assume we should support interactive/filterable overflow tags only for filterable Tag items. Please confirm?
