### ISSUE TITLE
compulsoryColumns is deselect/select by select all checkbox in customize datagrid column 

### ISSUE THREAD

**Issue by SeonyuK** [carbon-design-system/ibm-products#4091]
## What package(s) are you using?

- [X] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

In the datagrid component, when customizing the columns in the modal the compulsoryColumns can be deselected by the Select all button.

 
> Is this issue related to a specific component?

DataGrid

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Should not be deselected the compulsoryColumns

> What browser are you working in?

Chrome 

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

V2.18.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
Click the customize column button
2. Step two
Uncheck the Select All button 

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-products/tree/main/examples/carbon-for-ibm-products/SidePanel

## Additional information
![Screenshot 2024-01-19 at 3 22 23 PM](https://github.com/carbon-design-system/ibm-products/assets/144151347/e84f1fae-3ea1-46c6-ad8c-c855a3af4900)

- Screenshots or code
- Notes

```[tasklist]
### Acceptance criteria
- [ ] Exclude frozen columns from select all
```

**Comment by Ratheeshrajan** [comment]
Closing as #4191 & #4194 merged.
