### ISSUE TITLE
Update image variants for full page errors

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#4138]
As part of full page errors, we will need to update the illustrations for each variant.
[Illustrations on Box →](https://ibm.box.com/s/6bg84cfaafxx3ioph3n88fwcvmpe4ieg)

Reached out to @thefirstartist and Colleen Yates about getting the image without a background. Unfortunately, the way the images are created, we’re unable to remove the background, which makes implementing this a little bit trickier to get working across all themes.

The Box folder includes both dark and light variants. I believe we can try to leverage the theme variables in the SVG markup to use the [background](https://carbon-elements.netlify.app/themes/examples/preview/#background) token as the fill. We will need to modify the SVG file itself to do this.

We may also be able to replace the stroke colors with a single variable as well — at a quick glance, I’m seeing #000000 for the light illustrations and #e0e0e0 for dark illustration strokes. These don’t map to the same token, but `$border-inverse` seems like a viable alternative, but we can verify with @thefirstartist.

| Variant | Illustration           |
---------|------------------
403         | Access denied   |
404         | Page not found  |
Other      | default / generic |
```[tasklist]
### Acceptance criteria
- [x] Illustrations update with each error variant
- [x] Illustrations update according to theme
- [x] Add or update tests based on variant / `kind`
```

**Comment by devadula-nandan** [comment]
@elycheea these were done in issue #4080 as in acceptance criteria, lmk if anything else is required.
