### ISSUE TITLE
Datagrid AI enhancements: column headers

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#4162]
## What will this achieve?

We want to add the ability to include the AI slug into all variations of column headers within the Datagrid.

## How will success be measured?

We should match the support that `@carbon/react` has added for incorporating the AI slug into the data table, this issue is meant to focus on the addition of the slug into the column headers. This will include making sure that it works together with all column header types (standard, sortable column headers, resizable columns, custom rendered column headers).

## Additional information

- [Carbon DataTable with slug](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-datatable--column-slug-sort)

**Comment by mattrosno** [comment]
Hi @matthewgallo - I added this issue to the C4AI phase 2 milestone, and I also documented in our C4AI asset status table here:

https://airtable.com/appCAqlGVN8tRUbAp/tblHqPusgkK8hIeHo/viwPD80oVVWwAk0xA?blocks=hide

You'll notice there's a column "Updated AI gradient?". Once @tw15egan is done with this PR:

https://github.com/carbon-design-system/carbon/pull/15662

The `Datagrid` should probably be updated to the latest AI gradient as well as add row AI indications.

Do you want to create an issue for this, or want me to?

**Comment by matthewgallo** [comment]
Hey @mattrosno! Thanks for the airtable link. We have an issue for rows here, #4193. @lee-chase created a PR to [update the AI gradients](https://github.com/carbon-design-system/ibm-products/pull/4184/files) which was merged yesterday. I'll make sure that the column headers/rows use the same gradient that @tw15egan applied to the DataTable.

**Comment by matthewgallo** [comment]
Actually, looks like I don't have access to that airtable link

**Comment by mattrosno** [comment]
@matthewgallo here's the share link: https://airtable.com/appCAqlGVN8tRUbAp/shr71ZyLlIGORz3Vh/tblHqPusgkK8hIeHo
