### ISSUE TITLE
Page header - Page actions with icon warning error

### ISSUE THREAD

**Issue by cnrahulrkr** [carbon-design-system/ibm-products#4169]
Creating page actions with an icon in the page header throws a warning error on the console. It says iconDescription is missing.

## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

Sample code:
```js
<PageHeader
  title={"Test"}
  breadcrumbOverflowAriaLabel={"Test"}
  breadcrumbs={[
    {
      href: "/dashboard",
      key: "Dashboard",
      label: "Dashboard",
    }
  ]}
  pageActions={[
    {
      key: "primary",
      kind: "primary",
      label: "Add",
      renderIcon: Add,
    }
  ]}
>
  Test
</PageHeader>
```

```
Warning: Failed prop type: renderIcon property specified without also providing an iconDescription property.
```

> Is this issue related to a specific component?

PageHeader

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Should not throws error

> What browser are you working in?

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

"@carbon/ibm-products": "^2.21.0",
"@carbon/react": "^1.48.1",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-products/tree/main/examples/carbon-for-ibm-products/SidePanel

## Additional information

- Screenshots or code
- Notes

**Comment by amal-k-joy** [comment]
@cnrahulrkr , Kindly pass the `pageActionsOverflowLabel` prop as below that will set as MenuButton label to solve the issue.
<PageHeader
  title={"Test"}
  _pageActionsOverflowLabel={'button label'}_
  breadcrumbOverflowAriaLabel={"Test"}
  breadcrumbs={[
    {
      href: "/dashboard",
      key: "Dashboard",
      label: "Dashboard",
    }
  ]}
  pageActions={[
    {
      key: "primary",
      kind: "primary",
      label: "Add",
      renderIcon: Add,
    }
  ]}
>
  Test
</PageHeader>

**Comment by cnrahulrkr** [comment]
Thanks @amal-k-joy , it worked.
