### ISSUE TITLE
Missing math operator in latest @carbon/ibm-products

### ISSUE THREAD

**Issue by sean-anderson-ibm** [carbon-design-system/ibm-products#4176]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

Using @carbon/ibm-products@2.22.0 I'm seeing the following error when attempting to render a storybook:
```
Missing math operator.
     ╷
7621 │   width: calc(40rem 75% - 1rem);
     │               ^^^^^^^^^^^^^^^^
     ╵
  node_modules/@carbon/ibm-products/css/index.css 7621:15  @use
  .storybook/styles.scss 9:1                               root stylesheet
```
This seems to have been introduced in v2.22.0 as when I downgrade to v2.21.0 the issue isn't present.

> Is this issue related to a specific component?

no

> What browser are you working in?

Firefox

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)

v2.22.0

> package are you using?

@carbon/ibm-products

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Cloud pak for integration

## Steps to reproduce the issue
1. Install @carbon/ibm-products@2.22.0
2. when running a build, the SCSS error mentioned above should appear

**Comment by matthewgallo** [comment]
This has been resolved with #4183 and released in `@carbon/ibm-products@2.23.0`. Feel free to reach back out if you experience any further issues!
