### ISSUE TITLE
Regression: Tearsheet stacking style

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/ibm-products#4177]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

The Tearsheet stacking style is specified as a modification in the y position and scale:

<img width="234" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/28265588/d7fcc624-41cb-4e0f-a6b4-01b01c5b75ce">

Lately, only the y position is applied:

<img width="242" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/28265588/916af8fe-b5da-44b7-901b-adf7bff5525e">

> Is this issue related to a specific component?

Tearsheet

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

`@carbon/ibm-products@2.22.0`

## Steps to reproduce the issue

Open all three Tearsheets in the story: https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-tearsheet-tearsheet--stacked

## Additional information

This seems to be a regression. The v1 package styling is still correct: https://v1-ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-tearsheet-tearsheet--stacked

**Comment by matthewgallo** [comment]
I believe this was introduced after a recent change in the `useResizeObserver` [here](https://github.com/carbon-design-system/ibm-products/pull/4141/files#diff-aff2a1481969b9b68a5def82977b5f4c4643c0ad4f4b9815b7751e11ae9968b5R9).

**Comment by matthewgallo** [comment]
Stacking custom properties before:
![image](https://github.com/carbon-design-system/ibm-products/assets/10215203/85e28c9e-9c5e-4e8f-98fc-23a4ea173809)
Stacking custom properties after:
![image](https://github.com/carbon-design-system/ibm-products/assets/10215203/29bd65df-bddd-4351-a78b-dc978e90f514)

**Comment by matthewgallo** [comment]
Hey @janhassel this has been resolved with https://github.com/carbon-design-system/ibm-products/pull/4183 and released in `@carbon/ibm-products@2.23.0`. Feel free to reach back out if you experience any further issues!
