### ISSUE TITLE
Datagrid AI enhancements: rows

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#4193]
## What will this achieve?
We want to add the ability to include the AI slug into all variations of column headers within the Datagrid.

## How will success be measured?
We should match the support that @carbon/react has added for incorporating the AI slug into the data table, this issue is meant to focus on the addition of the slug into the *rows*. We'll need to confirm this works with selectable rows and rows with expansion.

## Additional information
[Carbon DataTable with slug](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-datatable--column-slug-sort)

**Comment by mattrosno** [comment]
Adding this to our phase 2 milestone so we can track this issue alongside the other Carbon for AI issues.

**Comment by mattrosno** [comment]
Just an FYI, the DataTable has the new AI gradient in `@carbon/react@1.50.0`:

https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-datatable--column-slug-sort

**Comment by matthewgallo** [comment]
Oh cool, I'll open a new issue to update versions and make sure we use those!
