### ISSUE TITLE
Datagrid NestedRows extension crashes in SSR

### ISSUE THREAD

**Issue by hoiwingh** [carbon-design-system/ibm-products#4203]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

When doing server-side rendering of Datagrid with the nested rows extension (useNestedRows), the server crashes with the following error:

```
document is not defined ReferenceError: document is not defined
    at useNestedRowExpander (/home/module/app/node_modules/@carbon/ibm-products/lib/components/Datagrid/useNestedRowExpander.js:32:20)
```

The extension references `document` which is not available on server side.
https://github.com/carbon-design-system/ibm-products/blob/main_v1/packages/ibm-products/src/components/Datagrid/useNestedRowExpander.js#L27

## Steps to reproduce the issue

1. Render Datagrid with `useNestedRows` on server side

**Comment by matthewgallo** [comment]
PR for both v1 and v2 have been merged, this will be released tomorrow morning.
