### ISSUE TITLE
Dependency upgrades: yarn upgrade should happen first

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#4219]
## What package(s) are you using?

- [X] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

After the latest dependency upgrade action failed, it appears that the yarn upgrade (`yarn upgrade:dependencies:yarn`) should occur first otherwise GitHub Actions seems to pull in the yarn version specified in `.yarn/releases` which ends up being different if there is an upgrade available for yarn. This mismatch in versions will cause build issues as seen [here](https://github.com/carbon-design-system/ibm-products/actions/runs/7736082786/job/21092836131).

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Dependency upgrade should not crash with `yarn` upgrades.

**Comment by elycheea** [comment]
^ I had a PR for this but it started failing yesterday even after changes to stopped so I can investigate again. (Could be cache??)
