### ISSUE TITLE
Tearshhet won't display in full screen mode

### ISSUE THREAD

**Issue by wood-doug** [carbon-design-system/ibm-products#4231]
If a containing div is in full screen mode, the Tearsheet doesn't display

**Comment by elycheea** [comment]
@wood-doug Can you provide us a minimal reproduction in CodeSandbox so we can investigate this further?

**Comment by wood-doug** [comment]
No, I don’t have the time to do that.  But I’m internal and we can do a Webex, and you can have my FullScreen behavior component to use to reproduce it.  BTW: the one from Carbon_IoT that I replaced worked correctly.

**Comment by wood-doug** [comment]
The TRIRIGA team needs this fixed.  Please contact me at dougwood@ibm.com for a webex demo of the issue.

**Comment by elycheea** [comment]
@wood-doug We do also host an [office hours](https://ec.yourlearning.ibm.com/w3/meeting/10409311) on Wednesdays if you are able to attend that. It would help a lot if we could see how the code is set up to understand what other factors are affecting the tearsheet from rendering properly.

**Comment by wood-doug** [comment]
Updating to the latest carbon did not resolve this.

You can have my Fullscreen component if that will help with this.

**Comment by matthewgallo** [comment]
Here is a working stack blitz given the FullScreen component shared with us. Using the `portalTarget` prop on the Tearsheet seemed to help, it displays as expected and you can interact with it as you would when not in full screen mode.

**Comment by matthewgallo** [comment]
https://stackblitz.com/edit/github-tmeksz

**Comment by wood-doug** [comment]
I got it to work using the referenced example.
