### ISSUE TITLE
Carbon for IBM Products v2.20.0 Storybook getting started not rendering in Firefox

### ISSUE THREAD

**Issue by My-Money29** [carbon-design-system/ibm-products#4242]
Original [issue](https://github.ibm.com/CDAI-design/pal/issues/1496) from CDAI-PAL

### Bug description

HTML code is visible.
URL/Link of Page

Link here: https://carbon-for-ibm-products.netlify.app/?path=/docs/overview-getting-started--docs

### Viewing Platform:

    OS: macOS Sonoma 14.2.1
    Browser: Firefox
    Version: 121.0.1 (64-bit)

Screenshots

![Image](https://github.com/carbon-design-system/ibm-products/assets/101175720/e675061a-c166-4560-99ba-fe7b95fe8d84)

### @elycheea reply to original
@My-Money29 Looks like this is specific to Firefox. This should most likely be opened on our public repository. I wonder if we need to show the “getting started” guide at all though. It does look like Carbon only shows their banner and links out to the README instead of showing in Storybook.
```[tasklist]
### Acceptance criteria
- [ ] Remove Getting started page from Storybook
- [ ] Add link back to ibm-products GitHub repo ([example](https://react.carbondesignsystem.com/?path=/docs/getting-started-welcome--welcome))
```

**Comment by sstrubberg** [comment]
@My-Money29 I'm using FF 124.0.1 and I'm not having issues. Can you update and confirm?

**Comment by elycheea** [comment]
@sstrubberg The Getting started page (not overview) doesn’t show the contributors table. That said, I don’t know if we _need_ to show our README in Storybook at all.

**Comment by My-Money29** [comment]
> @My-Money29 I'm using FF 124.0.1 and I'm not having issues. Can you update and confirm?

Still the same for me, utilizing FF 124.0.1 :/ 
![image](https://github.com/carbon-design-system/ibm-products/assets/101175720/df77fc39-8462-4379-9728-6f038d1c1dba)

**Comment by sstrubberg** [comment]
Yeah, i'm following now. Can we just remove it? We already have the contributor list at https://github.com/carbon-design-system/ibm-products?tab=readme-ov-file#contributors-

**Comment by elycheea** [comment]
@sstrubberg Agree. I think we should just remove it. This used to be our main page before we added the banner. We didn’t remove it after adding the v1, v2 banners but probably could have. Doesn’t really serve much purpose here now.

Might be worth adding links back to GitHub though.
