### ISSUE TITLE
useDatagrid hook called twice (in separate components) to create 2 separate Datagrids caused the app to crash

### ISSUE THREAD

**Issue by darq37** [carbon-design-system/ibm-products#4299]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

`useDatagrid` hook called twice (in separate components) to create 2 separate Datagrids caused the app to crash.
Below Error message is shown:
```Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.```

![image (10)](https://github.com/carbon-design-system/ibm-products/assets/44163074/9c457fc1-c208-43e9-9168-579bb35cf177)

The bug is somewhere in Datagrid's useFilters hook.

> Is this issue related to a specific component?
Datagrid

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?
Chrome, Firefox
> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
    "@carbon/ibm-products": "2.24.0",
    "@carbon/react": "1.49.0",
    The bug has been present for at least 3 months. Version `    "@carbon/ibm-products": "2.6.1",
` does not have this issue
> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one - call useDatagrid() twice
2. Step two - the app dies

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-products/tree/main/examples/carbon-for-ibm-products/SidePanel

https://codesandbox.io/p/devbox/vibrant-http-yppxkl?file=%2Fsrc%2FExample%2FDatagridTwo.jsx%3A8%2C9
## Additional information

- Screenshots or code
- Notes

**Comment by matthewgallo** [comment]
Following up on a thread in slack, it looks as though this is fixed by wrapping your columns in `useMemo`. This is also recommended by `react-table` as well. While this is in the context of `react-table` v8, I think [this explanation](https://github.com/TanStack/table/issues/4227#issuecomment-1195642504) around `useMemo` also feels applicable to v7.
