### ISSUE TITLE
DataGrid - initial state value for sorting

### ISSUE THREAD

**Issue by mariusd-ibm** [carbon-design-system/ibm-products#4301]
## What will this achieve?

- enhancement: setting an initial state value for sorting in DataGrid (similar to the enhancement recently made for [initially expanded rows](https://github.com/carbon-design-system/ibm-products/pull/4088)).

## How will success be measured?

Success is achieved when, I'm able to set initial sorting state for DataGrid component.
So that on page load specific column would have visual reflection of sorting (sorting arrow) 
<img width="310" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/92723202/f1f18b49-5148-43cc-8105-08640c656a46">
 

## Additional information

- Designs
- Existing code
- etc

**Comment by matthewgallo** [comment]
This will be included in next week's release
