### ISSUE TITLE
Datagrid: Column Select/Reorder not honoring parent <Theme>

### ISSUE THREAD

**Issue by crichtonibm** [carbon-design-system/ibm-products#4315]
## What package(s) are you using?

- [X] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

When using the customize col/reorder feature of datagrid, it is not honoring Theme that it is nested within.  The floyout filter panel is doing this fine, I would expect the reorder panel to behave the same way

> What browser are you working in?
Chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

"@carbon/ibm-products": "2.21.0",

## Steps to reproduce the issue
Great a datagrid with useCustomizeColumns and useColumnOrder and nest inside theme. Open the col reorder panel and it is still using the default theme
  
<Theme theme="g10"><Datagrid datagridState={{ ...datagridState }}/></Theme>

```[tasklist]
### Acceptance criteria
```

**Comment by elycheea** [comment]
Hi @crichtonibm! Thanks for taking the time to report this! Could you create a minimal reproduction in [CodeSandbox](https://ibm-products.carbondesignsystem.com/?path=/story/overview-examples--c-4-p-gallery-code-sandbox) or [Stackblitz](https://ibm-products.carbondesignsystem.com/?path=/story/overview-examples--c-4-p-gallery-stackblitz). It’ll help us better understand and investigate this issue.

**Comment by elycheea** [comment]
@oliviaflory @carrenelloyd Do we have much precedent on how modals should render if launched from a nested theme that isn’t page level? 🤔 I think that’s the cause for the theme not being honored in this case.

**Comment by oliviaflory** [comment]
@elycheea a little challenging for me to comment on without seeing a reproduced example or screen shots, but I can take a stab at it!

I would think all the layers should follow the layering logic from v11.. so if the modal is aware it's nested within `layer-02` (data table) it should render in `$layer-03` and match the flyout menus

<img width="1143" alt="Screenshot 2024-03-15 at 12 16 57 PM" src="https://github.com/carbon-design-system/ibm-products/assets/45692622/bce5c9c0-3cde-4ba8-adac-0c17af9aa602">


---
But if the modal thinks it's nested in layer-01, (aka not considering the data table as it's parent layer) then I could see it rendering in the opposite layer token from the menu. aka layer-02 

<img width="1141" alt="Screenshot 2024-03-15 at 12 17 07 PM" src="https://github.com/carbon-design-system/ibm-products/assets/45692622/e189745e-0059-43eb-a3e3-4bb251b28a72">

---

Again it would be really helpful to see some screen shots from the team experiencing this, my mockups are assumptions of what layers exist!

The modal has the overlay so it's less apparent that it isn't following the theme logic and will definitely be differentiated from the background.

**Comment by elycheea** [comment]
@crichtonibm @oliviaflory brought this up with the Carbon design team and believe that the modal (or tearsheet) should follow `$layer-01` by default. Even if the component that renders it is in a nested theme, the modal itself is rendered as part of the larger experience.

> We think that is the best approach because you might get a really washed out modal and nested form components if the modal were in the layering model and ends up as `layer-02` or `layer-03`.

Based on this, I do think the current behavior is correct.
