### ISSUE TITLE
Prevent PageHeader using title as trailing breadcrumb

### ISSUE THREAD

**Issue by richardpilot** [carbon-design-system/ibm-products#4323]
## What will this achieve?
I would like to prevent the `PageHeader` component using the title prop as the trailing breadcrumb on scroll. The component already allows you to use the `isCurrentPage` prop in the PageHeader `breadcrumbs` prop to achieve the same effect and it would allow the dev to provide a more concise title to appear when it's a breadcrumb. A suggestion could be to see whether `isCurrentPage` is already specified before performing this behaviour.

A good example of this use case in the the PageHeader's own storybook

![image](https://github.com/carbon-design-system/ibm-products/assets/13081745/2cb27755-7008-4d44-94a9-7dd6a3e56bfe)
![image](https://github.com/carbon-design-system/ibm-products/assets/13081745/0f7500dd-2a44-4b99-a50c-3ad7c103d0ae)

## How will success be measured?

When either an alternative collapsed title can be provided or the isCurrentPage in breadcrumbs are honoured and the title prop not used.

## Additional information

```[tasklist]
### Acceptance criteria
- [ ] Add prop for custom breadcrumb title
- [ ] Add a test
```

**Comment by davidmenendez** [comment]
hey @richardpilot a fix was merged last week, which you should be able to see here https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-page-header-pageheader--fully-loaded-and-some&globals=viewport:basic
