### ISSUE TITLE
SidePanel: condensed title/subtitle border appears during entrance animation

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#4329]
## What package(s) are you using?

- [X] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

During the entrance animation of the `SidePanel` the border which should only display when the panel has scrolled is visible and then disappears after the animation has completed. It should not be visible during the entrance animation of the side panel.
> Is this issue related to a specific component?

SidePanel

> What browser are you working in?

Chrome
> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

Latest
> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

N/A
## Steps to reproduce the issue

1. Visible in latest storybook

**Comment by matthewgallo** [comment]
@mikeolasov fyi 👀

**Comment by makafsal** [comment]
@matthewgallo @mikeolasov - This issue is resolved by fixing the issue #3975 in the PR #4680
