### ISSUE TITLE
Datagrid nested rows not picking up changes in expansion state

### ISSUE THREAD

**Issue by hoiwingh** [carbon-design-system/ibm-products#4335]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

We are using Datagrid with `useNestedRows`, and we want the nested rows to be expanded by default. We therefore provide `expandedRowIds` in `initialState`. However, the nested rows are not expanded even the row ids are included in `expandedRowIds`.

It appears to us that `expandedRowIds` are only consumed initially (see this [code](https://github.com/carbon-design-system/ibm-products/blob/main/packages/ibm-products/src/components/Datagrid/useNestedRows.js#L19)). Any subsequent changes to it are not picked up by `useNestedRows`. However, like any typical application, `expandedRowIds` is initially undefined/empty because it takes time to fetch data before `expandedRowIds` can be computed and provided to Datagrid. Therefore it is important that `useNestedRows` can pick up changes in `expandedRowIds`.

## Steps to reproduce the issue

1. Use Datagrid with `useNestedRows`
2. Provide `expandedRowIds` in `initialState`
3. Fetch data and render the Datagrid

**Comment by hoiwingh** [comment]
In order to pick up changes in `expandedRowIds`, I think the `expandedRowIds` object should be included in the dependencies array here - https://github.com/carbon-design-system/ibm-products/blob/main/packages/ibm-products/src/components/Datagrid/useNestedRows.js#L30

**Comment by matthewgallo** [comment]
Possibly resolved in the issue @Ratheeshrajan worked on with [incorrect ids in nested rows](https://github.com/carbon-design-system/ibm-products/issues/3887)? Have you tried one the the latest releases that includes the fixes for selectable nested rows?
