### ISSUE TITLE
The frozen column doesn't follow the hover color on DataGrid

### ISSUE THREAD

**Issue by SeonyuK** [carbon-design-system/ibm-products#4338]
The frozen column doesn't follow the hover colour on the DataGrid
## What package(s) are you using?

- [X] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.
When the user hovers a row, the frozen column doesn't follow the hover color on the DataGrid. This is from this [fix](https://github.com/carbon-design-system/ibm-products/pull/4051)
![Screenshot 2024-02-14 at 3 07 14 PM](https://github.com/carbon-design-system/ibm-products/assets/144151347/9b8f294f-7bd8-4526-8412-3c48421b3a9a)

> Is this issue related to a specific component?
DataGrid

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Should remain the same as other columns 

> What browser are you working in?
Chrome 

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
v2.26.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-products/tree/main/examples/carbon-for-ibm-products/SidePanel

## Additional information

- Screenshots or code
- Notes

**Comment by xmannyxfreshx1** [comment]
Just adding another note to this defect, this is also true when a row is selected. The rest of the row is highlighted expect the sticky action column.
<img width="972" alt="Screenshot 2024-02-21 at 5 49 39 PM" src="https://github.com/carbon-design-system/ibm-products/assets/13371221/6fb3bc15-59c2-4865-8d8a-894a86c1348b">
