### ISSUE TITLE
Remounting datagrid when the data is refetch from server 

### ISSUE THREAD

**Issue by SeonyuK** [carbon-design-system/ibm-products#4340]
## What package(s) are you using?

- [X] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

Remounting Datagrid when the data is refetch from the server 
 it was working fine with v2.18.1 (Can test v2.19.0 or 2.19.1 because lottie-web ) but when updated to v2.19.2  it is doing weird behaviour.

> Is this issue related to a specific component?
Datagrid

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Should just rerender not remount

> What browser are you working in?
Chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
v2.26.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-products/tree/main/examples/carbon-for-ibm-products/SidePanel

## Additional information

- Screenshots or code
- Notes

**Comment by elycheea** [comment]
@matthewgallo to do an initial investigation on what changed between 2.18 and 2.20.

**Comment by SeonyuK** [comment]
@matthewgallo any update for this?
We really need this get fixed to release our new table.

**Comment by tom-youd** [comment]
I'm also seeing this problem - it would be nice to see what the problem is but until then I think I'll revert below 2.18

**Comment by SeonyuK** [comment]
@matthewgallo We found the solution in our implementation for this issue. 
I don't mind closing this issue but looks like there is another person who has the same issue.

**Comment by tom-youd** [comment]
Would you be able to share how you worked around this?

**Comment by tom-youd** [comment]
I’ve managed to work round it, so ignore my comment above

**Comment by matthewgallo** [comment]
Hey @tom-youd and @SeonyuK! It sounds like you both have been able to find solutions to this issue. Ok if we close this now?

**Comment by SeonyuK** [comment]
For me yes!

**Comment by matthewgallo** [comment]
@tom-youd feel free to reach back out if you see this behavior again, thanks!
