### ISSUE TITLE
When will toggle be implemented in the Tearsheet component?

### ISSUE THREAD

**Issue by tom-youd** [carbon-design-system/ibm-products#4353]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## What did you want to know?

The Carbon website and IBM products patterns [pages](https://pages.github.ibm.com/cdai-design/pal/patterns/creation-flows/usage/#anatomy-of-a-wide-tearsheet) have images with a toggle within the influencer, but looking at the code there doesn't seem to be a way to enable it. I do see a [style](https://github.com/carbon-design-system/ibm-products/blob/main/packages/ibm-products-styles/src/components/CreateInfluencer/_create-influencer.scss#L60) for the toggle. Was there a reason it was removed the react code was removed?

We'd like to know if this is something that is either been removed or could be considered to be added fairly soon - Two teams within IBM are looking to use it

**Comment by richardpilot** [comment]
Registering my interest in this feature too.

**Comment by elycheea** [comment]
@tom-youd @richardpilot This was was removed as part of the Tearsheet since the designs for this were never completed. You should still be able to include one in the Tearsheet, although I believe the CreateTearsheet may make this a bit harder to achieve.
