### ISSUE TITLE
Add support for removing filterable tags from tag overflow modal

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#4358]
Reported during the [`TagSet` review](https://github.ibm.com/CDAI-design/pal/issues/1396) of the accessibility audit.

Filtering was enabled on `TagSet` in #3421, but in the [view all modal](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-tag-set-tagset--with-close-and-overflow-tags), tags are not filerable. Believe this is just hardcoded.

Because this would allow all filters to be removed, we may need a design opinion on the appropriate behavior if all tags are removed.

This should also be considered _after_ we determine if `TagOverflow` _replaces_ `TagSet` or is complementary to it.
```[tasklist]
### Acceptance criteria
- [ ] Verify that `<Tag filter>` have been replaced with `DismissibleTag`
- [ ] Add prototype and empty state for when all tags are removed
- [ ] Discuss any additional UX considerations with design
- [ ] Ensure this is applied for TagOverflow as well as TagSet
```

**Comment by elycheea** [comment]
Note that filterable tags should now use `DismissibleTag`.

**Comment by szinta** [comment]
This issue has already been addressed in TagOverflow implementation. In TagOverflow, currently we are using `Tag` component with `filter` prop. I'll change it to `DismissibleTag` after checking with @laurenmrice. 

Also please note that, in Overflow modal filterable tags will be shown only if the `overflowType` prop value is set as `tag`. If `overflowType` is `default`, then we are displaying read-only tags in Overflow modal.

**Comment by davidmenendez** [comment]
@szinta thanks for pointing that all out. @elycheea do we want to implement this fix still or push to use the new component?

**Comment by elycheea** [comment]
I think we can keep with the implementation in `TagOverflow` for now. Let’s open a followup issue for updating to `DismissibleTag` though.

**Comment by oliviaflory** [comment]
@elycheea we're keeping tag set and deprecating tag overflow, correct? should we close this one?

**Comment by elycheea** [comment]
@oliviaflory Yeah, let’s close this one. It’s already implemented in `TagSet`. In the utilities, I imagine we’ll explore ways to invert control and allow our consumers to handle some of the rendering (e.g. they have more direct control over whether to use a modal or what goes in it).
