### ISSUE TITLE
Issue with Column Order in DataGrid Column Customization 

### ISSUE THREAD

**Issue by marinamas** [carbon-design-system/ibm-products#4379]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive) - Yes
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.
In DataGrid with column customization , when we set Initial state having Column order and hidden columns .
  Though the order of the column is mentioned, it would always add the hidden columns to end of customization component.
  Expected behavior would be to have the column order retained irrespective of whether the column is hidden or not

> Is this issue related to a specific component?
  DataGrid
> What did you expect to happen? What happened instead? What would you like to
   Expected behavior would be to have the column order retained in the customization component list

> What browser are you working in?
  Safari
  Chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
      2.26.0

## Steps to reproduce the issue
 
1. Use the DataGrid along with Column Customization.
2. Set the initial state with  hiddenColumns,  columnOrder.
3.  Add few column id under hiddenColumns. Though we mention the order of Columns the customization component adds hidden
 columns at the end in the list . 
4. Though the column is hidden , the order in which it is displayed should be according to the column order 

## Additional information
 initialState: {
    columnOrder: [
     "rowIndex",
     "firstName",
     "someone1",
     "lastName",
     "age",
     "visits",
    ],
    hiddenColumns: ["lastName"],
   }
   
![image](https://github.com/carbon-design-system/ibm-products/assets/80206173/f1fcbd3b-e299-4718-8c17-2ecc471470fd)

```[tasklist]
### Acceptance criteria
- [ ] Column order should retain position even when column is hidden
- [ ] Add story for column order in `initialState`
```

**Comment by elycheea** [comment]
Looks like retaining column order _is_ the intended design based on the design guidance[^1].

[^1]: https://pages.github.ibm.com/cdai-design/pal/components/data-table/column-customization/usage#anatomy

**Comment by elycheea** [comment]
Note, when investigating this — when we first uncheck a column, it does retain position at least in the tearsheet. May be some re-rendering that happens because we were able to replicate this behavior later.

**Comment by marinamas** [comment]
Yes .Retaining column order is intended and it works.
But my concern is when we hide some columns and save the selection( I mean
save to BE APIs) so when user comes back the selection is saved.


But what happens is , when I give the column order( which  includes both
hidden and visible columns  order  )   and hidden columns in the initial
state props of DataGrid.. the order of hidden columns is not shown as per
the column order but is been pushed to the end of the list. as shown in the
screenshots attached in the bug.

Please let me  know if you need any further details.

Thanks,
Marina

**Comment by davidmenendez** [comment]
just needs the V1 PR reviewed https://github.com/carbon-design-system/ibm-products/pull/4549
