### ISSUE TITLE
Investigate macOS screenreader interpreting nested elements as groups

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#4406]
Followup from [accessibility audit](https://github.ibm.com/CDAI-design/pal/issues/1245) and previous Datagrid accessibility reviews #3505.

> Screenreader testing: 
>
> - I'm observing the same behavior here that I have in other components.  When reading out content of the tags, voiceover announces a group, then actual content, then end of group - [see video](https://github.ibm.com/CDAI-design/pal/issues/1396#issuecomment-69206922)

At a quick glance, this might be _specific_ to macOS and not with other screenreaders[^1][^2]. Will need to look into this more to understand what our best option is. In the meantime, it might make sense for us to document all the “group” issues together too.

[^1]: https://stackoverflow.com/a/76001309
[^2]: https://www.a11yproject.com/posts/getting-started-with-voiceover/
```[tasklist]
### Acceptance criteria
- [ ] Evaluate methods discussed below
- [ ] Investigate if tags announced as groups is specific to CFIP or Carbon
```

**Comment by davidmenendez** [comment]
left a follow up comment here https://github.ibm.com/CDAI-design/pal/issues/1396#issuecomment-73777905

basically, with regards tagset, the issue lies with carbon and their usage of a title attribute.

**Comment by davidmenendez** [comment]
also looking at this [documentation](https://www.w3.org/International/questions/qa-html-dir#blockelements) regarding the `dir` attribute i'm also fairly certain that that particular attribute also isn't necessary

**Comment by davidmenendez** [comment]
this underlying issue regarding tags was fixed in carbon. i'm going to set some time aside to find out what voiceover testing guidelines (if any) carbon has so that we can try to evaluate how to catch problems like this moving forward.
