### ISSUE TITLE
Datagrid fails on initial load when isFetching is true and using the filter panel

### ISSUE THREAD

**Issue by xmannyxfreshx1** [carbon-design-system/ibm-products#4441]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description
> Describe in detail the issue you're having.

- Datagrid fails on initial load when isFetching === true and filter panel is used. The error originates from `componentStack: 
    at FilterPanel (webpack-internal:///./node_modules/../../node_modules/@carbon/ibm-products/es/components/Datagrid/Datagrid/addons/Filtering/FilterPanel.js:59:25)`
- isFetching is set to true on initial load because we are waiting on data from our api call. When I set isFetching to false, the datagrid loads in an empty state, then renders the returned data.

> Is this issue related to a specific component?

- Datagrid, filter panel

> What did you expect to happen? What happened instead? What would you like to
> see changed?

- expected the datagrid to load without errors

> What browser are you working in?

- Chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

- `"@carbon/ibm-products": "2.27.0",` I believe the changes here: https://github.com/carbon-design-system/ibm-products/pull/4207 may have introduced this bug. @matthewgallo 

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

- CP4AIOps

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-products/tree/main/examples/carbon-for-ibm-products/SidePanel

## Additional information

- Screenshots or code
- Notes

**Comment by xmannyxfreshx1** [comment]
@matthewgallo I've tested this on `2.30.0-alpha.9` and `2.30.0` and confirmed the added checks allows the datagrid to load properly. 👍🏽

**Comment by matthewgallo** [comment]
Great news 😄
