### ISSUE TITLE
DataGrid Global Filter search not working for 6 characters definu

### ISSUE THREAD

**Issue by rukmanid2312** [carbon-design-system/ibm-products#4447]
DataGrid Global Serach filter not working for 6 characters  d, e, f, n ,i, u

 What package(s) are you using?
@carbon/ibm-products v 2.29.0

Description:
Go to datagrid component with global search filter , try to filter table conents for these 6 cahracters one at a time. The filter won't work. however for all other alphabets filter works fine.

**Comment by elycheea** [comment]
Hi there! Thanks for taking the time to report this! Could you create a minimal reproduction in [CodeSandbox](https://ibm-products.carbondesignsystem.com/?path=/story/overview-examples--c-4-p-gallery-code-sandbox) or [Stackblitz](https://ibm-products.carbondesignsystem.com/?path=/story/overview-examples--c-4-p-gallery-stackblitz). It’ll help us better understand and investigate this issue.
