### ISSUE TITLE
Sticky header overlap issue on scroll in DataGrid

### ISSUE THREAD

**Issue by marinamas** [carbon-design-system/ibm-products#4521]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive) Yes
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.
- Create a DataGrid Table and set the first column sticky.
- Scroll the content horizontally, Now hover on the first column header
- The scrolled column headers are overlapped with the sticky header  

> Is this issue related to a specific component?
DataGrid

> What did you expect to happen? What happened instead? What would you like to
- The content should be hidden when scrolled and not overlap with the above content 

> What browser are you working in?
Chrome and Safari

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
2.30.0

> package are you using?
 "@carbon/react": "1.52.0",
  
> Please create a reduced test case in CodeSandbox
> https://codesandbox.io/p/sandbox/brave-poincare-2ffcfr?file=%2Fsrc%2FExample.js%3A109%2C22

## Additional information
<img width="763" alt="Screenshot 2024-03-08 at 4 44 35 PM" src="https://github.com/carbon-design-system/ibm-products/assets/80206173/7ea09234-3014-4e11-9110-83b45ffdf6b9">

**Comment by matthewgallo** [comment]
@marinamas I believe this was recently fixed. Let us know if this is still an issue for you.
