### ISSUE TITLE
Sidepanel close button is covered by scroll bar

### ISSUE THREAD

**Issue by xmannyxfreshx1** [carbon-design-system/ibm-products#4525]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

- Vertical scroll bar covers the close 'x' button.
- More noticeable on firefox 

> Is this issue related to a specific component?

- Sidepanel, slide-in

> What did you expect to happen? What happened instead? What would you like to
> see changed?

- Render the close button above the scroll bar

> What browser are you working in?

- Chrome
- Firefox

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

`"@carbon/ibm-products": "2.30.0",`

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

- CP4AIOps

> Can be seen in the official storybook
>
> https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-side-panel-sidepanel--slide-in

## Additional information

- Firefox
![Screenshot 2024-03-08 at 10 13 57 AM](https://github.com/carbon-design-system/ibm-products/assets/13371221/5366ad0b-7464-4164-ac9b-f2d04f9bf299)

-Chrome
![Screenshot 2024-03-08 at 10 26 07 AM](https://github.com/carbon-design-system/ibm-products/assets/13371221/6bc6122b-ee33-4f22-a03e-a49889de0b5b)

**Comment by elycheea** [comment]
Hey @xmannyxfreshx1, I believe this is a duplicate of #3975 which we were investigating but don’t believe we found a good approach yet. :(
