### ISSUE TITLE
Add telemetry config to CI

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#4537]
Making a reason for us to sit in a meeting room together sometime soon @francinelucca <3

`@carbon/ibm-products` was onboarded via #4165.
We’ve since added numerous components, largely through the Security migration effort. It would probably make sense to update our config as part of our release process since we wouldn’t be able to track any updates to a component without a release.

This can be done through CI as documented in the **[ibm-telemetry/telemetry-js-config-generator](https://github.com/ibm-telemetry/telemetry-js-config-generator)** repo.

[Here](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/11563) is the `@carbon/web-components` on-boarding PR. Can be used as a reference.

**Comment by matthewgallo** [comment]
Complete 🎉
