### ISSUE TITLE
Investigate Storybook 8 changes

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#4539]
Looking into Storybook 8 changes against the some of the Storybook simplification.

**Comment by elycheea** [comment]
Lee and Matt to follow up after Matt’s return from vacation.

**Comment by lee-chase** [comment]
Made a little progress here, but it was hard going. 

It refused to process the MDX file used for getting started reporting `Invariant failed: No matching indexer found for` this despite a clean create react app project with storybook 8 being perfectly happy to process it.

Next up was complaints about the way some of our stories are written. The best course of action may be to cut down to a single file to find a pattern that can be applied elsewhere.

https://github.com/lee-chase/ibm-products/tree/storybook8

**Comment by lee-chase** [comment]
Cutting it down just to APIKeyModal we get this error, however the same seem to be possible in the a clean project.

![image](https://github.com/carbon-design-system/ibm-products/assets/15086604/842066d0-1219-4a79-aa9a-159aa7b5cbc7)

This works in test react app project
![image](https://github.com/carbon-design-system/ibm-products/assets/15086604/b31ebe91-072c-4834-8ba6-79b1cdb89c89)

**Comment by matthewgallo** [comment]
We'll be moved over to Storybook 8 with #5019, moving to Vite from Webpack resolved _a lot_ of issues that I think both @lee-chase and myself encountered when initially looking at this.
