### ISSUE TITLE
Focus is captured by Tab used in Tearsheet when state is first updated

### ISSUE THREAD

**Issue by BrHowell** [carbon-design-system/ibm-products#4543]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

I have a Tearsheet containing Tabs, and in one of them I have a TextInput that updates a state object when changed. When I first switch to this tab and begin typing, the focus is moved to the Tab itself. This only happens with the first typed character, though if I switch to another Tab and then back, the issue will occur again.

I am seeing this with a Tearsheet body that contains a tab list, and also Tearsheets using the `navigation` prop to set up the tabs.

> Is this issue related to a specific component?

This relates to the `Tearsheet` component when using `Tabs` in it. I had tested the `Tabs` on their own and was not able to reproduce this issue (as can be seeing in the CodeSandbox link below).

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Focus to remain with the input field, rather than captured by the Tab.

> What browser are you working in?

Firefox

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

2.30.0

## Steps to reproduce the issue

1. Open the CodeSandbox example below.
2. Click either the Open Tearsheet or Open Tearsheet With Navigation button (both examples show this issue)
3. Click on `Tab 2`
4. Start typing in the text field. The focus is immediately take away towards `Tab 2`.

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/p/sandbox/tearsheet-tabs-example-t9hqgj?file=%2Fsrc%2Findex.js%3A15%2C21

**Comment by elycheea** [comment]
@makafsal Believe this started happening after our focus trap updates so may be helpful to take a look at this use case.
