### ISSUE TITLE
SidePanel hijacks the user's focus on state changes

### ISSUE THREAD

**Issue by modean** [carbon-design-system/ibm-products#4547]
## What package(s) are you using?

```
    "@carbon/colors": "11.20.1",
    "@carbon/ibm-products": "2.31.0",
    "@carbon/layout": "11.20.1",
    "@carbon/react": "1.52.0",
    "@carbon/styles": "1.52.0",
    "@carbon/themes": "11.32.0",
    "@carbon/type": "11.25.1",
```

## Detailed description

> Describe in detail the issue you're having.

If typing or selecting something on the UI the `SidePanel` receives the focus and thus the current input element looses its focus which interrupts entering data.

The cause for this is that on each state change, the `SidePanel` seems to re-render and thus catches the focus.

> Is this issue related to a specific component?

Yes: `SidePanel`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The `SidePanel` should not catch the focus if it's open and the user continues working in the main content area. In our app the use case is that the `SidePanel` provides help that assists the user while providing data. Thus the panel must not be closed.

Closing the panel would be a workaround to prevent unwanted effects such as loosing the focus unintentionally.

> What browser are you working in?

Google Chrome `Version 120.0.6099.234 (Official Build) (arm64)`

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

See above.

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

n/a

## Additional information

See Slack conversation on #ibmproducts-pal-dev.

**Comment by elycheea** [comment]
@modean It should be available once we fix our release action. It should have gone out today but we’re investigating to see the cause of the failure.

**Comment by modean** [comment]
@elycheea and @makafsal  I updated to `"@carbon/ibm-products": "2.35.0"` but to me it looks like as if the focus handling is still the same.

That is you type something into an input control on the main content area and the state update causes the `SidePanel` to re-render and thus grab the focus from the input control on the main content area to give it to the close icon on the `SidePanel`.

That way it is not possible to continue typing data into the input control on the main content area. I also posted a short flick on Slack to demonstrate what I am observing.

**Comment by modean** [comment]
@makafsal wouldn't it be an option to use the `usePreviousValue` hook to check whether `open` was previously already `true` and thus refrain from setting the focus to either the first element of the `SidePanel` component or to the element that is specified by `selectorPrimaryFocus`? 

My rational is, that if the `SidePanel` was already opened the assumption should be that the user actions are intentional and thus explicitly setting the focus on each state change the user is causing by what he or she is doing may be counter intuitive.

For the time being I solved the focus issue in a way where I set the `selectorPrimaryFocus` explicitly to the HTML input element's ID that is currently being changed/modified by the user. After the change I set `selectorPrimaryFocus` to an empty string in the `onBlur` event handler. That way typing into the HTML input element won't be interrupted by the `SidePanel`. Tho there's a constant animation of the `SidePanel` component during each state change and thus re-render. IMO the animation should only take place if the `SidePanel` initially opens and not while it gets re-rendered.

@elycheea I can also join the office hour call the discuss this particular item and maybe also the other items I reported. I think for the `SidePanel` component our team needs to make a decision whether to continue using it or whether to use another component that does not expose such a behaviour.

**Comment by makafsal** [comment]
@modean You mean this happens in every state change? I think, then have to check the code, could you please share a codesandbox to demonstrate the exact usage. Because the sidepanel depends on the `open` state value, the sidepanel only re-render when any change happens to that value.

One solution I'm thinking to implement is that, if you don't want to switch the focus to the sidepanel from main content immediately after opening it, I could give a property like `autoFocus` and it will be a boolean, so you could disable the auto-focus when opening the side panel.

**Comment by modean** [comment]
Hi @makafsal you can try to replicate the issue with the animation and the focus handling using [this CodeBox sandbox](https://codesandbox.io/p/devbox/createfullpagesample-9plsx3?file=%2Fsrc%2FApp.tsx%3A75%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluocoy1i00073b6gweqod0r2%2522%252C%2522sizes%2522%253A%255B60%252C40%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluocoy1h00023b6gm1qk9c77%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluocoy1i00043b6gpfqz4y2j%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluocoy1i00063b6gwnnik835%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B42.82810142949501%252C57.17189857050499%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluocoy1h00023b6gm1qk9c77%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluocoy1h00013b6gl2ktsvu7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cluocvpo600023b6gaex7i91z%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cluod7e8b00023b6g5ljvbv5e%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A75%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A75%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cluocoy1h00023b6gm1qk9c77%2522%252C%2522activeTabId%2522%253A%2522cluod7e8b00023b6g5ljvbv5e%2522%257D%252C%2522cluocoy1i00063b6gwnnik835%2522%253A%257B%2522id%2522%253A%2522cluocoy1i00063b6gwnnik835%2522%252C%2522activeTabId%2522%253A%2522cluod8cxy00693b6gkxxrjb5p%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522cluod8cxy00693b6gkxxrjb5p%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2523%2522%257D%255D%257D%252C%2522cluocoy1i00043b6gpfqz4y2j%2522%253A%257B%2522id%2522%253A%2522cluocoy1i00043b6gpfqz4y2j%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluocoy1i00033b6ghnzu21m4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cluocoy1i00033b6ghnzu21m4%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

Open the SidePanel and then try to type something into the Topic name text field while the SidePanel is open.

**Comment by modean** [comment]
Thanks @makafsal for pointing out that the markup of the `SidePanel` component should not be part of the render() function as provided by the HeaderContainer Carbon component.

Now I don't see the focus issue nor the animation issue any longer.
