### ISSUE TITLE
Glitchy behavior in spreadsheet

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-products#4551]
When selecting a new cell, sometimes, the value from the previously selected cell appears briefly in the newly selected cell.

![Kapture 2024-03-14 at 12 49 13](https://github.com/carbon-design-system/ibm-products/assets/15086604/d1b46baf-58ca-45b1-a30c-893d9ca42318)

## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

**Comment by matthewgallo** [comment]
Fixed in https://github.com/carbon-design-system/ibm-products/pull/4586
