### ISSUE TITLE
Tags with filter need to be replaced with `DismissibleTag`

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#4556]
`@carbon/react@1.53.0` introduces `DismissibleTag` which should replace use of Tag with filters.

```[tasklist]
### Acceptance criteria
- [ ] Investigate the Tag updates from Carbon (is DismissibleTag stable??)
- [ ] Replace `<Tag filter>` with `<DismissibleTag>`
- [ ] Update tests
- [ ] Reinstate tests from #4552
- [ ] Search for any other cases not documented
```

To see the full list of tests that were modified as a result of this change, please see commits from #4552[^1].

[^1]: https://github.com/carbon-design-system/ibm-products/pull/4552/files/ed643916b2474f300f4d329d06746f1c769e2dee..19d36540c5673c25feae7ecd141d210c82319a1c

**Comment by AlexanderMelox** [comment]
Should this be an epic? This should list all the components that use <Tag filter /> not just PageHeader and Tagset, It's also being used in Datagrid, etc.

**Comment by AlexanderMelox** [comment]
Below is documentation on the current process on DismissibleTag

Filter tags current:
<Tag filter type="gray" onClose={...}>Label</Tag>
New DismissibleTag:
<DismissibleTag type="gray" onClose={...} text='Label' />
Proposed solution 1:
(filter__deprecated || dismissible) && <DismissibleTag type="gray" onClose={...} text='Label' />
Proposed solution 2 (rely on a passed onClose prop from user):
onClose && <DismissibleTag type="gray" onClose={...} text='Label' />

**Comment by AlexanderMelox** [comment]
**TagOverflowModal.tsx**
```
    <ModalBody className={`${blockClass}__body`} hasForm>
        {getFilteredItems().map(({ label, id, filter }) => {
          const isFilterable = overflowType === 'tag' ? filter : false;
          return isFilterable ? (
            <DismissibleTag
              key={id}
              text={label}
              onClose={() => onTagClose({ label, id })}
            />
          ) : (
            <Tag key={id}>{label}</Tag>
          );
        })}
      </ModalBody>
```
