### ISSUE TITLE
DataGrid resets the filters applied, table selection and other state values when the row values changes

### ISSUE THREAD

**Issue by marinamas** [carbon-design-system/ibm-products#4560]
## What package(s) are you using?

- [ ] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)

## Detailed description
- Create a DataGrid table with selection and filters.
- Apply some filters or select any of the row.
- On some interval try to update the row data supplied to the DataGrid.
- Whenever the row data changes, it will reset the data grid state. ( This doesn't happen with DataTable , also if the column / header value is changed the datagrid state doesn't get reset     

> Is this issue related to a specific component?
DataGrid

> What did you expect to happen? What happened instead? What would you like to
The selection or filters should not be cleared on rowdata update.

> What browser are you working in?
Chrome
Safari

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
 "@carbon/ibm-products": "2.31.0",

> Please create a reduced test case in CodeSandbox
https://codesandbox.io/p/sandbox/brave-poincare-2ffcfr?file=%2Fsrc%2FExample.js%3A102%2C27

## Additional information
Screen Recording 2024-03-15 at 5.03.08 PM

**Comment by marinamas** [comment]
Uploading Screen Recording 2024-03-15 at 5.03.08 PM.mov…

**Comment by marinamas** [comment]
Any update by when this issue could be fixed ? This is important , because this was the expected behavior with DataTable.

**Comment by matthewgallo** [comment]
@marinamas was this one of the issues you were able to resolve over slack?

**Comment by marinamas** [comment]
@matthewgallo this is fixed . It is the same issue we discussed over slack
