### ISSUE TITLE
Investigate drag and drop keyboard actions in customize columns

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#4578]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

Arrow keys are not moving drag and drop items fully in customize columns tearsheet.

> Is this issue related to a specific component?

`CustomizeColumnsTearsheet`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

<kbd>Arrow</kbd> key should just move the row up or down to the next position, probably.

> What browser are you working in?

Chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

2.31.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Navigate to Datagrid customize columns
2. Open customize columns tearsheet
3. Use keyboard actions to move “columns” (<kbd>Space</kbd> to select)
4. etc.

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-products/tree/main/examples/carbon-for-ibm-products/SidePanel

## Additional information

- Screenshots or code
- Notes

**Comment by matthewgallo** [comment]
This seems to happen because the container is scrollable, dnd-kit has an [example with draggable items in a scrollable container](https://master--5fc05e08a4a65d0021ae0bf2.chromatic.com/?path=/story/presets-sortable-vertical--scroll-container) so I'll compare and see what changes we can incorporate from there.

**Comment by ljcarot** [comment]
Not addressing this feature in current Datagrid.  Example will be available in TanStack repo.
