### ISSUE TITLE
css variables from Theme not defined in `Tearsheet`

### ISSUE THREAD

**Issue by mconway-ns1** [carbon-design-system/ibm-products#4589]
## What will this achieve?

The Tearsheet component is missing the theme-defined CSS variables, responsible for defining colours and other stylistic attributes for each chosen theme

## Additional information

reproduced here
https://stackblitz.com/edit/github-ikhubk?file=src%2FExample%2FExample.jsx

**Comment by matthewgallo** [comment]
We've seen some questions come up regarding theming around Tearsheet as well, will be helpful to get design input on this issue as well.

**Comment by oliviaflory** [comment]
Closing because we will address token usage in #6127
