### ISSUE TITLE
DataSpreadsheet refactor: Refactor handlers into separate utilities or hooks

### ISSUE THREAD

**Issue by amal-k-joy** [carbon-design-system/ibm-products#4597]

**Comment by sstrubberg** [comment]
@amal-k-joy, @matthewgallo tells me you completed this work? Can you confirm?

**Comment by amal-k-joy** [comment]
> @amal-k-joy, @matthewgallo tells me you completed this work? Can you confirm?

@sstrubberg , This is completed and the code is merged.
