### ISSUE TITLE
Clean up SearchBar props

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#4602]
> FYI, noticing that several of the props, (scopesTypeLabel, scopes, selectedScopes, translateWithId, sortItems) are meant to be passed to the MultiSelect. Since these are all related, I wonder if it would make sense to follow the approach from @davidmenendez where we have Dropdown in AddSelect and we group these related props in an object/array.
> 
> 
> 
> yeah i agree with this. basically any time that we're working with multiple carbon components we should do our best to enable users to pass as many props to those components for maximum flexibility. unless there's a specific callout in the design to not use something specific we should probably have something like `btnProps = {}` and `multiSelectProps = {}` 

 _Originally posted by @davidmenendez in [#4239](https://github.com/carbon-design-system/ibm-products/issues/4239#issuecomment-2010497027)_
```[tasklist]
### Acceptance criteria
- [ ] Group related props (e.g. `multiSelectProps`)
- [ ] Update [migration notes](https://github.com/carbon-design-system/ibm-products/issues/4239#issuecomment-1965282111) and add to [Box note](https://ibm.ent.box.com/notes/1419297632926)
```

**Comment by elycheea** [comment]
@jlongshore Do we want to add more migration detail in Box or include details directly in #4437

**Comment by jlongshore** [comment]
> @jlongshore Do we want to add more migration detail in Box or include details directly in #4437

Yeah If you like you can do your work in the Box note and I can update the migration doc from it...
