### ISSUE TITLE
Team Forming: Create a support rotation program

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/ibm-products#4613]
#### Acceptance criteria

- A notification will be surfaced in the squad channel to let maintainers know who's on the hook to support.
- ~Create a support.md file in our github docs that outlines how triaging bugs works along with our commitment to support.~
- Playback to the team how support and triage works.

REF https://github.com/carbon-design-system/carbon/blob/main/docs/guides/support.md

```[tasklist]
### Tasks
- [x] Create list of team pairings
- [x] Add Slack workflow, same workspace as our channels
```

**Comment by elycheea** [comment]
Could do daily rotation via Slack workflow. Can have multiple devs to add coverage for timezones and possibly devops + support channel.
