### ISSUE TITLE
Update generate component script to use TypeScript

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#4627]
## What will this achieve?

When we create new components, there is a generate component script that can be run to scaffold the correct setup of files, configuring package-settings, exporting the new component. This is an issue to think about when the right time is to have the actual component itself moved from `.js` to `.tsx` file.

I don't think we need to set a timeline on this for now, but wanted to make sure it's something we plan for later on.

**Comment by elycheea** [comment]
Agree. Putting this in the icebox for now since in some previous discussions, we said _not_ to require TypeScript for new components. We might be reaching the point soon where we should start shifting to TypeScript on default though. 🤔

**Comment by AlexanderMelox** [comment]
Are we still keeping `PropTypes` in the generate or just Typescript props? 

```js
DISPLAY_NAME.propTypes = {
  /**
   * Provide the contents of the DISPLAY_NAME.
   */
  children: PropTypes.node.isRequired,

  /**
   * Provide an optional class to be applied to the containing node.
   */
  className: PropTypes.string,

  /* TODO: add types and DocGen for all props. */
};

```

**Comment by matthewgallo** [comment]
For now we'll keep both until something more concrete has been decided from https://github.com/carbon-design-system/ibm-products/issues/4466
