### ISSUE TITLE
Filtering and Search in Datagrid with nested rows is not working as expected

### ISSUE THREAD

**Issue by Sreejith-Websphere** [carbon-design-system/ibm-products#4652]
If we apply filter in datagrid, its not filtering from nested rows (but sorting and pagination works)
used useFiltering hook, (tested in chrome)

when we click clear filter also its not listing all data back from nested rows

search also not fetching data from nested rows
<img width="1789" alt="Screenshot 2024-04-05 at 12 59 03 PM" src="https://github.com/carbon-design-system/ibm-products/assets/87368885/8cf5430e-b406-4242-ba12-ed2c75284c38">
<img width="1789" alt="Screenshot 2024-04-05 at 12 59 12 PM" src="https://github.com/carbon-design-system/ibm-products/assets/87368885/673bfc6b-143f-418b-afa8-e6782c855b67">

**Comment by lee-chase** [comment]
Hi @matthewgallo @elycheea 

Any chance this is possible without having to upgrade to V8 of `react-table`?

That said it is a slightly weird way to filter a row that has success, but child that failed.

**Comment by rcsatheeshkumar** [comment]
We are using data-grid in IBM product and we are facing a similar issue in search with data-grid with nested rows. If a row is shown in search result and search value gets cleared, then only the parent row gets restored but the nested rows are not restored.  It could be reproduced in the storybook itself(https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-nestedrows--nested-rows-usage-story) as shown below, 

https://github.com/carbon-design-system/ibm-products/assets/17987392/e20db41d-575e-4f2a-91f5-75bdba838d80. 

I believe, it will get fixed once the issue posted by Original Poster gets fixed. So, could some one let me know about the ETA for providing a fix for this issue ?

**Comment by elycheea** [comment]
Link to Stackblitz provided by @lee-chase 
https://stackblitz.com/edit/github-6w6hhw-ieejed?file=package.json

**Comment by rcsatheeshkumar** [comment]
Hi Team,
This issue is blocking our QA tasks, could you please share the ETA for this fix and expedite the fix please. Thanks.

**Comment by matthewgallo** [comment]
Unfortunately this stems from the current version (v7.x.x) of `react-table` that we are using and this bug will not be fixed in that library unless we upgrade `react-table` which is not planned right now.

A workaround does exist however, by adding a `getSubRows` property to the `useDatagrid` hook. We'll update our storybook with the following workaround as well.

```jsx
const NestedRows = () => {
  const columns = React.useMemo(() => defaultHeader, []);
  const [data] = useState([]); // data
  const datagridState = useDatagrid(
    {
      columns,
      data,
      DatagridActions,
      getSubRows: (row) => row.subRows, // adding this property makes the subRows visible again after search/global filter is removed
    },
    useNestedRows
  );

  return <Datagrid datagridState={datagridState} />;
};
```

**Comment by rcsatheeshkumar** [comment]
@matthewgallo is there a workaround to make the search consider the nested rows content as welll ?

**Comment by Xirax** [comment]
I'm attaching a video with most recent behavior which is not fully correct (We can't search for nested rows):

https://github.com/user-attachments/assets/91d40353-776e-4486-9171-cdf81ab2ac78

**Comment by RichKummer** [comment]
Hey @Xirax , could you please open a new issue for the missing behavior? Thank you!

**Comment by matthewgallo** [comment]
If issue still exists, we can use the new issue for any missing behavior.
