### ISSUE TITLE
Datagrid when rows expanded child rows labels are cutting off (not fully shown)

### ISSUE THREAD

**Issue by Sreejith-Websphere** [carbon-design-system/ibm-products#4653]
when we expand rows in Datagrid the child rows labels are cutting off. Attaching the carbon-for-ibm-products sample example and the example where I tested
Eg: FirstName column in carbon-for-ibm-products example and Name column in my example

![Screenshot 2024-03-28 at 5 25 44 PM](https://github.com/carbon-design-system/ibm-products/assets/87368885/31381a31-abcf-48a4-98a4-5280dc9bf32b)
![Screenshot 2024-03-28 at 5 28 34 PM](https://github.com/carbon-design-system/ibm-products/assets/87368885/a8241ee4-0d24-44b3-9a0b-84b16e77399b)

**Comment by matthewgallo** [comment]
Hey @Sreejith-Websphere, this was addressed in #4656 and will be included in our next release.

**Comment by Sreejith-Websphere** [comment]
Thanks @matthewgallo
