### ISSUE TITLE
Get Started: Identifying subcomponents

### ISSUE THREAD

**Issue by ljcarot** [carbon-design-system/ibm-products#4683]
Breaking down the pattern into subcomponents (dev & design) e.g. drawer, cards.

```[tasklist]
### Tasks
- [x] Investigate if we need another size for the selectable tags or if these are just examples for flow
- [ ] Confirm if we need to build a drawer component or patterns
```

**Comment by elycheea** [comment]
### Notes from Apr 5, 2024
- Getting started card with 3 variants (default, image, numbered)
- Section tabs / drawer can that may include additional content

Item 6 from anatomy ... seems very similar to radio button or progress indicator except not necessarily continuous steps. Feels like a new state for “visited” or “completed” — feels selectable. — @mbgower
Should see if we can explore other ways to communicate the status in this case.

Think we can probably start refining just the getting started card variants. Bridget’s already broken these down well enough so far.

**Comment by elycheea** [comment]
@mbgower @kingtraceyj Also remembered after chatting with Jeff that the Checklist also uses a similar style to indicate “status.” We discussed tags with text during our call but can see the continuity with the [Checklist component](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-novice-to-pro-checklist--checklist) too.

**Comment by elycheea** [comment]
@ljcarot I think selectable tags are part of the new tags Lauren’s been sharing so I think we can remove that from the list.

Looks like drawer is taking shape as a component/variant but probably still a question where it lives (core, products).

@kingtraceyj where do we want to put the issue for the work you’re doing now so we can at least track it on the board?

**Comment by ljcarot** [comment]
@kingtraceyj or @oliviaflory Sounds like we want a new issue for Design related to the vertical tabs and related design decisions.  Is that correct?  If we do that, do we close this issue?

**Comment by elycheea** [comment]
Can probably close this issue once we open an issue in Core for vertical tabs. @kingtraceyj to share issue and close this one once created.

**Comment by kingtraceyj** [comment]
@elycheea tracking specs here: https://github.com/carbon-design-system/carbon/issues/16297

**Comment by kingtraceyj** [comment]
@elycheea opened the dev ticket here! https://github.com/carbon-design-system/carbon/issues/16305

i still need to tie up a few loose ends but i think were 90% of the way there.
