### ISSUE TITLE
Data Grid Virtual Scrolling : Use a Sliding data window

### ISSUE THREAD

**Issue by crichtonibm** [carbon-design-system/ibm-products#4686]
## What will this achieve?
Virtual scrolling would never run out of resources when used with extremely large datasets
## How will success be measured?
When using an extremely large dataset (100k ,1M rows ...), you should be able to continue scrolling without overtaxing the browser resources.
## Additional information
The way virtual scrolling works today is via 'bucket growth'. The fetch callback is called when it needs to grow the number of available rows. But it is a continual growth. If the dataset is extremely large, this will not be sustainable.  Supporting a sliding window approach would have the DataGrid asking the application to provide specific window of data based on the users scrolling direction.   The application would obtain and provide that data to the DataGrid

**Comment by elycheea** [comment]
@crichtonibm Would you be able to contribute an enhancement for this request?

**Comment by ljcarot** [comment]
We've been investigating [TanStack ](https://tanstack.com/table/latest)[Table](https://tanstack.com/table/latest), a third-party, open-source offering, which provides extensive data table capabilities surpassing what our Carbon Datagrid offers. It provides much more flexibility and customization. TanStack Table is headless which means it can easily be added alongside Datagrid component in your product or application. The benefits of more flexibility for product teams and less maintenance for Carbon makes it a win win. Lastly, it is available in multiple frameworks including [React](https://github.com/carbon-design-system/tanstack-carbon/tree/main/react#readme) and [Web Component](https://github.com/carbon-design-system/tanstack-carbon/tree/main/web-components#readme) so it provides an option to non-React product teams.

For these reasons, we have decided to transition from building our own custom table component to using an example-based approach with TanStack Table. Datagrid will still exist in our library for existing teams but we are announcing the deprecation* of the Datagrid component in v2.54.0 release so teams can begin to work through the transition. Details about how to use both Datagrid and TanStack together can be found [here](https://github.com/carbon-design-system/tanstack-carbon/tree/main). 

*Deprecation means that no new features will be added however sev 1 and sev 2 bugs will be supported.
