### ISSUE TITLE
useSelectRows - select-all checkbox results in getRowProps-not-found exception when there are unrendered rows

### ISSUE THREAD

**Issue by andygellaiibm** [carbon-design-system/ibm-products#4748]
## What package(s) are you using?
- [X ] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description
I'm having an issue with the useSelectRows hook, if the grid contains rows that currently aren't rendered/visible.  When the select-all checkbox is clicked (on the header row) , the following exception occurs:

react-dom.development.js:11340 Uncaught TypeError: row.getRowProps is not a function
    at stateReducer.js:96:1
    at Array.forEach (<anonymous>)
    at stateReducer (stateReducer.js:95:1)
    at react-table.development.js:1055:1
    at Array.reduce (<anonymous>)
    at react-table.development.js:1054:1
    at updateReducer (react-dom.development.js:15318:1)
    at Object.useReducer (react-dom.development.js:16425:1)
    at Object.useReducer (react.development.js:1512:1)
    at useTable (react-table.development.js:1059:1)
    
This can be recreated by going to the Expandable Rows demo at [(https://v1-ibm-products.carbondesignsystem.com/?path=/docs/ibm-products-components-datagrid-datagrid--basic-usage#expandable-rows)]
- Change "Items per page" from 10 to 5, which will cause 5 rows to go unrendered
- Click on the select-all checkbox, the page will go blank, with the "row.getRowProps is not a function" exception

I checked the v7 react-table documentation, it appears the getRowProps function is attached only to those rows that are currently visible/rendered.

> What browser are you working in?
macos Chrome 123.0.6312.106
 
> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
1.72.2

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
N/A at this time

## Steps to reproduce the issue
See above

**Comment by davidmenendez** [comment]
this should be fixed in #4763
