### ISSUE TITLE
snapshot test isn't running automatically

### ISSUE THREAD

**Issue by davidmenendez** [carbon-design-system/ibm-products#4752]
as @matthewgallo pointed out [here](https://github.com/carbon-design-system/ibm-products/issues/4043#issuecomment-1971879772) right now the snapshot test is failing. this is primarily because the snapshot test, as far as i can tell, isn't being run anywhere automatically. right now i think it can only be triggered manually. we need to update the CI checks and probably the pre commit lint to make sure tests are running properly before PR's get merged.

**Comment by elycheea** [comment]
Thank you for opening this! Matt and I noticed this a while back but I guess we never opened an issue. I am pretty sure they were previously working since I would need to update them in the dependency PRs though. 🤔
