### ISSUE TITLE
Datagrid row select checkbox tooltip support

### ISSUE THREAD

**Issue by mariusd-ibm** [carbon-design-system/ibm-products#4755]
## What will this achieve?

Datagrid enhancement to allow tooltips on select row checkbox

## How will success be measured?

I can add tooltips to datagrid select row checkbox

<img width="414" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/92723202/5cc6474a-3812-41b8-92a7-84ecae8c293e">

in particular we need it for disabled checkboxes

**Comment by adamkaynan** [comment]
Hello team! 
Can I nudge this one as a designer to advocate for how valuable it is for us -- but also at large. It seems like any element should have the ability to support a tooltip.

**Comment by oliviaflory** [comment]
Hi @mariusd-ibm and @adamkaynan disabled items are considered non-interactive and therefore cannot have a tooltip on hover. Please see the issue outlining the reasoning from the Carbon Design System team and the Accessibility team [here](https://github.com/carbon-design-system/carbon-website/issues/3758).

Closing this issue as we will not be adding this enhancement to Data Grid
