### ISSUE TITLE
Improve screenreader interpretation of Datagrid

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#4769]
Reported by @kristastarr in the [Datagrid review](https://github.ibm.com/CDAI-design/pal/issues/1575) from the accessibility audit.

### Screenreader testing

(Reported using macOS VoiceOver.)

> 1. This is related to [Comment A above][^1], regarding the base component. In this variation, the table headers contain multiple `title`s, and also since the `<input>` element is inside the `<th>`, the aria label for it (`"resize-column"`) is being read out as part of the title header in addition to the title of `"Row index"` (which doesn't really make sense if you're not visually looking at the table) and then the actual cell contents are read out so we hear it for a third time
Example of what the screenreader is reading out:

| Screenreader | Code |
---------------|------|
![image](https://github.com/carbon-design-system/ibm-products/assets/1717398/67cea532-fc12-4a8b-9dd0-85a5162e2650) | ![image](https://github.com/carbon-design-system/ibm-products/assets/1717398/a279e93b-17d2-481d-8bb2-8c32f33a4a76)

> 2. Let's look into how we can use `aria-label` to specify what the slider input is tied to — like what column name. Currently it just says you are inside a column header, but not which one

![image](https://github.com/carbon-design-system/ibm-products/assets/1717398/75d2bb98-2521-4b8c-b741-284779e6ba8d)

[^1]: #4581 
```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/ibm-products/issues/4799
```

**Comment by ljcarot** [comment]
Since we are moving to TanStack Table, closing this issue as not planned.
