### ISSUE TITLE
The API for MultiStepTearsheetStep and CreateFullPageStep is different (description)

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-products#4778]
In a Tearsheet step `description` is a node and `onPrevious` is a function.
In CreateFullPageStep `description` is a string and `onPrevious` does not exist.

## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

I was recently asked to switch a prototype from multi step tearsheet create pattern to a full page create pattern. On doing so I found that the API for the two is subtly different despite having very similar purposes and patterns.

In particular description as a string in a step is a blocker.

```[tasklist]
### Tasks
- [ ] Change prop type of `CreateFullPageStep` `description` prop from `string` to `node`
```

**Comment by matthewgallo** [comment]
`description` can be easily updated to `node`, however `onPrevious` was an enhancement that was added to `CreateTearsheetStep`. Can you open a separate issue for that part of it?

**Comment by lee-chase** [comment]
Added #4787 as per request @matthewgallo
