### ISSUE TITLE
CreateFullPage button bar isn't accessible but requires scrolling

### ISSUE THREAD

**Issue by modean** [carbon-design-system/ibm-products#4783]
## What package(s) are you using?

    "@carbon/colors": "11.21.0",
    "@carbon/ibm-products": "2.34.0",
    "@carbon/layout": "11.21.0",
    "@carbon/react": "1.54.0",
    "@carbon/styles": "1.54.0",
    "@carbon/themes": "11.34.0",
    "@carbon/type": "11.26.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-router-dom": "6.22.3"

## Detailed description

> Describe in detail the issue you're having.

If using the `CreateFullPage` component together in an app that uses the Carbon UI Shell and the `PageHeader` component, the button bar of the `CreateFullPage` component is not visible. Instead the user has to scroll to be able to access the buttons on the button bar.

The scrolling happens despite the fact, that the complete UI would fit into the real estate area of the browser. The horizontal scrollbar vanishes once the `SidePanel` component is in open state.

**Note**: There's also a horizontal scrollbar due to the `SidePanel` component being used.

> Is this issue related to a specific component?

I suspect it is related to `CreateFullPage` component and how it calculates its height. I.e. the height seems to be set via a `style` property that uses CSS `calc()`.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The button bar should be visible and thus accessible without the need to scroll down.

> What browser are you working in?

Chrome 123.0.6312.105 (Official Build) (arm64)
Firefox 124.0.2 (64-bit)

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

"@carbon/ibm-products": "2.34.0"

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

n/a

## Steps to reproduce the issue

I created a CodeBox [at the following location](https://codesandbox.io/p/devbox/createfullpagesample-9plsx3?file=%2Fsrc%2FApp.tsx%3A75%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluocoy1i00073b6gweqod0r2%2522%252C%2522sizes%2522%253A%255B60%252C40%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluocoy1h00023b6gm1qk9c77%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluocoy1i00043b6gpfqz4y2j%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluocoy1i00063b6gwnnik835%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B42.82810142949501%252C57.17189857050499%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluocoy1h00023b6gm1qk9c77%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluocoy1h00013b6gl2ktsvu7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cluocvpo600023b6gaex7i91z%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cluod7e8b00023b6g5ljvbv5e%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A75%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A75%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cluocoy1h00023b6gm1qk9c77%2522%252C%2522activeTabId%2522%253A%2522cluod7e8b00023b6g5ljvbv5e%2522%257D%252C%2522cluocoy1i00063b6gwnnik835%2522%253A%257B%2522id%2522%253A%2522cluocoy1i00063b6gwnnik835%2522%252C%2522activeTabId%2522%253A%2522cluod8cxy00693b6gkxxrjb5p%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522cluod8cxy00693b6gkxxrjb5p%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2523%2522%257D%255D%257D%252C%2522cluocoy1i00043b6gpfqz4y2j%2522%253A%257B%2522id%2522%253A%2522cluocoy1i00043b6gpfqz4y2j%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluocoy1i00033b6ghnzu21m4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cluocoy1i00033b6ghnzu21m4%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) to replicate the issue.

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-products/tree/main/examples/carbon-for-ibm-products/SidePanel

See above.

## Additional information

![image](https://github.com/carbon-design-system/ibm-products/assets/659775/e3ff5158-abc4-49d7-8c4e-c1dea8f8ed93)

![image](https://github.com/carbon-design-system/ibm-products/assets/659775/ab75dd58-5f56-4808-ab81-450b2d9b8ed5)

The point to understand from the images is that the screenshot that has the buttonbar is missing the upper part of the screen due to the scrolling.

**Comment by makafsal** [comment]
@modean This should be handled from the app side. Please see: https://codesandbox.io/p/devbox/createfullpage-with-global-header-jcycv5

If you've any questions feel free to ping in Slack.

**Comment by modean** [comment]
Hi @makafsal I have something similar (e.g. calculating the height in the stylesheet) already in place cause we wanted to move forward. Tho I considered it a hack that we had to introduce.

**Comment by makafsal** [comment]
@modean Then no worries that is the way to handle it for now.
