### ISSUE TITLE
Improve screenreader interpretation of column customization

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#4799]
Reported by @kristastarr in the Datagrid [customize columns review](https://github.ibm.com/CDAI-design/pal/issues/1576) from the accessibility audit.

### macOS Voiceover

> 1. The title is read out as "Customize columns fourteen slash fifteen" - it's not clear that this is referring to the 14 items selected in a list of 15. 
> 2. I'm not clear what the "6 items" are referring to in this case.  Also it's announcing "Find column" several times which I don't think is the intention 
> ![Screenshot 2024-03-22 at 5 32 06 PM](https://media.github.ibm.com/user/144832/files/d049db9a-6936-4143-9cd6-e16c9e84b6c7)
> 3. Upon first entering the list box, the number of items and the drag-drop instructions are read out as desired BUT - once navigating through the list, each list item is read out three times, and then the instructions are read out - every single time 
> ![Screenshot 2024-03-22 at 4 57 14 PM](https://media.github.ibm.com/user/144832/files/30547fa4-cc55-4941-8530-42f20316fe82)
> ![Screenshot 2024-03-22 at 4 57 26 PM](https://media.github.ibm.com/user/144832/files/13a164be-b959-4077-bd5e-b498fdf11e87)
> ![Screenshot 2024-03-22 at 4 57 55 PM](https://media.github.ibm.com/user/144832/files/f3b5ecb2-7a0f-4f47-bf82-38650361ad96)
> 
> 4. When you are searching, there is no feedback vocalized to let you know if any results are returned so you don't really know what to do next.  [Here's an example ](https://www.w3.org/WAI/WCAG22/Techniques/aria/ARIA22.html) using `role="status"` to announce search results 
> 
> 5.  This is announced as "Dimmed selected" - I think we need to give a more descriptive status here ("disabled", "locked", etc). A sighted user can see the lock icon to know that it is locked, and a SR user needs that info as well, but might not necessarily equate "dimmed" with "locked" since that's a visual cue
> ![Screenshot 2024-03-22 at 5 42 09 PM](https://media.github.ibm.com/user/144832/files/92ae2bb9-dcbf-4f0b-b196-09adf22a642d)
> 
> 6. After you tab to a list item and press space to initiate the move process - regardless of if you are able to move the item or not - if you shift+tab backwards back into the search box, and begin searching, as the number of list items changes based on what the search returns, VO announces every time that the list item selected for moving is changing position.  (like if an item was 3 out of 10 in the list and then following the search became for example, 2 of 5 items). Having things announced that way is great when you are moving the items around in drag-and-drop mode, but in this context, it's confusing the way it describes that it has been "grabbed" when in reality the list of items just changed 
> 
> ![Screenshot 2024-03-22 at 5 12 45 PM](https://media.github.ibm.com/user/144832/files/c9b3bd2c-e513-4b26-9304-79a7c55b4829)
> ![Screenshot 2024-03-22 at 5 16 49 PM](https://media.github.ibm.com/user/144832/files/4625566a-6426-4155-8ee2-8f3282708b1c)
> 
> If your search causes the draggable item to be removed from the list, but then you adjust the search so that the item does get returned as part of the results, it announces that the list item is dropped 
> ![Screenshot 2024-03-22 at 5 17 19 PM](https://media.github.ibm.com/user/144832/files/40845332-32c3-4c50-99ac-7ae6d87c2f66)
> 
>

**Comment by ljcarot** [comment]
Since we are moving to TanStack Table, closing this issue as not planned.
