### ISSUE TITLE
Get Started: Implementation

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#4809]
[Figma specs](https://www.figma.com/file/z5GvCED9gBr1b71soW3fIb/Get-started-pattern?type=design&node-id=567%3A19898&mode=design&t=WgjXCuaKLjv4aDj6-1)

Bridget still looking into positioning for status indicator (feels similar to radio button) so expect this to change over time.

The smaller cards will never include image.
May need to tie a minimum sizes to variant or conditional image based on size? 🤔 

These should use use productive card under the hood. The image and numbered variants can likely build off the default/base version. 

![Get started card -specs (1)](https://github.com/carbon-design-system/ibm-products/assets/15822070/ca606022-1a46-4934-908f-eb4dbb49299d)

### Acceptance Criteria

- Determine whether to create new Get Started component
- Should use clickable variant of productive card
- Add gradient mixin
- Add support for default variant
- Add support for icon (renderIcon) using crossroads as default
- Add support for status indicator (3 states — see [Checklist](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-novice-to-pro-checklist--task-states))
- Add support for metadata section
- Add under Components/Card in Storybook (tbd)
- Add support for `image` — decorative (empty alt)
- At small screen sizes, `image` not displayed
- Add support for `number` variant

**Comment by elycheea** [comment]
Create follow up issue to update remaining novice-to-pro components to use the mixin (currently see gradient repeated in ~8 files).

**Comment by sstrubberg** [comment]
#### Questions

- Can we implement this using Logical Properties? (where necessary)
- Does this need any accessibility testing written?
- E2E testing?
- Typescript support out of the gate?

**Comment by elycheea** [comment]
> * Can we implement this using Logical Properties? (where necessary)
+1 — we’re _starting_ to look into them and adopt them in some of the newer work but haven’t really added it as part of acceptance criteria yet. #3556 

> * Does this need any accessibility testing written?
We do a very baseline `toBeAccessible()` in scaffolding but not sure how much additional testing we need. Definitely open to pulling in some rigor if Dotcom devs have any input. :)

> * E2E testing?
Currently we’re only doing e2e for avt. But agree we should include this story as part of this initial implementation instead of adding it retroactively.

> * Typescript support out of the gate?
Probably depends on Cards which haven’t been migrated to `.tsx` yet.
