### ISSUE TITLE
Allow user to manipulate focus on step updates

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-products#4814]
## What will this achieve?

Currently there is no way to set focus on each step or react to step interactions.

Two things would allow quick keyboard navigation. 
- The ability to focus on an element when a new step is displayed
- The ability to move focus to 'next' when the step has been completed.

## How will success be measured?

- [ ] It is possible to set focus on displaying a new step.. 
- [ ] It is possible to focus on next when a step is complete
- [ ] All multi-step panels (CreateFullPage, CreateTearsheet etc)

This could be achieved for instance by:
1. Adding a prop to manipulate step focus are available
2. Adding a step status prop which sets focus on 'next' when 'complete'
3. Raising events before and after step change (could remove need for 1.)

Preferably all of the above are possible

**Comment by elycheea** [comment]
> The ability to focus on an element when a new step is displayed

@lee-chase For clarification, is this referring to allowing focus on `Location` on the second step of the [create tearsheet](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-patterns-create-flows-createtearsheet--multi-step-tearsheet&globals=viewport:basic) example?
