### ISSUE TITLE
Allow user to set current step in all multi-step operations

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-products#4815]
## What will this achieve?

It will allow the user to jump check/update each step.

Currently `initialStep` in CreateFullPage cannot be used for this purpose as it seems to always return to the first step.

## How will success be measured?

It will be possible in all multi-step processes to jump to a previous step.

**Comment by matthewgallo** [comment]
Following back up with this issue, I added `initialStep: 2` to the `CreateFullPage` props in storybook and it rendered the second step. Can you provide a reproduction of this @lee-chase?
