### ISSUE TITLE
TBD interim Cloud on website

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-products#4881]
Possible paths forward *Issue will be updated after Wednesday meeting

New IA separating Cloud components from PAL components
- _If Cloud has to stay on for unknown amount of time_

Add notification to website about Cloud exit
- Banner on homepage (Carrie might already have?)

If we leave Cloud components mixed in: add notification to individual component pages "This is a Cloud component"
- Link to new pal website (even if staging)

**Comment by elycheea** [comment]
FYI, I do have a branch with the banner although actual colors may have been tweaked or adjusted from Jeeyoung.
We used the branch to test some things — the banner code would need to be added in both the CDAI-design/pal and CDAI-design/cloud-pal repos based on the investigation.

**Comment by oliviaflory** [comment]
@elycheea Could you share a screen shot or the banner or a link to your branch?

**Comment by elycheea** [comment]
![image](https://github.com/carbon-design-system/ibm-products/assets/1717398/47a165e1-b189-46ab-b1f2-ed54fba2d560)

I think the colors may be more updated in Jeeyoung’s latest, but the branch for it is here.
https://github.ibm.com/CDAI-design/pal/tree/cloud-pal-banner
