### ISSUE TITLE
Adding focus to tearsheet component 

### ISSUE THREAD

**Issue by psurana2** [carbon-design-system/ibm-products#4893]
## What package(s) are you using?

@carbon/ibm-products": "^2.27.0",
 "react": "^17.0.2",

## Detailed description
On keyboard tab press, focus doesnt come on the title , subtitle and body of the tearsheet component . And also the close button should be focusable first then the other component of the tearsheet 

> Is this issue related to a specific component?
TearsheetNarrow 

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Focus has to come on the title, subtitle , body of the tearsheet component 
> What browser are you working in?
Firefox, Chrome 

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
@carbon/ibm-products": "^2.27.0",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
We  work for GI team and above issue is raised as a AVT issue

**Comment by makafsal** [comment]
@psurana2 - There are a couple of reasons why we don't focus the title, subtitle and body of the tearsheet:

**Screen Reader Confusion**: When a screen reader encounters a form, it usually announces it as a "form" followed by any instructions associated with the form. If the title text also receives focus, screen reader users might hear the announcement twice, which can be confusing and disrupt the workflow.

**Focus Should Be on Interactive Elements**: The primary purpose of focusing elements on a web page is to allow users to interact with them using the keyboard or assistive technologies.  Titles are informational and don't require user input, so focusing them doesn't add value for accessibility.

**Keyboard Navigation**: When using the keyboard to navigate a web page, users typically expect to land on the first interactive element within a form, which is usually the first input field.  Focusing the title would disrupt this expected navigation flow.

I greatly appreciate it if you could check the [accessibility guidelines](https://www.w3.org/TR/WCAG22/#focus-order).

**Comment by psurana2** [comment]
OK thanks @makafsal

**Comment by psurana2** [comment]
Also wanted a clarification from you @makafsal . The content of the terasheet which is clickable tile or tags ( that is the body ) isnt that also focusable ?
