### ISSUE TITLE
Condition builder: Async docs insider review of the Usage tab guidance

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/ibm-products#4900]
### Acceptance Criteria

- Do Async docs insider review of the guidance with @aagonzales and @jeanservaas and @laurenmrice for the Usage tab

Link:
Usage Guidance - [Editable Figma file ](https://www.figma.com/file/BRk3lEQVpJ8jn6jj7UO4mK/Condition-Builder---Usage-Guidance-v7?type=design&node-id=0%3A1&mode=design&t=c3r6FV9t5ilWhu2h-1)

- Consider the Data structure and does that need it's own tab or does it live in Usage.

**Comment by aubrey-oneal** [comment]
Here is the [usage template in Figma](https://www.figma.com/design/XQqHxu38CiY3Vx1iHdafIa/Image-production-guidelines?node-id=2651-218&t=eXVB6TqEwPcCfM9u-0)!
