### ISSUE TITLE
Focus not coming on the content of the tearsheet

### ISSUE THREAD

**Issue by psurana2** [carbon-design-system/ibm-products#4905]
### Package

Carbon for IBM Products

### Description

In the component, focus is coming on the text input on keyboard tab press but doesnt come to the rest of the content (body) of the component like tags or clickable tile

### Component(s) impacted

Tearsheet, Tearsheet Narrow

### Browser

Chrome, Firefox

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v2.27.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

GI-Asset service

### CodeSandbox or Stackblitz example

http://localhost:9000/?path=/story/manage-tags-assignassettagmodal--default&activeLocale=en

### Steps to reproduce the issue (if applicable)

Add content such as clickable tile in the body other than user input and button to check if focus is coming on the body

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by elycheea** [comment]
Hi there! Thanks for taking the time to report this! Could you create a minimal reproduction in [CodeSandbox](https://ibm-products.carbondesignsystem.com/?path=/story/overview-examples--c-4-p-gallery-code-sandbox) or [Stackblitz](https://ibm-products.carbondesignsystem.com/?path=/story/overview-examples--c-4-p-gallery-stackblitz). It’ll help us better understand and investigate this issue.

**Comment by psurana2** [comment]
https://stackblitz.com/edit/github-hlqngl?file=src%2FExample%2FExample.jsx 

@elycheea  you can refer to this

**Comment by makafsal** [comment]
@psurana2 @elycheea - I've tried to reproduce the issue locally (because the above Stackblitz is not working for me), but I didn't encounter such an issue, the `ClickableTile` is focused as expected.

https://github.com/carbon-design-system/ibm-products/assets/9197089/4ed165ff-a77e-4181-8c5c-808d6b83b4b7

@psurana2 - Could you provide a working CodeSandbox instance, it'll be helpful for me to understand the exact scenario.

**Comment by psurana2** [comment]
```
 <ClickableTile
            role="button"
            tabIndex={0}
            key="tagValue1"
            id="tagValue1"
          >
            Category value
          </ClickableTile>
```

CAn you just add this one piece of code before the inputs and check if the focus comes on this componenet or not

**Comment by makafsal** [comment]
@psurana2 Sure, I tried it and it is working as expected.

Please see the CodeSandbox: https://codesandbox.io/p/devbox/reverent-http-gz5gc2?file=%2Fsrc%2FExample%2FExample.jsx%3A3%2C51

If possible could you please reproduce it in the CodeSandbox?

**Comment by psurana2** [comment]
Can u make this CodeSandbox editable? 
And also is it because if the version we are using ? we are using v2.27.0

**Comment by makafsal** [comment]
@psurana2 - Editable CodeSandbox: https://codesandbox.io/p/live/04e6b647-f56f-42fd-a6f4-3af5a17fd3df

**Comment by Vinodbs** [comment]
@makafsal in the screen recording provided, how do we navigate through the different tabs via keyboard? Im not sure if the tabs in the tearsheet is keyboard operable. Can you please verify.

**Comment by makafsal** [comment]
@Vinodbs Indeed, they are keyboard accessible. Use the tab key to switch focus and use the left and right arrow keys to move between tabs.


https://github.com/carbon-design-system/ibm-products/assets/9197089/c84af142-7382-4bf3-aaf0-704283a27c6b

**Comment by Vinodbs** [comment]
the sandbox code where it is working as per required is using"@carbon/ibm-products": "2.37.0",

however we are using v2.27.0 
Please let us know if there is any solution .
thanks

**Comment by Vinodbs** [comment]
Please let us know if there is any solution .

**Comment by makafsal** [comment]
@Vinodbs This issue is related to the `Tab` component. Focus is going to the `TabList` div element, as a workaround you can give `tabindex="-1"` for the `TabList` component in your code.

```
<TabList aria-label="Tab list" tabIndex={-1}>

**Comment by makafsal** [comment]
@elycheea @Vinodbs @psurana2 I have raised an issue in the Carbon repo: https://github.com/carbon-design-system/carbon/issues/17287
