### ISSUE TITLE
[Datagrid: Datagrid does not remember current selection and expansion state when re-rendering

### ISSUE THREAD

**Issue by flannanl** [carbon-design-system/ibm-products#4911]
### Package

Carbon for IBM Products

### Description

When using `Datagrid` with `useNestedRows` and `useSelectRows`, any selection or expansion state done in the rows are not preserved after re-rendering.

### Component(s) impacted

Here is a snippet that can show the issue. With this snippet, if you try to select or expand a row within the 5-sec refresh, you will see all the selection and expansion states you have done are lost after re-rendering. I do have a current workaround at the moment, but this is a hack of using some of the internal functions available in `datagridState` to preserve the selection and expansion states.

```
import React, { useEffect, useMemo, useState } from 'react';
import {
  Datagrid,
  useDatagrid,
  useNestedRows,
  useSelectRows,
} from '@carbon/ibm-products';
import { makeData } from './utils/makeData';

const defaultHeader = [
  {
    Header: 'Row Index',
    accessor: (row, i) => i,
    sticky: 'left',
    id: 'rowIndex', // id is required when accessor is a function.
  },
  {
    Header: 'Age',
    accessor: 'age',
  },
  {
    Header: 'First Name',
    accessor: 'firstName',
  },
  {
    Header: 'Last Name',
    accessor: 'lastName',
  },
  {
    Header: 'Visits',
    accessor: 'visits',
  },
];

export const Example = () => {
  const columns = React.useMemo(() => [...defaultHeader], []);
  const [data, setData] = useState(makeData(10));

  useEffect(() => {
    setTimeout(() => {
      setData((pastData) =>
        pastData.map((d) => ({
          ...d,
          age: Number(d.age) + 10,
        }))
      );
    }, 5000);
  }, []);

  const rows = useMemo(() => {
    const parentRows = [];
    for (let i = 0; i < data.length; i = i + 2) {
      parentRows.push({
        ...data[i],
        subRows: [data[i + 1]],
      });
    }
    return parentRows;
  }, [data]);

  const datagridState = useDatagrid(
    {
      columns,
      data: rows,
    },
    useSelectRows,
    useNestedRows
  );

  return <Datagrid datagridState={{ ...datagridState }} />;
};

export default Example;
```

### Browser

Chrome, Safari

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v1.72.2

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

IBM Cloud Projects

### CodeSandbox or Stackblitz example

https://stackblitz.com/edit/github-tqgv7v?file=src%2FExample%2FExample.jsx,src%2FExample%2Futils%2FmakeData.jsx

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by matthewgallo** [comment]
Hey @flannanl, this is actually something that is configurable from `react-table` by providing the `autoResetSelectedRows` property to the `useDatagrid` hook.

```jsx
const data = useDatagrid({
  columns,
  data,
  autoResetSelectedRows: false,
});
```

**Comment by flannanl** [comment]
Seems to work for me. Thanks.
