### ISSUE TITLE
Fix failing Netlify builds

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#4920]
## What will this achieve?

Fixes failed deploys in several PRs.

## How will success be measured?

Deploy previews work in our PRs again!

## Additional information

- Designs
- Existing code
- etc

**Comment by matthewgallo** [comment]
I think we can finally safely close this one. I was able to get the `storeStoryV7` setting to work which drastically decreased our built storybook assets, `main.js` entry point went from `~36mb` to `~8mb`.

I've been able to confirm with several open PRs that merging these changes allows Netlify to build once again 😅
