### ISSUE TITLE
Enhancement proposal: grouping for NotificationsPanel

### ISSUE THREAD

**Issue by a-roberts** [carbon-design-system/ibm-products#4924]
## What will this achieve?

we'd love to be able to use the NotificationsPanel to group similar errors by, say, title or description.

This could be achieved on the UI through:

<img width="106" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/12814972/7a03d38e-fd16-4f9c-ba00-5acb0343b885">

which would be provided for each Notification where there are similar problems (or anything else we would want to group).

There are several ways this could be implemented - a simple "doGrouping" type prop (that'd be a boolean) and would look for some known prop (say, the title), and if set, instead of producing new Notification items, we'd have them available via clicking to view more. They could be available via the hidden items now showing as they would without grouping.

Another way would be via a set of enums (e.g. groupOn={foo|bar|baz}) where items could be grouped based on specific props provided to the NotificationsPanel (e.g. title, description, anything else).

And another way would involve a custom grouping function that could be applied for each element found.

## How will success be measured?

This question "how will success be measured" is confusing in this case given this is an enhancement request so that we needn't create our own NotificationsPanel-like component, or do grouping via another rudimentary way. 

## Additional information

- Designs
- Existing code
- etc

**Comment by aubrey-oneal** [comment]
- [ ] Chat with Core. This issue may move over there (related to Ben's work)
- [ ] Core also has the shell enhancement umbrella issue: https://github.com/carbon-design-system/carbon/issues/16296
