### ISSUE TITLE
Enhancement proposal: custom footer within NotificationPanel

### ISSUE THREAD

**Issue by a-roberts** [carbon-design-system/ibm-products#4927]
## What will this achieve?

We'd like to be able to provide our own footer where, having noticed the Notifications within the NotificationsPanel, but still needing support, one could be provided with a set of useful links with appropriate icons, as so:

<img width="249" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/12814972/d37ac7d4-3c9e-4df0-a6b3-8bea5063d044">

Currently we don't believe this to be possible.

I expect this would be done through a new NotificationsPanelFooter component that we could define and pass through a prop and, when set, would be rendered appropriately.

**Comment by elycheea** [comment]
@a-roberts After some review with our team, we think the [Assist Me panel](https://pages.github.ibm.com/cdai-design/pal/components/onboarding/assistance-panel/usage) may be better suited for this sort of help and support content.
