### ISSUE TITLE
Replace `main_v1` branch with `v1`

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#4932]
## What will this achieve?

Rename* the `main_v1` branch to just `v1`.
Dotcom and core use the version name as well for their previous versions.

*This could be actual rename _or_ just a new branch.

## How will success be measured?

Replace `v1` with `main_v1` and update any actions or docs that reference `main_v1` with `v1`.
`v1` should also include branch protection.

## Additional information

- Designs
- Existing code
- etc

**Comment by matthewgallo** [comment]
Used same branch protections for `v1` as we had for `main_v1`. Did some initial testing by running the v1 upgrade dependencies action and it works as expected. I'll delete `main_v1` and then we should be able to close this.
