### ISSUE TITLE
Review design to dev delivery process that the workgroup has created

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-products#4944]
- [x] Review Design Delivery process from the workgroup
   - [x] [Box folder](https://ibm.ent.box.com/folder/191976316844?s=vinogh9rnc6txijtexglffxsqxjcjssx)
- [ ] Identify crossover with component specs
- [x] Make suggestions for any additions we'd want for PAL component specs
- [x] Design Delivery doc will publish to C4IP website in L0 between Design kits and Contributing to IBM products with title 'Design Delivery' for this phase

**Comment by ljcarot** [comment]
John is currently working in VSCode building the 4 pages of content that will be called ‘Design Delivery’.  It will have subsections Overview; File preparation; Design review meeting; & Post delivery.  He has help to create and publish the PRs.  He said it should be all done this week, at the latest Monday.  It will live as guidance below ‘Design Kits’ in the current left nav at the same level of C4IP.
The original issue -> https://github.ibm.com/CDAI-design/pal/issues/1097

**Comment by ljcarot** [comment]
Design delivery has been published
