### ISSUE TITLE
[DataGrid]: Allow DataGrid column width to spread out responsively when minWidth or Width specified

### ISSUE THREAD

**Issue by ShiriKremer** [carbon-design-system/ibm-products#4961]
### The problem

I am using the DataGrid component and want the columns to have min width / width but spread out responsively to the entire space available in the table  (as in Carbon) and not hold their initial size
(leaving much empty space to the right of them - as can be seen in the capture below)

https://github.com/carbon-design-system/ibm-products/assets/147585390/fa45e1dc-fdac-4633-b78d-c3950efb2852

### The solution

Possible solutions:
1. Be be able to pass to width non numeric content such as 20% (as regular width field can get) and have column spread out  accordingly
2. If minWidth specified and there is more space available, add space to these columns as the DataGrid area expands

### Owner/main maintainer(s)

Matt Gallo

### Product/offering

Turbonomic

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by elycheea** [comment]
This issue has dependencies on https://github.com/carbon-design-system/ibm-products/issues/4977 but this would likely cause some major breaking changes so we likely won’t be able to pursue this until our next major version.

**Comment by ljcarot** [comment]
We've been investigating [TanStack ](https://tanstack.com/table/latest)[Table](https://tanstack.com/table/latest), a third-party, open-source offering, which provides extensive data table capabilities surpassing what our Carbon Datagrid offers. It provides much more flexibility and customization. TanStack Table is headless which means it can easily be added alongside Datagrid component in your product or application. The benefits of more flexibility for product teams and less maintenance for Carbon makes it a win win. Lastly, it is available in multiple frameworks including [React](https://github.com/carbon-design-system/tanstack-carbon/tree/main/react#readme) and [Web Component](https://github.com/carbon-design-system/tanstack-carbon/tree/main/web-components#readme) so it provides an option to non-React product teams.

For these reasons, we have decided to transition from building our own custom table component to using an example-based approach with TanStack Table. Datagrid will still exist in our library for existing teams but we are announcing the deprecation* of the Datagrid component in v2.54.0 release so teams can begin to work through the transition. Details about how to use both Datagrid and TanStack together can be found [here](https://github.com/carbon-design-system/tanstack-carbon/tree/main). 

*Deprecation means that no new features will be added however sev 1 and sev 2 bugs will be supported.
