### ISSUE TITLE
[Datagrid]: Datagrid should allow to take the class name for column 

### ISSUE THREAD

**Issue by SeonyuK** [carbon-design-system/ibm-products#4965]
### Package

Carbon for IBM Products

### Description

There is no way to add a class for datagrid columns. We can add the cell but not <td> 

### Component(s) impacted

![Screenshot 2024-04-22 at 10 58 18 AM](https://github.com/carbon-design-system/ibm-products/assets/144151347/06b017bd-95f1-46a3-aac8-dc94f922f879)
![Screenshot 2024-04-22 at 10 56 18 AM](https://github.com/carbon-design-system/ibm-products/assets/144151347/c6760464-6302-4993-8e9b-6eada22a4398)

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v2.35.0

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

QRadar suit

### CodeSandbox or Stackblitz example

you can check in the storybook

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by kennylam** [comment]
Fixed in #4967
