### ISSUE TITLE
First-time Orientation: Figma kit discussion

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-products#4982]
Discuss what and where we want to publish PLG Get started documentation

Determine how we want to deliver the Orientation flow (Get started) assets and future PLG design assets

- What type of Figma files are teams expecting
   - Mini kit like AI: A PLG specific kit
   - In the All themes kit 

### Option 1: PLG kit
**A mini Figma kit that has all PLG assets for designers**
- Onboarding Orientation (Get started)
   - Usage docs
   - Examples of layouts
   - Get started cards
   - How to link tabs?
- Feature Preview
   - Usage docs
   - Examples of layouts

**Website**
- Do we need to publish the docs on the website if they are in the kit? Similar to AI approach

### Option 2
**Website**
- Publish website docs on Product PAL
   - Include "experimental" notification
   - Include instructions on where to find each component?

**Figma**
- Product PAL kit
   - Add Get started cards
   - Add Feature preview banner
   - Interstitial (make sure it's there)
- Carbon Core kit
   - Vertical tabs
   - Tags

```[tasklist]
### Tasks
- [x] Discuss strategy with the Carbon teams and PLG workstream team
- [ ] Open follow on issues based on decision
```

Bridget's current [Figma file](https://www.figma.com/file/QH8ex9Mh1xnNIJLZkBlE5w/Novice-to-pro-%7C-Documentation?type=design&node-id=3289%3A653&mode=design&t=VQDzVM28rs0a85CY-1)

**Comment by oliviaflory** [comment]
### Option A
_**Discussed at the workshop Apr 25**_
Provide a "Get started" kit similar to how we delivered AI

Figma file would contain:
- Card components
- Tab components (?)
- Usage guidance

Within IBM Product PAL Figma project:
- Folder called PLG experiences
   - "Get started"
   - "Preview"
   - etc... 

Once PLG is production ready, we will publish the usage guidance on the Product PAL website and within the Product PAL all themes kit

### Option B
PLG has a L1 section in the nav
- 
Publish the guidance

**Comment by sstrubberg** [comment]
dupe https://github.com/carbon-design-system/ibm-products/issues/5233

**Comment by ljcarot** [comment]
As our understanding of the content in this PAL is evolving, it feels like there is another potential option that we can standardize on and that is that each pattern, the equivalent of a recipe, should have their own Figma kit and in the case where the pattern of patterns expands out, we could have one Figma kit for the collection of recipes (e.g. Onboarding).  This is similar to the AI Essentials Kit.  It's a collection of recipes on how to embed AI in your product.  

We may need a template for this kind of Figma Kit for Patterns especially when the Kit refers to coded components as it doesn't have to repeat the details that are provided in the All Themes Kit, and in the website docs but its goal is to provide designers with a detachable design to use in their product designs.

**Comment by oliviaflory** [comment]
We've decided to move forward with Option 2:

- Provide the components (ingredients) in Carbon core and Carbon for IBM Products kits
- The website will document the various pattern options and provide the recipe list 

Next steps
- Open an issue to add the get started cards into C4IP all themes
- Open an issue for design exploration on documenting a recipe

**Comment by ljcarot** [comment]
@oliviaflory Can this be closed?

**Comment by oliviaflory** [comment]
Yes! Thank you for reminding me. Closed
