### ISSUE TITLE
Setting Datagrid column widths can cause content to be hidden

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-products#4988]
### Package

Carbon for IBM Products

### Description

Content in columns to right of child rows not hidden.

Currently 
<img width="1206" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/15086604/6ef7697f-a401-4cc6-8d8a-d72888eccae7">

With a simple bit of CSS
```scss
.#{$block-class}__table .#{c4p-config.$pkg-prefix}--datagrid__cell:not(:first-child) {
  z-index: 1;
}
```

<img width="1055" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/15086604/eacd3ffd-893b-4197-89a4-431e9b2aef1a">

### Component(s) impacted

Datagrid

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.32.0

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Product/offering

AppEngine

### CodeSandbox or Stackblitz example

N/A

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by sangeethababu9223** [comment]
Hi @lee-chase ,
Could you please share a codesandbox / Stackblitz sample for the issue?

**Comment by sangeethababu9223** [comment]
Hi @lee-chase ,
Could you please update to the latest version and try?
This is already fixed with the PR https://github.com/carbon-design-system/ibm-products/pull/5398

**Comment by sangeethababu9223** [comment]
Hi @lee-chase ,
Closing this issue since this is already fixed in the latest version.
