### ISSUE TITLE
Audit Product PAL assets Components vs Patterns

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-products#4997]
Audit the PAL assets against the definition of Component and Pattern that we established in the pre-work for the workshop. 

- [x] Revisit the [Schema](https://next.carbondesignsystem.com/contributing/schema) and how we define things there
- [x] Revisit the [component vs pattern qualifiers](https://app.mural.co/t/ibm14/m/ibm14/1712688667860/3f0186f4a5277271933131d37c543640ef7ea715?sender=u926d32b52769ed4adca52559) from the workshop pre-work
- [x] Create a quick write up of component vs pattern qualifiers
- [x] Create audit in Airtable: duplicate and work off of [existing airtable](https://airtable.com/appURFSG6dypHTXcd/tbl4PtqbxPthKR2s5/viwIIP2QAFLhV2UaK?blocks=hide
) and [Product site audit](https://www.figma.com/file/gmlnTUu8PQtgJoiHnkgzXd/IBM-Product-PAL-IA?type=design&node-id=0-1&mode=design&t=jk05Z0AorwbnuD2E-0).
- [x] After the audit we need to refine our opinion of what needs to change. We will keep components and patterns separate in our IA but need to reduce the number of patterns.

**Comment by aubrey-oneal** [comment]
Note that we can consider this for a future workstream:
Discuss the idea of having example code for patterns (showing several permutations of filter pattern). How would this impact IA in website and Storybook? How feasible is this?

**Comment by oliviaflory** [comment]
### Review Notes May 15
Met with: Linda, Jeannie, Carrie, Elysia, Scott, Taylor, Tracey, Aubrey, Olivia

Reviewed Olivia's progress on Component and Pattern definition and audit, see [Figma file](https://www.figma.com/design/V71R5HZaTFpF2B0AX3D12v/Component-vs-Pattern-definition?node-id=0%3A1&t=X7onANE8NRL5Q0Y9-1)

**Feedback**
- Component definition is most clear
- The challenge has now shifted from component vs pattern to pattern vs flow or template
- Need to get crisp on the definition of pattern, flow and templates
- Split between Option 1 (two categories) and Option 2 (4 categories) – see figma for details

**Next steps**
- Iterate on the definitions
- Iterate on the list of patterns/flows again to see if we can move any more
- Answer: how would we handle flows or templates that are not PLG
- Explore if a recipe checklist on the overview pages would help 
- Do some testing with our community

**Comment by oliviaflory** [comment]
Closing as completed in sprint 17. Presented to C4IP and DSAG
