### ISSUE TITLE
React 19: `useRef` requires an argument 

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#5038]
## What will this achieve?

This should be a relatively easy change but my guess is that it will be required across a lot of different components. [See more info here.](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#useref-requires-argument)

## Additional information

- Designs
- Existing code
- etc

```[tasklist]
### Tasks
- [x] Add list of components that this impacts
- [x] find and replace
```

**Comment by elycheea** [comment]
@amal-k-joy mentioned that many of the Typescript issues should already have added argument for `useRef`. We can use this issue to track any others that still need to be updated.
