### ISSUE TITLE
Discuss globalization approach for condition builder

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#5043]
Dotcom uses JSON as well for masthead so may be some approaches we can investigate or adopt.

- https://github.ibm.com/webstandards/ibm-dotcom-translations
- https://github.com/carbon-design-system/ibm-products/blob/v1/packages/security/src/globals/nls.js
- https://react.i18next.com/
- https://lokalise.com/blog/react-i18n-intl/

**Comment by amal-k-joy** [comment]
@elycheea 
We have  exposed a prop `translateWithId`  which a optional callback which gets called from component with message id as the argument, and the user can return the text corresponding to that id. This is an approach carbon has already used. Can we close this issue?
