### ISSUE TITLE
Tabs on PageHeader rendering incorrectly: Scroll Behaviour when it's not needed

### ISSUE THREAD

**Issue by sean-anderson-ibm** [carbon-design-system/ibm-products#5105]
### Package

Carbon for IBM Products

### Description

On the page header component, when provided tabs as a navigation option, no matter how much space there is or how many tabs you provide you get an arrow being rendered to see more tabs, but if you click on that arrow button, then the one to put you back to where you were, this option disappears. This leads to a confusing experience for the user as it appears this arrow button should do something, but ends up having no impact, apart from covering part of the clickable area for the first tab. 

https://github.com/carbon-design-system/ibm-products/assets/123759511/1d34945f-b14c-4ea4-bf77-1eef030eeaf9

### Component(s) impacted

PageHeader, can be seen in the storybook, codesandbox linked or the video above. This is based on the example from the storybook with no code changes.

### Browser

Firefox

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v2.37.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

Cloud Pak For Integration (Platform UI)

### CodeSandbox or Stackblitz example

https://codesandbox.io/p/devbox/nostalgic-keller-3hrpws

### Steps to reproduce the issue (if applicable)

Create a pageHeader with tabs, or go to the pageHeader example codesandbox/stackblitz from the storybook.

### Release date (if applicable)

This has been seen on multiple versions for about the last month or so, but is still being seen on v2.37.0

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by matthewgallo** [comment]
Hey @sean-anderson-ibm, I was looking at your code sandbox example provided and don't see the arrows appearing even after resizing. Was there anything else that caused them to become visible for you?

**Comment by sean-anderson-ibm** [comment]
Just checked and this seems to be an issue when using Firefox, Chrome doesn't seem to have these arrows which might explain why we're seeing different things. If you try that code sandbox in Firefox you should see those arrows

**Comment by jesper-perl** [comment]
I too have come across this issue.

Firefox 127.0
@carbon/ibm-products 2.43.1
@carbon/react 1.60.1

**Comment by devadula-nandan** [comment]
hi @sean-anderson-ibm @jesper-perl ,
looks like this bug was from `@carbon/react` and was fixed in the later release.

https://github.com/user-attachments/assets/794bf1ce-0001-4f50-b67b-9e72550d4848
