### ISSUE TITLE
CSS prefix__cls-xx does not apply for svg that has in-line style due to strict CSP

### ISSUE THREAD

**Issue by aknguyen7** [carbon-design-system/ibm-products#5168]
## What will this achieve?

I have `@use "@carbon/ibm-products/scss/components/HTTPErrors"` with `import { HTTPError403 }` from `'@carbon/ibm-products'`; for the 404 page and it renders fine but I just noticed that some of the css does not apply for the svg as the images is darker compare to the design here https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-patterns-http-errors-httperror404--with-all-props-set

Inspecting the elements it has <style> as part of the svg:
![image](https://github.com/carbon-design-system/ibm-products/assets/30509453/9719fbc6-b8db-476e-9326-dba365ac27e6)

The css classes with `prefix__cls-xx` does not get apply since it's in-line <style> therefore it's being prevent to load due to the strict CSP policies. You would see something like

![image](https://github.com/carbon-design-system/ibm-products/assets/30509453/e2274e2d-da1c-4b49-b058-e15903d85c6c)

To reproduce the problem, enable the CSP policies `default-src 'self'; img-src 'self' data:; style-src 'self'; script-src 'self'; frame-ancestors 'self'`

I just want to note this issue, right now we have a workaround by adding these prefix__cls-xx css class to our css. 

![image](https://github.com/carbon-design-system/ibm-products/assets/30509453/48bb3ad6-8de3-43ad-88d8-ebd943aa070d)

## Additional information

- Designs
- Existing code
- etc

**Comment by sstrubberg** [comment]
@aknguyen7 can we get a [repro](https://carbon-for-ibm-products.netlify.app/?path=/story/overview-examples--c-4-p-gallery-code-sandbox&globals=viewport:basic)?
