### ISSUE TITLE
Setup VRT

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#5236]
create a branch on main, and add percy integration code taking reference from https://github.com/carbon-design-system/ibm-products/tree/feat/percy-integration, test the integration by making few test prs on this branch, if there is any false reporting, exclude the stories, until we fix/skip the conflicts responsible for false reporting

https://www.browserstack.com/docs/percy/integrate/storybook

**Comment by ljcarot** [comment]
Any update on the status of setting up VRT?

**Comment by elycheea** [comment]
@devadula-nandan to add some additional details and refinement on current status.
