### ISSUE TITLE
[DataSpreadsheet]: SelectionAreaChange does not capture every event + Selection mouse move gets stuck when remove onclick

### ISSUE THREAD

**Issue by AustinGitHub** [carbon-design-system/ibm-products#5262]
### Package

Carbon for IBM Products

### Description

https://github.com/carbon-design-system/ibm-products/assets/10100397/650e7460-a4a3-4070-9c3d-72aa8f68fa35

When I release the click hold on the selection sometimes when I move my mouse around, it still thinks it is in selection mode is is highlighting other cells. 

I would expect the `selection area change` to receive update when we are going from cell to cell, seems this is not the case.

### Component(s) impacted

DataSpreadsheets

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.38.0

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

IBM DataStage

### CodeSandbox or Stackblitz example

https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-data-spreadsheet-dataspreadsheet--data-spreadsheet&globals=viewport:basic

### Steps to reproduce the issue (if applicable)

See Video. 

For the selection being active when mouse is no longer being drag held, this occurs sometimes but pretty common. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by AustinGitHub** [comment]
Will take a look at this today

**Comment by AustinGitHub** [comment]
![Screenshot 2024-06-12 at 12 52 34 PM](https://github.com/carbon-design-system/ibm-products/assets/10100397/e2449eb0-3833-4855-b68f-364487d49f17)

Issue is that the selection did change but the comparison in the code is incorrect

**Comment by AustinGitHub** [comment]
For this issue "Selection mouse move gets stuck when remove onclick"
This is because the `onMouseUp` event seems to only be recorded if we do mouse up on the cell that we initially clicked down on. When we click and drag then do mouse up, it does not get recorded. Debugging this part of this issue.

**Comment by elycheea** [comment]
@all-contributors add @AustinGitHub for code
