### ISSUE TITLE
Datagrid: column customiztion when header is React component

### ISSUE THREAD

**Issue by mariusd-ibm** [carbon-design-system/ibm-products#5268]
### Package

Carbon for IBM Products

### Description

I have one of the columns in datagrid as ReactElement e.g.
```
{
    id: 'info',
    Header: <ToggleTip />
}
```

I expect to have column listed in column customization. However it is not.

### Component(s) impacted

Datagrid
<img width="515" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/92723202/380de2bd-2ebc-476a-b414-160bbf2e647b">
https://carbon-for-ibm-products.netlify.app/?path=/docs/ibm-products-components-datagrid-columncustomization--docs

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v2.34.0

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

Turbonomic

### CodeSandbox or Stackblitz example

https://carbon-for-ibm-products.netlify.app/?path=/docs/ibm-products-components-datagrid-columncustomization--docs

### Steps to reproduce the issue (if applicable)

1. create datagrid where one of the columns header is react component
2. open column customization

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by mariusd-ibm** [comment]
related thing is happening with table cells and header, on hover if value is not plain text it shows _[object Object]_
<img width="146" alt="image" src="https://github.com/carbon-design-system/ibm-products/assets/92723202/901ea8dc-ae6c-49d0-bef5-acac1a889fdb">
I would expect ability to control on hover text

**Comment by nowyDEV** [comment]
It's because some components provided to `Header` field might lack `children` prop.
They are filtered-out from the draggable list.

https://github.com/carbon-design-system/ibm-products/blob/de9c862ad77ef955ee7b57a113be4e832d2dca22/packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/DraggableItemsList.js#L47
https://github.com/carbon-design-system/ibm-products/blob/main/packages/ibm-products/src/global/js/utils/getNodeTextContent.js#L38

As a workaround, it's possible to turn off TypeScript error and provide children prop to React element anyways (even though it does not use/support it).

Before:

```tsx
        return {
            id: 'unparkable',
            Header: (
                <SomeComponent
                    someProp={{
                        children: <Information size={20} aria-label='Info' />,
                        label: '',
                    }}
                    otherProp='bottom'
                />
            ),
```

After:

```tsx
        return {
            id: 'unparkable',
            Header: (
                // @ts-expect-error - providing `children` prop is required to make column customization work
                <SomeComponent
                    someProp={{
                        children: <Information size={20} aria-label='Info' />,
                        label: '',
                    }}
                    otherProp='bottom'
                >
                    Label
                </TurboToggleTip>
            ),
```

**Comment by ljcarot** [comment]
We've been investigating [TanStack ](https://tanstack.com/table/latest)[Table](https://tanstack.com/table/latest), a third-party, open-source offering, which provides extensive data table capabilities surpassing what our Carbon Datagrid offers. It provides much more flexibility and customization. TanStack Table is headless which means it can easily be added alongside Datagrid component in your product or application. The benefits of more flexibility for product teams and less maintenance for Carbon makes it a win win. Lastly, it is available in multiple frameworks including [React](https://github.com/carbon-design-system/tanstack-carbon/tree/main/react#readme) and [Web Component](https://github.com/carbon-design-system/tanstack-carbon/tree/main/web-components#readme) so it provides an option to non-React product teams.

For these reasons, we have decided to transition from building our own custom table component to using an example-based approach with TanStack Table. Datagrid will still exist in our library for existing teams but we are announcing the deprecation* of the Datagrid component in v2.54.0 release so teams can begin to work through the transition. Details about how to use both Datagrid and TanStack together can be found [here](https://github.com/carbon-design-system/tanstack-carbon/tree/main). 

*Deprecation means that no new features will be added however sev 1 and sev 2 bugs will be supported.
