### ISSUE TITLE
[DataGrids]: Inline Edit code examples are not working on StackBlitz and Code Sandbox

### ISSUE THREAD

**Issue by AustinGitHub** [carbon-design-system/ibm-products#5273]
### Package

Carbon for IBM Products

### Description

![Screenshot 2024-05-20 at 4 02 50 PM](https://github.com/carbon-design-system/ibm-products/assets/10100397/5c1f1508-d4d1-4507-9cba-b734b4adad8e)

https://carbon-for-ibm-products.netlify.app/?path=/docs/ibm-products-components-datagrid-editablecell--docs

### Component(s) impacted

DataGrids

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.38.0

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

IBM

### CodeSandbox or Stackblitz example

https://stackblitz.com/github/carbon-design-system/ibm-products/tree/main/examples/carbon-for-ibm-products/EditableCell?file=src%2FExample%2FExample.jsx

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by annawen1** [comment]
Hi @AustinGitHub we currently only have stackblitz and codesandbox examples for just the main component (DataGrid) and not the extensions (editable cell)

**Comment by AustinGitHub** [comment]
But they are listed on the docs page for editable cell, if they don't work. Shouldn't that be removed?

**Comment by AustinGitHub** [comment]
![Screenshot 2024-05-22 at 8 03 09 AM](https://github.com/carbon-design-system/ibm-products/assets/10100397/5e64a124-79bf-4c87-ae30-e3fffecdba99)

**Comment by matthewgallo** [comment]
Ahh, yes. We were wondering where those links were coming from, thanks for the screenshot. We'll either add examples for them or remove them from the docs for the time being.

**Comment by AustinGitHub** [comment]
@matthewgallo do you know when that change is going to happen? I see this is still the case for the story book, so unsure why the issue was closed. Thanks!

**Comment by mstudio** [comment]
This is also an issue with https://ibm-products.carbondesignsystem.com/?path=/docs/ibm-products-components-datagrid-expandablerow--docs#coded-examples

Related issue: https://github.com/carbon-design-system/ibm-products/issues/5524
