### ISSUE TITLE
Styling broken for ProductiveCard in v2.39.0

### ISSUE THREAD

**Issue by jonrober-80** [carbon-design-system/ibm-products#5281]
### Package

Carbon for IBM Products

### Description

They styling for the `ProductiveCard` component looks like it has broken between v2.38.0 and v2.39.0 (possibly because of this PR? - https://github.com/carbon-design-system/ibm-products/pull/5054/files)

Screen shot of the ProductiveCard using v2.38.0 (working as expected)
![image](https://github.com/carbon-design-system/ibm-products/assets/40994463/f2cd57f1-d7a3-4a30-8393-adb49feb200e)

Screen shot of the ProductiveCard using v2.39.0 (styling is broken)
![image](https://github.com/carbon-design-system/ibm-products/assets/40994463/797c0181-8c9f-4a82-af3b-940f7705e033)

I believe that you can also see the problem when looking at the storybook for `ibm-products`

https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-cards-productivecard--with-caption&globals=viewport:basic

![image](https://github.com/carbon-design-system/ibm-products/assets/40994463/ae299326-5381-4fe7-a68c-46aeb79de67b)

### Component(s) impacted

ProductiveCard

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v2.39.0

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

IBM App Connect

### CodeSandbox or Stackblitz example

https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-cards-productivecard--with-caption&globals=viewport:basic

### Steps to reproduce the issue (if applicable)

Navigate to the ibm-products storybook (https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-cards-productivecard--with-caption&globals=viewport:basic) and view the `ProductiveCard` component

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by davidmenendez** [comment]
thank you for pointing this out! i've identified the bug and will push a fix ASAP
