### ISSUE TITLE
Add Figma and GitHub link

### ISSUE THREAD

**Issue by aubrey-oneal** [carbon-design-system/ibm-products#5293]
<img width="247" alt="Screenshot 2024-06-12 at 10 16 23 AM" src="https://github.com/carbon-design-system/ibm-products/assets/47198241/c913dc1f-fbca-4b2c-adb1-a01fa8586961">

Acceptance criteria:
- [x] A link to the all themes Carbon for IBM Products Figma kit (v11) is added to the bottom of the LHN
- [x] Link to Products GitHub

**Comment by ljcarot** [comment]
Wording 'Figma kit (v11)'
