### ISSUE TITLE
AI Storybook Docs: CreateSidePanel

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/ibm-products#5307]
#### Acceptance Criteria

Follow similar approach as seen in [Datagrid slug docs](https://carbon-for-ibm-products.netlify.app/?path=/docs/ibm-products-components-datagrid-ailabel--docs).

```[tasklist]
### Tasks
- [ ] Include example usage within CreateSidePanel storybook docs page
```

**Comment by elycheea** [comment]
Closed by #6468
