### ISSUE TITLE
AI Storybook Docs: SidePanel

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/ibm-products#5308]
#### Acceptance Criteria

Follow similar approach as seen in [Datagrid slug docs](https://carbon-for-ibm-products.netlify.app/?path=/docs/ibm-products-components-datagrid-ailabel--docs).

```[tasklist]
### Tasks
- [ ] Include example usage within SidePanel storybook docs page
- [ ] Add docs section
```

**Comment by ljcarot** [comment]
@IgnacioBecerra Just checking in on your progress with this issue.  thx!
