### ISSUE TITLE
[Bug]: FullPageError has keys mismatch in version 2.35.0 and 2.39.0

### ISSUE THREAD

**Issue by akshat-rastogi** [carbon-design-system/ibm-products#5326]
### Package

Carbon for IBM Products

### Description

The issue causes the page not to render the label because the `label` was `errorLabel` in the previous version. This causes the page to not show any title when label is passed.  Documentation highlights only the latest version and not v2.35.0. 

### Component(s) impacted

FullPageError

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.35.0

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Product/offering

@carbon/ibm-products

### CodeSandbox or Stackblitz example

https://carbon-for-ibm-products.netlify.app/?path=/docs/ibm-products-patterns-full-page-error-fullpageerror--docs

### Steps to reproduce the issue (if applicable)

Switch to version 2.35.0 and the label prop doesn't work.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by elycheea** [comment]
@akshat-rastogi Thanks for reaching out! Since the `FullPageError` was and is still experimental at the time of this writing, this is not a breaking change yet. Please update the prop in your code to use `label` instead of `errorLabel`.
