### ISSUE TITLE
DataGrid : Option to disable/enable  datagrid tooltip 

### ISSUE THREAD

**Issue by marinamas** [carbon-design-system/ibm-products#5351]
### Package

Carbon for IBM Products

### Description

By default the DataGrid adds  tooltip for the table header and table body.
In situations when the column content is not a plain text but a JSX element , the tooltip displays incorrect value 

We can either
- Disable the tooltip for the required column or Provide a custom string whenever a cell value is a JSX element /component

<img width="593" alt="Screenshot 2024-05-28 at 8 14 34 PM" src="https://github.com/carbon-design-system/ibm-products/assets/80206173/4ec81804-1432-4570-944a-d06e2e4c6b48">

### Component(s) impacted

DataGrid 

### Browser

Chrome, Safari, Microsoft Edge

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

"@carbon/ibm-products": "2.40.0",

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

Infrastructure 

### CodeSandbox or Stackblitz example

https://codesandbox.io/p/sandbox/datagrid-clear-fliter-issue-forked-plpt64?file=%2Fsrc%2FExample.js%3A161%2C7

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by davidmenendez** [comment]
issue has been resolved. please keep an eye out for our latest release and let us know if anything else comes up.
