### ISSUE TITLE
Add floating-ui to `@carbon/ibm-products` TagSet

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#5354]
```[tasklist]
### Tasks
- [x] Enable `autoAlign` prop with `Popover` component in `TagSetOverflow` to confirm floating-ui
- [x] Update stories to show the functionality + docs
```

**Comment by davidmenendez** [comment]
i talk about it in greater detail in #5406 but basically i don't think the current form of `TagSet` will support floating UI. i will assist sinta with implementing it in `TagOverflow`

**Comment by elycheea** [comment]
@sstrubberg @ljcarot Based on David’s investigation, I’m going to close this as not planned since `TagOverflow` was already intended to replace the `TagSet` in time (as a component v. utility is still up for discussion).
