### ISSUE TITLE
Component Accessibility Status: Add keyboard navigation AVT tests for each component

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/ibm-products#5362]
REF https://github.com/carbon-design-system/carbon/issues/14522

## AVT Audit

We have 2 different types of list here:
1. High priority components that **need or already have** Keyboard Nav AVT
1. Low priority components that **need or already have** Keyboard Nav AVT
1. Components that **_do not need_** Keyboard Nav AVT

We can tackle the high priority components first, and leave the low priority ones to tackle afterwards.

```[tasklist]
### High Priority
- [ ] Add a draft title or issue reference here
```

```[tasklist]
### Low Priority
- [ ] Add a draft title or issue reference here
```

**Comment by elycheea** [comment]
Closing this since we expect to include these in the complex states work.
