### ISSUE TITLE
[Feature Request]: PageHeader component to support dropdown menus

### ISSUE THREAD

**Issue by joker23** [carbon-design-system/ibm-products#5364]
### The problem

Originally, the pageheader component supported having dropdown menus; however, after the typescript migration, that is no longer the case. This enhancement request for that capability to be implemented in typescript. This is used right now in our product:

![image](https://github.com/carbon-design-system/ibm-products/assets/2494686/c6c78466-c618-4047-9651-bdc75414d6db)

### The solution

We should have feature parity with the original pageheader (or provide a way to reference the original page header implementation while the typescript implementation is no fully compatible with the original design.

### Links to other materials

Relates to https://github.com/carbon-design-system/ibm-products/issues/4632

### Owner/main maintainer(s)

?

### Business priority

High Priority = pressing release

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by elycheea** [comment]
Tagging this also to the more composable page header discussion in #4632. Keeping this in triage until we have more chance to discuss this one with @ljcarot more.

While we could wait until the composable page header work comes about, it may be worth discussing if we want to support additional types in the meantime to unblock teams or if there are other implications that we’re not ready to enable without more design consideration.

**Comment by matthewgallo** [comment]
Hey @joker23, can you join an [upcoming office hours](https://ec.yourlearning.ibm.com/w3/join/event/10408799) to give some more detail here?
