### ISSUE TITLE
[Feature Request]: Datagrid doesn't have a way to enable/disable inline edit per cell for specific use cases

### ISSUE THREAD

**Issue by AustinGitHub** [carbon-design-system/ibm-products#5379]
### The problem

How we originally have it 

https://github.com/carbon-design-system/ibm-products/assets/10100397/cfa8c8eb-8c08-441b-b430-56a5c3ec2c98

But with data grid, I am not seeing a way where we can say that a specific cell in terms of row to column can be editable or not. This is crucial to our implementation and there isn't a way to do this for DataGrids that I am able to see available

https://github.com/carbon-design-system/ibm-products/assets/10100397/b08ebc84-4713-43b5-b7e3-8bee7124ffa5

### The solution

I think the `data` needs to be segmented to be an object such as 

```
[
    {
        "headerName": "FIRST_NAME",
        "length": 0,
        "isNullable": false,
        "dataType": "VARCHAR",
        "extended": false,
        "scale": undefined,
    },
  ]
 ```
 
 To be something like this 
 ```
[
     { "headerName": "FIRST_NAME", isEditable: true },
     { "length": 0, isEditable: true },
     { "isNullable": false, isEditable: true },
     { "dataType": "VARCHAR", isEditable: true },
     { "extended": false, isEditable: true },
     { "scale": undefined, isEditable: false },
  ]
 ```

### Owner/main maintainer(s)

IBM

### Product/offering

DataStage

### Business priority

High Priority = pressing release

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by AustinGitHub** [comment]
@matthewgallo can you make a comment on this and let me know if this is possible to do as of now or needs to be worked on? Because this will require a bit of a refactor on how datagrids is done and would like to get a change like this in sooner than later. Need feedback on this and ETA if someone plans to work on it, otherwise I can take up this change as this is high priority for us. Thanks!

**Comment by matthewgallo** [comment]
Hey @AustinGitHub, you're right that this is something Datagrid is not currently capable. I'll take a look at this and follow up in this issue!

**Comment by AustinGitHub** [comment]
Thank you!
