### ISSUE TITLE
[Datagrid column customization]: The selected columns is incorrect (displays negative values)

### ISSUE THREAD

**Issue by kevinkowa** [carbon-design-system/ibm-products#5402]
### Package

Carbon for IBM Products

### Description

https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-columncustomization--column-customization-usage-story

If you click select all, then unselect all we get a negative number on the modal title for number of selected columns.
![Screenshot 2024-06-04 at 8 46 06 AM](https://github.com/carbon-design-system/ibm-products/assets/15097482/e16a1801-fcfd-4b1d-92cf-c239458ca38e)

Expected:
To show the correct number of selected columns

### Component(s) impacted

https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-columncustomization--column-customization-usage-story

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.39.0

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Product/offering

FTM

### CodeSandbox or Stackblitz example

-

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by SeonyuK** [comment]
@devadula-nandan 
The original issue has been fixed so now the disabled checkbox remains checked. However, the disabled columns are not counted in the selection value.
![Screenshot 2024-06-18 at 8 57 17 AM](https://github.com/carbon-design-system/ibm-products/assets/144151347/612a8365-845c-4ba7-9697-327503b1b5b6)

@elycheea @matthewgallo should I open the issue separate from this?

**Comment by devadula-nandan** [comment]
hi @SeonyuK ,
i could see the count being right in the storybook, could you reproduce this in stackblitz if possible? 
<img width="2168" alt="Screenshot 2024-06-19 at 8 38 50 PM" src="https://github.com/carbon-design-system/ibm-products/assets/47176249/309e36e7-a206-4bd7-8796-5010ae96a6bb">

**Comment by devadula-nandan** [comment]
hey @SeonyuK 
can we get a reproduction of this on stackblitz? as we are not noticing this in our storybook.
<img width="1261" alt="Screenshot 2024-06-19 at 9 09 07 PM" src="https://github.com/carbon-design-system/ibm-products/assets/47176249/fdd04ce4-bfb8-49c5-87dc-67b1e2e4dfaa">
<img width="1261" alt="Screenshot 2024-06-19 at 9 09 35 PM" src="https://github.com/carbon-design-system/ibm-products/assets/47176249/090975a6-383e-4086-b6a8-3e811ec2a716">
