### ISSUE TITLE
Condition builder: Usage tab guidance continuation

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-products#5426]
follow on from #4900 

### Resources
- [Usage template](https://www.figma.com/design/XQqHxu38CiY3Vx1iHdafIa/Image-production-guidelines?m=auto&node-id=3118-7793&t=mKfzTrPNU44l8UW6-1) in Figma

### Notes
- Consider referencing the [Data table](https://carbondesignsystem.com/components/data-table/usage/) and [Tree view](https://carbondesignsystem.com/components/tree-view/usage/) usage docs to see how we've formatted complex components with variants
- Sync with Jeannie and Lauren
- Naming consider: simple and tree? 

### Deliverable
- [ ] Draft of the Conditions builder usage docs

**Comment by My-Money29** [comment]
I've been focusing solely on this task.
Considering I'm out on holiday most of next week, I imagine the effort is at least another full week of work and sync on this task.
