### ISSUE TITLE
[Bug]: deselects everything include disabled column on Datagrid configuration modal

### ISSUE THREAD

**Issue by SeonyuK** [carbon-design-system/ibm-products#5428]
### Package

Carbon for IBM Products

### Description

When the user uses Select all to configure the Datagrid columns, it deselects everything including the disabled column.

### Component(s) impacted

![Screenshot 2024-06-04 at 2 08 08 PM](https://github.com/carbon-design-system/ibm-products/assets/144151347/6186e381-dd2c-43b6-a93e-e29a4e538dd9)

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.36.0

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

QRadar suit

### CodeSandbox or Stackblitz example

Storybook

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by annawen1** [comment]
Adding screen recording here as well

https://github.com/carbon-design-system/ibm-products/assets/54281166/da905014-2a88-4621-9693-a1b244769467
