### ISSUE TITLE
[Multiaddselect]: admin/editor role can open the dropdown

### ISSUE THREAD

**Issue by ariellalgilmore** [carbon-design-system/ibm-products#5450]
### Package

Carbon for IBM Products

### Description

The "role" (ie admin, editor, etc.) dropdown can be open/closed when clicking on the text "Role". Seems like only the dropdown itself should be able to do this.

https://github.com/carbon-design-system/ibm-products/assets/20210594/419b5cd4-e0b4-46c3-8da1-d1f672a82b73

### Component(s) impacted

multiaddselect

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.41.0

### Severity

Severity 4 = The problem is not visible to or noticeable to an average user. Affects minor functionality, no workaround needed.

### Product/offering

n/a

### CodeSandbox or Stackblitz example

https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-patterns-add-and-select-multiaddselect--with-modifiers&globals=viewport:basic

### Steps to reproduce the issue (if applicable)

go to: https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-patterns-add-and-select-multiaddselect--with-modifiers&globals=viewport:basic

click on one of the checkbox "items" and then click on the "role" next to the dropdown

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by davidmenendez** [comment]
after some investigation i have confirmed that this is actually a problem with `Dropdown` within `Tearsheet`. here's a stackblitz replicating the behavior https://stackblitz.com/edit/github-csnnba-wu3lci?file=src%2FExample%2FExample.jsx

**Comment by davidmenendez** [comment]
further investigation shows this problem persists through the carbon `ComposedModal`. i will have to do some additional debugging and submit my fix to core.

you can see the problem persisting in their storybook https://react.carbondesignsystem.com/?path=/story/components-composedmodal--with-scrolling-content

**Comment by davidmenendez** [comment]
I've traced the bug back to core and will be submitting a fix there. issue for reference https://github.com/carbon-design-system/carbon/issues/16846

**Comment by davidmenendez** [comment]
just waiting on the PR in carbon to be merged https://github.com/carbon-design-system/carbon/pull/16847

**Comment by davidmenendez** [comment]
https://github.com/carbon-design-system/carbon/pull/16847 has been merged. fix should be included in the next carbon release. closing issue 🎉
