### ISSUE TITLE
Unable to use data grid using 2.42.0

### ISSUE THREAD

**Issue by tom-youd** [carbon-design-system/ibm-products#5468]
### Package

Carbon for IBM Products

### Description

I've updated to use the latest `Ibm-products` package (2.42.0) which was published 5/6 hours ago.
I get this on screen and with unit tests too
![Screenshot 2024-06-11 at 11 11 59](https://github.com/carbon-design-system/ibm-products/assets/56865994/8f9bc083-811b-4846-aac1-8569ad006bab)

### Component(s) impacted

Datagrid - possibly others which use the feature flag changes

### Browser

Chrome, Safari, Firefox

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.42.0

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Product/offering

CP4I

### CodeSandbox or Stackblitz example

n/a

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by gssspillai** [comment]
@matthewgallo / @elycheea 
Can we reopen this issue as we're still encountering the following error with `"version": "2.70.1"` of `@carbon/ibm-products`:

`Error: Unable to find a feature flag with the name: `enableSidepanelResizer``

We're not explicitly using any feature flag for the `SidePanel` component, so this may be coming from an internal usage or dependency.

Could you clarify whether this flag needs to be defined manually, or if it's expected to be bundled with the library?
