### ISSUE TITLE
[Feature Request]: Ability to hide the select checkbox of nested rows when using useNestedRows along with useSelectRows

### ISSUE THREAD

**Issue by rcsatheeshkumar** [carbon-design-system/ibm-products#5478]
### The problem

Please provide the ability to hide the select checkbox of nested rows when using useNestedRows along with useSelectRows. Currently when we select a parent row with nested rows, all nested rows gets selected. I would like to have the ability to not render the checkbox for nested rows at all so that the only parent row could be selected. 
![image](https://github.com/carbon-design-system/ibm-products/assets/17987392/5525ec19-2ac6-4f88-8d72-4c62d2a382a8)

### The solution

![image](https://github.com/carbon-design-system/ibm-products/assets/17987392/989be826-a5db-4785-8fb7-a061775a45e2)

### Owner/main maintainer(s)

IBM

### Product/offering

FTM

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by oliviaflory** [comment]
@rcsatheeshkumar Would you be able to provide more clarity around this feature request? 
1. Could you clarify your product name for us? 
2. Your solution doesn't show the parent selected, so we'd like to understand what happens there.
3. You could consider attending DSAG or Carbon Office Hours to show us some of your ideas too

**Comment by rcsatheeshkumar** [comment]
> @rcsatheeshkumar Would you be able to provide more clarity around this feature request?
> 
> 1. Could you clarify your product name for us?
> 2. Your solution doesn't show the parent selected, so we'd like to understand what happens there.
> 3. You could consider attending [DSAG ](https://ec.yourlearning.ibm.com/w3/meeting/10412251)or[ Carbon Design Office Hours](https://ec.yourlearning.ibm.com/w3/series/10289694?layout=grid) to show us some of your ideas too (_internal to IBM only_)

1. Financial Transaction Manager
2. When a checkbox is checked on a parent row, only that row (may be with nested rows as it children) would be available as `selectedData` for batch actions. 
3. Sure, I'll explore those options, if more clarity is required from my end.

**Comment by oliviaflory** [comment]
@rcsatheeshkumar 

I'm trying to understand the user flow a bit more. Your solution example doesn't show any row selected

1. Can a child row be selected at any time? Like the below example:
2. If yes, I think it may be unusual to show the checkboxes in some scenarios and hide the checkboxes in others. Would disabling the child rows work?




When a parent row is selected, the nested children cannot be de-selected

**Comment by oliviaflory** [comment]
@rcsatheeshkumar I am trying to understand the user flow a bit better, your solution example doesn't show any row selected.

1. Can a child row be selected at any point? Like the example below

![Image](https://github.com/carbon-design-system/ibm-products/assets/45692622/7faf33d9-d44b-4343-a858-2b8c7c696885)


2. If a child row can be selected at other times, it may be confusing to show the checkboxes at some points and hide them in others. Would disabling the checkboxes of child rows work like the below? It achieve the same thing and should be possible now:

![Image](https://github.com/carbon-design-system/ibm-products/assets/45692622/31469eef-6ae1-4919-bf37-bf8fb763a883)

**Comment by rcsatheeshkumar** [comment]
@oliviaflory 
1. In my use case, child rows could not be selected at point in time. 
2. We already have reached this state of disabling the checkbox in child rows. However, it is not aesthetically good. So, we would like to hide those checkboxes.

**Comment by oliviaflory** [comment]
@rcsatheeshkumar Thanks for clarifying.

There is some concern amongst the design team about removing the checkboxes of the children in evaluating this enhancement request. Would you and your designers be willing to come to one of our Carbon Design Office hours to discuss this further? [Your Learning link](https://ec.yourlearning.ibm.com/w3/event/10408782) and the agenda to sign up is in the Your Learning event

- Removing the checkbox entirely is surfacing some UX questions, will the user understand the children are part of the group and cannot be un-selected
- We would love to understand the UX a bit better with real content, what is the user doing in this usecase?
- Secondarily, the alignment is not very good when the checkbox is removed
- Have you considered a read-only checkbox for the children? The documentation for [read only states](https://carbondesignsystem.com/patterns/read-only-states-pattern/) can be found here and I've provided an example

<img width="840" alt="Screenshot 2024-07-08 at 11 23 13 AM" src="https://github.com/carbon-design-system/ibm-products/assets/45692622/da2fb580-9059-437e-92de-15726f0bab38">

**Comment by oliviaflory** [comment]
@rcsatheeshkumar we will be closing the issue for now, if you'd like to talk with our design team and our Office Hours times don't work for you please let us know
