### ISSUE TITLE
List all components being migrated to Carbon (Menu and combo button, status icon)

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/ibm-products#5490]
List all components needing to move to Core Figma kit in Box/AIrtable with associated date to unblock #5051

**Comment by ljcarot** [comment]
List created and tracked in airtable here -> https://airtable.com/appY30x3q9FcdIcL1/shr3i0dwaWXcRwIn9/tbl81O5yRLA4gGh1T
