### ISSUE TITLE
Add floating-ui to ButtonSetWithOverflow

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#5491]
At smaller screen sizes (use `containerWidth` in Storybook to demonstrate), ButtonSetWithOverflow collapses to use MenuButton.

Verify that Carbon version with MenuButton floating UI is updated in our library. Blocked until `@carbon/react` adds support for floating ui to `OverflowMenu`.

```[tasklist]
### Tasks
- [ ] Enable `enable-v12-overflowmenu` feature flag to ButtonSetWithOverflow overflow menus
- [ ] Update tests if applicable
```

**Comment by elycheea** [comment]
floating-ui was been added to the new OverflowMenu. Will open an issue for adopting the v12 overflow menu.

**Comment by amal-k-joy** [comment]
Closing this as not planned.
As we analysed, `ButtonSetWithOverflow` component uses carbon `MenuButton` rather than `Overflowmenu` and 
`enable-v12-overflowmenu`  feature flag is not available for `MenuButton`. 
Also we can explore more and adopt floating UI in the new PageHeader V2.
