### ISSUE TITLE
[Dataspreadsheets]: (Performance) When we have 1 million rows, env crashes

### ISSUE THREAD

**Issue by AustinGitHub** [carbon-design-system/ibm-products#5502]
### Package

Carbon for IBM Products

### Description

<img width="811" alt="Screenshot 2024-06-13 at 12 57 38 PM" src="https://github.com/carbon-design-system/ibm-products/assets/10100397/70ddae0b-d8ea-474a-8a1e-8834b8be8166">

The render isn't so much the issue I am seeing, but it looks like the calculations are not able to do numbers these high. Because it does a scroll loading on UI I noticed, but some loops I think might need to be adjusted. There should be way to fix this. 

### Component(s) impacted

Data spreadsheets

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.42

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

IBM

### CodeSandbox or Stackblitz example

N/A

### Steps to reproduce the issue (if applicable)

Pull the code and change the generate Data rows to 1 million

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by AustinGitHub** [comment]
Making note, users for the product we are working on may have 1 million rows of data for whatever reason. I asked our UX team on how we should handle this in meantime.

**Comment by kennylam** [comment]
Hi @AustinGitHub! Yes 1 million rows is an incredible amount of data. Even Excel caps out at that amount of rows. Perhaps breaking up the data into more manageable chunks would be a better solution?

**Comment by AustinGitHub** [comment]
Not sure yet, I haven't had time to take further look. Will try next week

**Comment by elycheea** [comment]
@AustinGitHub haven’t heard back to hopefully means you were able to resolve this on your end.

**Comment by AustinGitHub** [comment]
Sorry I was on vacation, for now this is fine to close. Haven't been able to look into it. I am thinking if we can't resolve it on our end there might be a way to resolve it on carbon products end but due to some time constraints not sure if I will be able to get to it soon. I have this noted though on my side as something we need to look into for our project. Thanks!
