### ISSUE TITLE
Create Guidelines section and move pages

### ISSUE THREAD

**Issue by aubrey-oneal** [carbon-design-system/ibm-products#5503]
Depends on #5475 

When this issue is finished, the Guidelines section should match the [final draft in this IA Figma](https://www.figma.com/design/gmlnTUu8PQtgJoiHnkgzXd/IBM-Product-PAL-IA?node-id=0-1&t=zDFAUFYWxtd8s1DC-0). This issue is blocked until we have tree nav. 

Tasks
- [x] Create a submenu after Patterns called `Guidelines` 
- [x] Create a page called `Accessibility`. Add content from issue #5504 , which merges content from Keyboard tabs and Keyboard guidelines and adds additional accessibility guideline.
- [ ] ~Rename the `AI design guidance` submenu to `Artificial intelligence` and move the section and its accompanying pages under Guidelines. Requires tree nav.~
- [x] Rename the `Content guidance` submenu to `Content` and move the section and its accompanying pages under Guidelines. Requires tree nav.
- [x] Move Emails page under Guidelines
- [ ] Rename `IBM Products layouts` to `Layouts` and move under Guidelines
- [x] Rename `Try and buy routes to market` to `Routes to market` and move under Guidelines

![Image](https://github.com/carbon-design-system/ibm-products/assets/47198241/0852e664-8650-46d0-acc7-4ba5b1e4038b)

**Comment by oliviaflory** [comment]
This issue was addressed in #5475 and https://github.com/carbon-design-system/carbon-for-products-website/pull/111
