### ISSUE TITLE
[Datagrid]: Hidden columns are included in search results.

### ISSUE THREAD

**Issue by filipmadejIBM** [carbon-design-system/ibm-products#5509]
### Package

Carbon for IBM Products

### Description

Hidden columns are included in the search.

### Component(s) impacted

Datagrid

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.39.0

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Product/offering

na

### CodeSandbox or Stackblitz example

https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-columncustomization--column-customization-usage-story&globals=viewport:basic

### Steps to reproduce the issue (if applicable)

Go here https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-columncustomization--column-customization-usage-story&globals=viewport:basic

1. Unselect all columns in custome cilumn view and leave rowID as visible.
2. Type "apples" in the search box.
3. One item appears in the search.

I would expect that hidden columns are not included in the search

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by filipmadejIBM** [comment]
Any ETA on this ?

**Comment by szymonbrandys** [comment]
When can I expect it to be fixed and delivered?

**Comment by Xirax** [comment]
Any updates / changes?

**Comment by jakubkloc** [comment]
Its  available in version 2.50.0?
