### ISSUE TITLE
DataGrid uses index as ID which causes issues when table has dynamic data

### ISSUE THREAD

**Issue by marinamas** [carbon-design-system/ibm-products#5510]
### Package

Carbon for IBM Products

### Description

- DataGrid uses index as ID which works fine when the row data is fixed.
- In scenarios when  a new record needs to be added dynamically to the table and if already a row is been selected , addition of new row retains the selection at the same index but the selected row data will be incorrect .

We can use row.originial.id as unique identifier for row click actions . But incase of dynamic table , we wont have a control to pass row.originial.id as unique identifier 

### Component(s) impacted

DataGrid

<img width="1728" alt="Screenshot 2024-06-14 at 7 20 34 PM" src="https://github.com/carbon-design-system/ibm-products/assets/80206173/c29f640f-ed0b-4dec-ab87-04332d995fef">

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

"@carbon/ibm-products": "2.40.0",

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Product/offering

Infrastructure 

### CodeSandbox or Stackblitz example

https://codesandbox.io/p/sandbox/datagridfilter-forked-ygvl56?file=%2Fsrc%2FExample.js%3A169%2C36

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by matthewgallo** [comment]
@marinamas this can be fixed by providing the `getRowId` property to the `useDatgagrid` hook. It will then be called when rows are selected to use the provided id rather than the id assigned by react-table.

```
getRowId: row => row.id,
```
