### ISSUE TITLE
[DataGrid]: DataGrid ExpandedRow examples are not working on StackBlitz and Code Sandbox

### ISSUE THREAD

**Issue by mstudio** [carbon-design-system/ibm-products#5524]
### Package

Carbon for IBM Products

### Description

404 errors for StackBlitz and CodeSandbox links here:
https://stackblitz.com/edit/github-oqgtfd?file=src%2FExample%2FExample.jsx,package.json

### Component(s) impacted

DataGrid

### Browser

Chrome, Firefox

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v2.43.0

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

IBM CCX

### CodeSandbox or Stackblitz example

https://stackblitz.com/github/carbon-design-system/ibm-products/tree/main/examples/carbon-for-ibm-products/ExpandableRow?file=src%2FExample%2FExample.jsx

### Steps to reproduce the issue (if applicable)

Visit links above

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by matthewgallo** [comment]
This is now resolved with @annawen1's updates [here](https://github.com/carbon-design-system/ibm-products/pull/5523).
