### ISSUE TITLE
Create image for About>Overview Page

### ISSUE THREAD

**Issue by aubrey-oneal** [carbon-design-system/ibm-products#5532]
See the [Figma](https://www.figma.com/design/lDM3X9hSrOE6vKLEf1CxbX/v11-IBM-Product-PAL-Website?node-id=2101-2939&t=S0sXNlmUSAySINYJ-0) for where for the About section. 

Tasks:
- [x] Create an image that illustrates which product offering use Carbon for IBM Products (App Modernization, Data & AI, IT Automation, Security, Sustainability Software, Infrastructure, and Finance & Operations)
- [ ] Send it to Aubrey to add to the v11 site
- [ ] Send it to Stephanie Cree to update the Cloud site 

This is the original image I found on the Cloud site that we can work off of.
<img width="759" alt="Screenshot 2024-06-18 at 9 40 18 AM" src="https://github.com/carbon-design-system/ibm-products/assets/47198241/b1c37fb2-0912-4ed1-830f-70e4eb81feba">

**Comment by ljcarot** [comment]
since the business pillar names change around can we keep to something more generic?

**Comment by jeanservaas** [comment]
[Carbon_ecosystem.ai.zip](https://github.com/user-attachments/files/16697556/Carbon_ecosystem.ai.zip)
![Carbon_ecosystem-07](https://github.com/user-attachments/assets/50acf2cd-9786-4c57-97f0-2024d48664f2)
