### ISSUE TITLE
[Datagrid]: using useNestedRows and DatagridPagination results in rows broken up into different pages

### ISSUE THREAD

**Issue by gkang999** [carbon-design-system/ibm-products#5533]
### Package

Carbon for IBM Products

### Description

When trying to expand a parent row with nested children rows, the nested rows are rendered on the next page(s) if the total row count (parent + nested children) is greater than the current page's item count limit. This could break up nested rows across multiple pages depending on how many nested rows there are. I would expect the nested rows to be rendered on the same page as the parent row.

### Component(s) impacted

Datagrid

Screenshots of issue:
![image](https://github.com/carbon-design-system/ibm-products/assets/80872747/ed015ab8-31dd-4722-ad76-c99b1d5273b5)
![image](https://github.com/carbon-design-system/ibm-products/assets/80872747/bcc6b4dd-3e51-4bc1-9250-cb9082ad15b5)

For reference (how it should look):
![image](https://github.com/carbon-design-system/ibm-products/assets/80872747/8b427f16-7be6-4b91-b8f9-173caf8c5661)

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

1.72.1

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

Global Cloud UI

### CodeSandbox or Stackblitz example

https://codesandbox.io/p/devbox/ancient-thunder-rmyxjg

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by elycheea** [comment]
@gkang999 shared this via the Slack support channel. Tagging it as an enhancement currently but also unsure if this is a limitation of `react-table` v7. Think we can use this issue to track and investigate whether we’re able to address this or if it’ll require update to `react-table` v8 (which would put this in the Icebox). 😓

**Comment by elycheea** [comment]
@gkang999 The original design guidance recommends against using items per page with nested rows.
https://pages.github.ibm.com/cdai-design/pal/components/data-table/nested-rows/usage#behaviors
