### ISSUE TITLE
Condotion Builder: Continue work on Usage page

### ISSUE THREAD

**Issue by My-Money29** [carbon-design-system/ibm-products#5542]
follow on from #4900 
follow on from #5426

### Resources
- [Usage template](https://www.figma.com/design/XQqHxu38CiY3Vx1iHdafIa/Image-production-guidelines?m=auto&node-id=3118-7793&t=mKfzTrPNU44l8UW6-1) in Figma

### Current Usage page (ver 0.4)
[Usage guidance](https://www.figma.com/design/BRk3lEQVpJ8jn6jj7UO4mK/Condition-Builder---Usage-Guidance---Carbon-team-review?node-id=2421-7313&t=9HcrBcJSmwRGmz47-1) in Figma

### Notes

- Sync with Tracy on the new version
- Variants naming consider: Non-Hierarchical, Hierarchical  

### Deliverable
- [ ] Draft of the Conditions builder usage docs

**Comment by My-Money29** [comment]
[Version 0.6](https://www.figma.com/design/BRk3lEQVpJ8jn6jj7UO4mK/Condition-Builder---Usage-Guidance---Carbon-team-review?node-id=2492-11833&t=7Y5HQm25LpmIr8Fp-1) is done. @janhassel, @amal-k-joy, @kingtraceyj, @RichKummer, @carrenelloyd, @elycheea, @sstrubberg 
Once we mark the final review as done, I'll create a separate Figma file for it an label is as final.

- Updated all the examples to reflect logical statement and updated design.
- Left the note about examples not appearing correctly on the Gatsby version.

**Comment by oliviaflory** [comment]
Closing for now to track the effort
