### ISSUE TITLE
UserAvatar: Release review

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#5544]
### Readiness

- [x] One or more scenarios for a design pattern have been identified as a useful unit of functionality to publish.
- [x] A functioning component or components delivering those scenarios have been delivered and merged to `main`.
- [ ] The component or components have completed an [accessibility review](https://github.com/carbon-design-system/ibm-products/blob/main/.github/ISSUE_TEMPLATE/accessibilty-review.md).
- [ ] One or more design maintainers have approved the implementation for those scenarios, preferably via [design review](https://github.com/carbon-design-system/ibm-products/blob/main/.github/ISSUE_TEMPLATE/design-review.md).
[🔗Open issue Design Review Link](https://github.com/carbon-design-system/ibm-products/issues/5543)

### Engineering review

- [ ] Breaking changes have only been introduced with prior approval, discussion
      and are documented in release notes. Deprecation notices and/or feature
      flags are included in the prior major version.
- [x] The implementation takes into account, and does not impair, remaining and
      anticipated design scenarios.
- [ ] Public component features (names, props, etc) are consistent with
      Carbon-defined conventions and are consistent internally. Where there
      isn’t an existing convention to apply, ensure robust precedents are being
      established.
- [ ] The UI produced is
  - [x] responsive,
  - [x] translatable[^1],
  - [x] cross-browser,
  - [ ] and responds to the currently set Carbon theme.
- [x] Components are functional components using hooks.
- [x] Public components which produce DOM structures support `className`.
- [x] Public components support a ref (via `React.forwardRef`).
- [x] Public component supports a Devtools attribute
- [x] All significant DOM elements have meaningful classes[^2] and include the
      package or Carbon prefix (no hardcoded prefixes).
- [x] Additional attributes that are not identified as props (such as `title`,
      `aria-*`, etc) are passed through to an appropriate DOM node of the
      component as HTML attributes.
- [ ] No warnings, errors or log messages in the console.
- [x] Each public component JS is exported in `/src/components/index.js`, each
      public component SCSS is included in `/src/components/_index.scss`, and
      each public component has a flag in `package-settings.js`.
- [ ] Each public component SCSS lists all of the Carbon and IBM Products
      components imported and used by the JavaScript code and explicitly imports
      the SCSS for each of these components.

### Standards

- [ ] No linter warnings or errors are produced.
- [x] Carbon tokens (theme, layout, motion) are used unless the design specifies
      otherwise.
- [x] All components utilizing motion must include reduced-motion queries for
      accessibility purposes.
- [ ] Code is formatted according to prettier rules (no use of
      `//prettier-ignore`).
- [ ] Code is clear, maintainable and follows standard React practices and the
      code guidelines.
- [x] Copyright header in every source file (js, css, scss etc.) with the
      appropriate years.

### Testing

- [x] There is a set of test cases for the components.
- [ ] The tests exercise all inputs (props, slots, etc) and verify appropriate
      outputs.
- [x] The tests validate the behaviors and interactions defined in the design
      where practical.
- [ ] The tests achieve at least 80% coverage. Usage of `istanbul ignore` is
      appropriate and not extensive.
- [ ] No warnings, errors, or log messages in the test output.

### Documentation

- [ ] Source code is satisfactorily commented and provides DocGen comments for
      all public components and their props.
- [x] There is a story for each design scenario. The stories expose all relevant
      props and actions, and additional usage documentation and code samples are
      available on the Docs story along with the props table.
- [x] There is an example (or multiple sandboxes if appropriate) on CodeSandbox
      and Stackblitz for the components.

[^1]: Any labels, text, or other strings within a component should use a prop.
[^2]: See Carbon’s [Developer Handbook](https://github.com/carbon-design-system/carbon/blob/main/.github/CONTRIBUTING.md) for guidance on [class names](https://github.com/carbon-design-system/carbon/blob/main/docs/developer-handbook.md#class-names).

**Comment by AlexanderMelox** [comment]
In Safari, the focus state does not show up
![Image](https://github.com/user-attachments/assets/39f5d4ea-0257-44c1-a910-efcec43394b4)

**Comment by AlexanderMelox** [comment]
Before wrapped theme
![Image](https://github.com/user-attachments/assets/c50ed442-03e2-4a17-a42d-b6867910c0b8)

After wrapped theme
![Image](https://github.com/user-attachments/assets/aea7f4fc-c754-4f5b-86c3-cd7ffff186c1)

**Comment by AlexanderMelox** [comment]
The `Avatar` component is initiated inside the `UserAvatar` component. Normally this is initiated outside the Parent component. 
```
    const Avatar = () => (
      <div
        {
          // Pass through any other property values as HTML attributes.
          ...rest
        }
        className={cx(
          blockClass, // Apply the block class to the main HTML element
          className, // Apply any supplied class names to the main HTML element.
          `${blockClass}--${backgroundColor}`,
          `${blockClass}--${size}`,
          // example: `${blockClass}__template-string-class-${kind}-n-${size}`,
          {
            // switched classes dependant on props or state
            // example: [`${blockClass}__here-if-small`]: size === 'sm',
          }
        )}
        ref={ref}
        role="img"
        aria-hidden="true"
        {...getDevtoolsProps(componentName)}
      >
        {getItem()}
      </div>
    );

```

**Comment by AlexanderMelox** [comment]
Consolor errors: 
![Image](https://github.com/user-attachments/assets/a5317dab-1fce-43be-8347-deccfba8eeb2)

**Comment by elycheea** [comment]
### Readiness
- No formal accessibility review process (CAG, QA), but default AVT checks are in place.
- #5543 not yet complete. Should figure out if our team reviews or if the contributors review.

### Engineering review
- Deprecation notices for `UserProfileImage` will be added after or when the `UserAvatar` is released as stable.
- Noticed that in Safari that the ring is missing. Should check with design if we intend for this to appear on click or just focus.
- Theming works when wrapped in a `<Theme>` component but this isn’t apparent in Storybook. May need to add documentation on different ways to handle theming using `UserAvatar`.
- Prop names look good. But might want to open an enhancement to support `autoAlign` when using `Tooltip`.
- User avatar SCSS files need to add imports for `Tooltip` and possibly `TooltipTrigger` in the `_carbon-imports.scss` and `_user-avatar.scss` files respectively.

### Other
- Seeing some issues with our coverage reports currently. Asking @davidmenendez to take a look since he’s working on #6109.
- Think the SCSS files could use some extra comments on how the themes are being handled.

**Comment by elycheea** [comment]
Another way we could consider showing the theme handling is borrowing from the updates @lee-chase made to [`Theme`](https://react.carbondesignsystem.com/?path=/story/components-theme--use-theme) in Carbon.

<img width="381" alt="image" src="https://github.com/user-attachments/assets/240f6c02-94bf-4487-bae1-aaf0a0071ec1">

This also might allow us to remove the `storybook-carbon-theme` attributes from the styling if we can instead rely on the theme component.

**Comment by elycheea** [comment]
Way to go @anamikaanu96 👏 

![Image](https://github.com/user-attachments/assets/b3c05a7e-a941-4b62-991b-f1d2880ef8db)
