### ISSUE TITLE
[CreateFullPage]: The Component is not using the full viewport height anymore

### ISSUE THREAD

**Issue by baraaabdelsalam** [carbon-design-system/ibm-products#5573]
### Package

Carbon for IBM Products

### Description

On earlier versions, the CreateFullPage used to use the full viewport height and now on `2.43.1` its not. and instead just sets the height to the content of the Step and either leaves a long empty space if the content is short to fill the viewport, or introduces a scrolling behaviour to the whole wizard which breaks the footer buttons fixed positioning.

### Component(s) impacted

The CreateFullPage

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v2.43.1

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

IBM z

### CodeSandbox or Stackblitz example
[Code Sandbox](https://codesandbox.io/p/devbox/sharp-shaw-yq7s76?file=%2Fsrc%2FApp.jsx%3A6%2C20-7%2C27)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by anamikaanu96** [comment]
Hi @baraaabdelsalam could you please refer this
[code sandbox](https://codesandbox.io/p/devbox/eloquent-haze-vtrnxf?workspaceId=507d9e83-833d-4d9b-9391-b1ad10c9ae19&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxvpfa3500083b6ilu9prfgg%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxvpfa3500033b6i2vnmqmt6%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxvpfa3500053b6ip9clk0o4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxvpfa3500073b6iuatwn8ru%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxvpfa3500033b6i2vnmqmt6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxvpfa3500023b6iojt8xuwx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A15%252C%2522startColumn%2522%253A22%252C%2522endLineNumber%2522%253A15%252C%2522endColumn%2522%253A22%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxvpfa3500033b6i2vnmqmt6%2522%252C%2522activeTabId%2522%253A%2522clxvpfa3500023b6iojt8xuwx%2522%257D%252C%2522clxvpfa3500073b6iuatwn8ru%2522%253A%257B%2522id%2522%253A%2522clxvpfa3500073b6iuatwn8ru%2522%252C%2522activeTabId%2522%253A%2522cm020yvnz000i3b6hign14h53%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxvpfa3500063b6ie67uj49l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522SETUP_TASKS%2522%252C%2522id%2522%253A%2522clzw9ihg5000e3b6h9ge94gsh%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clzw9jfwb001p3b6hcor3srkc%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cm020yvnz000i3b6hign14h53%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clxvpfa3500053b6ip9clk0o4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxvpfa3500043b6i41u23n6i%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clxvpfa3500053b6ip9clk0o4%2522%252C%2522activeTabId%2522%253A%2522clxvpfa3500043b6i41u23n6i%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

You just need to wrap the createFullPage in a div and set the viewport height in that div.

**Comment by elycheea** [comment]
@baraaabdelsalam Please take a look at the recommendation from @anamikaanu96 and reopen if you still have issues.
