### ISSUE TITLE
[a11y]: Focus coming out of Tearsheet Narrow component 

### ISSUE THREAD

**Issue by psurana2** [carbon-design-system/ibm-products#5598]
### Package

@carbon/ibm-products

### Browser

Chrome, Firefox

### Operating System

MacOS

### Package version

v2.27.0

### React version

v17.0.2

### Automated testing tool and ruleset

Manual

### Description

When we stack one tearsheet over the other , and when we close the second tearsheet the focus should return back to the first tearsheet.  But the focus is coming out of the tearsheet .

### Reproduction/example

https://stackblitz.com/edit/github-hlqngl?file=src%2FExample%2FExample.jsx

### Steps to reproduce

Close the second tearsheet component , the focus should return to the parent tearsheet 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate problems

**Comment by elycheea** [comment]
@psurana2 Have you tried using the `selectorPrimaryFocus` prop for the second Tearsheet?

**Comment by psurana2** [comment]
No @elycheea  I have not tried . Can u help me with it
