### ISSUE TITLE
Dynamic loading of child nodes in the datagrid with selectableNestedRows

### ISSUE THREAD

**Issue by Rakesh-Addepalle** [carbon-design-system/ibm-products#5600]
### The problem

Since loading all child nodes simultaneously isn't feasible for us, our objective is to load data one level at a time. We aim to display an expand button on rows that contain children (nested rows). Upon clicking this button, we'll retrieve the corresponding records from the backend and display them. Currently, based on the documentation, it seems there isn't a built-in feature supporting this functionality. Is there a workaround or alternative method to achieve this?

![Screenshot 2024-04-09 at 6 57 47 AM](https://github.com/carbon-design-system/ibm-products/assets/6954160/eb84643e-d7eb-4282-bb7d-7a9722558054)

### Owner/main maintainer(s)

Jaesik Han

### Product/offering

IBM OpenPages

### Business priority

High Priority = pressing release
Release targeted for December — would be good to get in asap.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by matthewgallo** [comment]
Example from react-table https://codesandbox.io/p/sandbox/github/tannerlinsley/react-table/tree/v7/examples/sub-components-lazy?file=%2Fsrc%2FApp.js%3A184%2C11&from-embed=

**Comment by AmandaFurukawa** [comment]
Is there an ETA on this bug?

**Comment by matthewgallo** [comment]
I've started working on this, I'll move it to the current sprint and will post any updates here 😄

**Comment by kglickman** [comment]
If we wanted to have some sort of paging for the dynamically loaded nested rows, we could maybe add a dummy row with a More button or something.  I assume we could just insert the new rows at the appropriate place in the grid?

**Comment by AmandaFurukawa** [comment]
@matthewgallo Kate thinks it would be too expensive to make a request for children before trying to expand so instead when expanding an item with no children can we show a message that says "No children" or "No data" unless the Carbon team has another suggestion

**Comment by matthewgallo** [comment]
Ok, that makes sense. This should be possible by adding a new `subRow` once you find out that there aren't any dynamic rows and the content of that `subRow` can say that there are no nested/child rows for the given row.
