### ISSUE TITLE
Slack announcement for Figma v11 All themes Beta

### ISSUE THREAD

**Issue by RichKummer** [carbon-design-system/ibm-products#5603]
Create a Slack announcement and push to the appropriate channels to surface the v11 All themes Beta library.

Use the [Slack blast](https://www.figma.com/design/kGpp8sOoRTvXW7ShabgMR7/C4IP---Slackblast-banner-template?node-id=18-69&t=CUPaev0n2UZ3RFnY-1) used for C4IP announcements.

**Comment by elycheea** [comment]
Linda already announced this!
