### ISSUE TITLE
[DataSpreadsheet]: Something is hardcoded for Column Index 1 to not read the proper value datatype 

### ISSUE THREAD

**Issue by AustinGitHub** [carbon-design-system/ibm-products#5617]
### Package

Carbon for IBM Products

### Description

On our end 

https://github.com/carbon-design-system/ibm-products/assets/10100397/d464eb1f-be17-4a61-9aa0-28e6feb8082f

One correlation I can make is in all the stories the column index 1 is all `Row Index` with integer datatype. I think there is something hardcoded on carbon products side to where when we have Column Index 1 if it isn't integer it will return undefined. 

This issue came from the conversion of `js` to `tsx`. So maybe some strict rule is being applied in `tsx` that cause this issue for us. Hi @amal-k-joy I saw you worked on the conversion for this component. I am going to investigate and see if I can fix, but just wanted to let you know in case if maybe you have understanding of what is occurring. Thanks!

### Component(s) impacted

Dataspreadsheets

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.39.0

### Suggested Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

IBM DataStage

### CodeSandbox or Stackblitz example

https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-data-spreadsheet-dataspreadsheet--large-dataset-spreadsheet-custom&globals=viewport:basic

### Steps to reproduce the issue (if applicable)

I need to investigate further, but I believe because in the story it is Row Index, there is some datatype detection issue being made. 

The storybook can sort of be replicated to my video I posted above, for example when we double click into row index, we see that it shows empty. That is similar to what I see on my implementation except it should treat this column as a string rather than an integer column. 

### Release date (if applicable)

We will need this to be in patch as soon as possible. If my understanding is correct, then we shouldn't be expecting user to always have Column index 1 as an integer column but treat it as any type of column they want, string or integer, etc. I am not 100% sure on this yet which is why I need to investigate. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by AustinGitHub** [comment]
https://github.com/carbon-design-system/ibm-products/assets/10100397/37a72db5-798e-4655-86b9-43b90fc6419e


This is reproducible

**Comment by matthewgallo** [comment]
Included as part of `2.45.0-rc.1`.
