### ISSUE TITLE
Explore how to publish a pattern ingredient list

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-products#5651]
### The problem
Since defining the difference between a component and pattern we want to explore how we should document pattern "recipes" on the website.

### Considerations
- The solution should work for both Carbon Core and C4IP
- C4IP has patterns that would likely link to Core components
- We will likely implement this in Gatsby
   - Try existing Gatsby components first
- Where are we sending adopters for ingredient links?
   - linking to website docs of each component
   - linking to storybook
   - Do we provide links for both?
- Assume that Patterns do not have Figma assets

### Reference
**Paste design**
- [Paste patterns](https://paste.twilio.design/patterns#patterns)
- [Paste "ingredients"](https://paste.twilio.design/patterns/button-vs-anchor#ingredients)

**Patterns to test**
- [Filtering](https://carbondesignsystem.com/patterns/filtering/)
   - Checkbox
   - Dropdown
   - Data table
   - Radio button
- [Delete and remove](https://pages.github.ibm.com/cdai-design/pal/patterns/removing/usage)
   - Modal
   - Checkbox
   - Link
   - Text input
- [First time orientation](https://pages.github.ibm.com/cdai-design/pal/patterns/onboarding/orientation/usage)
   - Get started cards
   - Interstitial
   - Vertical tabs

```[tasklist]
### Tasks
- [ ] Audit competitors
- [ ] Explore options for displaying pattern "ingredients" on a pattern docs page
- [ ] Playback to design team (Core and Product)
```

**Comment by kingtraceyj** [comment]
[Figma](https://www.figma.com/design/pqJKFDAm6HIuAMHZt9QKlQ/Pattern-exploration?node-id=40-4838&t=cAqZIHVcOLZJVucG-1)

### Table implementation:
Title of the asset table should be contextual:

- [Pattern] assets
- [Pattern variant] assets

**Table comprised of:**
Asset name with link to docs
Component libraries with link to story books
Usage

Links should include icons (Following accessibility table convention)

- Launch icon - takes user to another site (storybook, another PAL)
- Right arrow icon - takes user to another page within current site
- No icon - takes user to another section within current page (ie. another tab, a different anchor link)
<img width="707" alt="image" src="https://github.com/user-attachments/assets/36b5d130-4084-452f-9668-a879a2119094">


**Usage**
The usage column should add specific insight to why this particular component is being used,
placement within the pattern, or a specific component variant allowed or not allowed. This section should be concise. Use the Designing with [pattern] section to add more guidelines around using components if needed. 

### Placement:
**Pattern with no variants:**
Pattern asset table should be in the overview section ideally after an anatomy section. If a pattern does not have an anatomy section, the asset table should be placed after the overview image. This helps the user understand how the elements visually come together to form the pattern. 

**Pattern with variants:**
Patterns with multiple variants differ in how teams need organize information.

When a pattern has multiple variants, each variant has it’s own section that describes the specific implementation. The variant’s pattern assets table would ideally be placed after the variant’s anatomy section if there is one. If there is no need for an anatomy section, place the table within the variant overview. 

When a pattern has multiple variants with implementations that are very similar to each other and use the same components, the assets table can be consolidated into one table to reduce redundancy. Place the assets table in the overview section just as like a pattern with no variants. This might result in the pattern assets table stacking above the variant table so be sure to use a title for the both tables to add clarity and visual space between the two tables.
