### ISSUE TITLE
[Feature Request]: Merchandising pattern

### ISSUE THREAD

**Issue by ljcarot** [carbon-design-system/ibm-products#5686]
### The opportunity

**Merchandising pattern**

As a designer and/or developer focused on my product's PLG improvements, I want to create within my product, an Upselling experience (aka Merchandising) that highlights for a new or existing user how to upgrade or change subscription options within the product with the goal to help the user decide on the correct option.

Design: https://www.figma.com/design/wObxhfYM2Qq1Kldv58lfnF/Merchandising---Upsell-Designs?node-id=2509-41641&t=y6TaXXDq3gvLsZCZ-1

Prototype: https://www.figma.com/proto/wObxhfYM2Qq1Kldv58lfnF/Merchandising---Upsell-Designs?page-id=2509%3A41641&node-id=2526-77346&viewport=-2059%2C212%2C0.26&t=oBABq6zMtsCIbb70-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=2526%3A81087

Docs:

### The solution

This will be a pattern that explains different possible options for how a product may consider approaching this.  It's a recipe for success and includes references to the components available to put it all together.  

NO CODE REQUIRED, No kit work, Just docs.

Docs will be added to both sites (current and new) so the PLG team can meet their July 31 deadline for publishing.

### Owner/main maintainer(s)

Kiran Ravindra and Sunny Babbar

### Second/backup maintainer(s)

Cameron Calder

### Product/offering

PLG Innovation

### Business priority

High Priority = pressing release

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by oliviaflory** [comment]
Assigning myself and Tracey to track the effort we are putting in on reviewing and occasional mock ups of the content.
