### ISSUE TITLE
Tearsheet: actions should not be required

### ISSUE THREAD

**Issue by wkeese** [carbon-design-system/ibm-products#5704]
### Package

Carbon for IBM Products

### Description

Tearsheet's Proptypes says that the `actions` attribute is optional, but Tearsheet.d.ts marks it as required.

### Component(s) impacted

Tearsheet, TearsheetNarrow, TearsheetShell

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.45.0

### Suggested Severity

None

### Product/offering

IKC

### CodeSandbox or Stackblitz example

https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-tearsheet--tearsheet&globals=viewport:basic

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by elycheea** [comment]
@wkeese Thanks for opening all of these! If you’re able to open a PR for these, that would also be great!

**Comment by wkeese** [comment]
@elycheea - Can you explain how those files like Tearsheet.d.ts are generated?   Are they just from `declarations:true` in the Typescript config, or something fancier like https://github.com/mskelton/ratchet or [PropTypes.InferProps](https://dev.to/busypeoples/notes-on-typescript-inferring-react-proptypes-1g88)?

Obviously, the best solution is to convert all the components to Typescript, or at least all the components with incorrect types.

But I'm wondering if there's a faster way to fix this.
