### ISSUE TITLE
[CreateFullPage]: breadcrumbs prop is not typed as array in Typescript

### ISSUE THREAD

**Issue by awojciak** [carbon-design-system/ibm-products#5707]
### Package

Carbon for IBM Products

### Description

In docs of CreateFullPage component and its propTypes 'breadcrumbs' prop is typed as an array of objects. However, in Typescript type for props of this component, this prop is typed as a single object: https://github.com/carbon-design-system/ibm-products/blob/a49f23c7c00291efc9febd401b2f7472a4136642/packages/ibm-products/src/components/CreateFullPage/CreateFullPage.tsx#L87

Because of that, using array as breadcrumbs value causes Typescript error:
`Type '{ key: string; label: string; isCurrentPage: true; }[]' is missing the following properties from type 'HeaderBreadcrumbs': key, label ts(2739)
CreateFullPage.d.ts(25, 5): The expected type comes from property 'breadcrumbs' which is declared here on type 'IntrinsicAttributes & (CreateFullPageProps & RefAttributes<HTMLDivElement>)'`

### Component(s) impacted

CreateFullPage

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.45.0

### Suggested Severity

None

### Product/offering

IKC

### CodeSandbox or Stackblitz example

https://carbon-for-ibm-products.netlify.app/?path=/docs/ibm-products-patterns-create-flows-createfullpage--docs

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by elycheea** [comment]
@awojciak If you’d like to contribute a PR for this fix, we encourage you to!
