### ISSUE TITLE
Datagrid performace issue: DatagridContent from Datagrid is re-rendering 4 times

### ISSUE THREAD

**Issue by tushardhamor** [carbon-design-system/ibm-products#5712]
### Package

Carbon for IBM Products

### Description

We are noticing real performance issues caused by the Datagrid in our App where we have around 7 tables in a single page/panel and each time any state data changes (which is irrelevant to Datagrid data), the DatagridContent and its children components re-render 3-4 times! On that same panel we have input fields, on every keystroke each DatagridContent re-renders 4 times resulting in a sluggish experience. It easily gets to hundreds of re-renders on a simple input change by the user.

We also tried creating a very basic data grid just with few basic static column and row data without any other fancy stuff, and it still re-renders the DatagridContent and its children 4 times on any change affect data that is completely unrelated to the Datagrid data.

Note: We are also memoizing all the column and data objects.

### Component(s) impacted

All the component in our project where we have used Datagrid are getting impacted by multiple rendering.

<img width="588" alt="Screenshot 2024-07-23 at 3 23 14 PM (2)" src="https://github.com/user-attachments/assets/842728ad-1b42-47a1-b4bf-70bbed075f12">
<img width="302" alt="Screenshot 2024-07-23 at 3 20 51 PM (2)" src="https://github.com/user-attachments/assets/e68fb090-bc12-43a7-a913-378e0e5ce9ce">

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.43.1

### Suggested Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

Datagrid

### CodeSandbox or Stackblitz example

https://codesandbox.io/p/sandbox/github/carbon-design-system/ibm-products/tree/main/examples/carbon-for-ibm-products/Datagrid?file=%2Fsrc%2FExample%2FExample.jsx

### Steps to reproduce the issue (if applicable)

1. Adding the Datagrid component to the our component with static columns
2. Having an controlled input field in the same component.
3. We need the React Dev tool Profiler.
4. Now if we type 1 character in the input field then we will see 3-4 times DatagirdContent being re-rendered even thought both the input field data & Datagrid our unrelated.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by amal-k-joy** [comment]
Hi @tushardhamor ,
I think here  when you update the state of the input element, the parent component in which both input element and Datagrid contained will re-render. This will in-turn re-renders the Datagrid component which is as  expected. 

https://github.com/user-attachments/assets/e4efdf50-f0f2-4a77-a878-f6c4cef27172


But if you wrap your inputs to a separate component, and there by preventing the re-renders of parent , we can prevent  the re-rendering of Datagrid as well. Could you able to try any similar solutions?

https://github.com/user-attachments/assets/ec46b1a2-5437-43ed-ac06-3e07a2fb6ba8
