### ISSUE TITLE
DataGrid Column Customization is not working as expected when used along with Select rows and global filters

### ISSUE THREAD

**Issue by marinamas** [carbon-design-system/ibm-products#5713]
### Package

Carbon for IBM Products

### Description

- Create a simple Datagrid with Column Customization functionality and Select rows option enabled
- Go the the ColumnCustomization , and click on select all column option.
- Uncheck the checkbox to clear all the selection. And click on apply.
- This will also remove the checkbox column from the table , which is not expected.

### Component(s) impacted

DataGrid

![image](https://github.com/user-attachments/assets/e1fff87b-71f4-4873-b4ae-833a0f8a8d37)

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

"@carbon/ibm-products": "2.45.0",

### Suggested Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

NA

### CodeSandbox or Stackblitz example

https://codesandbox.io/p/sandbox/datagridfilter-forked-vhcgdf?file=%2Fsrc%2FExample.js%3A150%2C7

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by devadula-nandan** [comment]
Hi @marinamas ,
this got fixed in the latest release [2.46.0](https://github.com/carbon-design-system/ibm-products/releases/tag/%40carbon%2Fibm-products%402.46.0), could you check it and see if problem still exist?

**Comment by marinamas** [comment]
This is fixed in the latest release
