### ISSUE TITLE
Full screen with custom layout Firefox messed up

### ISSUE THREAD

**Issue by deathcave** [carbon-design-system/ibm-products#5714]
### Package

Carbon for IBM Products

### Description

Full screen with custom layout Fixfox messed up

### Component(s) impacted

InterstitialScreen components

### Browser

Firefox

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v2.45.0

### Suggested Severity

None

### Product/offering

ibm-product

### CodeSandbox or Stackblitz example

https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-onboarding-interstitial-screen-interstitialscreen--interstitial-screen-full-screen-no-media-with-cards&globals=viewport:basic

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by matthewgallo** [comment]
@deathcave can you check to see if this is still an issue? We're not seeing the layout issues anymore in Firefox. Thanks!
