### ISSUE TITLE
[Feature Request]: Disable Modal for TagSet component

### ISSUE THREAD

**Issue by jeesonjohnson** [carbon-design-system/ibm-products#5726]
### The problem

Currently, we do not have the option to disable the TagSet overflow modal. This is currently an issue for our product, since we chose to disable this component, in favour of our own custom component with custom functionality. However, with how the code is set up currently, the inbuilt `TagSetModal` cannot be disabled.  See [here](https://github.com/carbon-design-system/ibm-products/blob/main/packages/ibm-products/src/components/TagSet/TagSet.tsx#L402-L412). We have disabled it manually using CSS overrides. However, we would rather it be disabled by the use of a prop, so that the DOM does not become overly populated unnecessarily.
 

### The solution

Pass down a prop called, `showOverflowModal` (defaulted to `true`) that will disable the rendering of the component within the `TagSet` component. 

NOTE: I am happy to do this change, raise the appropriate PRs and do related testing. Just wanted to approval before attempting to make this change.

### Design link

N/A

### Links to other materials

Related code that needs to be changed: https://github.com/carbon-design-system/ibm-products/blob/main/packages/ibm-products/src/components/TagSet/TagSet.tsx#L402-L412

### Owner/main maintainer(s)

IBM Products

### Product/offering

IBM Cloud Pak For Integration

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by oliviaflory** [comment]
@matthewgallo following up with Michael G

**Comment by jeesonjohnson** [comment]
Hey @matthewgallo / @oliviaflory, has there been any update on this?
