### ISSUE TITLE
Datagrid tooltip component hover issue

### ISSUE THREAD

**Issue by marinamas** [carbon-design-system/ibm-products#5743]
### Package

Carbon for IBM Products

### Description

- Create a Datagrid table
- Add  tooltip component  next to the header name.
 Expected : on hover of the tooltip , the tooltip description should show up
  Current behavior : Tooltip hover doesn't show anything

https://github.com/user-attachments/assets/19b69d10-1bda-4086-abb8-77217e2484fe

### Component(s) impacted

Datagrid

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

"@carbon/ibm-products": "2.40.0",

### Suggested Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

NA

### CodeSandbox or Stackblitz example

https://codesandbox.io/p/sandbox/datagridfilter-forked-26hqww?file=%2Fsrc%2FExample.js%3A41%2C25

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by marinamas** [comment]
There is one more issue when we have a component rendered as a Header, when we try to resize there is no Ellipsis . Attached video below for reference


https://github.com/user-attachments/assets/e0eb2076-3660-4d1a-9713-1ec738331cf1

**Comment by marinamas** [comment]
This tooltip hover works with autoAlign in Chrome but not on Safari browser

**Comment by matthewgallo** [comment]
Hi @marinamas, can you try using the `autoAlign` prop now? We've made some dependency updates which have included `@carbon/react`s support for this.

**Comment by ljcarot** [comment]
We've been investigating [TanStack ](https://tanstack.com/table/latest)[Table](https://tanstack.com/table/latest), a third-party, open-source offering, which provides extensive data table capabilities surpassing what our Carbon Datagrid offers. It provides much more flexibility and customization. TanStack Table is headless which means it can easily be added alongside Datagrid component in your product or application. The benefits of more flexibility for product teams and less maintenance for Carbon makes it a win win. Lastly, it is available in multiple frameworks including [React](https://github.com/carbon-design-system/tanstack-carbon/tree/main/react#readme) and [Web Component](https://github.com/carbon-design-system/tanstack-carbon/tree/main/web-components#readme) so it provides an option to non-React product teams.

For these reasons, we have decided to transition from building our own custom table component to using an example-based approach with TanStack Table. Datagrid will still exist in our library for existing teams but we are announcing the deprecation* of the Datagrid component in v2.54.0 release so teams can begin to work through the transition. Details about how to use both Datagrid and TanStack together can be found [here](https://github.com/carbon-design-system/tanstack-carbon/tree/main). 

*Deprecation means that no new features will be added however sev 1 and sev 2 bugs will be supported.
