### ISSUE TITLE
[a11y]:  Tearsheet focus not coming on ContexSwitcher

### ISSUE THREAD

**Issue by psurana2** [carbon-design-system/ibm-products#5745]
### Package

@carbon/ibm-products

### Browser

Chrome, Firefox

### Operating System

MacOS

### Package version

v2.27

### React version

v17.0.2

### Automated testing tool and ruleset

Manual

### Description

In the tearsheet component, I am using ContextSwitcher component . While navigation through keyboard, on pressing Shift+Tab the focus goes to the contextswitcher and the same doesnt work in case of tab key press

### Reproduction/example

https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-tearsheet--with-navigation&globals=viewport:basic

### Steps to reproduce

Use a ContextSwitcher component 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate problems

**Comment by matthewgallo** [comment]
@psurana2 can you create a code sandbox showing this behavior? Thanks!

**Comment by makafsal** [comment]
@matthewgallo This happens because Firefox focuses on the content `div` element with the scrollbar.
