### ISSUE TITLE
AI docs: Add AI to Expressive card

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-products#5755]
## Add AI docs to the Expressive card page
- [x] Follow the instructions outlined in the [parent Epic](https://github.com/carbon-design-system/ibm-products/issues/4433)
- [x] Draft content for Usage tab
- [x] Draft content for Style tab (if applicable)
- [ ] Create image(s) and add to [v11 IBM Product PAL website](https://www.figma.com/design/lDM3X9hSrOE6vKLEf1CxbX/v11-IBM-Product-PAL-Website?node-id=334-2564&t=cm6MZDPOHqZj9PBD-1) Figma file
- [ ] Open Draft PR (wait to merge until Storybook fixes are addressed)

**Comment by ljcarot** [comment]
Is this complete @kingtraceyj

**Comment by kingtraceyj** [comment]
@ljcarot yes, it's sitting with the rest of the ai PRs: https://github.com/carbon-design-system/carbon-for-products-website/pull/289
