### ISSUE TITLE
AI docs: Add AI to Productive card

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-products#5756]
## Add AI docs to the Productive card page
- [x] Follow the instructions outlined in the [parent Epic](https://github.com/carbon-design-system/ibm-products/issues/4433)
- [x] Draft content for Usage tab
- [x] Draft content for Style tab (if applicable)
- [x] Create image(s) and add to [v11 IBM Product PAL website](https://www.figma.com/design/lDM3X9hSrOE6vKLEf1CxbX/v11-IBM-Product-PAL-Website?node-id=334-2564&t=cm6MZDPOHqZj9PBD-1) Figma file
- [x] Open Draft PR (wait to merge until Storybook fixes are addressed)

**Comment by aubrey-oneal** [comment]
## AI docs Template
[Original Carbon issue link](https://github.com/carbon-design-system/carbon-website/issues/4007)

### Usage tab checklist
[See example in Figma](https://www.figma.com/file/OJwBWBlctEgm9zYUCYbhu3/Carbon-for-AI-%E2%80%93-website-integration?type=design&node-id=80%3A7220&mode=design&t=XPoeQ0K8Ea0VbhbW-1)

-  [ ] Add inline notification to the top of the page under intro paragraph. The link should go to the AI component’s storybook example.
-  [ ] Add “AI presence” to the anchor links.
-  [ ] Add an H2 section for “AI presence” between “Modifiers” (or “Behaviors”) and “Related” content sections.
-  [ ] Copy the content from the template example and edit the template content to be specific to each component. Only the input components will get the extra revert h3 sections.
-  [ ] Create images for the components similar to the template examples (add images to the [v11 IBM Product PAL website](https://www.figma.com/design/lDM3X9hSrOE6vKLEf1CxbX/v11-IBM-Product-PAL-Website?node-id=334-2564&t=cm6MZDPOHqZj9PBD-1) file)

_If links to the general AI guidelines sections aren’t ready yet then don’t include links or hyperlinks yet. We will add these in later when ready._

### Style tab checklist
[See example in Figma](https://www.figma.com/file/OJwBWBlctEgm9zYUCYbhu3/Carbon-for-AI-%E2%80%93-website-integration?type=design&node-id=80%3A7192&mode=design&t=XPoeQ0K8Ea0VbhbW-1)

-  [ ] Add “AI presence” to the anchor links.
- [ ] Add an H2 section for “AI presence” at the end of the page
-  [ ] Copy the content from the template example and edit the template content where needed to be specific to each component.
-  [ ] Create an image for the component similar to the template examples. (add images to the [v11 IBM Product PAL website](https://www.figma.com/design/lDM3X9hSrOE6vKLEf1CxbX/v11-IBM-Product-PAL-Website?node-id=334-2564&t=cm6MZDPOHqZj9PBD-1) file)

_If links to the general AI guidelines sections aren’t ready yet then don’t include links or hyperlinks yet. We will add these in later when ready._
