### ISSUE TITLE
[BUG]: Radio buttons for changing row sizes not displaying properly in Data Grids when two or more present on the same page

### ISSUE THREAD

**Issue by pjborowiecki** [carbon-design-system/ibm-products#5763]
### Package

Carbon for IBM Products

### Description

Radio buttons for selecting a row size do not display properly on change in a Datagrid component, when two or more DataGrids are present on the same page.

![Screenshot 2024-07-18 at 17 00 55](https://github.com/user-attachments/assets/0b958945-5976-4188-a3e9-b8df8706155c)

### Component(s) impacted

Datagrid

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.45.0

### Suggested Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

IBM

### CodeSandbox or Stackblitz example

https://codesandbox.io/p/devbox/hopeful-tamas-f97ryh?layout=%257B%2522sidebarPanel%2[…]ebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to reproduce the issue (if applicable)

See the CodeSandbox example provided. The issue appears when displaying two Datagrids on the same page (or a Datagrid in a modal opened on a page that already has a Datagrid on it).

Try changing a row size and observe the marker (filled-in dot) disappear.

![Screenshot 2024-07-18 at 17 00 55](https://github.com/user-attachments/assets/0b958945-5976-4188-a3e9-b8df8706155c)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by szymonbrandys** [comment]
When can I expect it to be fixed and delivered? Thanks.

**Comment by pjborowiecki** [comment]
Hi @matthewgallo, could you provide me with an estimate of when we could expect the issue to be fixed please? I'd appreciate an update, thank you.

**Comment by szinta** [comment]
> Can you estimate when this issue will be resolved?

This issue has been fixed, and the fix will be available in version **2.50.0**, which is scheduled to be released on **September 25th**. 
If you want to validate the fix early, you can use the release candidate version **@carbon/ibm-products@2.50.0-rc.0**, which is set to be released on September 16, 2024.
