### ISSUE TITLE
EditInPlace when focused gets clipped on right side

### ISSUE THREAD

**Issue by David-Yuen** [carbon-design-system/ibm-products#5779]
### Package

Carbon for IBM Products

### Description

Using `EditInPlace` in a table, and it takes 100% width of the table cell. 
It looks good until you focus on it.. you can see the right side border has been clipped...

![image](https://github.com/user-attachments/assets/94a556e2-8647-4d27-a8dc-37ae6ab81566)

For temporary fix, i just added `margin-right: $spacing-01;` to the EditInPlace's outer container.

### Component(s) impacted

Impacts when added to a `Table` component as a Table cell input edit.. screenshot above

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.45.0

### Suggested Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

IBM Cloud Data Replication

### CodeSandbox or Stackblitz example

n/a

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by matthewgallo** [comment]
Hi @David-Yuen, can you create a code sandbox reproduction of this?

**Comment by David-Yuen** [comment]
https://codesandbox.io/p/devbox/flamboyant-albattani-md4m7v

it looks ok when first loads.. but when you click on the EditInPlace component, and it goes into editing mode.. the focus border on right side goes off-screen and then clipped. 

onload:
<img width="323" alt="Screenshot 2024-08-08 at 1 01 42 PM" src="https://github.com/user-attachments/assets/6694402f-ce12-42fd-b944-535149f2ef73">

focused:
<img width="341" alt="Screenshot 2024-08-08 at 1 02 09 PM" src="https://github.com/user-attachments/assets/5c6b5e93-01b2-4e1e-a919-1a4b24cd722a">

**Comment by davidmenendez** [comment]
hey @David-Yuen a fix has been issued in #5869 and should be included in our next scheduled release
