### ISSUE TITLE
EditInPlace tooltip extending out too far, causes scrollbar to appear

### ISSUE THREAD

**Issue by David-Yuen** [carbon-design-system/ibm-products#5780]
### Package

Carbon for IBM Products

### Description

I am using `EditInPlace` in a `Table` component as a Table cell input edit. 
I set `tooltipAlignment="top-right" `, but it still sticks out farther then the right edge of the `EditInPlace`..

![image](https://github.com/user-attachments/assets/7dfb502d-98b5-482b-8983-9e6dcedeba68)
1st screenshot shows tooltip but clipped because it reaches out further to right side of the EditInPlace component.
The component is 100% width of the table cell, so when hovering over and the tooltip appears, a scroll bar appears and you can scroll over to the right to see the remaining..

![image](https://github.com/user-attachments/assets/e534f033-a067-4251-a4cf-4cf521f3e697)
In 2nd screenshot, i scrolled over to the right.. But I am on mac and the scrollbar is auto-hidden so you cant see my scrollbar in the screenshot.

For temporary fix, i've added:
```
  .cds--icon-tooltip {
    --cds-popover-offset: 0rem;
  }
```
^this value is normally set to `0.5rem`, but if i set it to `0rem`, then it's positioned correctly, aligned with the right edge of the `EditInPlace` component and does not cause scrollbar to appear.
For some reason, setting to `0` value doesnt work, has to be `0rem` for some reason.. setting to `0` affected both horizontal and  vertical position of the tooltip.. but setting to `0rem` only adjusts the horizontal position..

### Component(s) impacted

Affects adding component to a `Table` as table cell. I think it might impact any page or component when aligning this component to the right side.. because the tooltip extends further than the `EditInPlace` position.

So far in other carbon components, when setting alignment to `left` or `right`, it aligns perfectly with the component's edges and does not cause scrollbar to appear. 
For example, i've assigned `align="bottom-right"` to a icon-only button component.. and if I have long text, it extends left but the end of the tooltip always aligns perfectly with the right edge of the button's edge.. 

```
                       [button1][button2]
                           [button2 tooltip]
```
^example of hovering over `button2`, the tooltip appears and the end of tooltip aligns with the right side of `button2`. This seems common across other carbon components.

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.45.0

### Suggested Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

IBM Cloud Data Replication

### CodeSandbox or Stackblitz example

n/a

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by davidmenendez** [comment]
hey @David-Yuen 

i believe this is a problem with the carbon table. you didn't provide a codesandbox, so i had to cobble something together based on what you described. if my assumptions are correct then i believe the problem here lies with this style rule
```
.cds--data-table-content {
    display: block;
    overflow-x: auto;
}
```
if you override the overflow to be `visible` this alleviate the problem. this screenshot should capture the intended behavior you're looking for


![Image](https://github.com/user-attachments/assets/39f6bb81-0d9c-474c-8844-c54d08a8a044)

**Comment by David-Yuen** [comment]
setting `overflow` to `visible` doesn't work, still creates scrollbar... 
Generally is.. I have set `tooltipAlignment="top-right"`, which the right edge of the tooltip should align with the edge of the `EditInPlace` component, but instead it's reaching farther to the right. 

I have a panel, and I have a carbon table that takes 100% width of the panel. I have added `EditInPlace` component inside the table's last column.. Table columns by default have some padding (like in your screenshot), but by design (such as the DataGrid), input fields should fill the full table cell, so removing padding with `padding: 0;`. This should setup the `EditInPlace` full width and height of the table cell like my screenshot. Since `EditInPlace` is in the last column, the right edge of the component should be aligned with the Table's right side edge.
Then if hovering over the Edit button, the tooltip will appear.. and because Table takes 100% width of panel, and if panel has overflow set to visible/scroll, the scrollbar should appear because the tooltip is reaching farther right side of the `EditInPlace`.. since this is also the edge of the table, it reaches outside of the table, and causes scrollbar to appear

I'm not sure if i can create a reproduction, i seem to always have issues with codesandbox, getting basic carbon components working.. May try later..

**Comment by David-Yuen** [comment]
https://codesandbox.io/p/devbox/jolly-tom-wc3qc9 I think this reproduces the problem.
tooltip is set like this: `tooltipAlignment="top-right"`, and the EditInPlace is positioned at the farthest right side of a container component (in this case, a Table, and farthest right column). 


Hovering over the EditInPlace component itself, everything still looks ok:
<img width="1428" alt="Screenshot 2024-08-12 at 1 43 02 PM" src="https://github.com/user-attachments/assets/2cf2d91c-133f-4bb1-a150-97b0e3ca5759">


But when you hover over the Edit button (or if focused, hover on Save button), the tooltip appears and pushing out the right side (exceeding outside of the edge of the parent component.. in this case, Table. This will create a scrollbar
<img width="1432" alt="Screenshot 2024-08-12 at 1 45 50 PM" src="https://github.com/user-attachments/assets/d7d462b9-ab53-4802-a0f8-d736d561f134">

In this screenshot, while the tooltip is visible, you can scroll to the right side a bit. 
<img width="235" alt="Screenshot 2024-08-12 at 1 46 46 PM" src="https://github.com/user-attachments/assets/fb0eaf32-da41-4e8e-b808-c4ab31e74ae5">

On a Mac, and with default settings, the scrollbar is auto-hidden so may not look so bad. But some may disable the auto-hide scrollbar, and in windows and other OSes, where scrollbars are always visible, this causes visual problems and breaking out and etc. 

When tooltips are aligned to the edges (like in this case, `right`), it should align with the edge of the button itself.. 
When implementing a icon button (in this case, EditInPlace component), we can plan for size and position of the component properly. While hover-overs (like tooltip) are like edge cases that aren't noticable without specific conditions, and causes a layout change.

**Comment by davidmenendez** [comment]
thanks for providing an example. this will help a lot. i'll take another look.

**Comment by davidmenendez** [comment]
@David-Yuen i see the behavior you're describing in the sandbox and i understand the frustration you're experiencing. unfortunately this is this an issue for carbon core. the underlying `EditInPlace` component is built on the carbon `IconButton`. as you can see [here](https://github.com/carbon-design-system/ibm-products/blob/bd91747bfb73a1ada8d49e5c569b1b3eb31070f0/packages/ibm-products/src/components/EditInPlace/EditInPlace.tsx#L307) nothing special is being done to implement the tooltip. it's just `IconButton`. if you look at the `IconButton` in the carbon [storybook](https://react.carbondesignsystem.com/?path=/story/components-iconbutton--playground&args=align:top-right) you'll see the slightly unaligned tooltip in the `IconButton`. If you believe this is a bug you should open an issue in the [core repo](https://github.com/carbon-design-system/carbon/issues).
