### ISSUE TITLE
Investigate `ConditionBuilder` test causing timeout issues when running in actions

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#5782]
### Package

Carbon for IBM Products

### Description

There is a `ConditionBuilder` test that intermittently causes timeout issues when running in github actions. This causes release actions such as `rc` and `full minor` actions to fail.

https://github.com/carbon-design-system/ibm-products/blob/main/packages/ibm-products/src/components/ConditionBuilder/ConditionBuilder.test.js#L151-L177

https://github.com/carbon-design-system/ibm-products/actions/runs/10185091190/job/28173861841

### Component(s) impacted

`ConditionBuilder`

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

Latest

### Suggested Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

Our team

### CodeSandbox or Stackblitz example

N/A

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by amal-k-joy** [comment]
@matthewgallo , it seems the test is not failing anymore after trying multiple times. Also I couldnt any network interaction for any of the tests in condition builder.
 However there can be a possible network interaction by `accessibility-checker` package while running the test '`it('has no accessibility violations'`)'
 Also in local, below error is thrown sometimes , how ever yarn test is success even with this error. So not sure the intermittent  test failure is connected to this error.
` [ERROR] ValidPoliciesMissing: No valid policy has been provided. Valid policy ids for the specified archive are: EXTENSIONS,IBM_Accessibility,IBM_Accessibility_next,WCAG_2_2,WCAG_2_1,WCAG_2_0`

_Note: a funtion in ACHelper.ts inside accessibility-checker is receiving curPolicy as `Custom_Ruleset`(from config file achecker.js) , whereas it expects one of `EXTENSIONS,IBM_Accessibility,IBM_Accessibility_next,WCAG_2_2,WCAG_2_1,WCAG_2_0`_

**Comment by amal-k-joy** [comment]
@matthewgallo , Should we keep this issue open or can be closed for now?

**Comment by matthewgallo** [comment]
It just timed out again [here](https://github.com/carbon-design-system/ibm-products/actions/runs/10526446129/job/29167315452?pr=5928). Typically we do see it stem from the accessibility tests so it's odd that the condition builder tests fail on other tests.

**Comment by amal-k-joy** [comment]
Its really odd. I have raised [this](https://github.com/carbon-design-system/ibm-products/pull/5794) PR . 
Looks like `toBeAccessible()` and `toHaveNoAxeViolations()` are promises , so I suspect the actually failed test case is this one, and since we have not added `await`, failure may show in subsequent testcases. Shall we merge this and watch for any errors ?
