### ISSUE TITLE
[CUSTOMIZE COLUMNS BUG]: If all the columns are unchecked, Save button should not be enabled

### ISSUE THREAD

**Issue by Xirax** [carbon-design-system/ibm-products#5843]
### Package

Carbon for IBM Products

### Description

If I click on Customize Columns button and deselect all of them leaving 0 active columns like on the video - Save button should be disabled. Otherwise it will lead to showing nothing at all which is not natural behaviour.
Link to notebook: [https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-columncustomization--column-customization-usage-story&globals=viewport:basic](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-columncustomization--column-customization-usage-story&globals=viewport:basic)

[video](https://github.com/user-attachments/assets/8483d158-8187-4fc7-ac21-7d372d97d292)

### Component(s) impacted

https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-columncustomization--column-customization-usage-story&globals=viewport:basic

### Browser

Chrome, Safari

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.45.0

### Suggested Severity

None

### Product/offering

IBM

### CodeSandbox or Stackblitz example

https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-columncustomization--column-customization-usage-story&globals=viewport:basic

### Steps to reproduce the issue (if applicable)

Customize Columns -> Deselect All -> Save

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by szymonbrandys** [comment]
It could be also a property that disallows saving configuration when all columns are unselected.

**Comment by jakubkloc** [comment]
Can you estimate when this issue will be resolved?

**Comment by jakubkloc** [comment]
its already implemented in 2.50.0 version?
