### ISSUE TITLE
  Inside Tearsheet radio button group behavior on using keyboard is different in chrome and Mozilla

### ISSUE THREAD

**Issue by Meenakshi34-lab** [carbon-design-system/ibm-products#5844]
### Package

Carbon for IBM Products

### Description

 I am using tearsheet component inside that radio group keyboard is showing different behavior in different browsers .Chrome it is up/down arrows in between radio button and firefox on tab click only it moves to next radio button

### Component(s) impacted

Accesibilty for radio option of radio group inside tearsheet ,

### Browser

Chrome, Firefox, Microsoft Edge

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v2.45.0

### Suggested Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

Awc project  using carbon react and carbon ibm products

### CodeSandbox or Stackblitz example

https://stackblitz.com/edit/vitejs-vite-yds8rg?file=src%2FApp.jsx

### Steps to reproduce the issue (if applicable)

Please use tearsheet and add radio button group and using keyboard see the behavior

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by ljcarot** [comment]
@amal-k-joy Can you please have Raghu take a look at this keyboard behavior and assess for us?

**Comment by devadula-nandan** [comment]
Here’s some additional information:
https://www.w3.org/WAI/ARIA/apg/patterns/radio/

**Comment by devadula-nandan** [comment]
Hi @ljcarot @amal-k-joy ,
As per the discussion with Raghu, the following behavior was inconsistent with Chrome.

<img width="839" alt="Screenshot 2024-08-19 at 1 35 47 PM" src="https://github.com/user-attachments/assets/c9b407dd-af44-424e-8678-278eeea0a795">

https://github.com/user-attachments/assets/5ed5f144-0b9d-4916-ad8b-6d5839b46851

and Firefox should be following the same behavior as Chrome.

**Comment by RichKummer** [comment]
Hey @Meenakshi34-lab , are you seeing this happen to the radio button group outside `tearsheet`?

**Comment by neambati** [comment]
Hi @RichKummer : We are facing issue inside the tearsheet as per our project.

**Comment by Meenakshi34-lab** [comment]
Hi @RichKummer We are facing this inside the tearsheet as in chrome we move from one radio button to other using up/down keys. Tab and Tab+shift move it out of radio button .In firefox and edge we can use tab to move between radio button.

**Comment by neambati** [comment]
@elycheea @RichKummer : Please let us know the current status of this issue.

**Comment by neambati** [comment]
@makafsal : Could you please update the status on this request

**Comment by makafsal** [comment]
@neambati @Meenakshi34-lab Please provide the `name` attribute for `<RadioButtonGroup>`.

```
<RadioButtonGroup
  legendText=""
  orientation="vertical"
  invalidText={'You must select at least one notification type.'}
  onChange={(e) => handleOnChange(e)}
  className="radioGrp"
  aria-label="Select at least one option."
  name="my-radio-group" // <-- ADD THIS
>
```
