### ISSUE TITLE
EditInPlace keeps focused state when invalid but field is not actually focused on

### ISSUE THREAD

**Issue by David-Yuen** [carbon-design-system/ibm-products#5852]
### Package

Carbon for IBM Products

### Description

Normally, if you focus on the `EditInPlace` component to give input, the state of the component gets focused by adding class `c4p--edit-in-place--focused`, and when you click away (remove focus or focus on another component), the focused state is removed.

But when the component has invalid input and you click away, the EditInPlace component stays focused even when it's not actually focused anymore. The focused state should be removed when component is no longer focused on, regardless of the invalid state. 

### Component(s) impacted

EditInPlace component

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.46.0

### Suggested Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

IBM Cloud Data Replication

### CodeSandbox or Stackblitz example

https://codesandbox.io/p/devbox/serene-wave-nlgmk5

### Steps to reproduce the issue (if applicable)

Reproduced here: https://codesandbox.io/p/devbox/serene-wave-nlgmk5 

## Normal scenario

Not focused
<img width="1033" alt="Screenshot 2024-08-12 at 4 22 43 PM" src="https://github.com/user-attachments/assets/21a9932d-f643-4c03-989b-562feaa5184a">

Focused
<img width="1059" alt="Screenshot 2024-08-12 at 4 24 06 PM" src="https://github.com/user-attachments/assets/f279903c-b939-47b0-b54a-8d6394059b4d">
^Clicking on EditInPlace component to edit, component is focused and `c4p--edit-in-place--focused` class is added. 

Remove focus
<img width="1072" alt="Screenshot 2024-08-12 at 4 26 58 PM" src="https://github.com/user-attachments/assets/fd990047-b227-4517-8c65-95d5580f154d">
Clicking away from EditInPlace component to remove focus, and `c4p--edit-in-place--focused` class is removed.

## Bug scenario

Not focused
Starting with same scenario above with just "abc" input.. not focused on EditInPlace component.
<img width="1050" alt="Screenshot 2024-08-12 at 4 28 49 PM" src="https://github.com/user-attachments/assets/e2d209e6-0109-4759-b646-b76958b2a034">

Focused and create invalid scenario (add numbers)
<img width="1057" alt="Screenshot 2024-08-12 at 4 30 28 PM" src="https://github.com/user-attachments/assets/23ef5743-b137-4db2-8bcd-dfeee30a05c3">
^Clickin on EditInPlace component to edit, which focuses on the component and adds `c4p--edit-in-place--focused` class.
Then added "1" to input to go into invalid state. This additionally adds `c4p--edit-in-place--invalid` class.. Both classes exist now.

Remove focus
<img width="1055" alt="Screenshot 2024-08-12 at 4 33 30 PM" src="https://github.com/user-attachments/assets/31fd8c01-5f31-4d59-b271-2cf4cdfa4cee">
First, hit the Enter key to submit/save the changes (keeping the invalid value).
At this time, technically you are no longer focused on the EditInPlace component.. but click somewhere else anyways.
The component keeps both invalid and focused state, but really it's not focused anymore.
This screenshot seems like i am still focused on the EditInPlace component, but i'm not.. If i had other components on the page, i could be clicking and typing in other fields and this would still look like this. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by AlexanderMelox** [comment]
@David-Yuen Taking a look at this, I noticed in our build and locally I can't replicate the issue but i do notice it in Codesandbox

https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-patterns-edit-and-update-editinplace--invalid&globals=viewport:basic

**Comment by AlexanderMelox** [comment]
Okay found a fix for this! That was easy 😅
