### ISSUE TITLE
[Feature Request]: Provide an option to not render the SidePanel close button

### ISSUE THREAD

**Issue by modean** [carbon-design-system/ibm-products#5856]
### The problem

Some products using the IBM Carbon Design System are using the action bar in the header to open menues or side panels. Usually the panel itself did provide a close button with an X symbol to close the panel.

Since recently the new w3 intranet page that also is based on the IBM Carbon Design System did implement a pattern, where the panel itself no longer did provide a close button. Instead the button in the action bar did turn into a close button exposing an X symbol. That way the action bar button starts to behave like a close button.

### The solution

To implement this pattern w/ the `<SidePanel />` component it would be necessary to have an option, that would allow to hide (e.g. not render) the close button of the `<SidePanel />` component. Instead the toggle button in the action bar would be used and in cases where the `<SidePanel />` component is in open state, the action bar button in the header would render an X icon.

Note: The implementation of the action bar buttons is not in scope with this feature request. The scope is just to provide an option that would allow to not render the close button of the `<SidePanel />` component.

### Links to other materials

How the close button is currently implemented if using the technique provided by the `<SidePanel />` component.

![image](https://github.com/user-attachments/assets/49199750-f9c2-4f0c-8edc-a48247301457)

How the close button would be rendered in cases where the action bar button would behave like a toggle button and thus indicating the state of the `<SidePanel />` component using an X icon if it is in open state.

![image](https://github.com/user-attachments/assets/03b2d5af-4c91-40dc-b67c-38e332b6a803)

### Owner/main maintainer(s)

???

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by oliviaflory** [comment]
Hi @modean 

If the panel is connected to the UI shell, you should be utilizing the `right panel` that is [provided in the UI shell](https://react.carbondesignsystem.com/?path=/story/components-ui-shell-header--header-w-actions-and-right-panel&globals=theme:white). Not the `side panel`

**Comment by modean** [comment]
Hi @oliviaflory 

I'd appreciate if we could focus on the feature request and thus maintain the context. If the idea is that the `<SidePanel />` must have a X icon to close it cause it was designed that way and cause it especially must not be used in the context of the Carbon UI Shell then I guess that is the correct answer to the feature request. It would then be helpful to update its documentation w/ a corresponding usage remark.

I used the `<SidePanel />` component cause it has a couple of features that otherwise would need to be implemented manually and cause its documentation does not explicitly call out, that it must not be used together with the UI Shell component. In the documentation of the `<SidePanel />` component the UI Shell is used but the `<SidePanel />` itself is triggered by a button in the content area.

The Carbon Design System styleguide is inconclusive wrt/ the close icon of the right panel. It just mentions that the icon must have an outline that flows into the panel if expanded.

**Comment by elycheea** [comment]
Hi @modean, the side panel docs do mention that it’s intended for [in-page context](https://pages.github.ibm.com/cdai-design/pal/components/side-panel/usage#when-to-use) but we can definitely take a look at improving how we’re communicating that since we don’t mention not to use it in place of the shell for when _not_ to use.

**Comment by modean** [comment]
Hi @elycheea IMO the documentation you referenced is also inconclusive. As you say the intend is not clearly communicated. If the intend is, that the `<SidePanel />` component must not be used as a drop-in replacement for the `<HeaderPanel />` component that is part of the Carbon UI Shell  then the "in-page context usage" argument becomes irrelevant. 

This especially holds true cause we are using the `<SidePanel />` component for the "Slide-in" scenario to provide context help information that depends on the main content area where the action that triggers the panel to slide-in is part of the Carbon UI Shell (help button with question mark glyph). This kind of usage is in-line with the intend as presented on the page you've just referenced.

I would also appreciate if the Carbon Design team could update their documentation.
