### ISSUE TITLE
Preserving Datagrid settings while navigating through tabs

### ISSUE THREAD

**Issue by p-szalast** [carbon-design-system/ibm-products#5888]
### Package

Carbon for IBM Products

### Description

**Issue regarding:** 
Tabs, each one contains Datagrid in it and each one has its own URL.

**When:**
1) changing row size / page / items per page on 1st Tab
2) changing Tab
3) changing back to 1st Tab

**Actual behavior:**
Settings as size, page, items per page are not preserved, but are back to default.

**Expected behavior:**
Settings as size, page, items per page are preserved for each Datagrid

### Component(s) impacted

<Datagrid>, <Tabs>

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v2.45.0

### Suggested Severity

None

### Product/offering

IBM

### CodeSandbox or Stackblitz example

https://codesandbox.io/p/devbox/youthful-tree-wh8r45?file=%2Fsrc%2FExample%2FExample.jsx

### Steps to reproduce the issue (if applicable)

On Tabs, each one contains Datagrid in it and each one has its own URL:
1) changing row size / page / items per page on 1st Tab
2) changing Tab
3) changing back to 1st Tab

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by matthewgallo** [comment]
There is a `onRowSizeChange` callback that you can use to save the row size and then pass that value to the `rowSize` property.

The pagination is a component that you provide and pass in to the `useDatagrid` hook so you should also be able to handle all of that on your end as well. You can provide an `initialState` object with pagination data as well.

```
initialState: {
  pageSize: 10,
  pageSizes: [5, 10, 25, 50],
},
```

**Comment by szymonbrandys** [comment]
@matthewgallo this issue is not only about the page size. It is also about `row size`
Is there a way to track this too? If not, please reopen the bug.

<img width="119" alt="Screenshot 2024-08-19 at 22 51 19" src="https://github.com/user-attachments/assets/a557ac5e-3f43-4add-b0b0-93d3e237d4eb">

**Comment by matthewgallo** [comment]
Yes, you can use the `onRowSizeChange` callback to save the row size and then pass that value into the `rowSize` property.
