### ISSUE TITLE
DataGrid select all doesn't work as expected

### ISSUE THREAD

**Issue by marinamas** [carbon-design-system/ibm-products#5898]
### Package

Carbon for IBM Products

### Description

- Create a DataGrid component , set  batchActions: true, 
- When select all button is clicked , it selects all the button 
- Uncheck Select All, only unselects the current page data

https://github.com/user-attachments/assets/b13e32da-23d1-42ca-b15e-9070537070a8

### Component(s) impacted

DataGrid batch action

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

"@carbon/ibm-products": "2.46.0",

### Suggested Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

NA

### CodeSandbox or Stackblitz example

https://codesandbox.io/p/sandbox/datagrid-tooltip-hover-issue-26hqww?file=%2Fsrc%2FExample.js%3A203%2C25

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by elycheea** [comment]
Thanks @marinamas for bringing this issue to office hours.

The [intended design](https://pages.github.ibm.com/cdai-design/pal/components/data-table/batchactions/usage#actions-across-multiple-pages) is that the checkbox in the column header should select the _current_ page only. This can be replicated in both in the CodeSandbox provided and the Storybook (increase rows + add pagination). 

Marina’s examples show that the initial selection _selects all items across all pages_ instead of just the current page.

**Comment by marinamas** [comment]
![image](https://github.com/user-attachments/assets/ca0248e7-e41a-4b21-b47e-47f1505e0b9e)

The use of useSelectAllWithToggle , doesn't display the tooltip properly

**Comment by elycheea** [comment]
@marinamas This is an older version of the select all and no longer recommended — our design has moved towards using the select all button in the batch actions toolbar.

**Comment by devadula-nandan** [comment]
Hi @marinamas,
could you elaborate the specific use case, you were talking about in the office hours, just to re validate it in my pr.

**Comment by marinamas** [comment]
@devadula-nandan , when using DatagridBatchActions component there is no option to select across pages

**Comment by marinamas** [comment]
> @marinamas This is an older version of the select all and no longer recommended — our design has moved towards using the select all button in the batch actions toolbar.

@elycheea In case we have an overflow component or any other complex component in the batch actions , using getBatchActions() is not feasible  .  In this case, use of DatagridBatchActions makes it convenient . But there is no way to get an option to select across all the pages while using DatagridBatchActions

![image](https://github.com/user-attachments/assets/a3fd083b-64c1-4be1-a914-ce6dd72a1763) .
We can still use useSelectAllWithToggle, but it has issues with tooltip as attached in the previous screenshots.

- We should also have an option to select across all pages in the batch even with DatagridBatchActions
