### ISSUE TITLE
Devtools support: not able to generate list of `ibm-products` components

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#5902]
### Package

Carbon for IBM Products

### Description

The [devtools repo](https://github.com/carbon-design-system/devtools) gets a list of all components to track and the way our list is generated is causing build issues, specifically the `cloud-cognitive.js` script, https://github.com/carbon-design-system/devtools/blob/base/packages/component-list/src/libraries/cloud-cognitive.js.

### Component(s) impacted

All components in our library with `devtools` extension support, which should be all released components.

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

N/A

### Suggested Severity

None

### Product/offering

Carbon devtools browser extension

### CodeSandbox or Stackblitz example

N/A

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by ljcarot** [comment]
We can uncouple from devtools to fix build issues if need be,

**Comment by matthewgallo** [comment]
This is in regards to build issues from a PR in the [devtools repo](https://github.com/carbon-design-system/devtools/pull/333) for v11 support, not directly our project. But it was the script for our components within that repo that needed to be fixed, just wanted to make sure I was tracking it here as well!
