### ISSUE TITLE
[Feature Request]: (DataGrid) Add field to hide the Actions Overflow Menu for certain rows

### ISSUE THREAD

**Issue by molyholy** [carbon-design-system/ibm-products#5903]
### The problem

Currently, when using `rowActions` in a `Datagrid`, the Overflow Menu will by default appear in every row.
<img width="404" alt="image" src="https://github.com/user-attachments/assets/6e5c81bd-9119-4d5f-a30b-43883f9ca6a4">

It would be useful to have an option that would hide the Overflow Menu for only certain rows, because it might not make sense for certain rows to have that Overflow Menu (our particular use case is explained in the "Solution" section).

I know there's a `shouldHideMenuItem` prop already, but it doesn't seem to hide the Overflow Menu itself, only the items inside. In our case, we only have one Overflow Menu item. WHich means the user can still click on the Overflow Menu, but nothing would open, which is confusing UX. [Here](https://codesandbox.io/p/sandbox/beautiful-star-dgsgfq) is a reproduction of the issue.

### The solution

Add a new prop called something like `shouldHideActionsMenu` which we can pass into a `rowActions` object, which will accept a callback with argument `row`, that way we can check if the row's properties to determine if it needs the OVerflow menu (basically works the same way as `shouldHideMenuItem`

The end result would look something like this (pardon the rectangles lol). In our case, we'd like to hide the Overflow menu for Expandable rows, so that the "parent" will not have the Overflow Menu, but any "child" row would have the Menu.
![image](https://github.com/user-attachments/assets/a87a0da6-cb99-4a51-9cd3-b7295eaedb48)

### Design link

I pulled the existing design from https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid--batch-actions&globals=viewport:basic

### Owner/main maintainer(s)

molyholy (?)

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by ljcarot** [comment]
We've been investigating [TanStack ](https://tanstack.com/table/latest)[Table](https://tanstack.com/table/latest), a third-party, open-source offering, which provides extensive data table capabilities surpassing what our Carbon Datagrid offers. It provides much more flexibility and customization. TanStack Table is headless which means it can easily be added alongside Datagrid component in your product or application. The benefits of more flexibility for product teams and less maintenance for Carbon makes it a win win. Lastly, it is available in multiple frameworks including [React](https://github.com/carbon-design-system/tanstack-carbon/tree/main/react#readme) and [Web Component](https://github.com/carbon-design-system/tanstack-carbon/tree/main/web-components#readme) so it provides an option to non-React product teams.

For these reasons, we have decided to transition from building our own custom table component to using an example-based approach with TanStack Table. Datagrid will still exist in our library for existing teams but we are announcing the deprecation* of the Datagrid component in v2.54.0 release so teams can begin to work through the transition. Details about how to use both Datagrid and TanStack together can be found [here](https://github.com/carbon-design-system/tanstack-carbon/tree/main). 

*Deprecation means that no new features will be added however sev 1 and sev 2 bugs will be supported.
