### ISSUE TITLE
[BUG] Tooltip not working on the Datagrid's "Customize columns" modal

### ISSUE THREAD

**Issue by pjborowiecki** [carbon-design-system/ibm-products#5909]
### Package

Carbon for IBM Products

### Description

Tooltip with the reminder of truncated text does not show in the Datagrid's "Customize columns". I would expect a tooltip with the sentence reminder to be displayed when hovered over "the...", since the current behaviour affects accessibility.

<img width="1543" alt="Screenshot 2024-08-21 at 10 01 57" src="https://github.com/user-attachments/assets/fa4060fb-e4f0-44d7-988f-5ae21ae61c87">

https://github.com/user-attachments/assets/bc20279e-b69a-458c-8a2b-6ce5afae62fb

### Component(s) impacted

Datagrid

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.45.0

### Suggested Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

IBM's Financial Transaction Manager

### CodeSandbox or Stackblitz example

There are several examples in your Storybook: https://ibm-products.carbondesignsystem.com/?path=/docs/ibm-products-components-datagrid-columncustomization--docs

### Steps to reproduce the issue (if applicable)

1. Pick any example with column cusomization in your story book: https://ibm-products.carbondesignsystem.com/?path=/docs/ibm-products-components-datagrid-columncustomization--docs

2. Click on the "Customize columns" icon

3. Hover over. the truncated text in the description ("the...")

4. Observe nothing happening, where the expected behaviour would be to display a tooltip with the sentence reminder

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by devadula-nandan** [comment]
something like [this](https://codepen.io/qiaoli116/pen/MqNObm) could solve this case.
