### ISSUE TITLE
[Tearsheet]: Tab key navigaton issue with Datepicker inside tearsheet

### ISSUE THREAD

**Issue by Geethkadali** [carbon-design-system/ibm-products#5910]
### Package

Carbon for IBM Products

### Description

**Expected behavior :** After selecting the start date and pressing Tab key, the focus would move directly to the end date field.

Instead, inside the tearsheet after selecting the start date and pressing the Tab key, the focus moves to the close tearsheet button/ outside of tearsheet and then returns to the start and end date fields. Outside the tearsheet, the focus correctly moves to the end date field as expected

### Component(s) impacted

https://stackblitz.com/edit/github-pjo2fh-rm6wjm?file=src%2FApp.jsx,package.json

https://github.com/user-attachments/assets/31d0c9c5-7be1-4deb-a780-3f9094c58601

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.47.0

### Suggested Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

Accessible Workplace Connection

### CodeSandbox or Stackblitz example

https://stackblitz.com/edit/github-pjo2fh-rm6wjm?file=src%2FApp.jsx,package.json

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by neambati** [comment]
Hi Amal, Could you please confirm on the fix status.

**Comment by makafsal** [comment]
@neambati @Geethkadali Our review of your implementation has revealed that passing the value `[undefined, undefined]` or `['', '']` to the `value` property of the DatePicker component results in unexpected behaviour.  This appears to be an issue with the DatePicker component itself, and I will raise an issue in the Carbon repository.

However, please see a workaround for a quick fix: https://stackblitz.com/edit/github-pjo2fh-kxgqiv?file=src%2FApp.jsx
```
// No need to pass an empty string ('')
const [startValue, setStartValue] = useState();
const [endValue, setEndValue] = useState();

...
<DatePicker
  value={
    startValue && endValue ? [startValue, endValue] : undefined
  }
>
...
```



https://github.com/user-attachments/assets/b3e374f8-dd54-4b46-90c6-185d17437ba4

**Comment by makafsal** [comment]
@elycheea Raised an issue related to DatePicker in the Carbon: https://github.com/carbon-design-system/carbon/issues/17310

**Comment by Geethkadali** [comment]
@amal-k-joy, on press Tab key after selection of only start date the focus moves to close tearsheet and also there is some glitch in firefox on Tab press from close tearsheet ,the whole tearsheet content is getting focused instead of the primary selector


https://github.com/user-attachments/assets/ba094a7f-a8e6-46b8-806f-2f7a769542e5



![image](https://github.com/user-attachments/assets/73cae3d8-d383-48a0-9d8d-a81938bcace6)

**Comment by makafsal** [comment]
@Geethkadali Firefox focuses on scrollable `div`, this issue is addressed in this [PR](https://github.com/carbon-design-system/ibm-products/pull/5973) - it'll be available in the Sep 25 release.

**Comment by Geethkadali** [comment]
Thank you
