### ISSUE TITLE
[Datagrid]: using MultiSelect filtering with instant update is broken

### ISSUE THREAD

**Issue by davidmenendez** [carbon-design-system/ibm-products#5935]
### Package

Carbon for IBM Products

### Description

i discovered this after discussing a separate issue from slack:

* in order to be more aligned with carbon functionality `MultiSelect` should be passing the entire `event` object to the consumer and not just `{ selectedItems }`

while investigating i also discovered these:

* using `MultiSelect` with batch filtering throws a console warning: `Warning: Cannot update a component ('FilterFlyout') while rendering a different component ('MultiSelect'). To locate the bad setState() call inside 'MultiSelect', follow the stack trace as described in...`
* using `MultiSelect` with instant filtering breaks the app `a.filter is not a function`

### Component(s) impacted

`Datagrid`

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.47

### Suggested Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Product/offering

ibm products

### CodeSandbox or Stackblitz example

https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-filtering-panel--panel-instant&globals=viewport:basic

### Steps to reproduce the issue (if applicable)

for the broken instant update:

go to the [storybook](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-filtering-panel--panel-instant&globals=viewport:basic), open the filter, and select an option under one of the multi select drop downs.

for the batch update warning:

*this only appears locally*. run storybook locally and open the [batch update story](http://localhost:3000/?path=/story/ibm-products-components-datagrid-filtering-panel--panel-batch&globals=viewport:basic). select an option from one of the multi select drop downs.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by davidmenendez** [comment]
<img width="1728" alt="Screenshot 2024-08-27 at 4 18 23 PM" src="https://github.com/user-attachments/assets/e23217c3-3f75-4cfb-8635-dc2821ec4ab5">

**Comment by elycheea** [comment]
@AlexanderMelox If you self-assign, make sure to add to backlog and add estimate. :)
