### ISSUE TITLE
[ProductiveCard]: Primary action ghost button styling is wrong

### ISSUE THREAD

**Issue by kenneth-nguyen1** [carbon-design-system/ibm-products#5956]
### Package

Carbon for IBM Products

### Description

When adding a primary button with icon to the ProductiveCard, I expected the icon fill color to match the button's blue text color and there to be spacing between the text and icon.

What actually happened is there was no spacing between the text and icon, and the icon was a black fill color. Screenshots below of expected (Storybook visual) and actual (Stackblitz demo)

### Component(s) impacted

Stackblitz link: https://stackblitz.com/edit/github-o7f1cm?file=src%2FExample%2FExample.jsx

![card-action-ghost-button-stackblitz](https://github.com/user-attachments/assets/13244246-9153-46f5-affa-941d2088298a)

Storybook link: https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-cards-productivecard--with-action-ghost-button&args=primaryButtonDisabled:!false;actionsPlacement:top&globals=viewport:basic

![card-action-ghost-button-storybook](https://github.com/user-attachments/assets/5c3f9903-01f7-43b1-8c48-09be2766c52b)

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

^2.26.0

### Suggested Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

Fusion

### CodeSandbox or Stackblitz example

https://stackblitz.com/edit/github-o7f1cm?file=src%2FExample%2FExample.jsx

### Steps to reproduce the issue (if applicable)

Add props to the ProductiveCard component to render a primary button with icon, either placement on top or bottom will both show the issue.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by AlexanderMelox** [comment]
@kenneth-nguyen1 there is a workaround for this, you can just pass in the Icon as a reference to the prop and it should have the right styling 

```
```

**Comment by AlexanderMelox** [comment]
![Image](https://github.com/user-attachments/assets/f78d55a9-c711-45ae-8466-545a8ac1e726)
