### ISSUE TITLE
[Chart]: Cannot able to customise chart labels for x axis and y axis

### ISSUE THREAD

**Issue by sheejajoni** [carbon-design-system/ibm-products#5974]
### Package

Carbon for IBM Products

### Description

In carbon charts it is not possible to customise the labels for x axis and y axis. Based on the data provided the axis are labelled automatically. Need a way to customise these labels.
<img width="796" alt="carbon-chart" src="https://github.com/user-attachments/assets/68a12cce-2f2c-453b-a33e-26e9bc49cf96">

### Component(s) impacted

Widget chart

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

V2.34.0

### Suggested Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

Infrastructure

### CodeSandbox or Stackblitz example

https://stackblitz.com/run?file=src%2Findex.js

### Steps to reproduce the issue (if applicable)

1. Add area chart
2. Supply data points
3. Based on the value supplied, the axis labels are plotted

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by amal-k-joy** [comment]
Hi @elycheea , 
This looks like an issue for Carbon Charts. Could we transfer this issue ?

**Comment by elycheea** [comment]
@sheejajoni I would check the [Carbon Charts documentation](https://charts.carbondesignsystem.com) and also check for any existing issues in their repository. If not covered, I would open this as an [enhancement request](https://github.com/carbon-design-system/carbon-charts/issues/new?assignees=&labels=enhancement&projects=&template=ENHANCEMENT.yaml&title=%5BEnhancement%5D%3A+) on their repo!
