### ISSUE TITLE
[Feature Request]: Add custom svg slot on `FullPageError` for custom error pages

### ISSUE THREAD

**Issue by stefan-cooper** [carbon-design-system/ibm-products#5975]
### The problem

I want to create a custom `FullPageError` for different error codes other than 404 and 403, and I want to use a different svg for each one.

### The solution

Add a new optional custom slot/parameter for svgs that can be used when the kind is `custom`. If not provided, then it will use the existing behavior

### Owner/main maintainer(s)

.

### Product/offering

IBM Event Endpoint Management

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by kingtraceyj** [comment]
@stefan-cooper do you mind sharing your imagery with us so we can understand a little more about the use case?

**Comment by jeanservaas** [comment]
@stefan-cooper just to clarify, we've chosed this suite of line-drawn monochromatic imagery specifically for these error states. This was discussed extensively in DSAG. If you want to contribute another illustration to this suite, that'd be awesome, and I'd take it up with Colleen Yates and the illustration guild. We'd like to avoid introducing other styles (full-color etc) in these scenarios for consistency. 

If there's something you feel like we're not considering here, please come to office hours to discuss. Thanks so much!
