### ISSUE TITLE
Dynamic nested rows skeleton always showing regardless of dynamic prop being set

### ISSUE THREAD

**Issue by jeesonjohnson** [carbon-design-system/ibm-products#5983]
### Package

Carbon for IBM Products

### Description

When using a nested row with the DataGrid component, we continuously see a loading skeleton beneath the nested rows, when there are more than 2 levels of nesting. 

See video below for visual example:

https://github.com/user-attachments/assets/4dae9bb6-5471-4211-a486-76e5f14e938a

We have identified that the reason for breakage, is due to changes made in [this PR](https://github.com/carbon-design-system/ibm-products/pull/5735). Even though in our code we do not supply the `getAsyncSubRows` rows prop to the table, we see related behaviour within our component. Specifically, this line of the [code](https://github.com/carbon-design-system/ibm-products/blob/main/packages/ibm-products/src/components/Datagrid/useNestedRowExpander.js#L50). We got it working locally by disabling this if statement, and checking for the `getAsyncSubRows` props is defined. 

### Component(s) impacted

DataGrid component

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.48.0

### Suggested Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

CloudPakForIntegration (CP4I)

### CodeSandbox or Stackblitz example

na

### Steps to reproduce the issue (if applicable)

Have multiple nested rows on a DataGrid component, without the `getAsyncSubRows` prop defined. Expand all rows and see the loading skeleton be rendered. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by amal-k-joy** [comment]
Hey @jeesonjohnson ,
Could you pease provide a codesandbox/ stackblitz with a minimal reproduction, so that we could assist better?

**Comment by jeesonjohnson** [comment]
Hi @amal-k-joy, I have attached an instance of the broken code-sandbox [here](https://codesandbox.io/p/devbox/sleepy-sunset-22cnkm?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0m4vg6f00083b6myiqkin6g%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0m4vg6f00033b6mkfi5487c%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0m4vg6f00053b6m7fnkamdy%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0m4vg6f00073b6m39tqr89k%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0m4vg6f00033b6mkfi5487c%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0m4vg6f00023b6mhb3kj7nk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FExample%252FExample.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm0m4vg6f00033b6mkfi5487c%2522%252C%2522activeTabId%2522%253A%2522cm0m4vg6f00023b6mhb3kj7nk%2522%257D%252C%2522cm0m4vg6f00073b6m39tqr89k%2522%253A%257B%2522id%2522%253A%2522cm0m4vg6f00073b6m39tqr89k%2522%252C%2522activeTabId%2522%253A%2522cm0m4vk2l00103b6m5jqsq1dt%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0m4vg6f00063b6m6jipsyv9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cm0m4vk2l00103b6m5jqsq1dt%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm0m4vg6f00053b6m7fnkamdy%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0m4vg6f00043b6m39j7m7h4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522cm0m4vg6f00053b6m7fnkamdy%2522%252C%2522activeTabId%2522%253A%2522cm0m4vg6f00043b6m39j7m7h4%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

As is indicated by my comment, the error persists when the `getSubRows: (row) => row.subRows` function is removed from the resource table props. This was not previously the case.
