### ISSUE TITLE
[Feature Request]: Condition builder: Allow component in properties label

### ISSUE THREAD

**Issue by rahulrkr08** [carbon-design-system/ibm-products#6025]
### The problem

Currently, condition builder properties labels allow only string. This request is to enable components in the properties label.

### The solution

Expected:
```
<ConditionBuilder
   ...
   inputConfig={{
    properties: [{
      ...,
      label: (
        <>
          <Tag>System</Tag>
          <span>Name</span>
        </>
    }],
  }}
/>
```

### Owner/main maintainer(s)

na

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by oliviaflory** [comment]
Hi @rahulrkr08 thanks for the feature request!

Could you provide any more detail about where you'd like the tag to be placed and what it's intention would be in the condition builder?

---

1. Would a tag appear within the Properties dropdown menu? (see pink arrow) 
2. Would there be only one tag or multiple tags allowed? 
3. If there are multiple tags, are there multiple tags on a single item? Or is it a single tag per item and the tags could say different things?
![Image](https://github.com/user-attachments/assets/ba94bd96-7981-41fa-8c57-7cc6afcaee11)

4. Would the tag appear in the string once the Property is selected? ie after `Color`
![Image](https://github.com/user-attachments/assets/37fc3871-7d9e-4634-b003-e96af8e092a0)

**Comment by rahulrkr08** [comment]
Hi @oliviaflory, Appreciate your effort in reviewing this feature request.

The idea behind this request is to have grouped properties. For example, some applications may have system-generated properties and user-created properties. 

- **properties Grouped:**
  <img width="391" alt="image" src="https://github.com/user-attachments/assets/536de094-b339-40bd-87a0-3f48fd396823">

- **Properties with tags:**
  <img width="485" alt="image" src="https://github.com/user-attachments/assets/efdc802d-1ad2-4d8c-a98f-6b738e26b18a">

- **properties grouped with expand / collapsible**
  <img width="313" alt="Screenshot 2024-09-17 at 6 42 07 PM" src="https://github.com/user-attachments/assets/e38d7cda-525a-46d7-9991-8003f7ba3aa9">

Also, I would like to extend this request to have a description of the property like the below screenshot. This will help to show fields or attributes with their unique key (see 2nd screenshot).

- Property with description
  <img width="524" alt="Screenshot 2024-09-17 at 6 42 46 PM" src="https://github.com/user-attachments/assets/59803ce7-06d1-4d86-bc4a-8f9e8e575972">

- Property with key
  <img width="366" alt="image" src="https://github.com/user-attachments/assets/68868955-8f8a-4530-8ca6-e2da05e2de9b">

Hope the above description might give you more idea about this request.
