### ISSUE TITLE
Datagrid: toggleRowSelected undefined error

### ISSUE THREAD

**Issue by wkeese** [carbon-design-system/ibm-products#6033]
### Package

Carbon for IBM Products

### Description

There's a race condition in Datagrid where clicking the "select all" checkbox gives an error about `toggleRowSelected()` being undefined.

`useDisableSelectRow()` depends on `row.toggleRowSelected()` being defined.

And react-table's `prepareRow()` function **does** define it.

However, the definition later gets erased.

The pertinent operations are:

1. `useTable()` (re)defines `instance.rows` with the original row (without any `toggleRowSelected()`):

    ```js
    Object.assign(getInstance(), {
      rows: rows,
      initialRows: [].concat(rows),
      flatRows: flatRows,
      rowsById: rowsById // materializedColumns,
    });
    ```

2. `useSelectRows()` creates new row objects (still without any `toggleRowSelected()`):

    ```js
    const { rows } = instance;
    const rowsWithSelect = rows.map((row) => ({ ...row, isSelectable: true }));
    Object.assign(instance, { rows: rowsWithSelect });
    ```

3. `DatagridSimpleBody`, `DatagridRefBody`, and `DatagridVirtualBody` call `prepareRow()`.

    ```js
      {rows.map((row) => {
        prepareRow(row);
        const { key } = row.getRowProps();
        return row?.RowRenderer?.({ ...datagridState, row, key });
      })}
    ```
    ... and `prepareRow()` assigns `toggleRowSelected`:

    ```js
    row.toggleRowSelected = function (set) {
      return instance.toggleRowSelected(row.id, set);
    };
    ```

All these operations happen many times during the display of a table, at least a table with server-side data that temporarily displays a skeleton.

However, in the end, the work down by `prepareRow()` is erased because `useTable()` and `useSelectRows() `run last:

The end of my console.logs show the timing (in our app):

```
react-table.development.js:3798 prepareRow$3, set row.toggleSelected {id: '0', original: {…}, index: 0, depth: 0, cells: Array(13), …}
react-table.development.js:3798 prepareRow$3, set row.toggleSelected {id: '1', original: {…}, index: 1, depth: 0, cells: Array(13), …}
react-table.development.js:1122 useTable, assigning instance.rows (2) [{…}, {…}]
useSelectRows.js:29 useSelectRows, set instance.rows to (2) [{…}, {…}]
react-table.development.js:3190 usePagination, set page from (2) [{…}, {…}]
useDisableSelectRows.js:58 useDisableSelectRows --> updatePageSelectAll, set selectableRows to (2) [{…}, {…}]
react-table.development.js:1122 useTable, assigning instance.rows (2) [{…}, {…}]
useSelectRows.js:29 useSelectRows, set instance.rows to (2) [{…}, {…}]
react-table.development.js:3190 usePagination, set page from (2) [{…}, {…}]
```
__

### Component(s) impacted

Datagrid

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.46

### Suggested Severity

None

### Product/offering

IKC

### CodeSandbox or Stackblitz example

https://stackblitz.com/edit/github-yzz9j5?file=src%2FExample%2FExample.jsx

### Steps to reproduce the issue (if applicable)

I tried to reproduce the problem but I couldn't get the race condition to fail in Stackblitz.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by wkeese** [comment]
I worked around the problem by creating a custom plugin and added it to `endPlugins[]`:

```js
import { Hooks, TableInstance } from "react-table";

/**
 * Call prepareRow() on each row to workaround race condition where toggleRowSelected() is undefined when user clicks
 * the "select all" checkbox.  See https://github.com/carbon-design-system/ibm-products/issues/6033.
 */
const usePrepareRow = (hooks: Hooks) => {
  const useInstance = (instance: TableInstance) => {
    const { rows, prepareRow } = instance;
    for (const row of rows) prepareRow(row);
  };
  hooks.useInstance.push(useInstance);
};

export default usePrepareRow;
```

Not sure if I should be updating `rows` or `page` though.  But anyway, maybe `prepareRow()` should be called from a plugin rather than from the components like `DatagridSimpleBody`.

**Comment by ljcarot** [comment]
We've been investigating [TanStack ](https://tanstack.com/table/latest)[Table](https://tanstack.com/table/latest), a third-party, open-source offering, which provides extensive data table capabilities surpassing what our Carbon Datagrid offers. It provides much more flexibility and customization. TanStack Table is headless which means it can easily be added alongside Datagrid component in your product or application. The benefits of more flexibility for product teams and less maintenance for Carbon makes it a win win. Lastly, it is available in multiple frameworks including [React](https://github.com/carbon-design-system/tanstack-carbon/tree/main/react#readme) and [Web Component](https://github.com/carbon-design-system/tanstack-carbon/tree/main/web-components#readme) so it provides an option to non-React product teams.

For these reasons, we have decided to transition from building our own custom table component to using an example-based approach with TanStack Table. Datagrid will still exist in our library for existing teams but we are announcing the deprecation* of the Datagrid component in v2.54.0 release so teams can begin to work through the transition. Details about how to use both Datagrid and TanStack together can be found [here](https://github.com/carbon-design-system/tanstack-carbon/tree/main). 

*Deprecation means that no new features will be added however sev 1 and sev 2 bugs will be supported.
