### ISSUE TITLE
TagSet breaks visuals of StructuredList

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/ibm-products#6034]
### Package

Carbon for IBM Products

### Description

When nesting a `TagSet` inside a `StructuredListCell`, the bottom border of the cells that don't contain a TagSet are broken.

This seems to only happen in Safari. Using regular `<Tag>`s don't cause this issue.

### Component(s) impacted

TagSet

### Browser

Safari

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.49.0-rc.0

### Suggested Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

watsonx.governance

### CodeSandbox or Stackblitz example

https://stackblitz.com/edit/github-ytnhnj?file=src%2FExample%2FExample.jsx

### Steps to reproduce the issue (if applicable)

In Safari:
<img width="641" alt="image" src="https://github.com/user-attachments/assets/86c30dc1-27d9-41fb-9754-33a500f8f9a4">

In Edge:
<img width="698" alt="image" src="https://github.com/user-attachments/assets/29eab078-1af4-44c7-b15c-45ff46f94464">

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by amal-k-joy** [comment]
Hey @janhassel ,
As I investigated this issue, this is no way related to Tagset. `<StructuredList>` in carbon is using `table display`. Any div with a margin inside a table cell cause this odd behaviour in Safari browser, which I think is a known [browser issue](https://github.com/tailwindlabs/tailwindcss/issues/8869). However they are suggesting a work around by setting `vertical-align to top, middle, or bottom` seems to remove the extra border for the cds--structured-list-td. 

https://github.com/user-attachments/assets/a48a107f-83fb-4b03-a790-3a268b8cb229

**Comment by amal-k-joy** [comment]
Please re-open if you feel any fix is required from our side.

**Comment by janhassel** [comment]
Thanks @amal-k-joy! I moved it to core: https://github.com/carbon-design-system/carbon/issues/17667
