### ISSUE TITLE
Toggletip in Datagrid header doesn't work when using useSortableColumns

### ISSUE THREAD

**Issue by molyholy** [carbon-design-system/ibm-products#6044]
### Package

Carbon for IBM Products

### Description

A common design pattern is putting a Toggletip in the header of a Datagrid to provide more info. Normally, this works fine, however, it breaks when you use `useSortableColumns`. When you go to click on the Toggletip, the row sorting function will take "precendence," so you can't open the Toggletip.

### Component(s) impacted

Datagrid
Toggletip (from @carbon/react)

### Browser

Firefox

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

^1

### Suggested Severity

None

### Product/offering

IBM Cloud

### CodeSandbox or Stackblitz example

https://codesandbox.io/p/sandbox/reverent-gianmarco-jzqnn9

### Steps to reproduce the issue (if applicable)

Open the CodeSandbox. Observe how when you click on the "x" button in the Datagrid header, the Toggletip content will not open.

Then remove `useSortableColumns` from the Datagrid's state. Observe how clicking on the "x" Toggletip button will now open the content as expected.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by ljcarot** [comment]
We've been investigating [TanStack ](https://tanstack.com/table/latest)[Table](https://tanstack.com/table/latest), a third-party, open-source offering, which provides extensive data table capabilities surpassing what our Carbon Datagrid offers. It provides much more flexibility and customization. TanStack Table is headless which means it can easily be added alongside Datagrid component in your product or application. The benefits of more flexibility for product teams and less maintenance for Carbon makes it a win win. Lastly, it is available in multiple frameworks including [React](https://github.com/carbon-design-system/tanstack-carbon/tree/main/react#readme) and [Web Component](https://github.com/carbon-design-system/tanstack-carbon/tree/main/web-components#readme) so it provides an option to non-React product teams.

For these reasons, we have decided to transition from building our own custom table component to using an example-based approach with TanStack Table. Datagrid will still exist in our library for existing teams but we are announcing the deprecation* of the Datagrid component in v2.54.0 release so teams can begin to work through the transition. Details about how to use both Datagrid and TanStack together can be found [here](https://github.com/carbon-design-system/tanstack-carbon/tree/main). 

*Deprecation means that no new features will be added however sev 1 and sev 2 bugs will be supported.
