### ISSUE TITLE
[DataGrid]: Cell doesn't leave edit state when we click out of it when inside the table  

### ISSUE THREAD

**Issue by AustinGitHub** [carbon-design-system/ibm-products#6045]
### Package

Carbon for IBM Products

### Description

When we click out of the cell it should go back to the static cell 

https://github.com/user-attachments/assets/dc433dbd-33cf-494e-a88c-46bb57943684

### Component(s) impacted

Datagrids

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.46.0

### Suggested Severity

None

### Product/offering

NextGen DataStage

### CodeSandbox or Stackblitz example

N/A

### Steps to reproduce the issue (if applicable)

See video

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by AustinGitHub** [comment]
I don't have time on my end to take further look into this, can someone please take a look? Thanks!

**Comment by ljcarot** [comment]
We've been investigating [TanStack ](https://tanstack.com/table/latest)[Table](https://tanstack.com/table/latest), a third-party, open-source offering, which provides extensive data table capabilities surpassing what our Carbon Datagrid offers. It provides much more flexibility and customization. TanStack Table is headless which means it can easily be added alongside Datagrid component in your product or application. The benefits of more flexibility for product teams and less maintenance for Carbon makes it a win win. Lastly, it is available in multiple frameworks including [React](https://github.com/carbon-design-system/tanstack-carbon/tree/main/react#readme) and [Web Component](https://github.com/carbon-design-system/tanstack-carbon/tree/main/web-components#readme) so it provides an option to non-React product teams.

For these reasons, we have decided to transition from building our own custom table component to using an example-based approach with TanStack Table. Datagrid will still exist in our library for existing teams but we are announcing the deprecation* of the Datagrid component in v2.54.0 release so teams can begin to work through the transition. Details about how to use both Datagrid and TanStack together can be found [here](https://github.com/carbon-design-system/tanstack-carbon/tree/main). 

*Deprecation means that no new features will be added however sev 1 and sev 2 bugs will be supported.
