### ISSUE TITLE
[Feature Request]: Use custom empty state image in Datagrid component

### ISSUE THREAD

**Issue by allisonishida** [carbon-design-system/ibm-products#6052]
### The problem

I want to be able to use a custom image for my Datagrid's empty state

### The solution

Add a prop to pass a custom empty state image

### Owner/main maintainer(s)

Unknown

### Product/offering

IBM Concert

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by oliviaflory** [comment]
Hi @allisonishida thank you for your feature request

The Design System Adoption Guild has put in a lot of effort to ensure that empty states are consistent across all IBM Products.

Can you share your custom image and the justification for why a custom image would benefit your users for us to evaluate this request? 

Thank you!

**Comment by allisonishida** [comment]
Thanks for the response @oliviaflory. By default we have the box empty state image, and I was looking for the magnifying glass empty state image. @wkeese informed me of the `emptyStateType` parameter on Slack which is what I was looking for. I don't think a custom image is necessary so I'll close out this issue, but can the `emptyStateType` be documented in the Storybook?

**Comment by oliviaflory** [comment]
@allisonishida  is there something beyond the current [empty state story](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid--empty-state&globals=viewport:basic) that you are looking for?
