### ISSUE TITLE
Dynamic nested rows - conditionally needs to hide expand button when subrows is not present for the row.

### ISSUE THREAD

**Issue by Rakesh-Addepalle** [carbon-design-system/ibm-products#6059]
### Package

Carbon for IBM Products

### Description

I'm working with the Data grid component, which includes nested rows where subrows are loaded dynamically. I need help implementing a way to conditionally hide the expand button for rows that don't have subrows.

I found this line of code causing the issue https://github.com/carbon-design-system/ibm-products/blob/1149ec6507a47fb034f6c2f31287ef7c59975399/packages/ibm-products/src/components/Datagrid/useNestedRowExpander.js#L78.

We are currently checking both row.canExpand and getAsyncSubRows. Can we rely solely on row.canExpand to display the expand button?

### Component(s) impacted

DataGrid component

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.49.0

### Suggested Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

OpenPages

### CodeSandbox or Stackblitz example

https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-nestedrows--dynamic-nested-row-story&globals=viewport:basic

### Steps to reproduce the issue (if applicable)

Have multiple nested rows on a DataGrid component, with getAsyncSubRows prop defined. Rows which doesn't have subRows property or subRows is empty still showing expand button.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by ljcarot** [comment]
We've been investigating [TanStack ](https://tanstack.com/table/latest)[Table](https://tanstack.com/table/latest), a third-party, open-source offering, which provides extensive data table capabilities surpassing what our Carbon Datagrid offers. It provides much more flexibility and customization. TanStack Table is headless which means it can easily be added alongside Datagrid component in your product or application. The benefits of more flexibility for product teams and less maintenance for Carbon makes it a win win. Lastly, it is available in multiple frameworks including [React](https://github.com/carbon-design-system/tanstack-carbon/tree/main/react#readme) and [Web Component](https://github.com/carbon-design-system/tanstack-carbon/tree/main/web-components#readme) so it provides an option to non-React product teams.

For these reasons, we have decided to transition from building our own custom table component to using an example-based approach with TanStack Table. Datagrid will still exist in our library for existing teams but we are announcing the deprecation* of the Datagrid component in v2.54.0 release so teams can begin to work through the transition. Details about how to use both Datagrid and TanStack together can be found [here](https://github.com/carbon-design-system/tanstack-carbon/tree/main). 

*Deprecation means that no new features will be added however sev 1 and sev 2 bugs will be supported.
