### ISSUE TITLE
[Feature Request]: Add selectedRowIds as a property for Datagrid's state

### ISSUE THREAD

**Issue by JoshPF** [carbon-design-system/ibm-products#6068]
### The problem

In our implementation of Datagrid, we need a way to override the default row selection, and would like to be able to pass in our own list of selectedRowIds as a prop to state (rather than only initialState).

### The solution

We'd like a property to be added to `datagridState.state` for selectedRowIds so we can override the default selection behavior and can manually control the list of selectedRowIds, rather than letting it be handled internally by Datagrid.

Some other Carbon components offer a similar property, including the old v10 carbon-addons-iot Table component (which is no longer supported, and the documentation recommends you switch to Datagrid when upgrading to v11)

### Design link

[Example of this in the v10 `carbon-addons-iot` package](https://github.com/carbon-design-system/carbon-addons-iot-react/blob/next/packages/react/src/components/Table/Table.jsx) (Ctrl+F for `selectedIds`)

### Owner/main maintainer(s)

Matthew Gallo

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by ljcarot** [comment]
We've been investigating [TanStack ](https://tanstack.com/table/latest)[Table](https://tanstack.com/table/latest), a third-party, open-source offering, which provides extensive data table capabilities surpassing what our Carbon Datagrid offers. It provides much more flexibility and customization. TanStack Table is headless which means it can easily be added alongside Datagrid component in your product or application. The benefits of more flexibility for product teams and less maintenance for Carbon makes it a win win. Lastly, it is available in multiple frameworks including [React](https://github.com/carbon-design-system/tanstack-carbon/tree/main/react#readme) and [Web Component](https://github.com/carbon-design-system/tanstack-carbon/tree/main/web-components#readme) so it provides an option to non-React product teams.

For these reasons, we have decided to transition from building our own custom table component to using an example-based approach with TanStack Table. Datagrid will still exist in our library for existing teams but we are announcing the deprecation* of the Datagrid component in v2.54.0 release so teams can begin to work through the transition. Details about how to use both Datagrid and TanStack together can be found [here](https://github.com/carbon-design-system/tanstack-carbon/tree/main). 

*Deprecation means that no new features will be added however sev 1 and sev 2 bugs will be supported.
