### ISSUE TITLE
Data grid extension editable cells : Error states of editable cells are not persistent in data grid. 

### ISSUE THREAD

**Issue by SwatiKat** [carbon-design-system/ibm-products#6072]
### Package

Carbon for IBM Products

### Description

**What happens** : When a user tries to enter or select entries which are not valid or are out of range in a editable cell (text input, number inputs) the validation error is only visible on editable and focus state and once the user moves to other cells in the table it disappears.

**Ideal case** : The error state needs to persist such that users know that the cell is still unresolved and needs attention. 

<img width="1158" alt="image" src="https://github.com/user-attachments/assets/9191194f-635d-4341-addb-751ec125097d">

<img width="1138" alt="image" src="https://github.com/user-attachments/assets/c33bcf8b-a443-4e5a-bb08-1ceb01941a9c">

https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-editablecell--editable-cell-usage-story&globals=viewport:basic

### Component(s) impacted

Editable cells of data table extensions which allow text,number, dropdown selection entries

### Browser

Firefox

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v2.50.0-rc.0

### Suggested Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Product/offering

IBM Power HMC

### CodeSandbox or Stackblitz example

https://codesandbox.io/p/sandbox/datagrid-tooltip-hover-issue-forked-qhxrpy

### Steps to reproduce the issue (if applicable)

1. Click on editable cell with either number input or text input
2. Provide an out of range or incorrect entry, you will see that the cell throws a validation error
3. Once you move out of the cell without resolving the error, the error state disappears and the user might forget this error is still present and unresolved. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by ljcarot** [comment]
We've been investigating [TanStack ](https://tanstack.com/table/latest)[Table](https://tanstack.com/table/latest), a third-party, open-source offering, which provides extensive data table capabilities surpassing what our Carbon Datagrid offers. It provides much more flexibility and customization. TanStack Table is headless which means it can easily be added alongside Datagrid component in your product or application. The benefits of more flexibility for product teams and less maintenance for Carbon makes it a win win. Lastly, it is available in multiple frameworks including [React](https://github.com/carbon-design-system/tanstack-carbon/tree/main/react#readme) and [Web Component](https://github.com/carbon-design-system/tanstack-carbon/tree/main/web-components#readme) so it provides an option to non-React product teams.

For these reasons, we have decided to transition from building our own custom table component to using an example-based approach with TanStack Table. Datagrid will still exist in our library for existing teams but we are announcing the deprecation* of the Datagrid component in v2.54.0 release so teams can begin to work through the transition. Details about how to use both Datagrid and TanStack together can be found [here](https://github.com/carbon-design-system/tanstack-carbon/tree/main). 

*Deprecation means that no new features will be added however sev 1 and sev 2 bugs will be supported.
