### ISSUE TITLE
Research current code coverage approach from core team

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#6107]
There’s likely still some smaller amount of research needed on our end to understand how this fits into our library and whether we’ll need some modifications from Core’s implementation of this.

```[tasklist]
### Tasks
- [x] Review [code coverage playback](https://ibm-my.sharepoint.com/:v:/r/personal/sstrubberg_us_ibm_com/Documents/Recordings/Demo%20Day%20_%20Sprint%20Kickoff-20240912_100656-Meeting%20Recording.mp4?csf=1&web=1&e=1dcTxJ&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifSwicGxheWJhY2tPcHRpb25zIjp7InN0YXJ0VGltZUluU2Vjb25kcyI6MTE2NS4xN319) from previous demo day
- [ ] Determine how we can implement the same or comparable checks in our library
```

**Comment by AlexanderMelox** [comment]
**Notes:** 

Q: What is Codecov?
A: Codecov is the all-in-one code coverage and quality solution for any test suite — giving developers actionable insights to deploy reliable code with confidence.

Q: How does this improve our current workflow?
A: Codecov allows us to be more aware of our test coverage whenever we create a PR. When we make a PR we will see the code coverage changes and we can be reminded to add tests for a new feature we implemented or a change in code.

It looks like we only need to add 1 new file, `codecov.yml` and update our `ci.yml`. 
[🔗 PR from Carbon core](https://github.com/carbon-design-system/carbon/pull/17304/files).

Overall the process looks straight forward.
