### ISSUE TITLE
PageHeader error: Error Maximum update depth exceeded when rendering the PageHeader

### ISSUE THREAD

**Issue by ofovweewere** [carbon-design-system/ibm-products#6110]
### Package

Carbon for IBM Products

### Description

In Next.js 13 and later, when using a loading page by adding loading.js to src/app/loading and export default observer(MyComponent) for a component (where observer is a MobX observer), an error occurs if MyComponent has a PageHeader child.

Note that the error dissappears if we delete src/app/loading

Finally, it doesn't matter whether loading.js returns some content or just returns null; the bug still occurs as long as there is a loading file present.
![image](https://github.com/user-attachments/assets/5764673a-4456-4d11-84fe-99b894271b0f)

### Component(s) impacted

PageHeader

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.11.2

### Suggested Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Product/offering

An AI product

### CodeSandbox or Stackblitz example

https://stackblitz.com/edit/nextjs-y2tf9z?file=app%2Flayout.tsx,app%2Floading.tsx,app%2Fpage.tsx,views%2Fheader%2FHeader.js,package.json,next.config.js,app%2Fglobals.css

### Steps to reproduce the issue (if applicable)

The steps can be seen in the Stackblitz example

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by amal-k-joy** [comment]
Looks like the issue will resolve when we define the breadcrumbs array outside the <Header> component or pass as prop from page component.  The breadcrumbs array may get recreated every time when the component re-renders which in-turn will re-render the Pageheader which leads to infinite re-render since we are listening to breadcrumbs array changes.

![image](https://github.com/user-attachments/assets/75579d48-a140-46cf-9b3b-72aac8d77353)
