### ISSUE TITLE
Work with `@carbon/react` team to determine shared codemods approach

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#6156]
Following up on earlier conversations on codemods. Think this would be a good opportunity for cross-pollination.

- [x] Work with `@carbon/react` team to determine developer experience of codemods in a single package
- [x] Work with `@carbon/react` team to investigate how `ibm-products` codemods appear in `@carbon/upgrade`
- [x] Continue refinement of #6126

**Comment by tay1orjones** [comment]
@elycheea Housing them in `@carbon/upgrade` in the monorepo makes sense to me 👍 I don't see a benefit of duplicating all the required infrastructure into this repo when you're going to have to manually author before/after test fixtures anyway.

To differentiate them we could start with a naming convention for the codemod(s): `ibm-products-*`

If/when the time comes we could do an onboarding/kickoff with y'all, myself, @2nikhiltom and @riddhybansal 🥳

**Comment by sangeethababu9223** [comment]
We had a discussion with the core carbon team about codemod implmentation for `ibm-products` and has also refined the epic issue for codemods. 
We'll be starting with codemod scripts mentioned in the epic.
