### ISSUE TITLE
Review Experimental components

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-products#6159]
Review all the Experimental/Preview components and determine next steps. We will document next steps in Airtable or open new issues

#### Participants:
Linda, Matt, Elysia, David, Olivia

### Components

- [x] Action bar
- [x] Big numbers
- [x] Coachmark
- [x] Condition builder
- [x] Data spreadsheet
- [x] Delimited list
- [x] Description list
- [x] Filter panel
- [x] Nav
- [x] Scroll gradient
- [x] Search bar
- [x] Status indicator
- [x] String formatter
- [x] Tag overflow
- [x] Toolbars
- [x] Truncated list
- [x] User avatar

### Patterns
- [x] Edit and update(s)
- [x] Empty state

### Onboarding
- [x] Coachmark
- [x] Get started cards
- [x] Guidebanner
- [x] Inline tip
- [x] Interstitial screens
- [x] Nonlinear reading

**Comment by oliviaflory** [comment]
## Deprecate ❌ 
#### Action bar 
- Deprecate
- Rewrite as a hook (tag set/overflow)

## Revisit in 3 months 🔮 
#### Big numbers 
- Modest usage 127 R / 252 M
- Move to core or repurposed as a utility?

**Comment by ljcarot** [comment]
@oliviaflory and @elycheea I think we can close this issue.  Do you agree?
