### ISSUE TITLE
DataGrid filtering is not working properly

### ISSUE THREAD

**Issue by sheejajoni** [carbon-design-system/ibm-products#6181]
### Package

Carbon for IBM Products

### Description

When we try to filter the table data items in the search filter it behaves strangely. For some characters it's working fine and for some characters it is not working
https://github.com/user-attachments/assets/11c2bb4d-7119-41e3-8446-178c5688ad3d

### Component(s) impacted

https://github.com/user-attachments/assets/8068a115-85d6-4aa9-bda1-a0cc8977ed59

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v8.12.5

### Suggested Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

Infrastructure

### CodeSandbox or Stackblitz example

https://pages.github.ibm.com/turbonomic-ui/turbo-ibm-cds-storybook.github.io/8.12.5/?path=/docs/components-datagrid--single-selection-template

### Steps to reproduce the issue (if applicable)

1. Go to link https://pages.github.ibm.com/turbonomic-ui/turbo-ibm-cds-storybook.github.io/8.12.5/?path=/docs/components-datagrid--single-selection-template
2. From DataGrid select Single Selection
3. In the search box, type letter 'a'. Filter is not working
4. 'In the search bar type letter 'd'. Filter is not working
5. For some characters the filter is not working

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by ljcarot** [comment]
We've been investigating [TanStack ](https://tanstack.com/table/latest)[Table](https://tanstack.com/table/latest), a third-party, open-source offering, which provides extensive data table capabilities surpassing what our Carbon Datagrid offers. It provides much more flexibility and customization. TanStack Table is headless which means it can easily be added alongside Datagrid component in your product or application. The benefits of more flexibility for product teams and less maintenance for Carbon makes it a win win. Lastly, it is available in multiple frameworks including [React](https://github.com/carbon-design-system/tanstack-carbon/tree/main/react#readme) and [Web Component](https://github.com/carbon-design-system/tanstack-carbon/tree/main/web-components#readme) so it provides an option to non-React product teams.

For these reasons, we have decided to transition from building our own custom table component to using an example-based approach with TanStack Table. Datagrid will still exist in our library for existing teams but we are announcing the deprecation* of the Datagrid component in v2.54.0 release so teams can begin to work through the transition. Details about how to use both Datagrid and TanStack together can be found [here](https://github.com/carbon-design-system/tanstack-carbon/tree/main). 

*Deprecation means that no new features will be added however sev 1 and sev 2 bugs will be supported.
