### ISSUE TITLE
Move `@carbon/web-components` Tearsheet into `@carbon/ibm-products-web-components`

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#6183]
### The problem

In order to resolve circular dependency issues in the Core monorepo after `@carbon/web-components` was moved, we need to move the Tearsheet web component into our own new web component package similar to how we moved `SidePanel` over.

### The solution

Add Tearsheet (along with stories) to `packages/ibm-products-web-components`. As there aren't any tests for the current Tearsheet web component in the core monorepo, a basic test suite should be created as part of this work as well, similar to Side panel.

### Owner/main maintainer(s)

Our team

### Business priority

None

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by elycheea** [comment]
This work should involve bringing the tearsheet in but does not cover removal of the web components tearsheet from the Carbon core monorepo.

**Comment by sangeethababu9223** [comment]
The component has been copied and properly set up in the `ibm-products-web-components` package with basic test cases. 
But there is some issue with the carbon theme integration in this package causing the component to look broken.
Once the theme integration issue is sorted, the draft PR raised can be moved to ready for review.
Keeping the PR in draft until this is sorted.
