### ISSUE TITLE
Add subdomain for new web components storybook site

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#6197]
`web-components.products.carbondesignsystem.com` is the url we've decided on for the new web component site. We'll need to add this custom domain in our netlify settings in order for it to work, reference current netlify site for configuration.

**Comment by elycheea** [comment]
`ibm-products-web-components.carbondesignsystem.com`?
`ibm-products-wc.carbondesignsystem.com`?

**Comment by matthewgallo** [comment]
We've got this all setup now! `ibm-products-web-components.carbondesignsystem.com` now routes to our netlify web component site.
