### ISSUE TITLE
Data grid:- Both the Carbon and the Pals grid show a scroll bar.  The issue is that the pals columns are bigger than they should be.

### ISSUE THREAD

**Issue by Rakesh-Addepalle** [carbon-design-system/ibm-products#6208]
### Package

Carbon for IBM Products

### Description

When using the Carbon React data table, the content is rendered without a horizontal scroll bar when the columns fit within the table. However, when content is rendered using the IBM Products data grid, a horizontal scroll bar appears unexpectedly, even though it should not.

### Component(s) impacted

Data grid.

### Browser

Chrome, Firefox

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.50.0

### Suggested Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

OpenPages

### CodeSandbox or Stackblitz example

https://stackblitz.com/edit/github-sqo4rx?file=src%2FApp.jsx,src%2FCarbonDataTable%2FCarbonDataTable.jsx,src%2FExample%2FExample.jsx,src%2FApp.scss,package.json

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by devadula-nandan** [comment]
@Rakesh-Addepalle
the overflow scroll issue is fixed, here is a solution for customizing widths
the carbon for ibm products use react-table which provides `width`,`minWidth`,`maxWidth` to customise the widths as per your requirements. here is an example directly from react-table https://react-table-v7-docs.netlify.app/docs/examples/column-resizing, they can be set even on individual column.
