### ISSUE TITLE
refactor feature flag tests

### ISSUE THREAD

**Issue by davidmenendez** [carbon-design-system/ibm-products#6235]
refactor feature flag tests to follow carbon approach. they should use our feature flags specific to C4P. remove explicit `false` setting.

**Comment by davidmenendez** [comment]
https://github.com/carbon-design-system/ibm-products/pull/6184#issuecomment-2402238731

**Comment by devadula-nandan** [comment]
path to carbon-react feature flag refactors
packages/react/src/components/FeatureFlags
