### ISSUE TITLE
[DataGrid]: Hover on column header is missing, impacting the affordance for column resizing

### ISSUE THREAD

**Issue by sammyschuckert** [carbon-design-system/ibm-products#6254]
### Package

Carbon for IBM Products

### Description

Our product team noticed a very subtle difference between the v10 version of the PAL data grid and the v11 version that has an impact on the affordance for column resizing. In v10 there was a hover state on the column header that indicated to a user the column width, making it easy to find the spot to move your cursor to for resizing. In the v11 version that hover state does no longer exist and thus making it harder for users to discover column resizing and more difficult to find the exact spot for resizing. 

### v10 PAL DataGrid
![Image](https://github.com/user-attachments/assets/2c39b0f0-e19b-46ae-9eb7-f731866acfac)

### v11 PAL DataGrid
![Image](https://github.com/user-attachments/assets/7ddac8d2-2436-406c-8187-7d45c969475c)

### Component(s) impacted

DataGrid https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid--basic-usage&globals=viewport:basic

### Browser

Firefox

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v2.52.0-rc.0

### Suggested Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

IBM Knowledge Catalog

### CodeSandbox or Stackblitz example

https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid--basic-usage&globals=viewport:basic

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by Mikadv** [comment]
Thank you for opening this issue. That is a really big UX bummer. Where should anyone using this component know how to resize the columns? And its even worse. Datagrid doesn't come with auto resizing. So this is critical function. I'd reason that because of this is a `Sev 2`
