### ISSUE TITLE
Review all open bugs and feature requests for Datagrid

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/ibm-products#6259]
### Problem
We need to review all the [bugs](https://github.com/orgs/carbon-design-system/projects/65/views/28) and [feature requests](https://github.com/orgs/carbon-design-system/projects/65/views/30) that are open against Datagrid and start communicating whether we will or will not fix / update the component, and start directing teams to TanStack

#### Review bugs
Determine if it's a bug to fix or if we will not fix it
Bugs that we will fix should be moved into a sprint / ready to be picked up
Bugs that we will NOT fix should have a boiler plate response added and closed

#### Review feature requests
Add boiler plate response added and closed

#### Boiler plate should include:
- Brief info that datagrid will be deprecated and new strategy of TanStack
- Direct people to TanStack readme

#### Read me should include:
- Info on TanStack
- Describe new strategy

### Acceptance criteria:
- [x] Create a Readme to tell people about our new strategy with TanStack
- [x] Create boiler plate response and share with Linda and Matt
- [x] Review all bugs and add response
- [x] Review all feature requests and add response
- [x] Issues that we will not address have been closed
- [x] Issues that we will address are moving into backlog

**Comment by ljcarot** [comment]
This is boilerplate response:
We've been investigating [TanStack ](https://tanstack.com/table/latest)[Table](https://tanstack.com/table/latest), a third-party, open-source offering, which provides extensive data table capabilities surpassing what our Carbon Datagrid offers. It provides much more flexibility and customization. TanStack Table is headless which means it can easily be added alongside Datagrid component in your product or application. The benefits of more flexibility for product teams and less maintenance for Carbon makes it a win win. Lastly, it is available in multiple frameworks including [React](https://github.com/carbon-design-system/tanstack-carbon/tree/main/react#readme) and [Web Component](https://github.com/carbon-design-system/tanstack-carbon/tree/main/web-components#readme) so it provides an option to non-React product teams.

For these reasons, we have decided to transition from building our own custom table component to using an example-based approach with TanStack Table. Datagrid will still exist in our library for existing teams but we are announcing the deprecation* of the Datagrid component in v2.54.0 release so teams can begin to work through the transition. Details about how to use both Datagrid and TanStack together can be found [here](https://github.com/carbon-design-system/tanstack-carbon/tree/main). 

*Deprecation means that no new features will be added however sev 1 and sev 2 bugs will be supported.
