### ISSUE TITLE
Create a list of any coded patterns that we plan to deprecate

### ISSUE THREAD

**Issue by ljcarot** [carbon-design-system/ibm-products#6260]
- Review telemetry data on stable and experimental patterns -> https://airtable.com/appY30x3q9FcdIcL1/tbl81O5yRLA4gGh1T/viwMUaHdUBS4rR9Jy?blocks=hide
- Flag patterns to deprecate by adding to [tracking issue](https://github.com/carbon-design-system/ibm-products/issues/6240)
- As we deprecate code from the package, need to create examples for the patterns where possible/applicable.

**Comment by elycheea** [comment]
@matthewgallo and I opened #6488 as a follow up since we would ideally want to create the pattern code before deprecation.
Still evaluating some other potential patterns that may need to be deprecated in favor of example code.
