### ISSUE TITLE
[DataGrid]: How to filter data through the backend when clicking on the left panel (click 'Apply')? Instead of front-end search.

### ISSUE THREAD

**Issue by BARBERTONY1** [carbon-design-system/ibm-products#6267]
### Summary

After filtering on the left panel, I get data form backend to set the data(like react setData), but the 'summary'(filter summary component) at the top of the table disappeared, and the filtering on the left also returned to its default. I guess it's because after resetting, the table status was reset. But my requirement is to get data form backend to filter data, not the frontend.
I couldn't find any relevant code that can be changed. Can you help me solve this problem?

### Name and organization

barbertony

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by BARBERTONY1** [comment]
supplement:
![Image](https://github.com/user-attachments/assets/8b3fe028-91f3-4ed7-a9f6-fbd00b33aa50)

**Comment by ljcarot** [comment]
We've been investigating [TanStack ](https://tanstack.com/table/latest)[Table](https://tanstack.com/table/latest), a third-party, open-source offering, which provides extensive data table capabilities surpassing what our Carbon Datagrid offers. It provides much more flexibility and customization. TanStack Table is headless which means it can easily be added alongside Datagrid component in your product or application. The benefits of more flexibility for product teams and less maintenance for Carbon makes it a win win. Lastly, it is available in multiple frameworks including [React](https://github.com/carbon-design-system/tanstack-carbon/tree/main/react#readme) and [Web Component](https://github.com/carbon-design-system/tanstack-carbon/tree/main/web-components#readme) so it provides an option to non-React product teams.

For these reasons, we have decided to transition from building our own custom table component to using an example-based approach with TanStack Table. Datagrid will still exist in our library for existing teams but we are announcing the deprecation* of the Datagrid component in v2.54.0 release so teams can begin to work through the transition. Details about how to use both Datagrid and TanStack together can be found [here](https://github.com/carbon-design-system/tanstack-carbon/tree/main). 

*Deprecation means that no new features will be added however sev 1 and sev 2 bugs will be supported.
