### ISSUE TITLE
Web component storybook, theme addon not working in deployed site

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#6279]
### Package

Carbon for IBM Products

### Description

Theme toolbar addon not working in deployed site

### Component(s) impacted

Tearsheet

### Browser

Chrome, Safari, Microsoft Edge, Firefox

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

Latest

### Suggested Severity

None

### Product/offering

N/A

### CodeSandbox or Stackblitz example

https://ibm-products-web-components.netlify.app/?path=/story/experimental-sidepanel--slide-over

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by sangeethababu9223** [comment]
Looks like this is fixed in the following [PR #6204 ](https://github.com/carbon-design-system/ibm-products/pull/6204)
