### ISSUE TITLE
[Feature Request]: Create flows should support Carbon's interactive progress indicator

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/ibm-products#6291]
### The problem

Users should be able to directly jump to a specific step in a create flow (e.g. CreateTearsheet) to revisit a specific choice they made without the need to repeatedly press "Previous" and then "Next"

### The solution

Add support for [Carbon's interactive progress indicator](https://react.carbondesignsystem.com/?path=/story/components-progressindicator--interactive).

### Owner/main maintainer(s)

-

### Business priority

None

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by oliviaflory** [comment]
@janhassel thanks for the feature request! This seems like a duplicate of #6030, I will close this issue unless there's something else you're looking for.

**Comment by janhassel** [comment]
@oliviaflory Yes definitely! I didn't find this other issue though probably because I was searching for generic "Create flows" and "CreateTearsheet". You might wanna change the title so it's easier to find as it doesn't only apply to CreateFullPage.
