### ISSUE TITLE
[ContentSwitcher]: Extra white space at bottom of icon tooltip

### ISSUE THREAD

**Issue by yinglejia** [carbon-design-system/ibm-products#6312]
### Package

Carbon for IBM Products

### Description

Go to storybook https://web-components.carbondesignsystem.com/?path=/story/components-content-switcher--icon-only and check the icon tooltip. There's extra white space at bottom of the icon tooltip for the first button and the tooltip text is cut off.

![Image](https://github.com/user-attachments/assets/5d9cd96e-ac20-45d7-9162-cabbe69e1cc4)

### Component(s) impacted

ContentSwitcher

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.52.0

### Suggested Severity

None

### Product/offering

IBM Environmental Intelligence

### CodeSandbox or Stackblitz example

https://web-components.carbondesignsystem.com/?path=/story/components-content-switcher--icon-only

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by matthewgallo** [comment]
Hi @yinglejia, this looks to be an issue for the core web component library.

**Comment by yinglejia** [comment]
@matthewgallo thanks, seems I assigned it to the wrong place.
