### ISSUE TITLE
[Hydration Error with EmptyState]: Nested NoDataEmptyState throws hydration errors on Next JS 15

### ISSUE THREAD

**Issue by DoaaRadwan** [carbon-design-system/ibm-products#6315]
### Package

Carbon for IBM Products

### Description

When using NoDataEmptyState as a nested component, a hydration error is thrown
 ![Image](https://github.com/user-attachments/assets/f808c47f-e7a8-4e63-8b82-9c543c09dd1b)

```
              {contentSwitcherIndex == 2 ? (
                <>
                  {array.length > 0 ? (
                    <Grid>
                      {array.map((s) => (
                        <Column
                          key={"Column" + s.s_name}
                          xlg={5}
                          lg={5}
                          md={4}
                          sm={4}
                        >
                          <ServiceTile
                            key={s.s_name}
                            service={s}
                          />
                        </Column>
                      ))}
                    </Grid>
                  ) : (
                    <NoDataEmptyState
                      style={{ padding: "2rem" }}
                      illustrationDescription="No data available"
                      subtitle="No data available at this time. If you think this is a mistake, please contact admin."
                      title="No data available"
                    />
                  )}
                </>
              ) : null}
```

### Component(s) impacted

[NoDataEmptyState](https://ibm-products.carbondesignsystem.com/?path=/docs/ibm-products-patterns-empty-state-nodataemptystate--docs)
![Image](https://github.com/user-attachments/assets/f808c47f-e7a8-4e63-8b82-9c543c09dd1b)

Both CodeSandbox and Stackblitz examples are not working
![Image](https://github.com/user-attachments/assets/fecc2116-8cdb-421d-9989-b5a530ec2559)

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

V2.38.0

### Suggested Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Product/offering

IBM Research

### CodeSandbox or Stackblitz example

Link is not working

### Steps to reproduce the issue (if applicable)

Create a Next js react project
Use NoDataEmptyState in a conditional rendering function or directly in the page body 

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by DoaaRadwan** [comment]
This is the best I could do to reproduce 
https://stackblitz.com/edit/stackblitz-starters-bk9xut?file=app%2FHome%2Fpage.tsx
However, I am not seeing the same error as local

**Comment by amal-k-joy** [comment]
Hi @DoaaRadwan ,
Could you share us more details probably in the Carbon Developer office hours ?

**Comment by DoaaRadwan** [comment]
> Hi [@DoaaRadwan](https://github.com/DoaaRadwan) , Could you share us more details probably in the [Carbon Developer office hours](https://ec.yourlearning.ibm.com/w3/join/event/10408799)?

Hi @amal-k-joy, what kind of details do you want ?
