### ISSUE TITLE
DataGrid IA explorations

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/ibm-products#6317]
Exploring how to handle DataGrid vs TanStack in IA

- [ ] Mock up examples
- [ ] Share with the team
- [ ] Refine follow on work in parent issue

**Comment by ljcarot** [comment]
@oliviaflory Trying to follow the trail of where this IA exploration work landed and the impact on the Code tab of the DataGrid components on our site.  Can you pls share the Figma file or where the exploration landed? Thx

**Comment by oliviaflory** [comment]
@ljcarot sorry I didn't realize the [Figma](https://www.figma.com/design/t5nfI1clIGhI4tZcR5zB9r/Datagrid-to-Tanstack-docs-exploration?node-id=2-5979&t=6Fcfe2Ksne394F4v-1) wasn't linked.

I'm going to write a few issues for what the next steps are in the epic today
