### ISSUE TITLE
deprecate status indicator

### ISSUE THREAD

**Issue by devadula-nandan** [carbon-design-system/ibm-products#6326]
deprecation steps
https://github.com/carbon-design-system/ibm-products/pull/6223/files

1. add deprecation flag in the components
2. document deprecation stuff like migration, story docs, ts deprecation, 
3. updating tests

note: we like to time it with core's status indicators.

**Comment by elycheea** [comment]
Realized this is also one of the Security components. While this may be included in Core’s updated status indicators, since this is experimental, moving this into #6318
