### ISSUE TITLE
Dynamically loaded nested rows example

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#6358]
### The problem

After our conversations with sponsor users for our new example based approach, there are some teams that rely on dynamically loading of nested rows. This is functionality contained in Datagrid that does not yet have an example in the [example monorepo](https://github.com/carbon-design-system/tanstack-carbon).

### The solution

Create a new example in monorepe, that dynamically loads nested rows. This example should use some type of mock api to emulate a more realistic scenario of how this would be used in a real setting.

### Owner/main maintainer(s)

Our team

### Business priority

None

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by AtharvaGadekar** [comment]
You can consider using a mocking tool like [Beeceptor](https://beeceptor.com/) to create a mock API with nested data structures. This approach can help illustrate the dynamic loading of nested rows in the Datagrid, providing a more realistic testing scenario without needing a complete backend.

**Comment by matthewgallo** [comment]
Hey @AtharvaGadekar, Beeceptor looks like a nice product. I'll maybe try it out in future projects.
