### ISSUE TITLE
Update `framer-motion` to latest compatible

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#6379]

**Comment by AlexanderMelox** [comment]
One thing to note that it is no longer `framer-motion` but just `motion`
Article about the changes. Good thing is they are going to focus more on vanilla api's for motion and utilizing the new [View Transition API](https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API). 
https://motion.dev/blog/framer-motion-is-now-independent-introducing-motion
