### ISSUE TITLE
Investigate resize event testing

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-products#640]
## What will this achieve?

Several components use `ReactResizeDetector` which has an onResize prop. This needs to be tested for each component that has this resize event listener.

Adding this to a test only triggers a resize event on the window, but does not call the `onResize` prop from the resize detector component.

```js
it('should test the onResize prop from react resize detector', () => {
  renderSomeComponent();
  global.innerHeight = 600;
  global.dispatchEvent(new Event('resize'));
});

```

**Comment by andrea-gm** [comment]
@matthewgallo could you add this issue to all of the relevant component Epics? I wonder if that could be a way to track that it gets done for each? Or do you think we need separate issues?

**Comment by matthewgallo** [comment]
We still have not found a solution for this as there aren't any specific guidelines around testing `react-resize-detector` using jest. For now, we've added `istanbul-ignore`s. Moving to on hold pipeline

**Comment by elycheea** [comment]
Suggest we move this back to new issues and discuss during backlog since the need to look into testing may still be relevant, but `react-resize-detector` has been removed.

**Comment by elycheea** [comment]
Should add some tests for the hook that Lee wrote in #2912

**Comment by elycheea** [comment]
@Ratheeshrajan are you interested in working on some testing items?
