### ISSUE TITLE
Upgrade stylelint to v16

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-products#6424]
Stylelint v16 does include some breaking changes with it going ESM only.

https://stylelint.io/migration-guide/to-16/

REF https://github.com/carbon-design-system/carbon/pull/17770

- [ ] Review the migration docs
- [ ] Review prior art from Core
- [ ] Update stylelint to 16 and resolve and breaking changes

**Comment by davidmenendez** [comment]
[PR open](https://github.com/carbon-design-system/ibm-products/pull/6510)

@elycheea one question regarding

> Review prior art from Core

can you expand upon this? thanks!

**Comment by elycheea** [comment]
@davidmenendez Haha, prior art just means reviewing the previous PR from the core team in case it helps as a reference. 😹
