### ISSUE TITLE
SidePanel: SlideOver animation is buggy

### ISSUE THREAD

**Issue by AlexanderMelox** [carbon-design-system/ibm-products#6460]
### Package

Carbon for IBM Products

### Description

When opening the SidePanel the animation looks weird

https://github.com/user-attachments/assets/20ab1f87-ad76-4dc2-969a-9c470e53dd2a

### Component(s) impacted

SidePanel

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.54.0-rc.1

### Suggested Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

n/a

### CodeSandbox or Stackblitz example

https://carbon-for-ibm-products.netlify.app/?path=/docs/ibm-products-components-side-panel-sidepanel--docs

### Steps to reproduce the issue (if applicable)

1. Open side panel
2. Notice the animation

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by elycheea** [comment]
Note: This is only visible from the Docs page and only on specific stories. @AlexanderMelox was about to reproduce this on “First element disabled” and “panel with second step” whereas I only saw the broken animation on “specify element to have initial focus” and “without title.”
