### ISSUE TITLE
Tearsheet: Element focussed twice when using stacked tearsheets

### ISSUE THREAD

**Issue by mconway-ns1** [carbon-design-system/ibm-products#6466]
### Package

Carbon for IBM Products

### Description

Expected : selectorPrimaryFocus to be focussed and not blurred
Actual: selectorPrimaryFocus is focused and then focussed again, causing the onBlur to fire with validation 

The problem seems to be in TearsheetShell. The `handleStackChange.claimFocus` and `useEffect` both focus the element c

### Component(s) impacted

https://github.com/carbon-design-system/ibm-products/blob/main/packages/ibm-products/src/components/Tearsheet/TearsheetShell.tsx

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

 @carbon/ibm-products@2.53.0 

### Suggested Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Product/offering

NS1

### CodeSandbox or Stackblitz example

https://stackblitz.com/edit/github-1qjirj?file=src%2FExample%2FExample.jsx

### Steps to reproduce the issue (if applicable)

see example in stackblitz

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by makafsal** [comment]
@mconway-ns1 I've tried reproducing the issue after downloading the Stackblitz example you provided, but I can't reproduce it locally.
How did you find this issue in the first place, were you able to reproduce this issue locally?

In Stackblits:

https://github.com/user-attachments/assets/b9efd285-13d9-40d4-8c8d-4c29dc10efb9


In local (downloaded from Stackblits):

https://github.com/user-attachments/assets/0ecfb20b-4b7e-41ff-bdfa-25713218060a
