### ISSUE TITLE
Security issue with normalize-url package

### ISSUE THREAD

**Issue by murtdagi** [carbon-design-system/ibm-products#928]
## What package(s) are you using?

- [x] Cloud & Cognitive
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description
The security scans has reported and issue that needs to be fixed for the upcoming release, the DCUT of which is by the end of this week.
Can someone look into this as a matter of priority?
Here's the screenshot showing where this pacakage is being used:
![image](https://user-images.githubusercontent.com/7819852/123074690-722bc080-d40f-11eb-9477-3e71c2e28cef.png)

> Describe in detail the issue you're having.

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of the @carbon/ibm-cloud-cognitive packge are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by dcwarwick** [comment]
@murtdagi Thank you for bringing this to our attention.

You mention that a security scan has reported an issue, but you haven't actually told us what the issue is. I presume from the screen shot that you included that it is something about normalize-url v.4.5.0. Can you tell us what security scan you're referring to, and what it says about normalize-url? Does it give some kind of message? Is there a link to more information about the security issue?

**Comment by dcwarwick** [comment]
@murtdagi PS I notice that `cacheable-request v7.0.2` was published on June 9th, and this updates its dependency to `normalize-url@^6.0.1`. If you remove your `yarn.lock` (or `package-lock.json`) file and run `yarn install` (or `npm install`) you should find that the dependency of `got v11.8.2` now gets fulfilled by `cacheable-request v7.0.2`, and the dependency of that gets fulfilled by `normalize-url v6.1.0`, and this will hopefully resolve the security scan issue you're seeing.

**Comment by joshblack** [comment]
Sorry for the delay @dcwarwick, we've been using this discussion as the focal point for these reports: https://github.com/carbon-design-system/carbon/discussions/8587

On our end, we'll make sure dependencies are up-to-date but most likely this will continue to pop up given the nature of static security analysis at the moment.

**Comment by murtdagi** [comment]
Thanks for the update
